### ISSUE TITLE
(Bug): Natron crash on AMD drivers

### ISSUE THREAD

**Issue by TechnoHT** [NatronGitHub/Natron#1010]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.5.0

### Operating system

Windows 11 23H2

### System specs

CPU: AMD Ryzen 7 3700X
GPU: AMD Radeon RX480 (Newest driver)

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

I tried to launch Natron on a new installation

### What did you expect to happen? What happened instead?

It should have launched as normal but crashed

### Step-by-step reproduction instructions

1. Start Natron on AMD GPU with latest driver installed

### Additional details

This is the content of the `!analyze -v` command I ran on the dump file when the crash happened

```NTGLOBALFLAG:  0

CONTEXT:  (.ecxr)
rax=0000000000000000 rbx=ffffffffffffffff rcx=0000000000001f01
rdx=0000000000000000 rsi=0000000000001f01 rdi=00000243e5759bc8
rip=00007fff14ffa7d3 rsp=000000ef947ff330 rbp=0000000000001f01
 r8=0000000000000140  r9=0000000000000001 r10=00000243e56f4378
r11=f7c000000000001f r12=0000000000000000 r13=00000243f337d170
r14=00000243f337cd70 r15=0000000000000400
iopl=0         nv up ei pl zr na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246
atio6axx+0x87a7d3:
00007fff`14ffa7d3 807c1a0100      cmp     byte ptr [rdx+rbx+1],0 ds:00000000`00000000=??
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007fff14ffa7d3 (atio6axx+0x000000000087a7d3)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000000
Attempt to read from address 0000000000000000

PROCESS_NAME:  Natron.exe

READ_ADDRESS:  0000000000000000 

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  0000000000000000

IP_ON_HEAP:  aaaaaaaaaaaaaaaa
The fault address in not in any loaded module, please check your build's rebase
log at <releasedir>\bin\build_logs\timebuild\ntrebase.log for module which may
contain the address if it were loaded.

FRAME_ONE_INVALID: 1

STACK_TEXT:  
000000ef`947ff330 aaaaaaaa`aaaaaaaa     : aaaaaaaa`aaaaaaaa 00000000`00000000 aaaaaaaa`aaaaaaaa aaaaaaaa`aaaaaaaa : atio6axx+0x87a7d3
000000ef`947ff338 aaaaaaaa`aaaaaaaa     : 00000000`00000000 aaaaaaaa`aaaaaaaa aaaaaaaa`aaaaaaaa 00000000`00000010 : 0xaaaaaaaa`aaaaaaaa
000000ef`947ff340 00000000`00000000     : aaaaaaaa`aaaaaaaa aaaaaaaa`aaaaaaaa 00000000`00000010 aaaaaaaa`aaaaaaaa : 0xaaaaaaaa`aaaaaaaa


STACK_COMMAND:  ~0s; .ecxr ; kb

SYMBOL_NAME:  atio6axx+87a7d3

MODULE_NAME: atio6axx

IMAGE_NAME:  atio6axx.dll

FAILURE_BUCKET_ID:  NULL_POINTER_READ_c0000005_atio6axx.dll!Unknown

OS_VERSION:  10.0.22621.1

BUILDLAB_STR:  ni_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

IMAGE_VERSION:  31.0.21921.1000

FAILURE_ID_HASH:  {293ca984-fe1d-7872-a5e3-1b79ed1e4eb0}

Followup:     MachineOwner
---------
```

The dump file is included here:
[WER.509147b1-08d3-4379-9ba9-af03222456c8.tmp - Copy.dmp](https://github.com/user-attachments/files/17612090/WER.509147b1-08d3-4379-9ba9-af03222456c8.tmp.-.Copy.dmp)

I have not yet been able to identify why the AMD OpenGL driver crashed, but it seems to not happen on my other PC with driver version 22.5.1 (Windows 10). However, using this driver on my Windows 11 causes a lot of trouble for other apps so I have opted out from this solution.

**Comment by TechnoHT** [comment]
Debugging with CodeXL gives pretty much the same context, could be that AMD is strictly following Khronos standards and does not wrap the incorrect render range like Nvidia drivers (Just speculation)

```
Reason: Array Bounds Exceeded
Address: 0x00007fff14ffa7d3
Details: The thread tried to access an array element that is out of bounds and the underlying hardware supports bounds checking.
```

Call stack:

```
PyInit_NatronEngine - Natron.exe
PyInit_NatronEngine - Natron.exe
PyInit_NatronEngine - Natron.exe
PyInit_NatronEngine - Natron.exe
0x00007ff72ef81799 - Natron.exe
0x00007ff72ef813d9 - Natron.exe
0x00007ff72ef814e5 - Natron.exe
BaseThreadInitThunk - KERNEL32.DLL
```

**Comment by acolwell** [comment]
I suspect this is likely fixed by [changes I made](https://github.com/NatronGitHub/Natron/pull/949) a while ago. You can try one of my [nightly Natron builds](https://github.com/acolwell/Natron/releases/tag/nightly) and see if you still have a problem.

**Comment by TechnoHT** [comment]
> I suspect this is likely fixed by [changes I made](https://github.com/NatronGitHub/Natron/pull/949) a while ago. You can try one of my [nightly Natron builds](https://github.com/acolwell/Natron/releases/tag/nightly) and see if you still have a problem.

@acolwell Unfortunately it is not fixed

```
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\u0407052.inf_amd64_84d15514ad17ffa0\B406619\atio6axx.dll
Report Id: cb9298e1-6445-40a5-a6c2-6630993e016f
Faulting package full name: 
Faulting package-relative application ID: 
```

The call stack keeps looping at `PyInit_NatronEngine` before crashing and I think it might not be the context creation that caused the problem

**Comment by TechnoHT** [comment]
My apology,

The nightly build fixed it, it was just because my drivers was not responding.
