### ISSUE TITLE
(Bug): a lot of warning: unknown warning option

### ISSUE THREAD

**Issue by Martinfx** [NatronGitHub/Natron#1027]
### Make sure to follow our issue report guidelines

- [ ] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron-2.5.1-pre2

### Operating system

FreeBSD-14.2-RELEASE

### Did you install Natron using the official installer?

- [ ] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [X] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

Compilation without warnings

### What did you expect to happen? What happened instead?

less warnings

### Step-by-step reproduction instructions

1. You compile Natron from source code.
2. You use FreeBSD clang version 18.1.6 (https://github.com/llvm/llvm-project.git llvmorg-18.1.6-0-g1118c2e05e67)
Target: x86_64-unknown-freebsd14.2
  

### Additional details

```
warning: unknown warning option '-Wshift-overflow=2'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
warning: unknown warning option '-Wduplicated-cond' [-Wunknown-warning-option]
warning: unknown warning option '-Wno-stringop-overflow'; did you mean '-Wno-shift-overflow'? [-Wunknown-warning-option]

```

**Comment by YakoYakoYokuYoku** [comment]
I also use Clang, mainly for development, and yes, I get those same warns. @acolwell you've added those flags by what blame shows, I know the purpose but I think those are best to be set by users rather than in the codebase. Any thoughts?

**Comment by acolwell** [comment]
I just created #1028  to fix this issue.
