### ISSUE TITLE
Remember Minimize state when reopening project

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#168]
_From @nicholascarroll on September 28, 2016 7:42_

### Problem

Please preserve state of minimized any node window was minimized when reopening closed projects. This is causing serious inconvenience for project files that have Primatte nodes, because Primatte accepts any click on the viewer and _minimize_ is the only way to prevent that.

Minimize node window affects functionality, not just layout.

**Expected behavior:** 
Remember if node was minimized so if you are using Primatte, it stays minimized.
**Actual behavior:**
The minimized Primatte nodes are set to open, which changes the functionality.
### Steps to Reproduce
1. Minimise a node
2. Close the project
3. Reopen the project
4. the node should be still minimised
### Versions
- **Natron version/commit** 
  2.1.4
- **OS version:** 
  Ubuntu 16.04 and OSX 10.11

_Copied from original issue: MrKepzie/Natron#1450_

**Comment by devernay** [comment]
@rodlie fixed in 2.3.15?

**Comment by rodlie** [comment]
This is for each node properties panel?
![node-minimized](https://user-images.githubusercontent.com/34516798/73038041-463e9100-3e51-11ea-98a5-a210d81b143a.png)


If so, as far as I can see the project format only has ``OpenedPanels``, so the node properties panel is either visible or not. Support for minimized must be added(?).

Current:
```
<OpenedPanels>
		<count>3</count>
		<item_version>0</item_version>
		<item>Node1</item>
		<item>Node2</item>
		<item>Natron_Project_Settings_Panel</item>
</OpenedPanels>
```

Alternative:
```
<OpenedPanels>
		<count>3</count>
		<item_version>0</item_version>
		<item>
            <Name>Node1</Name>
            <Minimized>true</Minimized>
        </item>
        <item>
            <Name>Node2</Name>
            <Minimized>true</Minimized>
        </item>
        <item>
            <Name>Natron_Project_Settings_Panel</Name>
            <Minimized>true</Minimized>
        </item>
</OpenedPanels>
```

Or just add :

```
<MinimizedPanels>
		<count>3</count>
		<item_version>0</item_version>
		<item>Node1</item>
		<item>Node2</item>
		<item>Natron_Project_Settings_Panel</item>
</MinimizedPanels>
```

Then of course check for minimized etc in code.

I would move this issue to 2.4.

**Comment by rodlie** [comment]
I have started on this, should probably have something working soon.

**Comment by rodlie** [comment]
So, I got it working, but loading the new project in Natron before my commit fails with ``Error while loading project: Unrecognized or damaged project file: input stream error``, and on 2.3.15 i get ``Error while loading project: This project was saved with a more recent version (2.3.16) of Natron. Projects are not forward compatible and may only be opened in a version of Natron equal or more recent than the version that saved it.`` (since it checks versions, else the error would be the same I guess).

Is this normal behavior?

The NTP has this additional data:
```
	<OpenedPanelsMinimized>
		<count>2</count>
		<item_version>0</item_version>
		<item>Node1</item>
		<item>Node2</item>
	</OpenedPanelsMinimized>
```

I would assume that unknown tags would be skipped, but I might be mistaken (if I remove ``OpenedPanelsMinimized`` I can open the NTP in older versions).

**Comment by devernay** [comment]
no, they are not skipped, you have to use the serialization version numbers and do the work manually (skipping the item before the version where it was introduced.
look for `PROJECT_GUI_SERIALIZATION_INTRODUCES_PYTHON_PANELS` in the code for an example.

**Comment by rodlie** [comment]
Ok, that was my understanding when I made the change, just wanted to confirm.

So, should I add something in RB-2.3 for backwards compatibility for this change, or do nothing (2.4 projects will not be backward compatible with 2.3).

**Comment by devernay** [comment]
Loading a project made with v1>v2 on v2 has never been supported, but v1
must be able to load a project created with v2

**Comment by devernay** [comment]
@rodlie it should probably also remember the "hide parameters without modifications" setting

**Comment by rodlie** [comment]
Ok, will add.

**Comment by rodlie** [comment]
Fixed in https://github.com/NatronGitHub/Natron/commit/df20487323aa871868482700c1287fd7d990cf82
