### ISSUE TITLE
Feature Request: Completion Meter for Taskbar Icon

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#169]
_From @alicelookingglass on September 29, 2016 23:4_

Blender has the feature that shows a render completion meter on the taskbar icon (Windows) while it is minimized.  I have come to rely on this feature rather heavily for my various workflows, and I would absolutely love it if Natron could do the same.

(I hope I put this feature request in the right place)

Thanks for all your amazing work!

_Copied from original issue: MrKepzie/Natron#1454_

**Comment by devernay** [comment]
_From @alicelookingglass on March 5, 2017 17:44_

Is this difficult to implement?  I'd only asked because it seems so common in numerous other software.

**Comment by rodlie** [comment]
This feature requires Qt 5.2+, I will add it when we move to Qt5.

**Comment by rodlie** [comment]
Feature removed in Qt6 (with no replacement).

> The QWinTaskbarButton and QWinTaskbarProgress classes have been removed due to warranting a cross-platform solution.

I can do this from scratch with minimal code and it will work in Qt4/Qt5/Qt6.

**Comment by rodlie** [comment]
Got it working on Windows:
![natron-taskbar](https://user-images.githubusercontent.com/34516798/132961387-cdfcfb50-4d4b-4edc-b4a4-77f692727072.png)

Will add support for macOS when I get the time, I will not do anything on Linux (until a proper standard is added).

Will work on any version of Qt since I don't use qtwinextras or anything like that. Will do a PR probably next weekend.

**Comment by rodlie** [comment]
Windows build available for testing: https://github.com/rodlie/Natron/releases/tag/taskbarV1

**Comment by rodlie** [comment]
Works almost on Mac:
![natron-macbar-test1](https://user-images.githubusercontent.com/34516798/133678660-0617262d-45fd-407f-9cdf-a790be252163.png)

The progress value is a bit wrong and for some reason the "stock" icon appears when done, probably something trivial I'm missing, will look more into this tomorrow (or Saturday).
![natron-macbar-test2](https://user-images.githubusercontent.com/34516798/133678933-32d02aa9-1e7b-401e-8ade-189ccd5b86ee.png)

**Comment by rodlie** [comment]
So, it seems to work on macOS now:

https://user-images.githubusercontent.com/34516798/133860436-9807482c-d05e-40d9-a2b8-f42e1b985022.mp4

I just created a simple green progress line and make the icon bounce when done (if not active window), can of course do something more fancy, but yeah... keep it simple.

**Comment by devernay** [comment]
@rodlie is it ready for PR? Would be nice to have on RB-2.4

**Comment by rodlie** [comment]
Will check, can probably do a PR tomorrow (also have the color palette changes ready).

**Comment by devernay** [comment]
don't forget to edit the CHANGELOG.md file

**Comment by devernay** [comment]
@rodlie can you make a PR for this?

**Comment by rodlie** [comment]
close, fixed in 2.4.3.
