### ISSUE TITLE
Opening a project destroys the current project if not saved

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#217]
_From @devernay on August 13, 2017 15:56_

### Steps to Reproduce

1. Launch Natron
2. Create a graph with few nodes, but do not save the project
3. Open a project
4. The graph that was created is destroyed

Natron should create a new project window but not destroy the current one

### Versions

* **Natron version/commit**: 2.3 & 3.0
* **OS version:** all

_Copied from original issue: MrKepzie/Natron#1657_

**Comment by Shrinks99** [comment]
Unable to replicate, pretty sure this was fixed, Natron opens a new graph and doesn't seem to destroy the old one anymore.

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/Natron/pull/382
