### ISSUE TITLE
Natron's breakpad crash reporter blocks Safari and Mail on macOS

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#219]
### Problem Description

I have an issue with Natron, when I launch it my safari can't open any pages. But when I close Natron, thats works.

Apple Mail doesn't display mail content either.

### Temporary Solution

To disable the crash reporter in Natron, do the following in a terminal:
```
mv /Applications/Natron.app/Contents/MacOS/Natron-driver /Applications/Natron.app/Contents/MacOS/Natron-driver.orig
mv /Applications/Natron.app/Contents/MacOS/Natron-bin /Applications/Natron.app/Contents/MacOS/Natron-driver
```

_Copied from original issue: MrKepzie/Natron#1662_

**Comment by devernay** [comment]
I first thought this was a joke, but no... Natron blocks loading an URL in Safari (10.1.2 on macOS Sierra here) by clicking on a bookmark or entering an URL, and as soon as one quits Natron, The URL loads! Clicking on links on an alredy loaded page works, though...

Tested with Natron 2.0.5-2.3.2 on macOS Sierra.
Frankly, this looks like an OS or Safari bug, unless someone gives me a clue

**Comment by devernay** [comment]
The bug is related to breakpad - the crash reporting system. This is a serious issue.

To disable completely the crash reporter, type the following in a terminal:
```
cd /Applications/Natron.app/Contents/MacOS
mv Natron-driver Natron-driver.orig
ln -s Natron-bin Natron-driver
```
Safari works fine after that.

**Comment by devernay** [comment]
Should be fixed by switching to crashpad, see https://github.com/MrKepzie/Natron/issues/1223 https://github.com/NatronGitHub/Natron/issues/145

**Comment by devernay** [comment]
Apple Mail is also affected (doesn't display mails content)

**Comment by devernay** [comment]
To disable the crash reporter in Natron, do the following in a terminal:
```
mv /Applications/Natron.app/Contents/MacOS/Natron-driver /Applications/Natron.app/Contents/MacOS/Natron-driver.orig
mv /Applications/Natron.app/Contents/MacOS/Natron-bin /Applications/Natron.app/Contents/MacOS/Natron-driver
```

**Comment by rodlie** [comment]
Do you know anything more? What is the status on crashpad?

**Comment by devernay** [comment]
The last release (2.3.14) has crashpad disabled anyway, so this won't be an issue anymore until someone re-enables crashpad/breakpad. In this case a switch to a more recent version would be advisable.
