### ISSUE TITLE
Natron 2.3.2 crashes with antialias and defocus from natron-plugins

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#221]
_From @Eneen on August 28, 2017 22:49_

Natron version: 2.3.2
Platform: Windows

It was working fine before version 2.3.2, but now it doesn't. It or crashes or stalls Natron or gives such message:
> [00:45:44.634] FXAA_Alpha: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

I get same thing with defocus:
> [00:47:44.801] Defocus: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

Sidenote: it crashes when I zoom in my project to get 1:1 preview

_Copied from original issue: MrKepzie/Natron#1667_

**Comment by devernay** [comment]
_From @MrKepzie on September 26, 2017 15:10_

Means OpenGL driver on your graphic cards is not high enough. You can enable software OpenGL rendering by checking the optional dependency during the installation of Natron, or move the opengl32.dll file located in Natron/bin/mesa to Natron/bin

**Comment by devernay** [comment]
_From @Eneen on September 26, 2017 15:13_

But I've got GTX 1050Ti with current (2017.08) drivers. How come it doesn't support current opengl?

**Comment by devernay** [comment]
_From @Eneen on September 29, 2017 11:27_

Ok, current drivers give same result:
`FXAA_Alpha: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.`

But screenshot tells I've got such extension:
![gl_arb_texture_non_power_of_two_bug](https://user-images.githubusercontent.com/25537418/31014184-ea9b2570-a519-11e7-9371-f34008d231ce.jpg)

**Comment by devernay** [comment]
Can you please post a zipped Natron project that shows the problem?

**Comment by devernay** [comment]
_From @Eneen on October 17, 2017 12:2_

Sure. I've sent you project via wetransfer. Antialias node is used on upper-left segment with ID mask file after keyer and invert. Currently it's disabled - I use blur instead. Please just disable blur and enable antialias to reproduce issue.

**Comment by devernay** [comment]
Sorry, I couldn't grab the file on time. Can you test with Natron 2.3.3?

**Comment by devernay** [comment]
Can you please test with the latest version (2.3.10) ?

**Comment by Eneen** [comment]
Same:
[18:44:21.480] FXAA_Alpha: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

**Comment by devernay** [comment]
Please follow these steps:

- launch Natron 2.3.10
- what is the information displayed in the "GPU Rendering" section of the preferences?
- create a ShaderToy node, connect it to the viewer
- does it render something?
- click Renderer Info... What is the information displayed in the window? copy-paste it here
- uncheck "Enable GPU Render" in the ShaderToy node
- does it render something?
- click Renderer Info... What is the information displayed in the window? copy-paste it here

**Comment by Eneen** [comment]
Here is GPU info:
![obraz](https://user-images.githubusercontent.com/25537418/39203273-96ba6af0-47f4-11e8-8d2b-5e4334232b0f.png)

Shadertoy shows colored background both on CPU and GPU

Renderer info (list is really long but ctrl+c shows only this, tell me what I need to check, I will):
`---------------------------
Shadertoy1
---------------------------
<p>OpenGL renderer information:<br>
GL_RENDERER = GeForce GTX 1050 Ti/PCIe/SSE2<br>
GL_VERSION = 4.6.0 NVIDIA 390.65<br>
GL_VENDOR = NVIDIA Corporation<br>
GL_SHADING_LANGUAGE_VERSION = 4.60 NVIDIA<br>
GL_EXTENSIONS = GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_AMD_vertex_shader_viewport_index GL_AMD_vertex_shader_layer GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect G
---------------------------
OK   
---------------------------
`

**Comment by devernay** [comment]
may be fixed ny recent work on OpenGL context limits. @Eneen can you check again with the latest beta?
