### ISSUE TITLE
Add MariaDB, SQLite3 and PostgreSQL python adapters + Qt plugins to the Natron binary distrib.

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#228]
_From @devernay on November 8, 2017 13:28_

### Problem

we already ship the MariaDB/MySQL and SQLite3 Qt plugins, we should also add:

- the PostgreSQL Qt plugin
- the MariaDB/MySQL, SQLite3 and PostgreSQL python adapters:
  - http://initd.org/psycopg/
  - https://dev.mysql.com/doc/connector-python/en/
  - https://docs.python.org/2/library/sqlite3.html

_Copied from original issue: MrKepzie/Natron#1694_

**Comment by rodlie** [comment]
Why is this needed?

Also, we should use mariadb-connector, it's LGPL.

**Comment by devernay** [comment]
for database access from natron scripts/pyplugs
