### ISSUE TITLE
ColorLookup No work, no normal operation

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#229]
_From @AlphaFase on November 16, 2017 1:56_

### Problem

There is a problem with the ColorLookup node
Ubutnu16.04: no work, no crash, but black screen, no modification of attributes
Windows7-10: program crash

### Steps to Reproduce

1. add "Read" Node
2. add "ColorLookup" Node
3. Adjusting "ColorLookup" node attributes
4. bug collapse

### Versions

* **Natron version/commit** (they can be retrieved from the About Window):  2.3.3
* **OS version:** 
*  > ubuntu16.04(x86_x64) 
* > windows7(x86_x64) 
* > windows10(x86_x64)

_Copied from original issue: MrKepzie/Natron#1696_

**Comment by devernay** [comment]
can you please test again with the latest version (2.3.10) ?

**Comment by devernay** [comment]
Can someone test ColorLookup on Linux and Windows?

**Comment by ebarranco** [comment]
Hi, it's works fine in Linux manjaro kde, [here.](https://youtu.be/CKfTzjCa_QQ)

**Comment by devernay** [comment]
We'll just need a Windows test, then -> @rodlie

**Comment by rodlie** [comment]
Works on Windows, close.
