### ISSUE TITLE
Texture node: rename Gradient/Regular to Gradient/Linear

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#230]
_From @hellocatfood on November 25, 2017 15:46_

In the Texture node the backgrounds you can choose aer Gradient/Regular and Gradient/Radial.

I think the former should be changed to Gradient/Linear as it more accurately describes the type of gradient and is in keeping with software such as GIMP, Inkscape and Blender.

_Copied from original issue: MrKepzie/Natron#1700_

**Comment by rodlie** [comment]
done in openfx-arena.
