### ISSUE TITLE
Write1 Error

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#244]
_From @legoruss1 on March 27, 2018 21:8_

when I go to render a 360 video mp4 as a mp4 after stabilizing it, I get an error: Write1: can only render RGBA or RGB components images
components image is currently rgb32f. Shot on a Nikon Keymission 360
TELL ME WHAT YOU NEED

_Copied from original issue: MrKepzie/Natron#1746_

**Comment by devernay** [comment]
ideally, a project that fails

**Comment by devernay** [comment]
@legoruss1 can you help and provide a sample project that fails?

**Comment by legoruss1** [comment]
https://1drv.ms/u/s!AndYJsfTjc6Rlq1QNDhCRtrBirA1-Q 

 a link to file that will produce the error. you don't need to stabilize to produce error. just try to render as mp4. proper stabilization requires a 3rd party  plugin

**Comment by devernay** [comment]
What should the project look like? Just read this video and write a new one? What video codec did you use (there are many codecs that support the mp4 format/container)

**Comment by legoruss1** [comment]
Just read and write the video. I was using the default mp4 codec, the one that comes up when you first go to write after reading
 MP4, codec avc1. All  MP4 codecs return the same error

**Comment by devernay** [comment]
It works for me.
In the Write1 control panel, click the "Info" tab, and copy-paste the info for the Source here.

**Comment by legoruss1** [comment]
Now I can't play back in any player, windows, vlc, GOpro vr

**Comment by devernay** [comment]
did you let the render finish? Which platform are you on? there should be a ffprobe.exe binary next to Natron, can you execute it from the command-line, as in `ffprobe test.mp4` and give the output?
What Natron version are you using?

**Comment by legoruss1** [comment]
Render finished, using windows 10. I am testing another codec.

**Comment by legoruss1** [comment]
Nope didn't work. What render settings are you using?

**Comment by devernay** [comment]
default settings, on macOS. Did you find the ffprobe binary, and could you get the info from the output mp4?

**Comment by legoruss1** [comment]
Got output in vlc. Needed to update.

**Comment by devernay** [comment]
probably fixed by the WriteFFmpeg rewrite. Check out the latest beta.
