### ISSUE TITLE
Links break when Node is copied

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#245]
_From @CameraRick on March 31, 2018 23:17_

### Problem

When making a copy of a Node, links (e.g. the used channels) break. The links don't work and I can also not unlink them anymore, they stay in the state from when the copy was made. It's not adjustable either, neither through Expressions nor UI

See here: https://youtu.be/FLiSgHZsOpM

**Expected behavior:** 
Links should be properly copied, or I should at least have the ability to unlink and relink again.

**Actual behavior:**
It breaks completely.

### Steps to Reproduce

1. Create two nodes, e.g. Blurs
2. Link the R channel selector of Blur1 to Blur2
3. Copy Blur2
4. See that Blur2_1 has no working R channel selection anymore

### Versions

* **Natron version/commit**: Natron 2.3.9
* **OS version:** Windows 10 Professional

_Copied from original issue: MrKepzie/Natron#1748_

**Comment by devernay** [comment]
probably won't fix this one

**Comment by devernay** [comment]
@CameraRick I recently fixed stuff in links, can you try and check if that issue is still present in the latest beta?

**Comment by CameraRick** [comment]
I'm actually not sure where to download the latest beta, the main page only has 2.3.15 stable in stock :o

**Comment by rodlie** [comment]
Releases are available from : https://github.com/NatronGitHub/Natron/releases

**Comment by CameraRick** [comment]
Sorry I tested it and forgot to get back. @rodlie for pointing out the location!

@devernay it seems to work now, so I guess the bug can be set to fixed :)

**Comment by devernay** [comment]
Great, thanks! And thanks for your help overall, Lucas!
