### ISSUE TITLE
Docking a tab makes app to just quit

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#247]
_From @fabiof17 on April 4, 2018 21:1_

### Problem

Trying to grab a tab to dock it somewhere else makes Natron to just quit.

### Versions

* **Natron version/commit** : snapshot 2.3.10 (04-04-2018)
* **OS version**  : Linux ( CentOS 7 - Xfce )

_Copied from original issue: MrKepzie/Natron#1755_

**Comment by devernay** [comment]
works for me - can you please test with the next snapshot?

**Comment by devernay** [comment]
_From @fabiof17 on April 5, 2018 6:39_

Ok

Le jeu. 5 avr. 2018 à 08:24, Frédéric Devernay <notifications@github.com> a
écrit :

**Comment by devernay** [comment]
@fabiof17 did you test it?

**Comment by rodlie** [comment]
Still an issue?

**Comment by fabiof17** [comment]
Hi Ole-André.
No, it has been fixed, but the issue had never been closed.
You can do it.

Thanks.

Fabrice

**Comment by rodlie** [comment]
I'm actually able to replicate this issue, the crash happens in X11. it seems to be related to the system Mesa graphics stack vs. the kernel driver on older (Intel) graphics cards. Don't think this is an issue on updated distros anymore.

**Comment by ebarranco** [comment]
I'm having a crash from moving the curve editor tab, but only this tab.
