### ISSUE TITLE
could you make a flatpak for natron?

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#251]
_From @chemel9 on April 9, 2018 2:36_

Hi, I really appreciate your work , is a good application

could you make a flatpak for natron?
in this way, users can install the application in any linux distribution

please.
thank you.

_Copied from original issue: MrKepzie/Natron#1759_

**Comment by devernay** [comment]
I can't (no time for this), but anyone who knows how to do this from a directory tree can give me the recipe, and I could integrate that in the build system

**Comment by rodlie** [comment]
What is the advantage of using this vs. what we have?

**Comment by devernay** [comment]
there is a flatpak already https://flathub.org/apps/details/fr.natron.Natron
