### ISSUE TITLE
GitLab mirror and CI integration

### ISSUE THREAD

**Issue by mash-graz** [NatronGitHub/Natron#257]
because of your call at the forum concerning the build system, i already started to mirror your actual NatronGitHub repository to GitLab.

https://gitlab.com/natron

i created this new Group resp. namespace to keep it isolated from my other activities and would really like to transfer the ownership or at least adminstrator rights with you to prevent any accusation of name piracy.

but i definitely prefere GitLabs CI capabilities and transparency over GitHub!

in the meanwhile it's also possible to utillize only GitLabs CI system for projects hosted GitLab, but the repository mirroring feature and a more traditional use of GitLabs services looks more reasonable to me.

nevertheless it's always a little bit tricky to work with mirrored repositories, because changes on the mirror have to be done solely in parallel branches or have to be merged at the upstream source. and this doesn't work very well together with automatic CI build process...

but as a starting point it's perhaps the most useful compromise.

i also would really like hear your opinion about GitLab and its CI system in general -- the pro and cons of such an attempt from your point of view.

until now i didn't use GitLab for any complex crossplatform builds, but i already utilized it for docker image creation (e.g. my recent [DaVinci Resolve container](https://gitlab.com/mash-graz/resolve)) and simple in-house debian package creation. but any other job, which can by realized in privileged  docker containers should be able within this infrastructure as well.

debian packages can be even hosted via [GitLab pages](https://about.gitlab.com/features/pages/) and a little bit of help from [aptly](https://www.aptly.info/) straight out of the CI system. (here is a little [example](https://gitlab.com/mash-graz/raspi3-firmware/blob/fixes_by_mash/.gitlab-ci.yml#L34), how this works and [looks](https://mash-graz.gitlab.io/raspi3-firmware/) like) 

[and btw. i would even suggest to use gitlab pages for natrons web page, although i already asked the mur.at preseidium in the meanwhile to support your project officially with virtual host etc. i'm quite sure, you'll get an letter about their final decision soon.]

for the debian/ubuntu/mint platform we can reuse the [already available package build adaptation written by christian mariallat]( https://cse.google.com/cse?cx=partner-pub-7392075759954682:3632489811&q=natron&oq=natron&gs_l=partner-generic.3...2364.3388.0.3716.0.0.0.0.0.0.0.0..0.0.gsnos%2Cn%3D13...0.1008j227968j6..1ac.1.25.partner-generic..0.0.0.#gsc.tab=0&gsc.q=natron&gsc.page=1). this makes it quite trival, to build packages of natron and its siblings for this platforms.

but i would really like to see an inclusion of the relevant debian subdirectory within the upstream repository. this would make it a lot easier to reproduce the build even by non CI experienced individuals.

as you already know -- because i was very often asking always just the same question -- i could never find out, how the CI build process of the natron binaries was realized in the past? i always guessed, OBS could be involved, but i couldn't find a satisfaying answer until now.

if you see any chance, to reuse the existing solution or at least parts of it, i would really appreciate it. it's quite frustrating to reinvent the wheel again.

but if we have to rewrite it from scratch, i think, i could manage at least the unix platforms.
i just have to ask for a little bit of patience and unavoidable reminders, because i'm so busy with other jobs, that i can not spend to much spare time on this particular challenge.

good luck!

but i really like your project and will try my best.

**Comment by devernay** [comment]
mirroring should be easy as long as it's one-way (from github to gitlab).
For example, let's say you are in the openfx-misc directory. First, set up a remote named github that points to the github version (this has to be done only once):
```
git remote add github https://github.com/NatronGitHub/openfx-misc.git
```
then, for each branch you want to mirror (most repos use only the master branch, Natron has also the RB-2.3 branch). master is the name of the branch in the following:
```
git pull github master
git push origin master
```
Put all these operations in a script that does it for all active branches of all repos, and voilà, you have an automatic mirror on gitlab.

I don't have any time to dive into gitlab, so if gitlab is a better option than github, someone has to take care of the migration. See https://about.gitlab.com/comparison/ for a comparison of gitlab vs github.

**Comment by devernay** [comment]
> as you already know -- because i was very often asking always just the same question -- i could never find out, how the CI build process of the natron binaries was realized in the past? i always guessed, OBS could be involved, but i couldn't find a satisfaying answer until now.

There are two CI systems running right now, which built Natron, the packages, and run the unit tests:
- a system based on physical maches (one windows 7, one OS X 10.6, one centos 6.4) which build at each push, and can be instructed to upload a snapshot or a release, based on the web interface. We call it "buildmaster"
- a system maintained globally by Inria, based on Jenkins (and Cloudstack to manage the virtual machines), which builds on Windows 10 (32/64), OS X 10.9 and centos 6.4 (32/64). I never used this system for releases.
- travis is also used https://travis-ci.org/NatronGitHub/Natron but the limitations of travis are such that no testing or packaging is done - only building.

> if you see any chance, to reuse the existing solution or at least parts of it, i would really appreciate it. it's quite frustrating to reinvent the wheel again.

I am cleaning up the script that run these builds, and I will publish them very soon. They can certainly be used on other CI systems such as gitlab, but I cannot do more than publish them.

The "buildmaster" system will probably be shut down forever during summer.

**Comment by devernay** [comment]
@mash-graz can you please contact me by email?

**Comment by devernay** [comment]
@Cinerar thanks for the links. Now someone has to find time to set it up!
The main problem (that we also have with travis and appveyor) is that fully building Natron and plugins, followed by running the unit tests, takes a long time. Travis kills us at 49mn, so we can just compile Natron and the basic plugins. see https://travis-ci.org/NatronGitHub/Natron : the coverity_scan builds now almost always error.
Do you know on any similar restriction on gitlab CI?

**Comment by mash-graz** [comment]
AFAIK gitlab has a default timeout of jobs, which is set to one hour per default, but this [can be reconfigured](https://gitlab.com/gitlab-org/gitlab-ce/issues/181),  and you also have a limited budget of 2000 minutes CI time per month -- but open source project usually get sponsord by them and may use some of the EE features and more computing time...

one of the really useful features of gitlab is it's thight docker integration. this can be utilized in farious ways to reuse already computed stages and make the whole CI process and testing much more effective.

one of the really puzzling issues i see, is the multiplatform build. although the gitlab-runner can be used on nearly any plattform. wich support at least the go language, it's in fact nearly impossible to cross compile osx code from the usual linux centric usual CI environment. this is not only caused by technical reasons, but also by legal restrictions regarding use of apple software on foreign kinds of machines. :(

but i'll start with the linux platform and look, how we can extend it step by step...

**Comment by Cinerar** [comment]
Runners timeout can be reconfigured in Settings -> CI/CD Settings -> General pipelines settings -> Timeout

**Comment by devernay** [comment]
We will concentrate on moving CI to GitHub Actions (https://github.com/NatronGitHub/Natron/issues/601), which seems to be a solid system.
