### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by Sunderland93** [NatronGitHub/Natron#258]
I start working on Natron's Flatpak package https://github.com/Sunderland93/org.natron.Natron
It's very WIP, and I need to help with it.
The main problem for now is that Shiboken failed to build with ld error. Also, Qt4 builded without any patches.

**Comment by devernay** [comment]
Hi Aleksei,
Can you wait for a few more days? I will publish the full script and patches to build the Natron dependencies.

**Comment by devernay** [comment]
please check out the info in https://github.com/NatronGitHub/Natron/blob/RB-2.3/tools/README.md

**Comment by Sunderland93** [comment]
@devernay there is a LOTS OF PATCHES :) Ok, I'll update build recipe for Flatpak this weekend.

**Comment by devernay** [comment]
Checkout the build-linux-sdk.sh script in the Jenkins dir. It should work out of the box.Le 30 avr. 2018 19:59, Aleksey Samoilov <notifications@github.com> a écrit :@devernay there is a LOTS OF PATCHES :) Ok, I'll update build recipe for Flatpak this weekend.

**Comment by Sunderland93** [comment]
@devernay I open a PR on Flathub. Please, review build recipe (org.natron.Natron.json) https://github.com/flathub/flathub/pull/368

**Comment by Sunderland93** [comment]
@devernay I open new PR with cnanged name https://github.com/flathub/flathub/pull/370

**Comment by Sunderland93** [comment]
Build recipe complete and works fine. For testing it:

1) You need Flatpak >= 0.10.0 and flatpak-builder
2) git clone https://github.com/Sunderland93/flathub.git -b fr.natron.Natron
3) flatpak-builder natron fr.natron.Natron.json
4) flatpak-builder --run natron fr.natron.Natron.json Natron

**Comment by Sunderland93** [comment]
Natron's flatpak package now on Flathub https://github.com/flathub/fr.natron.Natron
