### ISSUE TITLE
Render Problems - Specific Project

### ISSUE THREAD

**Issue by unkerjay** [NatronGitHub/Natron#259]
[Flat_Anim_Dark_Horiz.zip](https://github.com/NatronGitHub/Natron/files/1958876/Flat_Anim_Dark_Horiz.zip)

I understand that:

1) I need to have a write node

2) It needs to be (according to one issue I read) "Before" the Viewer node.

So, on simple examples where the Merge is clear, I attach the Write node to the Merge (or the last in a chain Merge node.  Fill in the blanks as to type of file and location and it's off to the races.

In this particular file, the View node extends out to three different locations.  So, when I try that with a Write node, it's just not possible.

So, my questions are two:

1) What's the right way to go about applying a Write node in this instance 

and

2) When I apply the Write node to a Merge node (just to see if maybe ANY merge node will work, it goes about 38 seconds and stops dead.  Tried multiple times, same nodes, (connected to the bottom most Merge node) same results

Thanx

**Comment by devernay** [comment]
The write node must be separate from the viewer, not linked together. Think of the viewer as a voltmeter that you can use to check the voltage at different places in your graph.Le 29 avr. 2018 17:43, unkerjay <notifications@github.com> a écrit :Flat_Anim_Dark_Horiz.zip
I understand that:

I need to have a write node

It needs to be (according to one issue I read) "Before" the Viewer node.

So, on simple examples where the Merge is clear, I attach the Write node to the Merge (or the last in a chain Merge node.  Fill in the blanks as to type of file and location and it's off to the races.
In this particular file, the View node extends out to three different locations.  So, when I try that with a Write node, it's just not possible.
So, my questions are two:
What's the right way to go about applying a Write node in this instance
and
When I apply the Write node to a Merge node (just to see if maybe ANY merge node will work, it goes about 38 seconds and stops dead.  Tried multiple times, same nodes, (connected to the bottom most Merge node) same results
Thanx

**Comment by devernay** [comment]
I don't understand the issue with that project, but this looks more like a "help needed" question. You should ask that on the forum https://discuss.pixls.us/c/software/natron
This place is more for bug reports.
If I may give you an advice when starting with Natron: when developing a project, *always* prefer writing individual frames (EXR, TIFF, whatever you want) than a single video file. Write the video file when everything is working.

**Comment by unkerjay** [comment]
Does it have to connect to anything?

If it doesn't, I get an error.

If it connects to the Viewer node I get an RGB / RGBA error.

And, so far, everywhere else I've connected, it fails.

Not just what's the proper way to connect, but, in looking at a project
with multiple merges at different points, how best to determine where the
write node should be to accurately render the project.

I'm confused at this point.

**Comment by cgvirus** [comment]
@unkerjay please join here for non bug issues for discussion:
https://discuss.pixls.us/c/software/natron
Or in facebook community.
