### ISSUE TITLE
Linux binaries should not depend on libselinux.so.1

### ISSUE THREAD

**Issue by PostPollux** [NatronGitHub/Natron#265]
### Problem

I have two Notebooks. Both run the latest version of Linux Manjaro with all updates installed. Both run Natron 2.3.10 fresh installed with no settings adjusted.
Notebook 1: Intel Core I7 4710 MQ, GTX 765M, 16Gb memory
Notebook2: Intel Core I7 8550-U, Intel UHD Graphics 620, 16Gb memory

On Notebook 1 everything works fine. With Notebook 2 however the read node does not work!
Each time I want to read a file I get the following message:
Error while creating node fr.inria.built-in.Read: Could not find a decoder to read jpg file format
or
Error while creating node fr.inria.built-in.Read: Could not find a decoder to read mp4 file format
or
Error while creating node fr.inria.built-in.Read: Could not find a decoder to read png file format

Of course depending on which file type I try to open. None is working. This message is the same, directly as popup in Natron and in terminal. Unfortunately there is no additional information in the terminal.

The rest seems to work. I can add things like a plasma noise or even the new lensflares from the pyplugs and then colorcorrect or chang stuff. Only read is not working.

Any idea how to resolve this issue?

### Steps to Reproduce

Hard, because it seems you need my Notebook 2

**Comment by devernay** [comment]
You probably installed other versions of the Natron plugins. Is there anything in `/usr/OFX/Plugins` on that laptop?
On both laptops: Clear the Plugins Load Cache, then launch Natron from a terminal (usually `/opt/Natron2/bin/Natron` or `~/Natron2/bin/Natron`), and compare the messages that appear.

**Comment by PostPollux** [comment]
Thanks Devernay!
Your hint helped me and I got it working. The problem was that the library "libselinux.so.1" seems not to be available by default in Linux Manjaro. I now remember that I manually installed it long time ago on my Notebook1 in order to run an AppImage of Kdenlive. That's why Natron worked on this machine without complaining.

It seems as if both Arena.ofx.bundle and IO.ofx.bundle are depending on libselinux.so.1.

Do you think it's possible to ship this library by default with Natron so that it works out of the box on Linux Manjaro?

Here is the terminal log:
`Natron Version 2.3.10
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
couldn't open library /home/johannes/Downloaded_Programs/Natron2/Plugins/OFX/Natron/Arena.ofx.bundle/Contents/Linux-x86-64/Arena.ofx because libselinux.so.1: cannot open shared object file: No such file or directory
couldn't open library /home/johannes/Downloaded_Programs/Natron2/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64/IO.ofx because libselinux.so.1: cannot open shared object file: No such file or directory
Info: init.py script not loaded (this is not an error)
Info: initGui.py script not loaded (this is not an error)
libpng warning: iCCP: known incorrect sRGB profile`

**Comment by devernay** [comment]
It would be better to get rid of the libselinux dependency if possible. Since this is a security-related component, it would not be a good thing to ship it with Natron. Two libraries are affected:
```
Binary file /opt/Natron-sdk/lib/libgio-2.0.so matches
Binary file /opt/Natron-sdk/lib/librsvg-2.so matches
```
but the only affected component seems to be gio-2.0, which is part of glib2. I'll try new glib2 builds with selinux disabled (`--disable-selinux` in the configure options), and rebuild also librsvg.

@Sunderland93 are you also building glib2 in the flatpak? https://github.com/NatronGitHub/Natron/issues/258 If yes, you should consider disabling selinux support too too.

**Comment by devernay** [comment]
New linux binaries for 2.3.11 are being built

**Comment by Sunderland93** [comment]
@devernay I use glib2 from flatpak SDK bundle. But I dont't know if it SeLinux-enabled.

**Comment by devernay** [comment]
@PostPollux new linux binaries on the web site. can you please check that it works on the machine without selinux?

**Comment by PostPollux** [comment]
Just installed it and it works fine now without the library being installed on the system. Thanks a lot Devernay!
