### ISSUE TITLE
Shadertoy: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#268]
### Problem

from that FB message: https://www.facebook.com/groups/NatronNation/permalink/983476598486575/

![32226772_10155916181989902_8077641591696654336_n](https://user-images.githubusercontent.com/3778071/39879955-8fd89984-547c-11e8-8d9c-d68f5da17ae3.jpg)

### Steps to Reproduce

1. Create a ShaderToy node (or any PyPlug that uses a Shadertoy)
2. Connect it to a viewer

### Troubleshooting

Here's what you should do, and the information you should report:

1. Is the error message you got the same as in the image above? If not, please give the full message.
2. in the Shadertoy node, click "Renderer Info..." and post the OpenGL version (which should be greater than 2.0) and the renderer name. Are the required extensions are in the list?
3. in Natron Preferences / GPU Rendering, is the displayed info consistent with what "Renderer Info..." above gave?
4. now uncheck "Enable GPU Render" in the Shadertoy node and click the refresh/recycle button on the top of the viewer. Click again "Renderer Info..." and it should say it now uses Mesa. Does it?
5. to temporarily fix this issue, in Natron Preferences / GPU Rendering, set "OpenGL Rendering" to "Disabled", **apply** changes, and **relaunch** Natron. Does that fix the issue?
6. Does the "Renderer Info..." in step 1. say it is using your graphics card? If not, you may have the wrong GPU drivers installed, please check if there are OpenGL dirivers available from your GPU manufacturer.

**Comment by fabiof17** [comment]
I have this this since the first version of Natron i've downloaded, 2 years back.
It happens sometimes on Linux. On Window 7 it's just nightmarish...(Quadro 4000)

**Comment by devernay** [comment]
@fabiof17 please follow the steps above and report the results

**Comment by BrowePankin** [comment]
Hi,
I got the described error. Natron 2.3.12. I cracked Troubleshoting help at it. It doesn't work for me.

OpenGL renderer information:
GL_RENDERER = GeForce GTX 660/PCIe/SSE2
GL_VERSION = 4.6.0 NVIDIA 397.93
GL_VENDOR = NVIDIA Corporation
GL_SHADING_LANGUAGE_VERSION = 4.60 NVIDIA
GL_EXTENSIONS = GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanc
---------------------------

**Comment by devernay** [comment]
@BrowePankin  your message was cut, can you please edit it? I don't need the full extensions list, just check that the required one is there.
Can you please give all the information from the top post? There are 6 questions.

**Comment by devernay** [comment]
OK, but can you please give the answers to all 6 questions from the top message (these are mostly yes/no)?
Actually I don't need the full list of extensions, only to check if GL_ARB_texture_non_power_of_two is within them (which is the case).

**Comment by BrowePankin** [comment]
1. Yes
2. GL_RENDERER = GeForce GTX 660/PCIe/SSE2
    GL_VERSION = 4.6.0 NVIDIA 397.93
    Yes. Present.
![image](https://user-images.githubusercontent.com/6229204/40679893-bc921920-6384-11e8-8379-19658f2779e2.png)
3. Yes.
![image](https://user-images.githubusercontent.com/6229204/40679981-f7a215ce-6384-11e8-994f-0b4342de3e18.png)
4. Yes
![image](https://user-images.githubusercontent.com/6229204/40680075-3af68346-6385-11e8-8c07-3663577bdec4.png)
5. No. Doesn't fix it.
6. Alert from step 1 is not visible.

**Comment by devernay** [comment]
@BrowePankin about step 5: did you set the preference to "Disabled", click "Save" in the preferences window, quit Natron nicely, launch Natron, check that it's still "Disabled", and test if the error still appears? I would be very surprised if switching to CPU-only rendering did not fix the issue.

**Comment by BrowePankin** [comment]
Yes, I did it.
If I use only Shadertoy the render is O.K. The problem above is comming when I use other sources like texts.

**Comment by rodlie** [comment]
I believe this is related to the OpenGL context issue. Should be fixed?

**Comment by fabiof17** [comment]
It's a very long time issue.

**Comment by rodlie** [comment]
Just bump the OpenGL context from 2 to something higher will "fix" it. I'm unsure if we have committed a fix for this, will need to check.

**Comment by rodlie** [comment]
Note that OpenGL context problem is a major issue, especially on Windows. On several machines I can't use anything Shadertoy related, just end up with GL_VERSION missing popup after a couple of frames, and Natron must be restarted.

On my newest machine setting context above 2 does not work anymore.

EDIT: I now need 10 contexts for some reason, well at least it works.

**Comment by devernay** [comment]
this may be fixed when we switch to Qt5 (Natron 2.6)
