### ISSUE TITLE
"Clear Plugin-ins Load Cache" was required on 2.3.11 install

### ISSUE THREAD

**Issue by torbach** [NatronGitHub/Natron#272]
Natron ceased reading/writing video

[14:32:20.055] 
Project: ERROR: The node fr.inria.built-in.Read version 1.0 was found in the script but does not exist in the loaded plug-ins.
[14:32:20.061] 
Project: ERROR: The node fr.inria.built-in.Write version 1.0 was found in the script but does not exist in the loaded plug-ins.

I did a fresh install..
Natron 2.3.11 
Windows 10

the fix  

Cache > **Clear Plugin-ins Load Cache**

**Comment by devernay** [comment]
This is really strange, since each version of Natron builds its own plugin cache. I'm closing this, and will reopen if other people have the same issue.
