### ISSUE TITLE
'DenoiseSharpen' node makes a crash

### ISSUE THREAD

**Issue by sus-unn** [NatronGitHub/Natron#273]
Problem
---------

DenoiseSharpen node makes a crash. Sometimes when I tweak values, sometimes right after I open the project. (with DenoiseSharpen node)

Crash log
-----------

I executed from the terminal to see crash log, but Natron only makes short message:
```cmd
Spawned process crashed, exiting.
```

Steps to reproduce
---------------------

1. Create new project
2. Import footage and connect it as a source to DenoiseSharpen node
3. Natron crashes while tweaking some values of node.
4. If I open the project again, it crashes after loading.
5. It may not, but goes back to 3 anyway

Versions
----------

Natron version - 2.3.10 64bit
OS - Windows 10 64bit /version 1709 / build 16299.431
AMD Ryzen 8 core Processor
16GB of RAM

**Comment by devernay** [comment]
Can you please test with the latest snapshot?

**Comment by sus-unn** [comment]
You mean latest commit or latest (stable) release?

**Comment by devernay** [comment]
I mean the latest snapshot that can be downloaded from natron.fr. On windows it is currently 2018-05-16.
You can also test with 2.3.11, but snapshot is preferred (requires having an account on natron.fr)

**Comment by sus-unn** [comment]
I don't know what is actually changed in the code but it seems it is stable now. Thanks!!
