### ISSUE TITLE
'GMIC Add Grain' node is trying to find wrong file

### ISSUE THREAD

**Issue by sus-unn** [NatronGitHub/Natron#278]
### Problem

While using 'GMIC Add Grain' , it tries to find an file in a directory that not exists.

**Expected behavior:** 
Before I found this error, 'GMIC Add Grain' node did not made any problem, so I expected it to be.

**Actual behavior:** 
Error message:
```
[05:23:21.889] GMIC_Add_grain2: *** Error in ./fx_emulate_grain/__fx_emulate_grain/*if/ *** gmic::fopen(): Failed to open file 'C:\Users\(my_username)\AppData\Roaming\gmic\grain_orwo_np20.cimgz' with mode 'wb'.
```
Problem is that in my computer, directory "gmic" doesn't even exists in "...\Roaming". 
(And the node is effecting nothing.)

### Steps to Reproduce

I can't explain detail of this because it worked without any matters til now.
I used it as usual. Only difference I know is that I uninstalled 2.3.10 and installed 2.3.11 recently.
Anyway here is screenshot of my node tree:
![image](https://user-images.githubusercontent.com/36620824/40388777-5f635108-5e4b-11e8-918b-72a59ad481dd.png)

### Versions

* **Natron version/commit** 
Natron version 2.3.11 fe372c9
* **OS version:** 
on windows 10. x86-64.

**Comment by devernay** [comment]
Do other windows users have this same issue?
Can you please test with the latest snapshot?

**Comment by devernay** [comment]
Closing, as we've not received feedback.
Also note the following (from the About G'MIC node):

If, for any reasons, your plug-in is unable to retrieve data from the Internet, you can download all those data files manually (as a single .zip file) at this address :

https://gmic.eu/gmic_all_data.zip

You must then decompress all files contained in this archive at the following location:

    for Unix-like systems : $HOME/.cache/gmic/
    for Windows systems : %APPDATA/gmic/
