### ISSUE TITLE
Timeline ticks not visible with GCC 8.1 to 9.1

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#279]
![76b416243d6cda9d308cc1a49141c8cebd4e31f4](https://user-images.githubusercontent.com/3778071/40421232-6b15c13a-5e8b-11e8-9ecb-90ce0b09ed7b.jpg)

see https://discuss.pixls.us/t/any-issue-with-a-natron-snapshot-please-discuss-here/7794/3

**Comment by devernay** [comment]
- release 2.3.10 was compiled with 7.3 and is OK
- release 2.3.11 was compiled with 8.3, and ticks are only visible when zooming a lot on the timeline
- snapshots compiled with GCC 8.1 don't have ticks except when zooming a lot
- snapshots compiled with GCC 7.3 are OK

I'm leaving this issue open until someone finds out what happens when using GCC 8, whether it is in ticks.cpp or TimeLineGui.cpp

**Comment by Teteros** [comment]
I can't reproduce this on Arch Linux

![ss](https://user-images.githubusercontent.com/5067989/40577777-adffed9e-6102-11e8-961b-169ae031d67a.png)

- Commit: 62162d2a02295962d991af54cd00ea3addbfdfde (one commit before `GUI: timeline is wrong with GCC 8.1`, and after v2.3.12 tag)

- `$ gcc --version` gcc (GCC) 8.1.0
- `$ qmake-qt4 --version`                                                                                                                                        
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib

PKGBUILD: https://gist.github.com/81fcda037a3724c3ae2ee7346508986b

**Comment by devernay** [comment]
It only happens in release builds on our build system (compiled with -O2 -g -fopenmp). I don't know if it's a bug in our code or in GCC, but reverting the compiler to GCC 7.3 fixed the issue.

**Comment by devernay** [comment]
and you can now also add CONFIG+=enforce-gcc8 if you want to take the risk

**Comment by cgvirus** [comment]
Seems to be solved in gcc version 8.3.0 
(Debian 8.3.0-4)

**Comment by yomgui1** [comment]
I've made a build of Natron using a Fedora 29 under a Docker image, with only system provider compiler, libraries and sdk, not the Natron SDK. Except for OpenFX-IO and SeExpr not found on Fedora repo.

I've attached two capture of the first launch: first is with Debug, second is in Release mode.
The Timeline looks ok for me but as I've just discovered Natron I can tell if there is something missing.

**Compiler**: gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
**Debug build made with**: qmake -r CONFIG+=debug
**Release build made with**: qmake -r
**Natron GIT SHA1**: cc97d59ade423ae241a3c2823aa66ca8ff837329

![capture natron 20190503 - debug](https://user-images.githubusercontent.com/8989517/57172879-316a2b00-6df4-11e9-85b5-14970878fde1.png)

![capture natron 20190503 - release](https://user-images.githubusercontent.com/8989517/57172886-4646be80-6df4-11e9-95cd-15ca84e576e4.png)

Note: my host Fedora 29 running under X11, not wayland.

**Comment by devernay** [comment]
@yomgui1 you need a patched Qt4 to get a proper build of Natron. Also, did you compile it with the proper flags (see above)?

**Comment by yomgui1** [comment]
I'm using system provided Qt4. Fedora may use patches to make their packages. I need to check what Natron patches do. I've removed the #error before compiling, for sure.

**Comment by devernay** [comment]
The Qt4 patches come from major sources (debian, homebrew, etc). These are curated by myself and solve many issue in Qt 4.8.7 (which is not officially maintained anymore).
The qtbase-threadpool patch, which is not included in any distro, is important to make the Natron thread pool efficient.
You should not use a system-provided Qt4 to build official Natron binaries, as they will miss some functionality

**Comment by devernay** [comment]
Reopening, see https://discuss.pixls.us/t/natron-2-3-15-prerelease-available-for-mac-and-linux/13439/3

**Comment by ebarranco** [comment]
Yes @devernay  the ticks reappear when I zoom a lot on the timeline.

**Comment by rodlie** [comment]
So, this issue was introduced in GCC 8.1? or GCC 8.0? If it's in the minor release is should be possible to diff the release? Has anybody tested the last GCC 8 release (.3)?

**Comment by devernay** [comment]
gcc 8.1 is the first gcc 8 release. Minor revisions have practically disappeared and are only for pre-releases. https://www.gnu.org/software/gcc/develop.html


The strange thing is (as far as I remember, because I cannot test it) that the other sliders (ie params) were not affected, but I would check if sliders for int params are affected, because that may have something to do with ints.

I would try to compile with GCC 9.1 but disable optimization (-O0) for ticks.cpp and TimeLineGui.cpp (make all, then remove the two .o, then make CXXFLAGS=...).
If it disappears, then we're on the good track. Then I would try with -O1 and -O2. Then add printfs to track down the difference.

OR

we could just revert to GCC 7.4 (the latest in the GCC 7 series), which shouldn't be affected, or GCC 7.3 if the bug is also in 7.4.

**Comment by rodlie** [comment]
Ok, will try to track down the issue this weekend.

Reverting to GCC7 will require some work on Windows since I will need to rebuild everything (from MSYS) against a new GCC or revert to a snapshot from 2018 (that includes GCC7) and rebuild the most critical packages.

**Comment by devernay** [comment]
yes, the best solution for now would be to just compile the source that exhibits the bug with lower optimization.

**Comment by rodlie** [comment]
Did a quick test on Windows and the timeline breaks when using -Ofast

**Comment by devernay** [comment]
Then it's probably a problem on our side, where we make an assumption about the result of a math operation that is false with -ffast-math. Could you try with -O2 -ffast-math? Could you track down where it diverges using qDebug or printfs?

**Comment by rodlie** [comment]
I might have found another issue related to this.

I was having problems getting output from the Text node in Windows yesterday when I discovered that the issue was in Natron. The RGBA params does not work and always return 0 (to the plugin), the knob UI also acts very strange (see video).

I can only replicate this on Windows.

See video: https://youtu.be/bcalZ3aeYb0
- 'Solid' works, it uses RGB params
- 'Radial' (or any plugin using RGBA params) don't work. Notice that whatever changes I do in the colordialog is not applied, and I only get black to white (no color) on the knob. The R, G, B, A values are returned as 0 to the plugin.

**Comment by rodlie** [comment]
'-Ofast' is not related to the Windows RGBA-param issue. I'm currently installing an older (known working) version of MSYS (with GCC 7) as a backup SDK.

**Comment by devernay** [comment]
It looks like a badly connected signal/slot: the value should be updated live and a new render should be triggered.
- Also, please first switch the RGBA param to "4" and set different values. For some reason it stays in single-value mode whereas it should switch to "4".
- What happens if you set the values manually and don't use the color dialog?

Everything is in KnobGuiColor, especially in KnobGuiColor::showColorDialog() if it's only related to the use of the color dialog

You should really try to debug/track down the issue rather than testing different compilers/libraries. Having to change a library or compiler is a very fragile fix.

**Comment by rodlie** [comment]
If I change the values manually it kind of works, the color knob has the correct color, but the plugin gets 0. If I click the color dialog button it starts with 0 (as with the plugins, seems like the color value in the param is 0), when I adjust the color in the dialog the param force switches to single-value mode. Will start debugging the issue.

Regarding the SDK, I just want to have something working on the side, just in case. The goal is to get it working on current MSYS of course.

**Comment by rodlie** [comment]
So, got an small update on the Knob RGBA issue.

I ended up in ```Knob getValue```. The return value from ```clampToMinMax``` is always -0, so that's the reason the knob and dialog are wrong, but why I don't know (If I set clamp=false and get the knob working I still get 0 in the plugin).

**Comment by devernay** [comment]
clampToMinMax os probably also called when the plug-in executes getvalue

**Comment by devernay** [comment]
I updated the linux builds in 2.3.15-pre5, using a fix suggested by @yomgui1 in https://github.com/NatronGitHub/Natron/pull/412
Can someone please check if the ticks stuff is fixed?

**Comment by rodlie** [comment]
ticks works on Linux and Windows.

**Comment by devernay** [comment]
Great! Let's close the issue, then! I've also fixed many more calls to std::pow. @rodlie and @yomgui1 can you check that I did things right, especially in ViewerGL.cpp where we were seemingly doing useless stuff.

**Comment by yomgui1** [comment]
looks good to me

**Comment by blackearth2014** [comment]
When will the windows version be ready for testing.

**Comment by rodlie** [comment]
Not sure, the knob issue must be resolved first, sadly I'm a bit behind on this as I have not been home that much this last week (I don't have Windows on my laptop).

I will be home most of this week so I will try to find a solution.

**Comment by blackearth2014** [comment]
Cool breeze

**Comment by ebarranco** [comment]
Yeah! the timeline is back to normal in Natron 2.3.15 RC6.

**Comment by rodlie** [comment]
Some more info regarding the Windows Knob issue:

The knob ``_minimums`` and ``_maximums`` are wrong on 4 dimensions. Mins/Maxs are ok until ``OfxRGBAInstance::setRange()`` is run, there the values are set to -0 and 0.

https://github.com/NatronGitHub/Natron/blob/3a065c6f5c849c5878f8023c4d02613e8a53e5d1/Engine/OfxParamInstance.cpp#L1969

**Comment by devernay** [comment]
Closing this issue since ticks are back. Thanks @yomgui1 .

@rodlie can you please file a separate issue with the relevant information for the RGBA Knob issue?
