### ISSUE TITLE
Needs screenshots

### ISSUE THREAD

**Issue by Sunderland93** [NatronGitHub/Natron#281]
It would be nice if we added some screenshots on:

1) Natron's site
2) Natron's GitHub page
3) Natron's Appdata file (to show in software managers, like GNOME Software)

Related issue https://github.com/flathub/fr.natron.Natron/issues/1

**Comment by devernay** [comment]
The web site should be switched to https://natrongithub.github.io/Fahad/ by @cgvirus which has a few screenshots, but maybe you can contribute more?

Feel free to use the sample projects (baymax and spaceship) to produce screenshots - I wish someone could also start an open tears of steel projects.

We can add you to the web team if you want. @aditiapratama @fabiof17 @blackearth2014 are other members.

Also, flatpak distribution should be mentioned in the download section.

The new web site also needs some text (it's mostly lorem ipsum for now) and more proofreading by native English speakers.

**Comment by Sunderland93** [comment]
> The web site should be switched to https://natrongithub.github.io/Fahad/ by @cgvirus which has a few screenshots, but maybe you can contribute more?

I'm not a web designer, so I do not know how to properly add screenshots to this site

**Comment by Sunderland93** [comment]
I only may put some screenshot to main page on GitHab

**Comment by aditiapratama** [comment]
@Sunderland93 can you upload the screenshot to Fahad/img directory? after upload just make a pull request.

Below the current file structure for image location,
![image](https://user-images.githubusercontent.com/982553/40580802-2947c774-6171-11e8-8212-3de3925d4eae.png)

**Comment by Sunderland93** [comment]
@aditiapratama Ok
