### ISSUE TITLE
Migrating to GitLab?

### ISSUE THREAD

**Issue by Sunderland93** [NatronGitHub/Natron#287]
After Microsoft is bought GitHub, many organizations have migrated to GitLab. Does Natron consider the possibility of switching to Gitlab? Or mirroring to GitLab?

**Comment by devernay** [comment]
I don't see the point. Anyone is free to mirror the code anywhere, but that's pure waste of time. 

Microsoft won't steal the code, it's GPL. Microsoft is also commited to open source software. Microsoft has been a member of the linux foundation for a longer time than GitLab.

Gitlab is also a private company, and may also be bought some day by another company (they already bought one, gitorious). So let's say Apple buys Gitlab, what will those open source projects do?
