### ISSUE TITLE
DNG Importing Broken in 2.12 and 2.11

### ISSUE THREAD

**Issue by ThomasMorley-T3D** [NatronGitHub/Natron#288]
Please ask questions ("how do I...?") on the [forum](https://discuss.pixls.us/c/software/natron), not by filing issues.

Please read carefully the [Troubleshooting](http://natron.readthedocs.io/en/rb-2.3/guide/getstarted-troubleshooting.html) section of the [Natron documentation](http://natron.readthedocs.io) before submitting an issue: this issue may already be signaled, or may have a simple workaround.

Make concrete suggestions for fixing the code ("here is a patch") by filing
a [pull request](https://github.com/MrKepzie/Natron/pull/new/master), not an issue.

### Problem

DNG Importing Broken in 2.12 and 2.11

**Expected behavior:** 
Load DNG

**Actual behavior:**

Didn't load got an error

 * If your problem can be reproduced using a Natron project, please include a link to the project on a file sharing service, or attach the project as a zip file to this issue, if possible.
 
 * If your problem is a crash in an official release/snapshot, please include verbose output from the application
 from a terminal if possible.  If you also submitted a crash report, indicate the CrashID if possible.
 
 * If you need to report a compilation issue, please create a [gist](https://gist.github.com)
 that contains the _full_ verbose build log.
 
 * If your problem is a crash in a build that you made yourself, please create a [gist](https://gist.github.com)
 that contains a _full_ backtrace.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
* **OS version:**

**Comment by ThomasMorley-T3D** [comment]
![34862074_10155979489054902_7098085690373570560_n](https://user-images.githubusercontent.com/11800663/41196381-4a9534e6-6c04-11e8-9ff5-3f594c1b1b4a.jpg)

**Comment by devernay** [comment]
This is a platform-dependent issue with the image reader (OpenImageIO,) so please:

- give the OS on which the issue happen
- give me the OpenImageIO info (create a reader, locate a jpeg, and click the OpenImageIO Info.. push button in the parameters panel). dng is probably not in the list of supported suffixes, but the libraw version is also important. I don't keep track of which libraw version was used to produce each binary.

Here's for example the info on Natron 2.3.12 macOS, which loads DNG.

![capture d ecran 2018-06-10 a 12 33 45](https://user-images.githubusercontent.com/3778071/41200729-9703484e-6caa-11e8-9985-141478a475ed.png)

**Comment by devernay** [comment]
Also, clear the OpenFX plugins cache, and on next load check for "missing DLL" messages in the console;

**Comment by devernay** [comment]
I just checked on windows, and it works with 2.3.12. It reads https://www.camerafv5.com/files/photos/raw1/calella1.dng from https://www.camerafv5.com/pages/raw-samples.php
Here's what OpenImageIO gives on my machine (windows 7):
![capture d ecran 2018-06-10 a 14 38 08](https://user-images.githubusercontent.com/3778071/41201665-03c50114-6cbc-11e8-9236-0bc36287a032.png)

Note that if your camera is one of the 84 cameras that will be added in libraw 0.19, then of course it's not supported in libraw 0.18. Libraw 0.19 is still beta.
https://www.libraw.org/download#changelog-beta

**Comment by ThomasMorley-T3D** [comment]
Thanks Fred. The issue is from William Young on FB. I asked him to drop over here and discuss the issue further.

**Comment by devernay** [comment]
OK, got it.
On Linux 64, OIIO is compiled without libraw support.
![screenshot from 2018-06-11 09-45-56](https://user-images.githubusercontent.com/3778071/41218801-93a2bec0-6d5c-11e8-84da-a7c904fb8117.png)

**Comment by devernay** [comment]
2.3.12 is fixed on Linux:
![screenshot from 2018-06-12 09-12-31](https://user-images.githubusercontent.com/3778071/41275312-c955e186-6e20-11e8-84bc-0be0ed7d21ab.png)
2.3.11 will be updated too
