### ISSUE TITLE
Tracker in "Transform" mode does not take into account the Center when Rotate != 0 or Scale != 1

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#289]
### Problem

Tracker in Match-Move mode works OK when Motion-Type is set to CornerPin in Tracker, not if set to Transform, UNLESS Center is set to 0,0.
BUG: the transform should depend on the center, and should be recomputed whenever the center is changed

Problem first noticed in https://discuss.pixls.us/t/two-point-tracking-am-i-doing-it-right/8009/10

**Expected behavior:** [What you expected to happen]

Translate parameters in the Transform should depend on the Center parameters.

**Actual behavior:** [What actually happened]

If Center is not set to 0,0 and there is a rotation component (Rotate != 0), the result is wrong.

### Steps to Reproduce

See attached project.
Whenever the Center is set to anything else than 0,0, the transform is wrong.

[trackertransformbug.ntp.zip](https://github.com/NatronGitHub/Natron/files/2101368/trackertransformbug.ntp.zip)
![image](https://user-images.githubusercontent.com/3778071/41399545-e3a36bda-6fba-11e8-968c-c4c796b4b387.png)

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 2.3.12
* **OS version:** all (tested on macOS)

**Comment by blackearth2014** [comment]
Wow. Thanks for fixing this. I had reported this issue almost over a year ago and posted a workaround by zeroing the transform center.

**Comment by blackearth2014** [comment]
It was over a year ago and I may have contacted Alex about personally.
