### ISSUE TITLE
2.3.12 dmg (for mac?)

### ISSUE THREAD

**Issue by brianmorton** [NatronGitHub/Natron#290]
Will there be a DMG for macOS?

**Comment by devernay** [comment]
It has been available for one month, both on SF and on natron.fr.
https://sourceforge.net/projects/natron/files/OSX/Universal/releases/
https://sourceforge.net/projects/natron/files/OSX/x86_64/ (64-bit only)

What is your issue exactly?

**Comment by brianmorton** [comment]
No issue, per se :)

I am a contributor for homebrew and was trying to maintain the latest version of your binary, but we use the releases page on github as a log of the latest release. Since there were no new DMGs included with the new versions, I thought I would reach out to see if there were binaries available somewhere else so that I could continue to maintain this.

Thank you.

Will there be a DMG going forward for all releases (I see 2.3.13 was just released)?

**Comment by devernay** [comment]
It's safer to download from sourceforge: I don't know how long natron.fr will stay up.
I may also put a 64-bit-only binary of 2.3.13 on SF (working on 10.9 and newer).
