### ISSUE TITLE
NatronRenderer 2.3.13 crash on quit (windows 10)

### ISSUE THREAD

**Issue by juliensilvestre** [NatronGitHub/Natron#291]
### Problem

NatronRenderer crash after rendering

**Expected behavior:** Rendering a simple .ntp file with one read and one write node via natronRenderer crash

**Actual behavior:** Crash after rendering the frame

### Steps to Reproduce

1. create a natron file with a read node connected to a write, save the file
2. running in commandline : NatronRenderer file.ntp
3. crash see below:
![crash](https://user-images.githubusercontent.com/17400092/42034450-5c9356b0-7ae0-11e8-8fcf-703d2d18c2d8.png)

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 2.3.13
* **OS version:** windows 10

**Comment by devernay** [comment]
This is a known issue, Natron often crashes when quitting, same for NatronRenderer. Nicely quitting complicated software such as Natron is not easy. Someone has to debug this.

**Comment by devernay** [comment]
This may be fixed by https://github.com/OpenImageIO/oiio/pull/2013 (fix included in OpenImageIO 1.8.5).
Someone has to build new windows binaries with OIIO 1.8

**Comment by rodlie** [comment]
Natron (on Windows) might hang on exit (after render, probably also related to OIIO), but does not crash anymore. Closing this issue.
