### ISSUE TITLE
SVG Files: Showing Wrong Pixel Format Errors

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#292]
Submitted by @blackearth2014  on the forum as https://discuss.pixls.us/t/svg-files-showing-wrong-pixel-format-errors-natron/8190

Natron 2.3.13 has a problem with displaying SVG files from Inkscape and Adobe illustrator color layer channels and layer alpha channels.

The image below shows the image as Color.RGB when no problems.

![](https://pixls-discuss.s3.amazonaws.com/original/2X/f/f701150ce3130dc10d0de4910e306feac18bf376.png)

The image below gives an error about wrong pixel values when trying to display and animate the additional color channel layers.

![](https://pixls-discuss.s3.amazonaws.com/original/2X/4/439dcb0b473c4edb3e528b8f5803514fff232530.png)

If anyone experiencing this current problem and have a workaround for the time being, please advise.

https://pixls-discuss.s3.amazonaws.com/original/2X/1/11d411c082bb7431f0166df73d95cabfcde97432.7z

Problem does not happen in 2.3.12

Probably due to https://github.com/NatronGitHub/openfx-arena/commit/a645fa74533bbeba83ea6134d0c8c6f649cec49d#diff-be8e42e88aea5562d001fcfbebfb7e97R207

SVG File:

[Untitled-1.svg.zip](https://github.com/NatronGitHub/Natron/files/2155139/Untitled-1.svg.zip)

**Comment by devernay** [comment]
@blackearth2014 please test next snapshot

**Comment by blackearth2014** [comment]
It works perfectly now. 

Thanks
Fred

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/openfx-io/commit/aaa4cdae52f77eeedbdfc9aa4c70696b85b1e744
