### ISSUE TITLE
Natron 2.3.13 don't import video files

### ISSUE THREAD

**Issue by demohero101** [NatronGitHub/Natron#293]
### Problem

Latest version don't import  video files and latest installation package was blocked by windows smartscreen. Some tools are missing as well.

Windows 10 pro 64 bit

![dontimport](https://user-images.githubusercontent.com/40764199/42165028-0ffbc336-7e10-11e8-9a0a-274a18f5d2bb.jpg)
![lack of menus](https://user-images.githubusercontent.com/40764199/42165029-1025e99a-7e10-11e8-8d3e-c7700e190bdb.jpg)

**Comment by devernay** [comment]
actually the console output is very often much more informative
