### ISSUE TITLE
GMIC_Blur_depthoffield broken 11 or 23 arg that's the question !

### ISSUE THREAD

**Issue by Jau-Al** [NatronGitHub/Natron#295]
### Problem

GMIC_Blur_depthoffield1: *** Error in ./ *** Command 'fx_blur_dof': Undefined argument '$12', in expression '$12' (for 11 arguments specified).

**Expected behavior:** [What you expected to happen]
For the poor last argument to be specified ?

**Actual behavior:** [What actually happened]
error *error bip* error etc...

 
 * If your problem is a crash in an official release/snapshot, please include verbose output from the application
```
~$ Natron
Natron Version 2.3.13
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
Info: init.py script not loaded (this is not an error)
Info: initGui.py script not loaded (this is not an error)
Loading project: /media/donnees/Capture/Videos/English/Natron/TiltShifting/Videos/Demo/demo.ntp

- Error encountered when calling G'MIC : '*** Error in ./ *** Command 'fx_blur_dof': Undefined argument '$12', in expression '$12' (for 11 arguments specified).'

```
### Steps to Reproduce

1. Add GMIC_Blur_depthoffield node
2. If error is not displayed, try changing a parameter value.]

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

https://chezjau.studio/ExtLinks/GMIC_Blur_depthoffield_broken.png

### Versions
Natron version 2.3.13 Release.
Python 2.7.15
Qt 4.8.7 / 4.8.7
Boost 1_67
Cairo 1.14.12 / 1.14.12
Hoedown 3.0.7 / 3.0.7
Ceres 1.12.0
OpenMVG 0.9.0
OpenGL renderers:
GeForce GTX 1070/PCIe/SSE2 from NVIDIA Corporation
OpenGL version 4.6.0 NVIDIA 390.67 with GLSL version 4.60 NVIDIA
Ubuntu 18.04 but linux kernel 4.17.8

**Comment by devernay** [comment]
not all GMIC plugin work.
the spec for this plugin is (see):
```
#@gui Blur [depth-of-field] : fx_blur_dof, fx_blur_dof_preview(1)
#@gui : Blur amplitude = float(3,0,20)
#@gui : Blur precision = int(16,2,64)
#@gui : Depth-of-field type = choice{"Gaussian","User-defined (bottom layer)"}
#@gui : Invert blur = bool(0)
#@gui : sep = separator()
#@gui : note = note("<small><b>Gaussian depth-of-field:</b></small>")
#@gui : Center (%) = point(50,50,0,0,255)
#@gui : First radius = float(30,0,200)
#@gui : Second radius = float(30,0,200)
#@gui : Angle = float(0,0,180)
#@gui : Sharpness = float(1,0,8)
#@gui : Preview guides = bool(1)
#@gui : sep = separator()
#@gui : note = note("<small><b>User-defined depth-of-field:</b></small>")
#@gui : Gamma = float(0,-2,2)
#@gui : note = note("<small>You can specify your own depth-of-field image, as a <b>bottom layer</b> image whose luminance encodes the depth for each pixel.
#@gui : Don't forget to modify the <b>Input layers</b> combo-box to make this layer active for the filter.</small>")
#@gui : sep = separator(), note = note("<small>Author: <i>David Tschumperl&#233;</i>.      Latest update: <i>2014/25/02</i>.</small>")
fx_blur_dof :
  _$0 ${1-10},0,$12
```

- `$1`is Blur amplitude (float)
- `$2`is Blur precision (int)
- `$3`is Depth-of-field type (choice)
- `$4` is Invert blur (bool)
- `$5`,`$6` is Center (point) defaulting at 50%,50% openfx-gmic sees it as a float **wrong** thus the missing param
- `$7`is First radius
etc...

I'll try to fix that for next release

**Comment by devernay** [comment]
should be fixed in the latest snapshot, please test
