### ISSUE TITLE
Feature Suggestion(s)

### ISSUE THREAD

**Issue by jBachalo** [NatronGitHub/Natron#297]
*EDIT by @devernay * You should post separate feature request for each of these. also, please search if there are not already corresponding feature requests

1  ~~**Lift**, **Gain** missing from Grade node!!! Lift, Gama, Gain are 3 must have nodes for any color correction work. I would consider this highest priority.~~ *EDIT* Lift = Black, Gain = White. The name of these parameters in Nuke is actually `black` and `white`

2  ~~No support for **RED camera RAW** and **DNG** sequences.~~ *EDIT* not possible unless RED publishes the specs for its codec and FFmpeg supports it. See https://trac.ffmpeg.org/ticket/2690 for R3D support. I don't know about RED DNG, but if LibRaw support it, then Natron should support it.

3 Right now the ‘L’ key only aligns selected nodes. It should distribute them as well.

4  Should be able to shift or control select multiple footage items at one time with Read node. (to automatically create multiple read nodes)

5  '**Sticky**' ~~and '**Clone**'~~ node equivalents! *EDIT* you can use the Backdrop node as a replacement for StickyNote. Notes can be cloned in Natron (selct node + Alt-K, or right-click/Edit/Clone node)

6  The ability to detach nodes by shaking them. This is a great time saving Houdini feature.

7  ~~Built in scopes. Something better than simply displaying a histogram.~~ *EDIT* duplicate of https://github.com/NatronGitHub/Natron/issues/79

**Comment by devernay** [comment]
@jBachalo please post seperate issues for the remaining tasks. I'm closing this meta-issue.
