### ISSUE TITLE
Cannot Loop Z Rotation In Card3D

### ISSUE THREAD

**Issue by benrob0329** [NatronGitHub/Natron#298]
### Problem

I cannot loop the animation for Z rotation in a card3D node.

**Expected behavior:** The animation Loops no problem.
**Actual behavior:** It says that no curve is selected, when one is in fact selected and any other curve will try to loop the X rotation.
 
![screenshot from 2018-08-07 12-52-23](https://user-images.githubusercontent.com/19180682/43790551-ece015c6-9a40-11e8-988d-3f9d7c7b0a8f.png)

[Scene 1.zip](https://github.com/NatronGitHub/Natron/files/2267320/Scene.1.zip)

### Steps to Reproduce

1. Select The Z Rotation Curve for the Card3D19 Node
2. Right Click
3. Predefined -> Loop

### Versions

* **Natron version/commit** (they can be retrieved from the About Window):  2.3.13 Release, from Official Flatpak
* **OS version:** Fedora 28

**Comment by devernay** [comment]
In step 1, to select the curve, you should actually click on the curve itself, and it should become yellow.
Does that fix the issue for you?

**Comment by benrob0329** [comment]
Yes, I don't know why it didn't do that before but it works now. Thanks!
