### ISSUE TITLE
Windows UNC Path

### ISSUE THREAD

**Issue by ruchitinfushion** [NatronGitHub/Natron#302]
Read node not supporting windows UNC path., Right now it forcing to use map drive letter. 
UNC path support will be helpful.
Thank you

**Comment by devernay** [comment]
I think this is an openimageio issue (or an openfx-io issue). Did you try to instalml openimageio command-line binaries and check if they accept UNC paths?
Can you give an example of UNC path?
Steps to solve:

- in the ReadOIIO plugin print the file path to console to check that the correct path is sent by Natron
- if the path is correct, check that the correct path is passed to the oiio API
- if yes, then it's an oiio bug!

**Comment by ruchitinfushion** [comment]
Now i'm using centos, will try that if i get windows system. Thanks

**Comment by devernay** [comment]
Need to be re-tested on the next Windows build.

**Comment by rodlie** [comment]
As far as I know this feature requires samba (libsmb) or some win32 native api (WNetAddConnection2?) support in OIIO (or reader).

**Comment by devernay** [comment]
Isn't mingw supposed to support UNC paths? http://mingw.org/wiki/Posix_path_conversion

**Comment by rodlie** [comment]
Unsure, will need to check. Something somewhere will need to communicate over SMB (and handle access/username/password).

**Comment by devernay** [comment]
Mounting the share is out of scope. We suppose the share is already mounted and authenticated.
The issue was about using the UNC path instead of the mounted drive letter.

**Comment by rodlie** [comment]
Then this issue is fixed. I mounted //GIR/media to Z, I then read in Z:\skate.png and the path in the read node is ``//GIR/media/skate.png``

![natron-unc](https://user-images.githubusercontent.com/34516798/73222589-e5ba9700-4163-11ea-94f4-4ba6b51de846.png)

**Comment by devernay** [comment]
@ruchitinfushion can you confirm it works with 2.3.15RC?

**Comment by rodlie** [comment]
I just re-tested against latest commit and it works here (the network path is used (``//SERVER/PATH``) instead of ``X:/PATH``). Closing issue.
