### ISSUE TITLE
Natron Splash screen ignore window focus?

### ISSUE THREAD

**Issue by mnhan32** [NatronGitHub/Natron#303]
Don't know if this is intended.
Natron Splash Screen is always on top no matter what your current windows focus is.
This is specially annoying, when you still want to do something-else while Natron starts, or in dual monitor setup, you try to open Natron in secondary monitor, splash screen will be on top of your primary screen.

**Comment by mnhan32** [comment]
It happens on both of my machine with Natron 2.3.14

Machine 1 : Windows7, QuadroK4000, 24 inch monitor x2
Machine 2 : Archlinux,  Geforce 970, 24 inch monitor x2

Natron splash screen always shows on primary monitor, and will always be on the top. Also, Natron GUI will only shows on primary monitor when startup. Most programs will startup where the mouse is. On linux, it's less an issue since Natron startup pretty fast on linux machine. It is Windows7 machine that take quite some time to startup and having a splash screen hanging on my primary monitor is a bit annoying to me.

**Comment by devernay** [comment]
Thanks for the feedback. Hopefully, someone with a bit of Qt4 knowledge and two monitors will be able to fix this.

**Comment by rodlie** [comment]
Removing ``ToolTip`` and ``X11BypassWindowManagerHint`` as window flags for the splash screen seems to work here (Linux), but I can't test on Windows yet.

**Comment by devernay** [comment]
@rodlie will you be able to test on windows before 2.3.15 release?

**Comment by aditiapratama** [comment]
This is still issue in 2.3.15 pre release

**Comment by rodlie** [comment]
This issue will be fixed soon.
