### ISSUE TITLE
Cannot animate G'MIC filters in Natron

### ISSUE THREAD

**Issue by hellocatfood** [NatronGitHub/Natron#305]
I’m attempting to animate a couple of G’MIC filters in Natron, specifically the Scale attribute in Old School 8Bit and the Higher Mask Threshold in Pixel Sort (although I have experienced this with other G’MIC nodes/attributes).

When I set a key the values update as I change the current frame as does the preview. However, when I render it the render takes only the lowest or highest value of that attribute.

Is there something wrong with the G’MIC filters? I’m using Natron 2.3.14 on Ubuntu 18.04. A sample file is below.

[cat.zip](https://github.com/NatronGitHub/Natron/files/2410563/cat.zip)

This is the expected output (gif made manually in GIMP)

![cat_2](https://user-images.githubusercontent.com/151947/45949093-71f9fe80-bff2-11e8-8de8-e82aa10fbb98.gif)

And here is the output of a Natron render.

![cat_1](https://user-images.githubusercontent.com/151947/45949048-46771400-bff2-11e8-938f-2fa7440f35bf.gif)

**Comment by devernay** [comment]
It seems like it's fixed in 2.3.15, can you test with the latest release candidate?

**Comment by hellocatfood** [comment]
works now, thanks!
