### ISSUE TITLE
[Usability] Select/Search for available filter by name

### ISSUE THREAD

**Issue by c776617** [NatronGitHub/Natron#306]
You can already search for filters in the node graph which is great. What is needed now is the ability to search among available filters in the "add node" rightclick menu.

Shift+SPACE perhaps

See blender's **Shift+A, Enter** node editor UI for reference

**Comment by devernay** [comment]
Did you try pressing the "tab" key?

**Comment by devernay** [comment]
no feedback.
tab search should work.
closing this
