### ISSUE TITLE
Chromatic Aberration correction in the OIIO RAW file reader

### ISSUE THREAD

**Issue by mash-graz** [NatronGitHub/Natron#309]
natron doesn't show any control in the OIIO RAW file reader tab to enable the automatic CA correction capabilities of libraw.

this would be a very useful, because many users are using rather questionable lenses on affordable blackmagic RAW cameras these days, because this devices do not support electronic lens correction.

see also: https://github.com/OpenImageIO/oiio/issues/2029

**Comment by devernay** [comment]
Agreed. This is a rather easy fix in openfx-io. There is already an extra parameters panel for libraw-specific options (eg bayer). Just add this one.
