### ISSUE TITLE
blocking refreshing problem

### ISSUE THREAD

**Issue by 3dsman** [NatronGitHub/Natron#310]
I've a problem with some nodes that refuse to refresh their input when i change input graph (or just a parameter in the input graph).
They just draw the output as if there were no modification in the input graph.
I tryed to make a sequence render, it failed the same way (render the sequence like if there were no modification) but without any error message like if they always have the previous graph in input.

i had this problem with Merge and NoOp nodes.
the only way i found was to remove it and create a new one.

clue: bugging nodes refuse to disconect their problematic inputs when i drag'n'drop the input arow out of the node

i'm working on a 128Gb xeon computer, ram and proc usage is low.

**Comment by devernay** [comment]
We don't have enough information to reproduce this bug.
clear all caches and/or refresh button should fix this whenever it happens.
