### ISSUE TITLE
So what to do now...

### ISSUE THREAD

**Issue by revast** [NatronGitHub/Natron#313]
I see that development was funded from Inria from 2013 to 2018. 
So what to do now...

Why is there no hint on the new website that developers are needed ?

Gathering developers is no easy task. I would have thought the Project gained enough momentum, but it seems the state in which it is now is not very desirable. Namely, the state is not really communicated. 

Working on plugins is good. But I guess a team has to be put together which manages the overall direction - even without a developer available. 

In terms of Funding:  Cowdfunding, Patreon.. come into my mind. Also eventually to switch the download of the Binaries to the same method Ardour uses (if there is enough momentum for that, that is!). The bounty thing that the original developers did try is not a practical way of financing, in my opinion it should go into the direction of Krita, which got a Massive boost through crowdfunding... 

A quick search also brought up these ideas:

- Spread the Word that help is needed. because this
https://www.reddit.com/r/opensource/comments/9s4jsc/natron_needs_help/
is not enough. And People which were willing to try it had crashes... 
- no sticky one the natron forum about the actual situation
- nothing on the homepage
- nothing on the old website (which has an expired ssl certificate, btw..) There should be a Statement at least.... Having 2 homepages online does not really make sense either, the issues in original github bug tracker is is still open as well, and people did accidentally post bugs there...

-Information output should at least cover reddit (r/vfx, motiongraphics, linux opensource ....), libregraphicsnews, blackmagic forum (as of https://forum.blackmagicdesign.com/viewtopic.php?f=22&t=82122#p455224 as fusion standalone seems to go EOL?), blendernation, http://polycount.com/,  ...

- Collect and Concentrate the good tutorials. The manual is nice, but there are ones like 
https://www.youtube.com/watch?v=RezGc1_fuC8&index=1&list=PLqazFFzUAPc7c67ZuC629CBVL-26e_5QE from TJ which really need special attention.

- Start to gather together the users, and ask them how to proceed (poll in Forum), tell them how to contribute (so much stuff to do where no coder is needed!)
- Managing social media and constandly feeding all the relevant spots is a grand task!
- Gathering the Funding of an opensource Project with ongoing Development is a major task, but it gets easier if you reach a certain momentum in userbase, and as krita, blender, ardour, godot... show, the development can be very sustainable then.
- you could also try to get a funding from the vendors of the proprietary ofx plugins, as they mention natron compatibility on their website, and this would fit in their business-model..

- Feature the artist's works, and crosspost it to gather attraction for new Users
- Make contests for challaging the artists

- https://natron.fr/team/ 
I guess all these guys are still interested in the wellbeing of this project 
- http://www.ati-paris8.fr/index.php?page=team&lang=en 
these, too, provided they are still using natron to teach their students...
- It would be great to have these people contacted and asked for their current opinion.

**Comment by magdesign** [comment]
https://discuss.pixls.us/t/crowdfunding-natron-3d-workspace/9912/9

**Comment by SilverWolf32** [comment]
I actually just found Natron recently, and it looks amazing! Blender _has_ a compositor, but it looks to be made mostly for effects on top of 3D scenes, not involved 2D graphics work. I really hope we'll be able to get the project going again.

I don't have time for full-on coding, even if I knew C++ or Qt -- I'm currently learning full-time in college -- but I may be able to help out with smaller things some of the time. User-facing documentation, perhaps?

I'm not on any social media or most online forums, so I can't help out much with promotion. But I did post [this](https://video.meta.stackexchange.com/questions/1534/natron-the-open-source-compositor-is-in-trouble) on the [Video Stack Exchange](https://video.stackexchange.com). I don't know how big that site is, and the meta areas tend to get visited less often, but hopefully at least some people will see it.

**Comment by revast** [comment]
cool! Every helping hand is welcome! As about of blender: they have a project ongoing right now which is called "everything nodes"  where the author of the animation nodes plugin is working full-time on getting basically the whole program based on nodes.  see [here]([https://www.youtube.com/watch?v=HQi2BqlQtnI])

**Comment by Amudtogal** [comment]
Hey,
I am so glad, that the community of Natron is still alive and working on!
In preparation of some upcoming short clips, I wanted to get started with Natron and dive into Compositing (which I have, to admit, no real experience yet).
However, I worked some time as a software engineer, developing a Python Plugin for Blender.
I am still far from being a good C++ or Qt coder, but I scratched the surface of it a bit...
As a master student, I can't provide that much of time, but I will try to contribute some time.
Fingers crossed for this program!

**Comment by SilverWolf32** [comment]
I noticed the natron.fr SSL certificate is still down. Do we still have the domain? Perhaps whoever owns it could set up a [Let's Encrypt](https://letsencrypt.org) certificate.

**Comment by devernay** [comment]
I still have the domain, but was not able (and do not have anymore time) to set the let's encrypt auto renewal. If someone is OK to maintain this domain (I still have it for 2.5 years) and set it up so that it points to natrongithub.github.io I'll give it back.

**Comment by WPFilmmaker** [comment]
@devernay could Gsoc work to improve Natron's situation? Could you tutor a student (or more) participating in the program?

**Comment by devernay** [comment]
entering GSoC is easy for software that have a developer team and a large user base. The problems with Natron are:
- no more developers (sorry, I now have a day job that only leaves me with time to spend with my family)
- the user base is a niche, and many users do not even declare themselves, because they do not want to make public the fact that they use Natron. So it is very difficult to evaluate the numbers of real users. We tried to enforce registration to download binaries or snapshots, but that doesn't work. The only count we have left is the number of followers for the facebook page, and it is very low compared to the user base of other software.
- I do not have time to mentor a young developer on this

**Comment by SilverWolf32** [comment]
And some users aren't even on Facebook in the first place. (:

Could the GitHub traffic page provide a useful metric? I know that's views and not downloads, but it might still give us an idea of how popular the project is.

**Comment by magdesign** [comment]
Here you can get some numbers:
http://www.somsubhra.com/github-release-stats/?username=NatronGitHub&repository=Natron

**Comment by Echolon** [comment]
Sad to read :(

Maybe this could be another option: https://nlnet.nl/

**Comment by Echolon** [comment]
@devernay maybe pin this thread and give it a proper title

**Comment by devernay** [comment]
Actually I'll close it, since there's already discussions in the forum https://discuss.pixls.us/c/software/natron

**Comment by Echolon** [comment]
Hmm, I would link it on the frontpage of the github repository and the natron website maybe
