### ISSUE TITLE
Failed to build with Cairo shared lib

### ISSUE THREAD

**Issue by Sunderland93** [NatronGitHub/Natron#328]
Hello. I try to build Flatpak-package of Natron with Cairo from Flatpak SDK. There is no Cairo static libs, and Natron failed to build with:

```
g++: error: /usr/lib/x86_64-linux-gnu/libcairo.a: No such file or directory
make[1]: *** [Makefile:106: NatronRenderer] Error 1
make[1]: Leaving directory '/run/build/natron/Renderer'
make: *** [Makefile:279: sub-Renderer-make_default] Error 2
make: *** Waiting for unfinished jobs....
```
Here is config.pri

```
boost-serialization-lib: LIBS += -lboost_serialization
boost: LIBS += -lboost_thread -lboost_system
expat: LIBS += -lexpat
expat: PKGCONFIG -= expat
cairo: PKGCONFIG -= cairo
pyside: PYSIDE_PKG_CONFIG_PATH = $$system($$PYTHON_CONFIG --prefix)/lib/pkgconfig:$$(PKG_CONFIG_PATH)
pyside: PKGCONFIG += pyside
pyside: INCLUDEPATH += $$system(env PKG_CONFIG_PATH=$$PYSIDE_PKG_CONFIG_PATH pkg-config --variable=includedir pyside)/QtCore
pyside: INCLUDEPATH += $$system(env PKG_CONFIG_PATH=$$PYSIDE_PKG_CONFIG_PATH pkg-config --variable=includedir pyside)/QtGui
```

**Comment by threedslider** [comment]
And if you can copy and paste to linux : [Cairo](https://github.com/rwinlib/cairo). It is working ?

**Comment by devernay** [comment]
@Sunderland93 what tries to link to cairo as a static lib?
Can you give the link line that fails (just above that error message), and try to figure out why a statis cairo is used?

**Comment by rodlie** [comment]
Natron builds against static Cairo as default on Linux/FreeBSD. You must override this in your config.pri

https://github.com/NatronGitHub/Natron/blob/c07e094da2861072b05441065f517cc15136f8f1/global.pri#L411

**Comment by devernay** [comment]
The reason why we linked to a static cairo is written in the comment: NatronRenderer will need X11 to run, even though we don't use the X11-specific parts of cairo (they should really have split that library in two).

But that was before Natron could handle OpenGL rendering in OFX plugins.

Now Natron always needs to link with OpenGL (and thus X11). SHouldn't we link to a dynamic cairo instead?

**Comment by rodlie** [comment]
Agree, especially since plugins also depends on Cairo (either static on all or shared on all).
