### ISSUE TITLE
EXR Data Window Issue

### ISSUE THREAD

**Issue by Chadt54** [NatronGitHub/Natron#332]
Please ask questions ("how do I...?") on the [forum](https://discuss.pixls.us/c/software/natron), not by filing issues.

Please read carefully the [Troubleshooting](http://natron.readthedocs.io/en/rb-2.3/guide/getstarted-troubleshooting.html) section of the [Natron documentation](http://natron.readthedocs.io) before submitting an issue: this issue may already be signaled, or may have a simple workaround.

Make concrete suggestions for fixing the code ("here is a patch") by filing
a [pull request](https://github.com/MrKepzie/Natron/pull/new/master), not an issue.

### Problem

Describe the problem or suggestion here.

**Expected behavior:** [What you expected to happen]
The pixels around the EXR's data window should be black.

**Actual behavior:** [What actually happened]
The pixel data looks corrupted.
![image](https://user-images.githubusercontent.com/1322965/56403480-82c6d600-629c-11e9-9069-507ac4b936c0.png)

### Steps to Reproduce

1. I read my EXR image in (that has a data window, resolution is 5K)
2. Try to set the Edge Pixels to "Black"
3. But, I still receive this issue as seen in the image above. Also,  (One thing I notice is that if I zoom into the image it sometimes becomes fixed, so maybe it's a resolution based bug?) Also, other nodes (like crop and reformat) that I try to place after the node complain about NaN pixel values I assume outside the exr data window region since there isn't data out there.

Is there a recommended procedure to working with exr data widows that I'm not understanding? Or, is this a bug?

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
Natron version 2.3.13 Release.
* **OS version:** 
Centos 7

**Comment by devernay** [comment]
Can you provide the EXR (if it's small enough, zip it and attach it to this issue)

**Comment by Chadt54** [comment]
It's been a while since I was doing this shot so I can't remember if this is the right file exactly as I was using in this issue, but it looks correct.

For me I tend to get errors with NaN in Natron almost any time I use an EXR with a data window. Also, I have a feeling this issue has to do with using resolution that are maybe too large for my video card to display, which causes strange things to happen. I noticed when I'm zoomed in a lot of issues tend to go away, and come back when I zoom out to view the entire image.

[ExrFile.zip](https://github.com/NatronGitHub/Natron/files/3169891/ExrFile.zip)

**Comment by devernay** [comment]
Does the “refresh/recycle” button fix the issues when they appear?

**Comment by Chadt54** [comment]
Yeah that seems to help, but I end up needing to press it a lot. I find that I need to constantly press Ctrl+Shift+K as I work to make things work correctly. Which makes working quite slow, but I guess I just deal with it since Natron is pretty much the best open source/free compositor that exists haha

Most of my problems come from when I have clients that want me to create 4K or 5K footage. When I just do HD or 720, almost no problems arise with the viewport.

Although, oddly, I found that sometimes if I just enable the Region of Interest button and stretch the region over the entire video it oddly speeds things up (and sometimes can fix things), even though it defeats the whole point of the tool haha

**Comment by devernay** [comment]
looks like it's fixed in 2.4
