### ISSUE TITLE
Cannot build Natron-sdk because natron.fr is down

### ISSUE THREAD

**Issue by fonkle** [NatronGitHub/Natron#337]
### Problem

Because natron.fr is down, I cannot build Natron-sdk. The Linux build script gets stuck repeatedly trying to contact _http://downloads.natron.fr/Third_Party_Sources_.

**Comment by devernay** [comment]
I think it can work without it. The script first tries downloads.natron.fr, but then tries the original source. Should be easy to disable any download from downloads.natron.fr

**Comment by devernay** [comment]
or someone who recently built the SDK, and thus downloaded everything, could build a mirror

**Comment by fonkle** [comment]
I see. This can indeed be fixed. I assume the files were hosted on natron.fr to improve availability over time?

Woul it be an idea to host them from the github repo? I will check if the 25mb file size limit is sufficient.

**Comment by fonkle** [comment]
Alas, GitHub file size limit (25MB) is not sufficient.

I am not sure how to proceed with this. I could simply remove the link to natron.fr but that would make the building process of _Natron-sdk_ less robust (at least when using the Linux script) than before.

A better way would be to store the needed source components on some static file server (behind some static domain name) like it was before, but that would require some file and domain name hosting account, preferably administrated by the maintainer of the project?

I could for instance create a mirror on say _natron-sdk.bitbucket.io_, which accepts bigger files for webhosting. That works (tested it), although I have no idea how the provided bandwidth would compare to the situation before.

**Comment by devernay** [comment]
It downloads and stores the sources locally. If a source is not available, the user can still look for it elsewhere.
I created a directory https://github.com/NatronGitHub/NatronGitHub.github.io/tree/master/files where we can put a few files.
There were a few precompiled binaries, such as natron-windows-installer.zip (used by build-Windows-sdk), which I found and put there, but I lost strings32.tgz and strings64.tgz which were statically linked binaries of the "strings" utility which could be run on CentOS 6.4. If somebody has them, please attach to this issue.

**Comment by devernay** [comment]
oh and I updated the scripts to try to download from natrongithub.github.io instead, tell me if it fixes the sdk build

**Comment by fonkle** [comment]
I have been gathering the source files and have been tested putting them on bitbucket.org , which will allow for bigger files. It is working fine so far. I think it will store all of the source files (I am only at about 3/4 of the way for the Linux SDK).

Maybe you could open an account like **natronsdk.bitbucket.io** ?

**Comment by fonkle** [comment]
So far only GCC (108 MB) and Qt (233 MB) are bigger than 100MB.

**Comment by fonkle** [comment]
Gnu m4 1.4.18 builds on Ubuntu 18.04, yet not on 18.10 + 19.04. I added a patch to make it work on 19.04:

> Try applying [this](http://git.openembedded.org/openembedded-core/tree/meta/recipes-devtools/m4/m4/m4-1.4.18-glibc-change-work-around.patch) patch. It is an OpenEmbedded-generated backport of upstream patch.

It is explained [here](https://gitlab.com/atilla/buildroot/commit/c48f8a64626c60bd1b46804b7cf1a699ff53cdf3): it is broken since glibc version 2.28, which was introduced in Ubuntu 18.10.

I'll test it with 18.04 to see if the patch works with older versions as well.

**Comment by Chadt54** [comment]
Why not just make a multipart zip file or 7zip file that are each less than 100MB?

Github repos can be up to 1GB, it's just the individual file sizes that can't exceed 100MB. So just split the files! haha

https://help.github.com/en/articles/what-is-my-disk-quota

https://stackoverflow.com/questions/4946804/does-gzip-support-multi-part-file-compression

**Comment by devernay** [comment]
@Chadt54 source distributions should never be modified, or you don't know what's in there. I'd never compile a GCC which is not an original GCC tar distrib.

@fonkle There is also a large file storage on github: https://git-lfs.github.com/ why not use that? Or do we need versioning at all?

**Comment by Chadt54** [comment]
Sorry, forgot about security being an issue

**Comment by fonkle** [comment]
Yeah I had a look at GitHub LFS, but it made the build process even more complicated, since you have to install an extension. Besides LFS I see 3 options:

1. Put source files in an external buffer on a host which supports files > 100MB. F.e. natronsdk.bitbucket.io.
2. Put source files in a buffer on the GitHub repo (natrongithub.github.io) and download GCC and Qt directly from their source.
3. Forget about the buffer and download everything directly. I don't like this option since some links are already obsolete (a few more small patches will follow to fix these).

I have tested putting the source files in a repo on BitBucket (bitbucket.org) which -despite the limited bandwidth- worked rather well. I am not sure if the licenses of all source packages permit this form of distribution?

**Comment by fonkle** [comment]
LFS cannot be used with public forks, so I cannot test it locally or upload files.

Is there any other way to upload the files to a new branch on NatronGithub.github.io?

**Comment by devernay** [comment]
I wouldn't use natrongithub.github.io, which has to stay lighweight, since it holds the website content.
An ftp or http repo makes much more sense than git, since we don't need to version these files. Why not use sourceforge for that? https://sourceforge.net/projects/natron/files/
Send me your sourceforge user name (I prefer by email), and I'll add you to the project

Remember that the 1GB limit on github is for the *full* history, so 10 versions of a 20MiB source file take 200MiB...

**Comment by fonkle** [comment]
The build script now works without any errors on CentOS 6.10.

The issue with mariadb was solved by simply installing the same version of cmake (currently 3.12.0) as is built by the script.

I will run another test tomorrow and then send a new PR upstream.

**Comment by devernay** [comment]
Note that you can upgrade safely cmake in the script. This is not going to
break anything

**Comment by fonkle** [comment]
I know, but the scripts stops at mariadb if the installed version is different from the version built by the script (then it cannot find the modules folder). So it is more important that the versions match.

I could make the script look at the installed version but that would make it more complex and thus error-prone. Maybe it would be better to improve on the documentation (a more detailed tutorial?) for building the SDK?

**Comment by devernay** [comment]
Do you mean that mariadb checks if all available versions of cmake in the PATH are the same versions? :-~

**Comment by fonkle** [comment]
No, but it looks for a cmake module in a path which includes the cmake version number, so if they do not match up, it will not find the right module.

This can be made more robust by adding 'hash -r' before building mariadb; then it will reset the cmake version to the version installed in the system and therefore find the needed modules.

I am not 100% sure if that could cause issues though, so the safest way is to install the same version of cmake in the system. Probably the best practice is to follow the cmake version from the CentOS 6.x repo?

**Comment by fonkle** [comment]
I close this issue since it is solved. Source files are hosted on SourceForge now.

**Comment by devernay** [comment]
BTW, can you please create an account on the docker hub and give me your
login? I'll add you to the natrongithub org so that you can push docker
images
