### ISSUE TITLE
Using Videolan Contrib system to manage 3rdparties

### ISSUE THREAD

**Issue by yomgui1** [NatronGitHub/Natron#347]
This is a feature request for Natron 3.x and more.

**Problem to solve**
Natron is build over many 3rdparties like Qt, libpng, FFMPEG, etc, even GCC is rebuild!
Is never easy to manage all dependencies and required patches over the time.
Moreover, this should be done for multiple platforms: GNU/Linux, MacOSX and Windows.

Current solution is to make an "SDK" tree. All the recipes are available into almost one file per platform in tools/jenkins/include/scripts: build-Linux-sdk.sh for GNU/Linux, build-Windows-sdk.sh for Windows (and I wonder how MacOSX is supported :-( ... )

Managing these huge files per platforms for adding/updating a deps is not easy.
And this is a custom system made by Natron, where there is almost only 1 or 2 people knowing how to do that.

At least, all patches are inside separated directories in tools/jenkins/include/patches.

**Solution proposed**

The well known Videolan project (aka VLC) has designed a successful 3rdparties management for their needs called "contrib":

https://github.com/videolan/vlc/tree/master/contrib

The system is based on **make** tool using simple and well supported Makefile scripts.
The improvement is the separation of each 3rdparties into directories: one per 3rdparties.
Then in each of them, patches and recipes are located:
* one file _rules.mk_ contains recipes
* one file for a SHA512 signature of the source archives to track the correctness of download
* multiple files for patches, all inside the related 3rdparty directory

This system gives these huge improvements for us:
* well separation of 3rparties
* support of sources fetching like tarball and GIT (as github)
* support of GNU/Linux, MacOSX and Windows already build
* support of system dependencies lookup: if the system proposes the needed library, it's not build.
* support of pkg-config
* **huge community of support for dependencies**
* **many of 3rdparties are also use by Natron (they already support Qt 5.12.x !!)**
* and many more...

Finally, I well known this system as I've used it in past for another project.
Using makefile gives many advantages for build reproduction, maintenance, etc.
So I propose myself to start the migration.

**Comment by devernay** [comment]
You can propose a parallel build system of course, but the current one works very well, and there are very probably dependencies that are not part of VLC (oiio?).
My advice is to start with what works already, and then propose am alternative, but I see no reason to switch the build system now.

**Comment by rodlie** [comment]
I agree with Frédéric, I see no reason to waste resources on a new build system.
