### ISSUE TITLE
SDKs: upgrade OpenImageIO to 2.1.10.0

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#350]
This is required for #309 (Chromatic aberration correction in raw files)

Only close this issue when all three SDKs have been upgraded (Windows/mingw64, Linux, macOS/MacPorts)

**Comment by devernay** [comment]
linux SDK updated

**Comment by rodlie** [comment]
Also updated on Windows. Will go through my changes on Sunday and do a PR (including the other MINGW-packages).

**Comment by devernay** [comment]
OK, nice. You can even jump to 2.0.9.
Do not forget to apply that patch: tools/jenkins/include/patches/OpenImageIO/2.0/oiio-2.0.8-invalidatespec.patch

Also, I wouldn't recommend touching the qt, pyside and shiboken packages.
As soon as you have a windows build, it would be nice to upload it to the 2.3.15pre release.

**Comment by rodlie** [comment]
Ok, will move to 2.0.9 (and check if I got the patch).

qt+pyside had to be modified, as they didn't build in the current state on latest MSYS2 (gcc 9.1). I did bump PySide to 1.2.4, but that I can revert (back to 1.2.2).

I will try to get as far as possible tomorrow.

**Comment by devernay** [comment]
Well if you manage to get pyside working, that's ok to upgrade it too!

**Comment by rodlie** [comment]
I will try using 1.2.4, if it breaks anything I will revert.

Btw, I noticed your comment regarding oiio 2.0.9 and Boost 1.70. I will stay on 2.0.8 until I get Natron up-and-running since I (MSYS) use Boost 1.70 and don't want to break anything at this point.

**Comment by rodlie** [comment]
What version of SeExpr should be used on Windows? In the SDK script SeEpxr 1.0.1 is still used and needs a patch (https://github.com/NatronGitHub/Natron/blob/RB-2.3/tools/jenkins/include/scripts/build-Windows-sdk.sh#L646) not available in the Natron repo. Upgrade to latest stable?

**Comment by devernay** [comment]
The problem is with boost, not oiio. It also breaks building oiio 2.0.8 on linux, with an obscure message. If your build runs OK, then keep it.
SeExpr is 2.11, and there are at least 4 patches to apply:
https://github.com/NatronGitHub/Natron/blob/RB-2.3/tools/jenkins/include/scripts/pkg/seexpr.sh

**Comment by devernay** [comment]
5 patches, actually

**Comment by rodlie** [comment]
Ok, I didn't have any issues building oiio 2.0.8 against Boost 1.70. Will update SeExpr to 2.11.

**Comment by rodlie** [comment]
https://github.com/OpenImageIO/oiio/pull/2429

We have crash reports related to this issue.

**Comment by devernay** [comment]
It's cool that it was found so quickly. hopefully 2.0.14 will be released early January  and have that patch

**Comment by lgritz** [comment]
If this is critical, I can tag a bug fix release immediately with just this fix.

**Comment by rodlie** [comment]
Would be nice to have the fix for Natron 2.3.15 release (and would be nice to release that before the end of this month(?)).

**Comment by lgritz** [comment]
Which is more helpful for you, a release of 2.0.x or 2.1.x?

**Comment by devernay** [comment]
@lgritz thank you for your help. I still haven't tested if 2.1 works for us, so a backport to 2.0 would be nice, but as I see it it's just a 2-line patch, so we don't even need an official OIIO release.

**Comment by lgritz** [comment]
Aha, well easy then. Already backported. Just use OIIO at commit 028cd32fdd for now.

**Comment by rodlie** [comment]
All platforms now use 2.1.10.x, close.
