### ISSUE TITLE
Ileagal listing on ecommerce site.

### ISSUE THREAD

**Issue by sixxkilur** [NatronGitHub/Natron#353]
Your Open Source Software Natron is  being sold by multiple users on Amazon.

https://www.amazon.com/Compositing-Screen-Chromakey-Software-Windows/dp/B07BFCKT7Q/ref=sr_1_23?keywords=chromakey&qid=1558013596&s=gateway&sr=8-23

https://www.amazon.com/Green-Screen-Software-Photography-Professional/dp/B07N35S2BY/ref=zg_bs_567570_1?_encoding=UTF8&psc=1&refRID=0WJYDX80899FQ11MX2CK

**Comment by devernay** [comment]
haha and it even seems that some people bought it.
It's not illegal, actually:
- https://www.gnu.org/licenses/gpl-faq.html#DoesTheGPLAllowMoney
- https://www.gnu.org/philosophy/selling.html

I'm closing this issue, but thank you for reporting!
