### ISSUE TITLE
Move to devtoolset on RHEL/CentOS

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/Natron#360]
We should consider moving to devtoolset-6 for CentOS. This is GCC 6.3.1 with custom backwards compatibility with CentOS 6 base libs. The biggest reason is to avoid issues with system libraries (Mesa, gcc etc) on Linux, and we don't have to distribute libstdc etc anymore.

We used devtoolset before we moved to 4.8.5.

**Comment by devernay** [comment]
we're using GCC 9 now, with C++11. There is no good reason to stick to older gcc version (the C++ ABI has remained the same for years)

**Comment by rodlie** [comment]
GCC6 does C++11 just fine, the reason is to avoid shipping libstdc/libgcc and avoid issues on Linux.

**Comment by rodlie** [comment]
Btw, I have a valid RHEL subscription and I got access to devtoolset-8 (GCC8) on RHEL6.x (not tested yet). v9 is probably not far away.

I will test both. Our Linux binaries had the best compatibility when we used devtoolset.
