### ISSUE TITLE
New color picker dialog/wheel/widget

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/Natron#363]
I have a better color picker dialog/wheel that I want to integrate into Natron, it's based on code from QtSolutions and is licensed under LGPL2. Ok?

**Comment by rodlie** [comment]
Screenshot (not from Natron):
![colorwheel](https://user-images.githubusercontent.com/34516798/59144405-cf46ac00-89d7-11e9-9e58-e88edb8de854.jpg)

**Comment by fabiof17** [comment]
Do you still plan to get it to Natron ?
Because there's no way we can stay with the system color picker.

**Comment by rodlie** [comment]
I added a new color dialog and color triangle in my own fork a while ago: https://github.com/rodlie/Natron/tree/newColorDialog

So, yes. But for now that will have to wait until we get 2.3.15 out.
