### ISSUE TITLE
Windows Fontconfig

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/Natron#365]
> Windows: If Natron is not installed in Program Files using the installer, the Text node does not work because fontconfig does not initialize properly.

I don't remember this issue, any more info on this?

I don't have access to Windows yet, but will get a Windows computer working sometime next week.

**Comment by rodlie** [comment]
This issue is related to fontconfig cache path in Natron vs TextFX.

Natron uses a custom path for the cache while TextFX uses the default path from fontconfig for cache.

**Comment by rodlie** [comment]
I don't think this issue is valid anymore.

Natron installed in program files uses font cache in HOME/.cache, Natron portable uses font cache in PORTABLE/var. This is supported by the Text plugin.

I ran 2.3.14 portable and no issues, I also ran the Text node in debug mode and verified that fontconfig worked:
```
FONT_CONFIG_PATH?C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-insta
ller/Resources/etc/fonts
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\fonts.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/10-hinting-slight.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/10-scale-bitmap-fonts.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/20-unhint-small-vera.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/30-metric-aliases.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/40-nonlatin.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/45-generic.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/45-latin.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/49-sansserif.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/50-user.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/51-local.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/60-generic.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/60-latin.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/65-fonts-persian.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/65-nonlatin.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/69-unifont.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/80-delicious.conf
Config files:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer
/Resources/etc/fonts\conf.d/90-synthetic.conf
Config dir:C:/Users/olear/Desktop/Natron-2.3.14-Windows-x86_64bit-no-installer/R
esources/etc/fonts/conf.d
Font dir:C:/Windows/fonts
Font dir:C:/Users/olear/.local/share/fonts
Font dir:C:/Users/olear/.fonts
Font cache:C:/var/cache/fontconfig
Font cache:C:/Users/olear/.cache/fontconfig
Font cache:C:/Users/olear/.fontconfig

```

**Comment by rodlie** [comment]
Actually there are some issues.

Natron from ProgramFiles will generate font cache in HOME/.cache/fontconfig.

Natron portable will use that cache if found, but if you delete HOME/.cache/fontconfig, then Natron portable will generate the new font cache in PORTABLE/var, this can't be right? Also, TextFX will generate it's own font cache since PORTABLE/var is not a valid cache path. but TextFX uses ROOT/var for font cache (how can a OFX plugin write directly to C: ?).

This must be an issue with fonts.conf.

**Comment by devernay** [comment]
Checkout how Gimp and Inkscape (portable and non-portable) handle this. See for example https://bugs.launchpad.net/inkscape/+bug/1196373

Note that TextFX should honor the `FC_CONFIG_FILE` env variable, which can be set by Natron itself or the system, and may come with a fallback fonts.conf in case it is not set, so that it works fine on hosts that don't have fontconfig. That way, it will always share Natron's fc cache.

**Comment by devernay** [comment]
Also, as for inkscape and gimp, the solution may require some changes to Natron's fonts.conf, or Natrons settings for fc environment variable, which is not `FC_CONFIG_FILE` but `FONTCONFIG_PATH`, see [here](https://github.com/NatronGitHub/Natron/blob/RB-2.3/Engine/AppManager.cpp#L473).

**Comment by rodlie** [comment]
I will add support for ``FC_CONFIG_FILE`` in TextFX, I just don't understand why /var/cache/fontconfig is first on the list:
Font cache:C:/var/cache/fontconfig
Font cache:C:/Users/olear/.cache/fontconfig
Font cache:C:/Users/olear/.fontconfig

**Comment by devernay** [comment]
This is a linux thing. Check out how the Inkscape and Gimp fonts.conf handle this on windows portable and non-portable. Windows may require a different fonts.conf

**Comment by rodlie** [comment]
I built TextFX with a different version of fontconfig than Natron, that was the reason for ROOT/cache issue, my bad.

``LOCAL_APPDATA_FONTCONFIG_CACHE`` seems like a ok solution.

**Comment by devernay** [comment]
I think it's a bad idea to have two conflicting versions of fontconfig around. The API hasn't changed that much, why not use the same version? It will also pose problems on Linux and macOS.
I also see that Natron's fonts.conf is currently missing the line
`<dir>WINDOWSFONTDIR</dir>` - I'll add that.

Natron's fonts.conf comes from inkscape for windows, with directories for Linux and macOS added (shouldn't harm windows)

**Comment by rodlie** [comment]
I used a different version when building a debug build of TextFX, just ignore that (/var is still around when using the same version)

Yes, WINDOSFONTDIR is missing from fonts.dir, but it seems hardcoded since it's always first in the list. Can't hurt to add it anyway.

I  think the /var issue is related to this https://github.com/NatronGitHub/Natron/blob/RB-2.3/Gui/Resources/etc/fonts/fonts.conf#L83

**Comment by devernay** [comment]
fixing that as we speak

**Comment by rodlie** [comment]
I can confirm that Natron portable + TextFX now works with: https://github.com/NatronGitHub/Natron/commit/820635f0c4aa5e03e57a04a0e671dfb5138887d7

It also works with the 2.3.14 binaries (just replace fonts.conf).

The cache is now in ``USER\AppData\Local\fontconfig\cache``

**Comment by devernay** [comment]
I think it may break linux and macOS, though, because it will create a directory named  `LOCAL_APPDATA_FONTCONFIG_CACHE` and use that as a cachedir

**Comment by rodlie** [comment]
I can check, if it does we just distribute a custom fonts.conf for Windows.

**Comment by rodlie** [comment]
Yeah, it will create the folder on Linux. We should just have a custom fonts.conf for Windows.

**Comment by devernay** [comment]
done in https://github.com/NatronGitHub/Natron/commit/3f18d1b22e7e84b3fc203e214b1e0ff3e5a60f34
