### ISSUE TITLE
License etc on new code commits

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/Natron#366]
What is the status on licensing etc for new code commits? Will new code still be under INRIA copyright, or "Natron Developers"? Or something else?

Just wondering, no rush on this.

**Comment by devernay** [comment]
As with any GPL-licensed open-source software. Bug fixes do not change the copyright, unless these are significant enough, in which case the contributor becomes a co-author. The license remains GPL. These are not my rules, these are the same rules as for any GPL-licensed open-source software.

Contributors should follow good practices and share a reasonable code of conduct (such as https://kde.org/code-of-conduct/).

**Comment by rodlie** [comment]
Good to know. Thanks.
