### ISSUE TITLE
NatronEngine.Effect.destroy() function not working

### ISSUE THREAD

**Issue by fabiof17** [NatronGitHub/Natron#368]
### Problem

NatronEngine.Effect.destroy() function not working.

**Expected behavior:** Remove a node.

**Actual behavior:** Node is not removed, and can't be manualy removed by user neither.
Natron may crash.

### Steps to Reproduce

1. Run following python script :

myBlur = app.createNode("net.sf.cimg.CImgBlur")
myBlur.destroy(1)

### Versions

* **Natron version :** 2.3.14
* **OS version:** Windows 10

**Comment by devernay** [comment]
Full script to reproduce is:
```
from NatronEngine import*
from NatronGui import *
from PySide.QtGui import *

app = natron.getGuiInstance(0)
myBlur = app.createNode("net.sf.cimg.CImgBlur")
myBlur.destroy(1)
```
