### ISSUE TITLE
rearrange node function

### ISSUE THREAD

**Issue by mapulse** [NatronGitHub/Natron#371]
### Problem

I try to sort all selected node natron node graph falling apart

**Expected behavior:**  I wanna sort nodes. but manually reorganization best all times
**Actual behavior:**  I try to sort all selected node natron node graph falling apart

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
Natron version 2.3.14
* **OS version:** 
Fedora 29 64bit

**Comment by devernay** [comment]
more details, maybe? steps to reproduce? sample project?

**Comment by devernay** [comment]
or a screencast maybe?
