### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [NatronGitHub/Natron#372]
i've downloaded version '2.3.14' but when selecting it in the macOS Finder, the Version Number entry is missing.

the CFBundleVersion and CFBundleShortVersionString entries in your Info.plist file are missing

**Comment by devernay** [comment]
can see the version number in the get info panel:
<img width="257" alt="image" src="https://user-images.githubusercontent.com/3778071/59241275-da5a3180-8bbb-11e9-9d32-70c461fb7486.png">

```
	<key>CFBundleGetInfoString</key>
	<string>2.3</string>
```
The Info.plist file is generated by qmake, we don't do anything custom beyond what qmake does

**Comment by core-code** [comment]
@devernay thanks for your reply. sorry, yes, i can confirm something shows up in the finder

two problems
• obviously 2.3 is not the version number. it should read 2.3.13
• actually the 'CFBundleGetInfoString' entry is deprecated for more than 10 years and needs to be removed. you need to use the 'CFBundleVersion' and 'CFBundleShortVersionString' entries

all of this should be easy with stock QMake things or just postprocessing the app with '/usr/libexec/PlistBuddy' while generating the DMG

**Comment by core-code** [comment]
try adding this to your Info.plist


```
	<key>CFBundleShortVersionString</key>
	<string>@FULL_VERSION@</string>
	<key>CFBundleVersion</key>
	<string>@FULL_VERSION@</string>
```

**Comment by devernay** [comment]
Feel free to do a pull request to change that. Frankly there are more important things to fix in Natron, that affect all platforms.
2.3 looks ok to me, as it is the real version number. 13 or 14 is a micro version number.

**Comment by core-code** [comment]
all Mac apps should have their real version number embedded. its also important in case you have multiple versions installed. without monotonically increasing numerical CFBundleVersion that won't work, as described in the Apple documentations. 

i'll try to send a PR.

**Comment by devernay** [comment]
fixed by #374

**Comment by devernay** [comment]
This doesn't work.
FULL_VERSION is only available in Qt5.
I'm reverting to SHORT_VERSION for the moment, we'll have to find another solution, maybe based on QMAKE_SUBSTITUTES

**Comment by devernay** [comment]
<img width="256" alt="image" src="https://user-images.githubusercontent.com/3778071/60943302-64201c00-a29a-11e9-93be-49301935b31e.png">

**Comment by devernay** [comment]
qmake 4.8.7 only replaces SHORT_VERSION: https://github.com/qt/qt/blob/0a2f2382541424726168804be2c90b91381608c6/qmake/generators/mac/pbuilder_pbx.cpp#L1280
