### ISSUE TITLE
Create dynamic videos with natron

### ISSUE THREAD

**Issue by matteoraggi** [NatronGitHub/Natron#381]
Is it possible with natron to create data driven dynamic videos like after effectsdoes? 
Example:
https://github.com/inlife/nexrender
https://www.themarketingtechnologist.co/creating-dynamic-videos-using-javascript-and-after-effects-the-basics/

**Comment by rodlie** [comment]
You can script (in Python) more or less anything you want in Natron, so yes.

I recommend you join the community at https://discuss.pixls.us/c/software/natron, several people there can probably help you.
