### ISSUE TITLE
Generic error in an external library

### ISSUE THREAD

**Issue by AnnaMargret** [NatronGitHub/Natron#387]
I am very new to working with computer software in general. I am making a short film and was going to test render it but...

### Problem 

**Expected behavior:** Render Write1.

**Actual behavior:** Rendering failed and this message popped up: Write1 error: Could not open video codec: Generic error in an external library.

![Screenshot (35)](https://user-images.githubusercontent.com/52499259/60599582-3c165180-9d9e-11e9-93d7-a5a9b30c1bb3.png)

**Comment by rodlie** [comment]
Could you try another codec/container and see if you get the same issue?

**Comment by AnnaMargret** [comment]
I have tried changing the codec/container multiple times, sadly does not work yet. 

[Sagan.um.Karlsdæturnar.thrjar.2.zip](https://github.com/NatronGitHub/Natron/files/3355779/Sagan.um.Karlsdaeturnar.thrjar.2.zip)

**Comment by rodlie** [comment]
Odd, I'm able to render just fine using your project on Windows and Natron 2.3.14. Will check if it's something I'm overlooking.

**Comment by rodlie** [comment]
Could you see if the Natron terminal window has any errors (or info) when it fails?

**Comment by AnnaMargret** [comment]
Thank you very much. Yeah, strange indeed. Do you have any idea what ''generic error in external memory'' might mean?

**Comment by AnnaMargret** [comment]
Oh I oversaw what you said, sorry. How do I open the Natron terminal window?

**Comment by rodlie** [comment]
It's a separate window while you run Natron.

**Comment by AnnaMargret** [comment]
Ahh... I think this means that the Images I am using are too large?

![Screenshot (37)](https://user-images.githubusercontent.com/52499259/60614093-c620e300-9dbb-11e9-9baa-2dbe2ac32267.png)

**Comment by rodlie** [comment]
You could try adding a crop before the write node.

**Comment by devernay** [comment]
H.264 is not designed for images that large, that's for sure.
You should rescale your input (to HD if you want H.264).
