### ISSUE TITLE
Exported video is only a 10th of a second

### ISSUE THREAD

**Issue by AnnaMargret** [NatronGitHub/Natron#392]
Hi. Wondering if there is anyone who knows what went wrong when I rendered my project.

### Problem

**Expected behavior:** Write node renders project and saves it as a mp4 file.

**Actual behavior:** I was able to render this animated rectangle, but when I opened the mp4 file it is only a tenth of a second in length and the rectangle animation is not visible.

mp4 video:

[kassaprufa.5.zip](https://github.com/NatronGitHub/Natron/files/3377534/kassaprufa.5.zip)

Natron project:

[kassaprufa.4.zip](https://github.com/NatronGitHub/Natron/files/3377535/kassaprufa.4.zip)

![Screenshot (38)](https://user-images.githubusercontent.com/52499259/60974759-282c9b80-a31a-11e9-88c5-3324d663fdc2.png)

**Comment by devernay** [comment]
fixed in 2.3.16beta and 2.4.0beta
