### ISSUE TITLE
Add Repology badge

### ISSUE THREAD

**Issue by luzpaz** [NatronGitHub/Natron#394]
Repology shows what repositories a package is available in. For space purposes the small badge is appropriate here. Example:
[![Packaging status](https://repology.org/badge/tiny-repos/natron.svg)](https://repology.org/project/natron/badges)

But in other contexts, the full badge is more informative. Example:  
[![Packaging status](https://repology.org/badge/vertical-allrepos/natron.svg?header=natron)](https://repology.org/project/natron/versions)

Let me know and I will make a PR if you're interested

**Comment by devernay** [comment]
I would say I like the tiny badge better! I just added it to README.md, no need to do a PR, thanks!
