### ISSUE TITLE
Flatpak doesn't include h264/mp4 support

### ISSUE THREAD

**Issue by paranoidfactoid** [NatronGitHub/Natron#399]
### Problem

The current Linux Flatpak build doesn't include MP4/h.264 support. Read and Write nodes can neither read in an mp4 file nor write one out. 
 
**Expected behavior:** [What you expected to happen]

To read and write an mp4 h.264. 

**Actual behavior:** [What actually happened]

Nodes fail to do so. Can read jpg and pngs, so image sequences work fine. 

[snip]

* **OS version:** 

Ubuntu 18.04.2LTS w/ official Natron flatpak.

**Comment by devernay** [comment]
@Sunderland93 can you jump in?

**Comment by devernay** [comment]
You should file an issue there: https://github.com/flathub/fr.natron.Natron/issues
Closing this, as this is not related to the Natron source code
