### ISSUE TITLE
binary builds do not contain documentation (at least on macOS)

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#401]
The Natron binaries seem to be missing the html documentation, at least on macOS.
Please @rodlie reply to this issue if it is also missing on windows or linux builds.

The scripts have to be fixed (those jenkins scripts were not really tested, and were never used to build a release)

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 2.3.15-pre2
* **OS version:** 10.14

**Comment by rodlie** [comment]
Generation of docs is disabled in the scripts (also broken if enabled).

I re-enabled it on Linux on my build server yesterday, not tested on Windows yet since I'm currently updating the SDK.

The following diff works on Linux (using pandoc 2.3.1):
```
--- a/tools/jenkins/gen-natron-doc.sh
+++ b/tools/jenkins/gen-natron-doc.sh
@@ -19,7 +19,7 @@ pushd "$NATRON_DOC_PATH"
 # For now, we regenerate the docs from a CI or SNAPSHOT build on Fred's mac, using:
 # cd Development/Natron/Documentation
 # env FONTCONFIG_FILE=/Applications/Natron.app/Contents/Resources/etc/fonts/fonts.conf OCIO=/Applications/Natron.app/Contents/Resources/OpenColorIO-Configs/nuke-defaul
-GENDOCS=0
+GENDOCS=1
 if [ "$PKGOS" = "OSX" ]; then
     RES_DIR="${TMP_PORTABLE_DIR}.app/Contents/Resources"
 else
@@ -37,17 +37,21 @@ fi
 SPHINX_BIN=""
 if [ "$PKGOS" = "Linux" ]; then
     SPHINX_BIN="sphinx-build"
-    "$NATRON_DOC_PATH"/genStaticDocs.sh "$TMP_PORTABLE_DIR/bin/$NATRON_RENDERER_BIN" "$TMPDIR/natrondocs$$" .
+    export LD_LIBRARY_PATH="${SDK_HOME}/lib" # python3 depends on libs in SDK_HOME/lib
+    "$NATRON_DOC_PATH"/../tools/genStaticDocs.sh "$TMP_PORTABLE_DIR/bin/$NATRON_RENDERER_BIN" "$TMPDIR/natrondocs$$" .
 elif [ "$PKGOS" = "Windows" ]; then
     #SPHINX_BIN="sphinx-build2.exe" # fails with 'failed to create process (\mingw64\bin\python2.exe "C:\msys64\mingw64\bin\sphinx-build2-script.py").'
     SPHINX_BIN="sphinx-build2-script.py"
-    "$NATRON_DOC_PATH"/genStaticDocs.sh "$TMP_PORTABLE_DIR/bin/${NATRON_RENDERER_BIN}.exe" "$TMPDIR/natrondocs$$" .
+    "$NATRON_DOC_PATH"/../tools/genStaticDocs.sh "$TMP_PORTABLE_DIR/bin/${NATRON_RENDERER_BIN}.exe" "$TMPDIR/natrondocs$$" .
 elif [ "$PKGOS" = "OSX" ]; then
     RES_DIR="$TMP_PORTABLE_DIR/Contents/Resources"
     SPHINX_BIN="sphinx-build-${PYVER}"
-    "$NATRON_DOC_PATH"/genStaticDocs.sh "${TMP_PORTABLE_DIR}.app/Contents/MacOS/$NATRON_RENDERER_BIN" "$TMPDIR/natrondocs$$" .
+    "$NATRON_DOC_PATH"/../tools/genStaticDocs.sh "${TMP_PORTABLE_DIR}.app/Contents/MacOS/$NATRON_RENDERER_BIN" "$TMPDIR/natrondocs$$" .
 fi
 $SPHINX_BIN -b html source html
+if [ ! -d "$RES_DIR/docs" ]; then
+    mkdir -p "$RES_DIR/docs"
+fi
 cp -a html "$RES_DIR/docs/"
 fi
```
I also had to fix some other issues (build scripts) on Linux, will commit fixes later today.

My builds (Linux for now, should have Win up soon) are currently here: https://natron.fxarena.net/snapshots/RB-2.3/

The full unit tests also needs to be fixed, they reference broken urls. Will fix

**Comment by devernay** [comment]
I made many fixed on the scripts, including the unit test scripts. Make sure to use the latest version

**Comment by rodlie** [comment]
I see the changes now, for some reason the updated unit tests where not included when I ran the build last night. Will re-run.

**Comment by devernay** [comment]
And also pandoc should not be needed, only Sphinx. Everything is in the source tree. Please disable the une of pandoc

**Comment by rodlie** [comment]
I didn't enable anything pandoc related, I just added pandoc in /usr/local/bin in case it was needed.

**Comment by devernay** [comment]
It should NOT execute the `genStaticDocs.sh`, only this line:
```
 $SPHINX_BIN -b html source html
```
Everything is in the sources (as rst files), and pandoc does *not* need to be run, so please only enable the sphinx-build call.
Just to be on the safe side, you should not have pandoc in the PATH on a build system (only on a dev system)

**Comment by devernay** [comment]
> for some reason the updated unit tests where not included when I ran the build last night

the scripts tried to clone Natron-Tests in the current script directory (which is stupid - nothing should be written there). Now it clones it at every build in the same directory as the other sources.
This will avoid many issues we had previously with just updating the tests instead of re-cloning them.

The large assets are now downloaded in the "src" dir in the workspace, so they are not deleted and re-downloaded at each build.

**Comment by rodlie** [comment]
New files:
* https://natron.fxarena.net/snapshots/RB-2.3/Natron-RB-2.3-201907162042-996bf1a-64-no-installer.tar.xz
* https://natron.fxarena.net/snapshots/RB-2.3/Natron-RB-2.3-201907162042-996bf1a-64.tgz

No pandoc used (only sphinx), and full unit tests completed (unit_tests_failures folder was empty).

I have done minimal testing outside that (I ran it on my machine did some basic stuff).

**Comment by devernay** [comment]
So did you make any change to the scripts?
You have to look at the script output. Very often the unit_test_failures script is empty but some tests failed. We should put a full test report in text format next to the binaries.
