### ISSUE TITLE
Blur node with guassian or quasi-guassian filter make a thick and wired feather

### ISSUE THREAD

**Issue by bakter** [NatronGitHub/Natron#408]
Wrong edge with guassian and quasi-guassian filter.

1. Put Blur node under Roto which contain a mask (no matter which channel used for blurring )
2. Set blur size 2 or other small value
3. Set gamma value in viewer to 50 to see the problem.

Using other filters do not cause this problem.

![BlurProblem](https://user-images.githubusercontent.com/42199257/61775956-473b2b00-adfa-11e9-8bad-21d789a54047.png)

Natron version 2.3.14 Release.
Gentoo Linux base system 2.6

**Comment by devernay** [comment]
Hum.
Do you know what gamma = 50 means?

This issue has already been raised multiple time, and is documented if you click on "?":
"
Note that the Gaussian filter [1] is implemented as an IIR (infinite impulse response) filter [2][3], whereas most compositing software implement the Gaussian as a FIR (finite impulse response) filter by cropping the Gaussian impulse response. Consequently, when blurring a white dot on black background, it produces very small values very far away from the dot. The quasi-Gaussian filter is also IIR.

A very common process in compositing to expand colors on the edge of a matte is to use the premult-blur-unpremult combination [4][5]. The very small values produced by the IIR Gaussian filter produce undesirable artifacts after unpremult. For this process, the FIR quadratic filter (or the faster triangle or box filters) should be preferred over the IIR Gaussian filter.
[1] https://en.wikipedia.org/wiki/Gaussian_filter

[2] I.T. Young, L.J. van Vliet, M. van Ginkel, Recursive Gabor filtering. IEEE Trans. Sig. Proc., vol. 50, pp. 2799-2805, 2002. (this is an improvement over Young-Van Vliet, Sig. Proc. 44, 1995)

[3] B. Triggs and M. Sdika. Boundary conditions for Young-van Vliet recursive filtering. IEEE Trans. Signal Processing, vol. 54, pp. 2365-2367, 2006.

[4] Nuke Expand Edges or how to get rid of outlines. http://franzbrandstaetter.com/?p=452

[5] Colour Smear for Nuke. http://richardfrazer.com/tools-tutorials/colour-smear-for-nuke/
"

**Comment by bakter** [comment]
If this is the expected behavior, then ok, just weird.

**Comment by devernay** [comment]
This is all about math and floating-point operations. Nuke's Gaussian is weird. Compositors should learn that a Gaussian filter is not a FIR and that they should use a FIR for their tricks. The name "Gaussian" was wrongly used by most compositing software because it looked cool. Thus the doc.

**Comment by bakter** [comment]
Thanks for your great answer, I should do more math :).
