### ISSUE TITLE
I can't find Text Node in Draw

### ISSUE THREAD

**Issue by Ryudaa** [NatronGitHub/Natron#409]
Hello.. I use Natron 2.3.14 in Ubuntu. I try to follow TJFree tutorial on youtube, but when he teach about Text Node, I can't follow him because there is no Text Node in my Natron.
Maybe it hidden somewhere, but it isn't in Draw...
![lapor](https://user-images.githubusercontent.com/53323453/61920924-7f22a980-af85-11e9-979d-59660c4fac9d.png)

**Comment by devernay** [comment]
Hi,
Did you apply the hotfix https://github.com/NatronGitHub/Natron/releases/download/2.3.14/Natron-2.3.14-Linux-hotfix.sh after installing 2.3.14?
If it doesn't work, can you please test 2.3.13 and the 2.3.15 prerelease from https://github.com/NatronGitHub/Natron/releases and report?

**Comment by Ryudaa** [comment]
I try to apply the hotflix, but I don't know how to do it because I installed Natron from Ubuntu Software (can't find Natron directory)..
Now I try to install it from https://natrongithub.github.io/ and it works fine without hotfix..
But I think I will apply hotflix just in case something went wrong

**Comment by devernay** [comment]
- download the hotfix
- execute `bash Natron-2.3.14-Linux-hotfix.sh <Natron_installation_folder>` where you replace the second argument by where you installed Natron
