### ISSUE TITLE
Feature Request: FrameRange "loop" option

### ISSUE THREAD

**Issue by chenycallen** [NatronGitHub/Natron#411]
I don't know if it is possible to see the "loop" option in the **frameRange** node like nuke timeClip node .
Or have other alternative nodes.
thank.🤗

Natron(FrameRange)
![Natron](https://i.imgur.com/ojIltQW.png)

Nuke(TimeClip)
![Nuke](https://i.imgur.com/fPhO1z3.png)

**Comment by devernay** [comment]
easy. will do.

**Comment by devernay** [comment]
are you on linux, mac or windows?
I'm uploading the new linux build

**Comment by chenycallen** [comment]
windows thanks

**Comment by devernay** [comment]
we don't have windows builds yet. coming soon
