### ISSUE TITLE
G'MIC plugins not showing up in Natron 2.3.15 RC6

### ISSUE THREAD

**Issue by fabiof17** [NatronGitHub/Natron#414]
Using installer on Centos 7 KDE.
But they show up and work using the "no installer" version.

**Comment by rodlie** [comment]
They are not included in the installer at all. Must be something in the build script that fails (or don't add GMIC.ofx.bundle). I can check a bit later today.

**Comment by rodlie** [comment]
Fixed. The next build will have GMIC.ofx included in the installer.
