### ISSUE TITLE
Read node class are different on Windows and Linux

### ISSUE THREAD

**Issue by fabiof17** [NatronGitHub/Natron#415]
On Windows, a Read node is of 'Read' class, on Linux of 'ReadOIIO'.

Natron 2.3.14

**Comment by devernay** [comment]
very strange. Can you give more details? maybe write a python script that creates a read node, prints its class, and thus gives a different result on linux and windows?

**Comment by rodlie** [comment]
I used https://natron.readthedocs.io/en/rb-2.3/devel/PythonTutorials/nodes/getSelectedNodesClass.html and the result is identical on Windows and Linux.

``fr.inria.built-in.Read``

**Comment by devernay** [comment]
closing, then
