### ISSUE TITLE
Binaries build system (Windows not yet available)

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#418]
### Problem

Everyone can now produce the Linux and macOS "official" binaries from the source code:

- for Linux, we now distribute [Docker images](https://github.com/NatronGitHub/Natron/tree/RB-2.3/tools/docker) based on CentOS6, which contain a precompiled [Natron Linux SDK](https://github.com/NatronGitHub/Natron/blob/RB-2.3/tools/jenkins/include/scripts/build-Linux-sdk.sh). It is also easy to install the SDK script on another Linux distribution, and even make a docker image out of it.
- for macOS, we updated the [build instructions](https://github.com/NatronGitHub/Natron/blob/RB-2.3/INSTALL_OSX.md) to build the binaries on a Virtual Machine, which is the recommended way because Natron requires dependencies built with specific options or patches. Natron can also be built easily on a physical machine (using either MacPorts or Homebrew) for debugging purposes.

Work on the Windows build system is done by @rodlie, who updated the previous build system. We have to make sure that this work is reproductible, and make sure that before the 2.3.15 release we have precise and reproductible instructions to produce these binaries, either on a physical system, on a virtual machine, or optionally in a [docker for windows](https://docs.docker.com/docker-for-windows/) image.

This issue tracks the development and issues with the three build systems:
- improve the build system documentation and the build process for all three architectures: we invite users to test and improve the already existing build systems.
- finalize and document the Windows build system.

This is the last blocking issue before the next official release (2.3.15).

**Comment by devernay** [comment]
Adding Natron "builders" to the issue so that they get notified: @yomgui1 @fonkle @Ivanohe73 @mash-graz

**Comment by rodlie** [comment]
I have several commits for the Windows build pending based on if we use MSYS current or a older MSYS snapshot. I have not found any (proper) solution to the Windows knob problems (will make a new issue when I'm on my Windows machine) on MSYS current yet. I can prepare a fallback SDK if needed.

**Comment by devernay** [comment]
As long as the procedure is fully reproductible starting from a clean system, and maintainable, then that's OK. It thus cannot be "download the 3Gb SDK from there", because that would mean it cannot be maintained and packages cannot be upgraded.

Would switching to a cross-compilation toolchain make sense for the future?

VLC has a large set of dependencies, and they compile the windows version on Debian. Most Natron dependencies are already there (and for the others we could probably use what we have in the Linux SDK). In fact, we may even want to consider moving the whole build system to use the VLC build system (in a future release) https://wiki.videolan.org/Win32Compile/

This is the list of the VLC packages: http://git.videolan.org/?p=vlc.git;a=tree;f=contrib/src

**Comment by rodlie** [comment]
Using a MSYS snapshot over time is doable, instead of upgrading binary packages we will need to build them using makepkg (from MINGW-packages master). This can at least be used until we find the issue with MSYS-current. All this can be reproducible as long as you download the correct MSYS base snapshot when you setup MSYS (and never update pacman).

Another option is to only use the MSYS toolchain and adapt our Linux build to work on Windows. Should "just" be a matter of adding patches and adjusting configure/cmake/etc.

A third option is to move to MXE for the Windows build. Some packages are missing but should be easy to add (Krita also uses MXE). Pros is that we can build it on more or less anything, cons are that we must use WINE to run the tests.

I have not looked at VLC, but I'm open for anything that simplifies the build system (on all systems).

**Comment by eszlari** [comment]
> In fact, we may even want to consider moving the whole build system to use the VLC build system (in a future release) https://wiki.videolan.org/Win32Compile/

afaik VLC wants to move to Meson (https://mesonbuild.com):

https://epir.at/2018/08/13/gsoc-2018/

**Comment by devernay** [comment]
@eszlari are they also moving to meson for third party packages? It seems like these do not use autotools but only gnu make. If you have any info on the box build system please post here. 
I think @yomgui1 also mentioned the vlc build system previously

**Comment by yomgui1** [comment]
@eszlari You misunderstood what this GSoC project does, but it's not your fault: the person behind has not correctly used the right words to explain what he/she does.

The VLC "build system" is composed by 3 majors layers:
1) at the bottom: a bunch of Makefiles to obtain a buildtools chain (extras/ directory)
2) then the "contrib" system: also a bunch of Makefiles that setup environment and calls the third-party build system (that can be anything, but mostly using buildtools chain created at first layer.
3) at  the top: the application build system, building VLC code.

The GOsC project changes only the third layer, not the toolchain/contrib. This is more logical, the goal is not to remake all contrib build system. That's not make sens (this is the patent of third-party, not VLC).

Natron has mostly the same 3 layered buildsystem, the difference is Natron uses bash scripts where VLC uses GNU Make.

The major improvement by using Make is to have a builtin dependency tree system (based on file modification time and "GCC -M" output) and a common files to support all platforms (mostly, exceptions may exist).

Makefiles are also more convenient than bash scripts to write and use (it works, but it's harder to use, like using ASM than C).
Personally, I just found that bash scripts are a bit "raw" and the fact to have different ones to build each platforms doesn't help for maintenance.

If there is a motivation to do, we can see other kind of backend for our "contrib" system than Make/bash: SCons, Meson, ... but the third-party build system cannot be touched (as it comes from their respective maintainers).

**Comment by rodlie** [comment]
Regarding Windows.

I will dedicated Monday (and Tuesday if needed) to finish the Windows build stuff, I will be using a older MSYS2 snapshot so we can get something usable out to the users.

I will keep MSYS-current and continue to test on that of course.

**Comment by threedslider** [comment]
I try to compile from scratch all third party for Natron but I have errors from QT4 when I compile Mingw 32bit. Do you have same issue ?

**Comment by rodlie** [comment]
Need more info, what kind of errors? How did you build Qt?

I will update the documentation regarding building on Windows, and start providing binaries, but it will have to wait until the second week of December as I'm busy with various deadlines on other projects.

**Comment by threedslider** [comment]
I have fixed a lot of errors, now i am compiling QT4... Hope it will finish as 100% :)

**Comment by threedslider** [comment]
Woohoo QT4 was compiled as successfully ! It takes nearly a day to compile lol

@rodlie you need this QT4 compiled version 4.8.7 ?

**Comment by threedslider** [comment]
@devernay need it there to be update from buildmaster.sh in version Natron 2.3.15-rc.11 ?

**Comment by threedslider** [comment]
This will be my first commit to contribute for Natron. I don't know if it is large or small change ?? So i took by cloning to RB-2.3-fix and make some change them... Hope you don't mind but How to pull request for small change (one commit) without large because it says there are more than 250 commit to pull resquest ?!

I fixed Natron from version and some other modification by enabling clang.

I have added keychain cause this script in buildmaster.sh ask to do it.

**Comment by rodlie** [comment]
A small update on Windows. I'm currently working on it as we speak. I will be using an older snapshot so it will take some time updating the existing packages (without breaking anything), but other than that the rest should be easy, I did most of the work back in October.

I will need to modify/update several packages, this means the ``MINGW-packages`` folder might get quite large, should I keep them separated from the main Natron repo?

Also note that latest MSYS2 has now removed everything related to Python2. This will not affect us since we use an older snapshot, but something to be aware of.

My goal is to have working binaries by Monday.

**Comment by devernay** [comment]
great! I don't think a large MINGW-packages dir is an issue. It's just patches and package desrciptions, right? I prefer to have everything in the same place (we already have the linux and the macos SDKs here)

**Comment by rodlie** [comment]
Yes, it's only text files. I'm currently dumping them here as they build: https://github.com/rodlie/Natron-MINGW

Will add them do the main repo when done.

**Comment by rodlie** [comment]
@devernay Can we host the MSYS/MINGW packages on SourceForge? (currently the size is ~800M total) Would make life a bit simpler for people setting up/using MSYS for developing/building Natron.

I have tested using SF as a pacman repo and it works fine (https://downloads.sourceforge.net/project/openfx-arena/MINGW-packages).

**Comment by rodlie** [comment]
So, I'm finally able to produce binaries, but ``Natron-Tests`` does not work yet. 

```
...

+ /home/olear/Natron-snapshot-workspace/tmp64/tmp_deploy/Natron-RB-2.3-202001112347-57da201-64-no-installer/bin/idiff.exe reference1.jpg output1.jpg -o comp1.jpg -warn 0.001 -fail 0.008 -failpercent 0.2 -hardfail 0.08 -abs -scale 30
+ true
+ '[' '!' -f output1.jpg ']'
+ '[' '!' -f comp1.jpg ']'
+ echo 'WARNING: /home/olear/Natron-snapshot-workspace/tmp64/tmp_deploy/Natron-RB-2.3-202001112347-57da201-64-no-installer/bin/idiff.exe failed for frame 1 in TestBloom'
WARNING: /home/olear/Natron-snapshot-workspace/tmp64/tmp_deploy/Natron-RB-2.3-202001112347-57da201-64-no-installer/bin/idiff.exe failed for frame 1 in TestBloom
+ failframe=1
+ '[' 1 = 1 ']'
+ cp reference1.jpg /home/olear/Natron-snapshot-workspace/tmp64/Natron-Tests64/failed/TestBloom-reference1.jpg
+ cp output1.jpg /home/olear/Natron-snapshot-workspace/tmp64/Natron-Tests64/failed/TestBloom-output1.jpg
+ cp comp1.jpg /home/olear/Natron-snapshot-workspace/tmp64/Natron-Tests64/failed/TestBloom-comp1.jpg
cp: cannot stat 'comp1.jpg': No such file or directory
+ failconf=1

...
```

Running manually:
```
$ DEPLOY_PATH/bin/idiff.exe reference1.jpg output1.jpg -o comp1.jpg -warn 0.001 -fail 0.008 -failpercent 0.2 -hardfail 0.08 -abs -scale 30
```
Nothing ... If I remove the options I get output and image:

```
$ DEPLOY_PATH/bin/idiff.exe reference1.jpg output1.jpg -o comp1.jpg
Comparing "reference1.jpg" and "output1.jpg"
  Mean error = 4.39812e-006
  RMS error = 0.00013133
  Peak SNR = 77.6327
  Max error  = 0.00392163 @ (6, 76, R)  values are 0.752941, 0.780392, 0.811765 vs 0.74902, 0.776471, 0.807843
  294 pixels (0.112%) over 1e-006
  294 pixels (0.112%) over 1e-006
FAILURE

$ ls -l comp1.jpg
-rw-r--r-- 1 olear None 4885 Jan 12 02:03 comp1.jpg
```

Is there something I'm missing or doing wrong?

**Comment by devernay** [comment]
try changing the option order maybe? put the positional arguments reference1.jpg output1.jpg at the end

**Comment by rodlie** [comment]
Tried that, also tried to remove them one by one.

**Comment by devernay** [comment]
any output with option "-v" ?

**Comment by rodlie** [comment]
Only when using ``cmd ref.jpg out.jpg -o comp.jpg``, but not when using options. Seems any option outside of ``-o`` breaks. 

Might be a broken build (the OIIO lib seems to work just fine), will try building different versions.

**Comment by rodlie** [comment]
idiff from v1.7 works, but 2.x does not. Will need to debug and find out where it fails.

**Comment by devernay** [comment]
Nice! did you submit the patch upstream to @lgritz ? (this affects all command-line tools in oiio btw)

**Comment by rodlie** [comment]
No, I just fixed it (for 2.0.x) and went to bed... I will adjust our existing patches for oiio 2.1 today and test that everything works as it should. Will submit patch upstream.

**Comment by devernay** [comment]
transition from 2.0 to 2.1 should go like a breeze. Actually that issue is already fixed in 2.1.
Maybe you should check whether some of the ifdef _MSC_VER in oiio should be rewritten as _WIN32 (there are only 32 of these https://github.com/OpenImageIO/oiio/search?p=2&q=_MSC_VER&unscoped_q=_MSC_VER )

**Comment by rodlie** [comment]
I had to change one extra _MSC_VER for 2.1: https://github.com/NatronGitHub/Natron/blob/RB-2.3/tools/MINGW-packages/mingw-w64-openimageio21/oiio-2.1.10-mingw.diff#L36 .

I should go through each of the ifdef, but I don't have time for that today.  OIIO v2.1 now builds with minimal changes on MinGW, that's a good thing :)

**Comment by rodlie** [comment]
Windows unit test status:
```
TestImageCR2 : FAIL
TestImagePCX : FAIL
TestImagePSB : FAIL
TestPolar : FAIL
TestReadMOV_ap4h : FAIL
TestReadMOV_apch : FAIL
TestReadMOV_apcn : FAIL
TestReadMOV_apco : FAIL
TestReadMOV_apcs : FAIL
TestReadMPEG1 : FAIL
TestTexture : FAIL
BayMax : FAIL
TestWriteFFmpeg/avi_m2v1 : FAIL
TestWriteFFmpeg/avi_mp4v : FAIL
TestWriteFFmpeg/mov_mp4v : FAIL
TestWriteFFmpeg/mp4_m2v1 : FAIL
TestWriteFFmpeg/mp4_mp4v : FAIL
```

**Comment by devernay** [comment]
I would take a closer look at BayMax results. The other ones are OK.

**Comment by rodlie** [comment]
The ``unit_tests_failures`` folder is empty and the output files are removed in the BayMax folder, the following are output from the terminal: https://gist.github.com/rodlie/97a939d6ca1c62b45802f8e64576b27d

Frame 12, 15, 21, 33 fails.

**Comment by devernay** [comment]
that looks almost OK, you'll take a closer look later.
So you you have RC binaries for Windows now? Can you add these to RC15?

**Comment by rodlie** [comment]
```
├── [   0]  compressed_no_installer
│   └── [181M]  Natron-RB-2.3-202001212349-8e4d28c-Windows-64-no-installer.zip
└── [   0]  offline_installer
    └── [151M]  Natron-RB-2.3-202001212349-8e4d28c-Windows-64.exe
```
I have not tested the installer yet, will test it on a couple of different machines. Portable is ok.

**Comment by rodlie** [comment]
Sorry for the delay, the installer has been tested on Windows 8.1, Windows 10 (19.03) and works. Will upload.

However, I noticed a doc bug (applies to all builds/platforms). The auto-generated (anything _*.html) HTML is broken. The stylesheet ``_static/markdown.css`` does not exists.

**Comment by bonalex01dev** [comment]
Hi I think many people would be interested in using NATRON on WINDOWS including me as a former Natron user.
Recent builds or updated tutorial for building  would be great! Any news on this ?
(Stability is probably preferred over performance for most users).
Thanks for all your work,
Alexandre.

**Comment by devernay** [comment]
@bonalex1 there are rather recent windows binaries for 2.3.15rc15 in the GitHub releases

**Comment by rodlie** [comment]
> Hi I think many people would be interested in using NATRON on WINDOWS including me as a former Natron user.
> Recent builds or updated tutorial for building would be great! Any news on this ?

We have recent builds (RC15) for Windows. The RC snapshots are not coordinated so the Windows builds might lag behind sometimes. At the moment I'm not ready to do a RC16 build since I'm trying to update some critical packages (move from OpenSSL 1.0 to 1.1 and rebuild everything that depends on that) that will break if not built properly.

Feel free to do your own builds, the Windows instructions should be on-par with the other platforms.

**Comment by bonalex01dev** [comment]
Thanks for the quick answers, I'll try to contribute to the documentation in return.

**Comment by rodlie** [comment]
@devernay :
Noticed that Travis now has experimental support for Windows. I was able to hack in (our custom) MSYS2 support and is now able to build openfx-arena on Travis against the Natron Windows SDK.

First successful build: https://api.travis-ci.com/v3/job/298193933/log.txt (https://travis-ci.com/github/rodlie/openfx-arena-1/jobs/298193933)

It's a bit slow (took 13min) and has issues downloading packages (this is a Travis issue, SF.net works fine from my computer) but works :)

**Comment by devernay** [comment]
@rodlie Any idea why the no-installer windows binary is 30MB larger than the installer version?

**Comment by rodlie** [comment]
Might be missing strip? Will check.

**Comment by rodlie** [comment]
Arena.ofx and GMIC.ofx is not stripped.

**Comment by rodlie** [comment]
Actually, Arena.ofx and GMIC.ofx is not stripped in the installer either. The reason is probably that they are stripped after the manifest is added (which won't work).

**Comment by rodlie** [comment]
I will now upload a new Windows build (Arena and GMIC is now stripped).

All 23 regular unit test now pass, this includes ``ModelSearch.HomographyMinimal``.

Regarding file size, before compression the offline-installer and no-installer are identical:
```
486M    Natron-installer
486M    Natron-RB-2.3-202003150238-cfbe314-Windows-64-no-installer
```
```
v2.3.15-rc17/
├── [144M]  Natron-RB-2.3-202003150238-cfbe314-Windows-64.exe
├── [170M]  Natron-RB-2.3-202003150238-cfbe314-Windows-64-no-installer.zip
└── [5.5K]  Natron-RB-2.3-202003150238-cfbe314-Windows-64-tests.txt
```
no-installer is compressed with regular zip while offline-installer is compressed with 7zip, that's the only reason for the difference I can see.

**Comment by bonalex01dev** [comment]
Hi,
you guys rock. This version works fine on Win10 (Shadertoy OK, GMIC Ok) !
At last some good news in these tough Cov19 days. Take good care of you.
I started working on the docs
