### ISSUE TITLE
rotopaint error

### ISSUE THREAD

**Issue by RafaMartorell** [NatronGitHub/Natron#419]
I enclose a file that I have made and you will see that if you select the main layer, the properties and animation of the others are lost. This is very annoying and prevented me from being able to recommend Natron as a multi-layer drawing tool.
[DRAW.ntp.zip](https://github.com/NatronGitHub/Natron/files/3479316/DRAW.ntp.zip)

**Comment by devernay** [comment]
Can you please give a step-by-step description of the issue, as instructed, and please be respectful of the Natron team. Saying that you cannot recommend Natron because of a bug will not help solving that bug.

**Comment by RafaMartorell** [comment]
No.
Your response does not encourage me to bother reporting a bug again. And I'm surprised that something so simple needs more explanation when I even put an example file.

**Comment by RafaMartorell** [comment]
> Can you please give a step-by-step description of the issue, as instructed, and please be respectful of the Natron team. Saying that you cannot recommend Natron because of a bug will not help solving that bug.

@devernay I apologize, I think we have misunderstood each other. It bothered me that you saw a lack of respect in my comment when this was never my intention. I responded badly and for this I apologize. It is not good that we are angry with each other because this is not positive at all. For my part it is already forgotten and I even tried with my little experience in Github to notify the bug again the way you recommended me.
Stress sometimes makes us not behave as we really are, my intention has never been to bother anyone, rather the opposite, try to help.
