### ISSUE TITLE
forbidden

### ISSUE THREAD

**Issue by kirelly** [NatronGitHub/Natron#424]
when downloading the installer, it stopped and said the file being forbidden, i checked the info about this and thought it was my internet and try the next day. it happen again and again, even on the portable archive, i thought i miss a requirement or something but nothing in your website said that. i only just found this because people saying its an alternative or similar to after effects and wanted to try 2d animating. im very surprised this happen. and i dont know if this happen already-

**Comment by rodlie** [comment]
You are unable to download Natron? Download links work fine here.

* https://github.com/NatronGitHub/Natron/releases/tag/v2.3.14
* https://sourceforge.net/projects/natron/files/

**Comment by devernay** [comment]
@kirelly is this solved?
