### ISSUE TITLE
Installer for Linux shows pixelated text and in some instances non-enlish text

### ISSUE THREAD

**Issue by luzpaz** [NatronGitHub/Natron#426]
Please ask questions ("how do I...?") on the [forum](https://discuss.pixls.us/c/software/natron), not by filing issues.

Please read carefully the [Troubleshooting](http://natron.readthedocs.io/en/rb-2.3/guide/getstarted-troubleshooting.html) section of the [Natron documentation](http://natron.readthedocs.io) before submitting an issue: this issue may already be signaled, or may have a simple workaround.

Make concrete suggestions for fixing the code ("here is a patch") by filing
a [pull request](https://github.com/MrKepzie/Natron/pull/new/master), not an issue.

Finally, please follow the [Code of Conduct](https://github.com/NatronGitHub/Natron/blob/RB-2.3/CODE_OF_CONDUCT.md) when interacting with the Natron community (both users and developers).

### Problem

Describe the problem or suggestion here.

**Expected behavior:** Readable installation

**Actual behavior:** Manageable but can be improved

 * If your problem can be reproduced using a Natron project, please include a link to the project on a file sharing service, or attach the project as a zip file to this issue, if possible.
 
### Steps to Reproduce

1. Download [Natron 2.3.14 installer](https://github.com/NatronGitHub/Natron/releases/download/v2.3.14/Natron-2.3.14-Linux-x86_64bit.tgz)     
2. Run Installer

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

![image](https://user-images.githubusercontent.com/4140247/64462313-fd6a8380-d0cd-11e9-91d7-a7ece9c9685a.png)

### Versions

* **OS version:** 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.4
DISTRIB_CODENAME=Illyria
DISTRIB_DESCRIPTION="Manjaro Linux"

**Comment by rodlie** [comment]
Could you run the installer through a terminal and post any errors/warnings?

**Comment by luzpaz** [comment]
No error warnings. But it did crash when I tried to run it
```
[foo@foo natron]$ ./Natron-2.3.14-Linux-x86_64bit
# Installation Wizard ends with no output and I choose to 'Start Natron now' 
[foo@foo natron]$ Natron Version 2.3.14
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
couldn't open library /home/foo/Natron/Plugins/OFX/Natron/Arena.ofx.bundle/Contents/Linux-x86-64/Arena.ofx because /usr/lib/libcairo.so.2: undefined symbol: FT_Done_MM_Var
Caught segmentation fault (SIGSEGV) from thread Main(0x25509d0), faulty address is 0x366a0 from 0x366a0
Backtrace:
```

**Comment by rodlie** [comment]
You need the Linux hotfix :
https://discuss.pixls.us/t/natron-2-3-14-linux-hotfix-1/13175

the installer probably has issues with fontconfig/freetype installed on
your system.

**Comment by luzpaz** [comment]
OK, the hotfix fixed the https://github.com/NatronGitHub/Natron/issues/426#issuecomment-531573274 
Thanks! 

But the pixelation (font) bug still exists.

**Comment by rodlie** [comment]
To fix the installer we will probably need to build against a static fontconfig and modify fontconfig to not use any config files (add hardcoded "failsafe" in the code or something similar).

I might have time to look at this by the end of this week, but I do have more important things to do (the Windows version of Natron).
