### ISSUE TITLE
Read EXR image sequence causes Natron to crash during project closure

### ISSUE THREAD

**Issue by jerlyn06** [NatronGitHub/Natron#427]
Natron 2.3.14/Window 7 Pro

I've been facing this issue for the last couple of days. I have a series of zip-compressed EXR images that I rendered using Autodesk's Maya that I'm bringing into Natron to convert into a h-264 HD movie. Everything renders fine but once render is finished and I want to close the project, Natron crashes. 

I don't see any error printing in the console as well. Note that this also happens with other EXR image sequences that haven't been through our Maya pipeline. 

A temp fix we've done is to add a task kill script to the app.beforeProjectClose callback in Project Settings. 

To Reproduce: 

1. Render zip compressed EXR with blackman_harris filter from Maya using mtoA 5.3
2. Bring the sequence in using Read Node
3. Render .mov in 2k using H264 
4. Close Natron [This is where Natron crashes]

**Comment by devernay** [comment]
This may be fixed by 2.3.15 already, as there were fixed upsteems to the openimageio threading code. Unfortunately there is still no windows build.
Volunteers are welcome to help @rodlie on that, but keep in mind that this is a significant amount of work

**Comment by rodlie** [comment]
I have a working win build of 2.15, I just have not had the time to make a re-producible sdk setup. I have the weekend off and have access to my win computer so I will make that a priority.

This issue should be fixed in 2.15.

**Comment by jerlyn06** [comment]
awesome, thank you! I look forward to .15!

**Comment by rodlie** [comment]
Closing, works fine on Windows with 2.3.15.
