### ISSUE TITLE
Bug import svg file in Natron version Natron version 2.3.14 Release. in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by Herd25** [NatronGitHub/Natron#428]
Hello, I am new to Natron but I have seen how its user guide is but I have an inconvenience when trying to read an svg file, this answers me with an error which says that it does not find the module and there was an error when loading it is supposed that this It works normally in other versions of natron I don't know if it is due to the version that ubuntu will handle but in that case I use the Natron version 2.3.14 Release.
on Ubuntu 18.04 LTS thanks

**Comment by rodlie** [comment]
Need more info, error message? sample svg file?

**Comment by devernay** [comment]
no feedback. I'm guessing @Herd25 did not apply the hotfix (see the release notes on github).
closing
