### ISSUE TITLE
Could not find layer Color in view Right in .exr

### ISSUE THREAD

**Issue by norru** [NatronGitHub/Natron#429]
If I attempt to read the attached EXR I get the following error message:

"Could not find layer Color in view Right in `/tmp/cant_read_in_natron.exr`
[cant_read_in_natron.exr.zip](https://github.com/NatronGitHub/Natron/files/3630496/cant_read_in_natron.exr.zip)

The EXR is perfectly valid. 

I am trying to migrate out of Nuke and this is one of my showstoppers.

In the meantime I need to keep backwards compatibility with existing projects. I have hundreds of thousands of existing images with this layout so converting them is not an option.

```
$ exrheader /tmp/cant_read_in_natron.exr

file /tmp/cant_read_in_natron.exr:

file format version: 2, flags 0x0
channels (type chlist):
    B, 16-bit floating-point, sampling 1 1
    G, 16-bit floating-point, sampling 1 1
    R, 16-bit floating-point, sampling 1 1
    right.B, 16-bit floating-point, sampling 1 1
    right.G, 16-bit floating-point, sampling 1 1
    right.R, 16-bit floating-point, sampling 1 1
compression (type compression): zip, individual scanlines
dataWindow (type box2i): (0 0) - (2047 1555)
displayWindow (type box2i): (0 0) - (2047 1555)
lineOrder (type lineOrder): increasing y
multiView (type stringvector):
    "left"
    "right"
nuke/full_layer_names (type int): 0
nuke/node_hash (type string): "572d0fb078ee559a"
nuke/version (type string): "11.0v3"
pixelAspectRatio (type float): 1
screenWindowCenter (type v2f): (0 0)
screenWindowWidth (type float): 1
type (type string): "scanlineimage"
version (type int): 1
```

Ubuntu 18.04
```
Natron version 2.3.14 Release.
Natron, an open source compositing software
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

See the Natron website for more information on this software.
This software was compiled from the source code branch tags/2.3.14 at version 5bbf5ed using GNU C++ version 7.3.0 with OpenMP 4.5 targetting Intel x86-64 for Linux.
The bundled openfx-io plugins were compiled from version 761faea.
The bundled openfx-misc plugins were compiled from version 3c007bf.
The bundled openfx-arena plugins were compiled from version 38e8e3a.
The bundled openfx-gmic plugins were compiled from version 096fe05.
```

**Comment by rodlie** [comment]
Works fine here. Please provide more information (Natron version/build/OS etc).

**Comment by norru** [comment]
Added information to the OP.

Do you see both Left and Right views correctly after loading? I can only see the Left one.

**Comment by norru** [comment]
Here's the project and a screenshot.
![cant_read_in_natron ntp — Natron_217](https://user-images.githubusercontent.com/889291/65239524-b49fcb00-dace-11e9-80eb-6e7faa52a29c.png)

[cant_read_in_natron.zip](https://github.com/NatronGitHub/Natron/files/3630882/cant_read_in_natron.zip)

**Comment by rodlie** [comment]
The image has ``Color`` (red) and ``right`` (blue) layers.

Could you test the latest RC release and see if you have the same issue?
https://github.com/NatronGitHub/Natron/releases/download/v2.3.15-rc.9/Natron-RB-2.3-201909090540-0b1ab28-64-no-installer.tar.xz

**Comment by norru** [comment]
Happy to test RC!

Did you set up Multiview?

**Comment by rodlie** [comment]
I didn't setup multiview, If I change view to ``Right`` I get the same error message.

**Comment by norru** [comment]
Tried the RC version, no changes.

**Comment by norru** [comment]
> Seems to be an old issue? https://discuss.pixls.us/t/issue-with-stereo-exr-multi-view/8258/4

Yes, it is the same issue.

**Comment by rodlie** [comment]
I did a quick test on older versions using https://github.com/openexr/openexr-images/raw/master/MultiView/Balls.exr

* 2.1.9 - ok
* 2.2.3 - ok
* 2.2.4 - ok
* 2.2.5 - ok
* 2.2.6 - ok
* 2.2.7 and beyond - **fail**

**Comment by devernay** [comment]
I would really like to have that bug fixed for 2.3.15. It's very probably an issue with the ReadOIIO plugin as you pointed out, and specifically these two commits : https://github.com/NatronGitHub/openfx-io/commit/963e1a880cd77ea06fdf43531b1bdce08c493004 https://github.com/NatronGitHub/openfx-io/commit/5de9b290e063abfefd3d24cd5631d7c88bfb3b20

**Comment by rodlie** [comment]
I though that as well, but it's actually https://github.com/NatronGitHub/openfx-io/commit/79ac6546e0a1aed7f14fd15fbc3dfd634b91d4c5

I tested https://github.com/NatronGitHub/openfx-io/commit/963e1a880cd77ea06fdf43531b1bdce08c493004 against Natron 2.2.7 and it works, going to https://github.com/NatronGitHub/openfx-io/commit/79ac6546e0a1aed7f14fd15fbc3dfd634b91d4c5 breaks.

I'm currently not able to test against openfx-io master on my machine (I think my oiio2 install is broken or something).

**Comment by devernay** [comment]
Will test with and without this commit, and will build a Linux version for testing by @norru

**Comment by norru** [comment]
Sounds good, please let me know when I can download a code drop to test.

**Comment by devernay** [comment]
Should be fixed by https://github.com/NatronGitHub/openfx-io/commit/af69a636c600ed5cf3fb93a48e00faba709cb312 and https://github.com/NatronGitHub/openfx-io/commit/f31d7b6a5451f94a651507680a67e8cced95e7ee

@norru can you please test with the latest Linux RC?

**Comment by devernay** [comment]
@norru any feedback? is it fixed in 2.3.15RC22?

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/openfx-io/commit/af69a636c600ed5cf3fb93a48e00faba709cb312 and https://github.com/NatronGitHub/openfx-io/commit/f31d7b6a5451f94a651507680a67e8cced95e7ee

**Comment by norru** [comment]
Sorry if I didn't reply earlier, I've long moved to a different project.
