### ISSUE TITLE
OSX: undefined symbol on OSX 10.7-10.8, missing libc++ and libc++abi on 10.6

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#431]
see https://discuss.pixls.us/t/error-when-launching-natron/14356/3

**Comment by devernay** [comment]
The missing symbol is present in libc++abi from OSX 10.9 on. Only 10.6-10.8 should be affected.
```
$ nm /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/usr/lib/libc++abi.dylib |fgrep __ZNSt12length_errorD1Ev |c++filt
$ nm /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/lib/libc++abi.dylib |fgrep __ZNSt12length_errorD1Ev |c++filt
$ nm /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libc++abi.dylib |fgrep __ZNSt12length_errorD1Ev |c++filt
0000000000026704 T std::length_error::~length_error()
```

The fix would be to ship our libc++abi/libc++ and prelink it on OSX 10.6-10.8

**Comment by rodlie** [comment]
Sound good to me, but don't "waste" too much time on versions older than 10.9 (IMHO).

**Comment by devernay** [comment]
Sure

**Comment by devernay** [comment]
It should be fixed in the Universal binary from this release: https://github.com/NatronGitHub/Natron/releases/edit/v2.3.15-rc12

**Comment by rodlie** [comment]
Lion (10.7.5):
```
Dyld Error Message:
  Symbol not found: __ZNSt12length_errorD1Ev
  Referenced from: /Users/USER/Desktop/Natron.app/Contents/MacOS/../Frameworks/libshiboken-python2.7.1.2.dylib
  Expected in: /usr/lib/libc++abi.dylib
 in /Users/USER/Desktop/Natron.app/Contents/MacOS/../Frameworks/libshiboken-python2.7.1.2.dylib
```

**Comment by devernay** [comment]
the condition was reversed. I will produce new test binaries soon

**Comment by devernay** [comment]
I will build with OIIO 2.1.9.0+patch

**Comment by devernay** [comment]
I updated the 10.6+ binary, can you please test @rodlie ?
I also upgraded OIIO to 2.1.9 and added HEIF/HEIC support.
HEIF support was also added to IM6/IM7 and OIIO in the Linux SDK.

**Comment by rodlie** [comment]
Works on 10.7.

I will try to update OIIO on Windows, HEIF/HEIC should be possible. Do we need to add more depends in IM? The only IM node that can use HEIF is ReadMisc.

**Comment by devernay** [comment]
The HEIF dependencies are the same for IM and OIIO (x265, libde265 and libheif)

**Comment by rodlie** [comment]
I don't have a mingw reference for oiio 2.1, so I might need to adapt patches etc. Will fix.

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/Natron/commit/0008ebe1a976bcc27310937d8f55ceedef14d84d followed by https://github.com/NatronGitHub/Natron/commit/0008ebe1a976bcc27310937d8f55ceedef14d84d
