### ISSUE TITLE
Transparency not preserved on gif export

### ISSUE THREAD

**Issue by hellocatfood** [NatronGitHub/Natron#433]
### Problem

When exporting to gif any alpha/transparency isn't preserved and is instead rendered as an opaque black background. See attached project. When rendered as png this problem doesn't occur.

[transparent_gif.zip](https://github.com/NatronGitHub/Natron/files/3788261/transparent_gif.zip)

### Versions
Natron version 2.3.15
Ubuntu 19.10

**Comment by rodlie** [comment]
Index colors are probably not supported(?).

**Comment by hellocatfood** [comment]
@rodlie thanks, you're correct that it's not supported. I got a pretty good explanation of why here https://www.facebook.com/groups/NatronNation/permalink/1379281345572763/
