### ISSUE TITLE
2.3.14 ImportError: No module named site

### ISSUE THREAD

**Issue by lolocomotive** [NatronGitHub/Natron#435]
### Problem

Evertime I try to launch, I get a command prompt Opening with following text written:

![Unbenannt](https://user-images.githubusercontent.com/49951010/69424082-04e21600-0d28-11ea-97e0-24524acc1a60.JPG)

And then the command prompt Closes instantly.

**Expected behavior:**

The app should start normally

**Actual behavior:** 

It just doesn't start

### Versions
* **Natron version/commit** Natron-2.3.14-Windows-x86_64bit-no-installer
* **OS version:** Windows 10 Home 64bit x86

**Comment by lolocomotive** [comment]
![Unbenannt](https://user-images.githubusercontent.com/49951010/69477424-8d26f080-0de6-11ea-8287-3a176d5e6af1.JPG)
And now it is doing this

**Comment by rodlie** [comment]
Seems like Natron tries to use an existing Python installation on your computer(?).

**Comment by lolocomotive** [comment]
> Seems like Natron tries to use an existing Python installation on your computer(?).

so what should I do?

**Comment by lolocomotive** [comment]
it is python 3.7 if you are wondering

**Comment by devernay** [comment]
Your python 3.7 installation probably set the PYTHON PATH and/or PYTHONHOME environment variables globally.
See https://docs.python.org/3/using/windows.html#configuring-python
Natron is python  2.7
Try inserting this environment variables and restart Natron.

**Comment by devernay** [comment]
did it fix the issue?

**Comment by devernay** [comment]
closing for now. Please reopen if the issue was not fixed

**Comment by lolocomotive** [comment]
> Try unsetting this environment variables and restart Natron.
Okay, so I did this, and now it shows again `ImportError: No module named site`
![Unbenannt](https://user-images.githubusercontent.com/49951010/81054094-7375f300-8ec6-11ea-8d27-7de336ca047a.PNG)

**Comment by rodlie** [comment]
Could you try https://github.com/NatronGitHub/Natron/releases/download/v2.3.15-rc20/Natron-RB-2.3-202005030031-426db22-Windows-64-no-installer.zip and give us the output from the console.

**Comment by lolocomotive** [comment]
Looks like it was because the path contains A non-ascii character ( ï ) and now it seems to work just fine.
Thanks for the help
