### ISSUE TITLE
Update the instructions to build on Windows

### ISSUE THREAD

**Issue by HackerJLY** [NatronGitHub/Natron#438]
hello, 

i'm reading "Installing with MSYS2" document

https://github.com/NatronGitHub/Natron/blob/RB-2.3/tools/jenkins/README.md

get and install the buildmaster ssh key. It can be obtained from the Natron-support source tree browser after logging in to http://gforge.inria.fr (click on "tree" above the shortlog, then on buildmaster, then on id_rsa_buildmaster.tar.gz.

when i click " source tree browser ", the page said below

Exiting with error
Permission denied. This project's administrator will have to grant you permission to view this page.

how can i get the buildmaster ssh key?

thank you !

**Comment by rodlie** [comment]
Info in https://github.com/NatronGitHub/Natron/blob/RB-2.3/tools/jenkins/README.md is outdated and meant for a (CI) server setup. I will update the Window build info next week.

**Comment by threedslider** [comment]
You will need with [Keychain](https://www.funtoo.org/Keychain) to make your rsa and put into you buildmaster directory.

**Comment by rodlie** [comment]
As said the information is old and incorrect. No keys etc are needed.

**Comment by devernay** [comment]
Hi Ole-André, since you're the only one for now working on the Windows build, would you also update the build instructions? I know it's a lot of work, but that would be great if anyone could be able to build it.
I think it's OK if the build is Windows 10-only, and it may facilitate things on your side. Or there can be an "easy way" to build on Win10, and a much harder way to build for Win 7 or 8.
According to this, Win7 is still on 27% of the windows desktops: https://gs.statcounter.com/windows-version-market-share/desktop/worldwide/ 
But my guess is that these desktops are not being used for compositing.

For reference, same chart for macOS:
https://gs.statcounter.com/macos-version-market-share/desktop/worldwide
Many older Mac Pros, which are still very powerful machines, cannot be upgraded to recent macOS versions because of Apple's plannes obsolescence policy, which is why we're supporting older macOS versions.

**Comment by rodlie** [comment]
I have the next week of so I will make sure the Windows side of things are up-to-date by the end of that week.

I does not matter if we build on 7, 8 or 10. The target will be Vista. I currently have machines with 8.1 (I did a complete working build of Natron in August on one 8.1 machine, I just didn't have the time to finish the packaging). I can upgrade to 10, but I would prefer not to use a moving/rolling OS on build servers.

My biggest problem has been MSYS2, staying on a older snapshot while updating various packages for security issues while staying compatible with existing binaries is a PITA. Even source packages for the exact snapshot I use has build issues.

I did try out MXE for Natron, but cross-compiling introduced more issues that had to be patched and at some point I just gave up. I'm however able to build the plugins use MXE (as long as we use CMake)

One thing I might look at (after I finish MSYS2) is to just use plain MinGW. There we can pick the toolchain and just build whatever on top of that (just use the Linux scripts and add patches we need from MSYS2).


Support for macOS will only be a problem when we move to Qt5, as 5.12+ requires Sierra (10.12).

**Comment by haoxixi** [comment]
> I have the next week of so I will make sure the Windows side of things are up-to-date by the end of that week.
> 
> I does not matter if we build on 7, 8 or 10. The target will be Vista. I currently have machines with 8.1 (I did a complete working build of Natron in August on one 8.1 machine, I just didn't have the time to finish the packaging). I can upgrade to 10, but I would prefer not to use a moving/rolling OS on build servers.
> 
> My biggest problem has been MSYS2, staying on a older snapshot while updating various packages for security issues while staying compatible with existing binaries is a PITA. Even source packages for the exact snapshot I use has build issues.
> 
> I did try out MXE for Natron, but cross-compiling introduced more issues that had to be patched and at some point I just gave up. I'm however able to build the plugins use MXE (as long as we use CMake)
> 
> One thing I might look at (after I finish MSYS2) is to just use plain MinGW. There we can pick the toolchain and just build whatever on top of that (just use the Linux scripts and add patches we need from MSYS2).
> 
> Support for macOS will only be a problem when we move to Qt5, as 5.12+ requires Sierra (10.12).

When will the latest compiled documentation for the window platform come out

> Info in https://github.com/NatronGitHub/Natron/blob/RB-2.3/tools/jenkins/README.md is outdated and meant for a (CI) server setup. I will update the Window build info next week.

When will the latest compiled documentation for the window platform come out？

**Comment by rodlie** [comment]
Documentation will be updated when we are done updating the Windows SDK and build scripts.

**Comment by aditiapratama** [comment]
Hello, 
Is the mingw packages update instruction is the latest? I'm on windows and would like to help to provide binary build.

**Comment by rodlie** [comment]
Closing, instructions for setting up the Windows SDK can be found in https://github.com/NatronGitHub/Natron/tree/RB-2.3/tools/MINGW-packages#install-msys2
