### ISSUE TITLE
Plugin issue in background usage

### ISSUE THREAD

**Issue by rodrigo-brito** [NatronGitHub/Natron#442]
### Problem

I trying to create a custom Docker image for small renders in a server.
I installed the natron in my computer (Ubuntu 18.04 x64) and copy the folder with plugins to Docker with the same linux version.

When a run the render command in a simple example of a sold screen, I receive an erro of non installed plugins.

**Command**
`./naton/bin/NatronRenderer test.ntp`

**Expected behavior:** [What you expected to happen]
Run normally as local machine

**Actual behavior:** [What actually happened]
```
Loading PyPlugs...
Loading project: /home/ubuntu/test.ntp
Error while creating node fr.inria.built-in.Write: The IO.ofx.bundle OpenFX plug-in is required to use this node, make sure it is installed.
[20:45:16.866] Project: ERROR: The node net.fxarena.openfx.Text version 6.9 was found in the script but does not exist in the loaded plug-ins.
[20:45:16.891] Project: ERROR: The node fr.inria.built-in.Write version 1.0 was found in the script but does not exist in the loaded plug-ins.
ERROR: Natron: Project file is missing a writer node. This project cannot render anything.
```

### Versions

* 2.3.13
* Ubuntu 18.04 x64

**Comment by rodlie** [comment]
How did you install Natron? (exact steps if possible)

**Comment by rodrigo-brito** [comment]
Hi @rodlie, I installed in two different ways, both with the same error.
The first on is wget in portable version, unzip and run NatronRenderer.
The second try was a normal installation with Natron Wizard to a local folder, I copied the folder to Docker and run the command inside the container.

The folder plugin has the files:
```
ubuntu@beta:~/natron/Plugins$ du -h
228K	./OFX/Natron/CImg.ofx.bundle/Contents/Resources
2.5M	./OFX/Natron/CImg.ofx.bundle/Contents/Linux-x86-64
2.7M	./OFX/Natron/CImg.ofx.bundle/Contents
4.0K	./OFX/Natron/CImg.ofx.bundle/Libraries
2.7M	./OFX/Natron/CImg.ofx.bundle
144K	./OFX/Natron/IO.ofx.bundle/Contents/Resources
2.4M	./OFX/Natron/IO.ofx.bundle/Contents/Linux-x86-64
2.6M	./OFX/Natron/IO.ofx.bundle/Contents
332K	./OFX/Natron/IO.ofx.bundle/Libraries
2.9M	./OFX/Natron/IO.ofx.bundle
600K	./OFX/Natron/Shadertoy.ofx.bundle/Contents/Resources/presets/default
608K	./OFX/Natron/Shadertoy.ofx.bundle/Contents/Resources/presets
620K	./OFX/Natron/Shadertoy.ofx.bundle/Contents/Resources
32M	./OFX/Natron/Shadertoy.ofx.bundle/Contents/Linux-x86-64
33M	./OFX/Natron/Shadertoy.ofx.bundle/Contents
4.0K	./OFX/Natron/Shadertoy.ofx.bundle/Libraries
33M	./OFX/Natron/Shadertoy.ofx.bundle
56K	./OFX/Natron/GMIC.ofx.bundle/Contents/Resources
6.8M	./OFX/Natron/GMIC.ofx.bundle/Contents/Linux-x86-64
6.9M	./OFX/Natron/GMIC.ofx.bundle/Contents
3.3M	./OFX/Natron/GMIC.ofx.bundle/Libraries
11M	./OFX/Natron/GMIC.ofx.bundle
1.3M	./OFX/Natron/Misc.ofx.bundle/Contents/Resources
14M	./OFX/Natron/Misc.ofx.bundle/Contents/Linux-x86-64
15M	./OFX/Natron/Misc.ofx.bundle/Contents
4.0K	./OFX/Natron/Misc.ofx.bundle/Libraries
15M	./OFX/Natron/Misc.ofx.bundle
256K	./OFX/Natron/Arena.ofx.bundle/Contents/Resources
3.5M	./OFX/Natron/Arena.ofx.bundle/Contents/Linux-x86-64
3.8M	./OFX/Natron/Arena.ofx.bundle/Contents
12M	./OFX/Natron/Arena.ofx.bundle/Libraries
16M	./OFX/Natron/Arena.ofx.bundle
79M	./OFX/Natron
79M	./OFX
412K	./PyPlugs
21M	./PySide
100M	.

```

**Comment by rodlie** [comment]
Is this 2.3.14? If so you will need to apply a hotfix https://discuss.pixls.us/t/natron-2-3-14-linux-hotfix-1/13175 before usage on Linux. Do you get errors on all nodes? Does a basic solid work? The plugins are in the correct folder relative to the NatronRenderer binary? ``../Plugins/OFX/Natron/``

**Comment by rodrigo-brito** [comment]
The binary is in `/natron/bin/NatronRenderer` and the plugins in `/natron/Plugins` parent directory.

**Comment by rodrigo-brito** [comment]
I executed the fix script, but the problem persists.

**Comment by rodlie** [comment]
Check if you are missing depends:
```
cd /natron/Plugins/OFX/Natron
ldd *.ofx.bundle/Contents/Linux-x86-64/*.ofx|grep found
```
You should also run the command without ``|grep found`` and see if some of the plugins link against system libraries.

**Comment by rodrigo-brito** [comment]
The command results in a few missing dependencies.
I installed: `sudo apt-get install libfontconfig1 libxrender1 libice6 libsm6 libxt6 libxrender1 libfontconfig1 libcups2` and the list is empty now.
But the error persists. :cry:

**Comment by rodlie** [comment]
You might need to remove the cache ``rm -rf ~/.cache/INRIA/Natron/``.

Do not install fontconfig, it is included with Natron. The hotfix should fix that issue (you need internet access when running the script). The problem is that some of the symlinks in Arena.ofx.bundle and IO.ofx.bundle are broken. You can review the issue with this command:

```
ls Plugins/OFX/Natron/Arena.ofx.bundle/Libraries
ls Plugins/OFX/Natron/IO.ofx.bundle/Libraries
```
Broken symlinks should be marked in red.

If this is too much work/hazel I would recommend downloading the latest 2.3.15 RC release.

**Comment by rodrigo-brito** [comment]
The symlinks are ok.
It works fine after the cache clean and install missing depends.
Thank you.

**Comment by rodrigo-brito** [comment]
@rodlie I shared the final image in my Github.
Maybe it helps future users with Docker.

https://github.com/rodrigo-brito/natron-docker
