### ISSUE TITLE
Meta-issue: 2.3.15 release blockers

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#445]
Solved/Fixed:

- ~~Installer for 2.3.11 blocked by Windows Defender https://github.com/NatronGitHub/Natron/issues/275 (check if this is still the case with the 2.3.15 installer)~~
- ~~Read EXR image sequence causes Natron to crash during project closure https://github.com/NatronGitHub/Natron/issues/427 (probably fixed thanks to OIIO upgrade)~~
- ~~Project Settings Not stored https://github.com/NatronGitHub/Natron/issues/439 PR #450 applied~~
- ~~Update the instructions to build on Windows https://github.com/NatronGitHub/Natron/issues/438~~
- ~~Binaries build system (Windows not yet available) https://github.com/NatronGitHub/Natron/issues/418~~
- ~~Could not find layer Color in view Right in .exr https://github.com/NatronGitHub/Natron/issues/429~~
- ~~Read node class are different on Windows and Linux https://github.com/NatronGitHub/Natron/issues/415~~
- ~~SDKs: upgrade OpenImageIO to 2.1.10.0 https://github.com/NatronGitHub/Natron/issues/350 (macOS and Lin OK, just update the Win SDK)~~
- ~~SIGSEGV while attempting to write a multi-view EXR with many custom views https://github.com/NatronGitHub/Natron/issues/315~~
- ~~Natron Splash screen ignore window focus?  #303 (check on Win)~~
- ~~Windows UNC Path #302~~
- ~~ColorLookup No work, no normal operation #229 (macOS and Lin OK, check on Win)~~

- ~~Adjusting User-Parameters crashes Natron (on OSX) #232~~
- ~~Error during installation proccess (OpenFX Extra Plugins) #214 (just try out the Win installer)~~
- ~~Rotopaint issue: stroke attributes are lost when changing visibility #205~~
- ~~Animated Font Family doesn't render https://github.com/NatronGitHub/Natron/issues/482~~
- ~~Adding a Retime node causes expressions to cease functioning https://github.com/NatronGitHub/Natron/issues/476~~

Moved to 2.4:

- Rendering silently stalls after X frames #248 (move to 2.4 if nobody submits a sample project) **[Moved to 2.4]**
- DnxHR is not properly formatted https://github.com/NatronGitHub/Natron/issues/329 (may have to wait for the WriteFFmpeg rewrite) **[Moved to 2.4]**
- Remember Minimize state when reopening project #168 (may be fixed already) **[Moved to 2.4]**

**Comment by rodlie** [comment]
Thanks for organizing the issues. I will finish build related issues for Windows first, then go through the rest and see what is or can be fixed for 2.3.15.

**Comment by devernay** [comment]
@rodlie do you have some time to go over the "to be checked" or "check on windows" issues in this list and close those that are fixed?
We should be able to release 2.3.15

**Comment by rodlie** [comment]
Sure, I'm free all day and tomorrow.

**Comment by devernay** [comment]
@rodlie the two remaining issues concern openfx-arena, can you check if there's an easy fix?

**Comment by rodlie** [comment]
Will finish https://github.com/NatronGitHub/Natron/issues/476 (I think I forgot to fix one of the plugins), it's getting late here (02:30), but I will try to fix it before I fall a sleep :)

A bit unsure about https://github.com/NatronGitHub/Natron/issues/482 yet (see last comment).

**Comment by devernay** [comment]
OK, let's try to tag the release on Sunday.
I never tested the updated build scripts on releases, so there may be a few hiccups.

**Comment by rodlie** [comment]
That sounds good. I have all weekend free for Natron if needed.

**Comment by devernay** [comment]
I just need to update the Natron doc before tagging the release.

**Comment by rodlie** [comment]
ok.

**Comment by rodlie** [comment]
I think https://github.com/NatronGitHub/Natron/blob/RB-2.3/tools/jenkins/build-natron.sh#L69
should be ``sed 's#tags/v##;' | cut -c1-3``

**Comment by devernay** [comment]
yes, fixed!

**Comment by rodlie** [comment]
Just finished a test (release) build on Windows, looks good. Splashscreen is ok, about section ok, terminal output ok, setup and installation ok.
