### ISSUE TITLE
Hang when an expression gets Tracker values

### ISSUE THREAD

**Issue by Vhati** [NatronGitHub/Natron#448]
New user here. I may be going about this the wrong way...

I'm trying to animate an effect's position by using an expression to copy a tracker's coordinates into another node's XY parameters. PROBLEM: Merely referencing tracker data hang's the UI. I was going to move a Lightning node's root around, but I can't get that far.

### Steps to Reproduce

* Read a video (short duration & low res in my case).
* Seek to a frame where something in-video moves into view.
* Add a Tracker node.
* Add a track. Place it on that moving thing.
* trackFW to get an animation trail.
* Add a Text node (for example).
* Set an expression for its Text parameter (wrapping in str()):

````
    str(int(Tracker1.tracker.track1.centerPoint.getValueAtTime(frame, 0)))
````

* The expression editor will preview a legitimate X position.
* Click OK. Natron will stop responding, become incredibly resource hungry and slow the whole OS almost to a standstill.

Before attempting to reproduce, have a command prompt ready with this pre-typed, to run when it hangs. Or click Natron's "X" and let the OS offer to forcefully terminate.

````
taskkill /F /IM "Natron.exe" /T
````

### Version

Official Natron 2.3.14 on Win 7

**Comment by devernay** [comment]
I fixed the code so that it runs with this expression, but the code is very fragile and buggy.

quick fix (and better alternative): use `getValue(0)` - on time-varying parameters, this is equivalent to `getValueAtTime(frame,0)`.

**Comment by Vhati** [comment]
Thank you.
