### ISSUE TITLE
Delete Rotopaint node makes Natron crash

### ISSUE THREAD

**Issue by ebarranco** [NatronGitHub/Natron#454]
### Problem
Delete Rotopaint node makes Natron crash.

### Steps to Reproduce

1. Add an image
2. Use Rotopaint (Do more than one stroke)
3. Select the node and delete it with Ctrl + x
4. Natron Crash.

**[I show you here.](https://youtu.be/wYjndNfOOUo)**

### Versions

* **Natron version/commit** 
Natron 2.3.15 RC15

* **OS version:** 
Linux

**Comment by rodlie** [comment]
Hi,

I'm not able to replicate. Could you run Natron from a terminal? Might give us some hints.

**Comment by ebarranco** [comment]
Hi @rodlie, I didn't clarify that I'm using Natron-RB-2.3-202001211722-2bf9f84-Linux-64-no-installer.tar.xz.
Here is the info from terminal:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Resource id in failed request:  0x24000a1
  Serial number of failed request:  110567
  Current serial number in output stream:  110567
```

**Comment by rodlie** [comment]
Thanks for the info, this is related to #247

* Linux distro and version?
* What kind of graphics card do you have?
* Are you using graphics drivers from the system (mesa+kernel)?
* Are you using graphics drivers from NVIDIA/AMD?
* Can you replicate the issue in #247? Just try dragging the properties dock or something.

**Comment by ebarranco** [comment]
My distro is Manjaro Linux KDE kernel Linux 5.4.10 rt
Graphics Card NVIDIA GeForce GTX 1050Ti
I use proprietary drivers video-nvidia-440xx
Yes, I have crashes moving the tabs.

**Comment by rodlie** [comment]
Thanks for the additional info.

This is a tricky issue, as I can only replicate (#247) on some systems (with Intel graphics). And I can't debug crashes like this.

Could be related to Qt4.

**Comment by ebarranco** [comment]
This is my terminal from the crash moving **only the curve editor tab**. All the other tabs move just fine.

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  7908
  Current serial number in output stream:  7909

```

**Comment by rodlie** [comment]
That error seems to be related to the driver.

https://askubuntu.com/questions/893922/ubuntu-16-04-gives-x-error-of-failed-request-badvalue-integer-parameter-out-o

**Comment by rodlie** [comment]
I tested on the only computer I have with Linux and NVIDIA. CentOS 7 with GTX 660 using 430.26 drivers from NVIDIA. No problems with X11.

On my laptop (Intel HD Graphics 3000) with Slackware 14.2 I can replicate #247, but on another laptop running the same graphics card and distro, but with a custom kernel (and mesa stack) I don't get the issue.

I believe most of these issues can be traced back to the graphics driver (stack).

**Comment by ebarranco** [comment]
I followed the steps even I don't have the same behavior from this post. The crash for Rotopaint it's gone but the crash from moving the curve editor tab is still there. I'm closing this and leaving a comment in that issue.

**Comment by cosoc** [comment]
如何处理，我的也是英伟达显卡。启动就关闭。
Natron-RB-2.3-202103050208-636eefe-Linux-64-no-installer

debian10

```shell
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x0
  Serial number of failed request:  5533
  Current serial number in output stream:  5533
```

**Comment by devernay** [comment]
@cosoc does it crash on startup? Did you try with the ubuntu20 binary too?

**Comment by cosoc** [comment]
> @cosoc does it crash on startup? Did you try with the ubuntu20 binary too?

yes! Unable to run, flash back
