### ISSUE TITLE
Has this project stagnated? 

### ISSUE THREAD

**Issue by JonTAllen** [NatronGitHub/Natron#458]
Has the development of this project stagnated/ceased development updates? I noticed the last updates to this software happened over two years ago.

I do not have software development skills, but would like to use the software and provide feedback. If there are no more updates being made, then any feedback I do have would seem to be moot.

**Comment by JonTAllen** [comment]
I reopened this issue because of the phrase "maintainer needed" on the website.

**Comment by devernay** [comment]
If you're running 2.3.14, apply the hotfix, or use 2.3.15rc

**Comment by devernay** [comment]
We are preparing the next release (2.3.15), which has a bunch of dudes and updates, and yes, we are still looking for a more sustainable way to maintain this software

**Comment by JonTAllen** [comment]
Okay, good. Glad to know it hasn't been abandoned.

**Comment by JonTAllen** [comment]
I closed this issue because I now know the software is not abandoned.
