### ISSUE TITLE
How do I install Natron on Debian Linux?

### ISSUE THREAD

**Issue by JonTAllen** [NatronGitHub/Natron#461]
I was told to install the hot fix. I checked the Wiki and there is no documentation there to show how to do this. I am running a heavily debian-based OS (Pure OS) and have no idea how to install Natron with the hot fix. 

I am using debian 10 "buster" variant.

**Comment by rodlie** [comment]
* GCC fix: https://discuss.pixls.us/t/natron-opengl-errors/16401/4?u=rodlie
 * Hotfix: https://discuss.pixls.us/t/natron-2-3-14-linux-hotfix-1/13175
