### ISSUE TITLE
Natron does not start / crash

### ISSUE THREAD

**Issue by michas0602** [NatronGitHub/Natron#462]
Natron crashes immediately.

### Steps to Reproduce

Start Natron.

### Versions

* **Natron 2.3.14**
* **OS version: Ubuntu Mate 20.04 daily** 
fresh install

Hardware: Nvidia GTX 660ti (Nvidia-driver 440)

Errormessage:

> couldn't open library /home/m/Natron2/Plugins/OFX/Natron/Arena.ofx.bundle/Contents/Linux-x86-64/Arena.ofx because /lib/x86_64-linux-gnu/libcairo.so.2: undefined symbol: FT_Done_MM_Var
Caught segmentation fault (SIGSEGV) from thread Main(0x340da10), faulty address is 0x366a0 from 0x366a0

**Comment by rodlie** [comment]
Hotfix: https://discuss.pixls.us/t/natron-2-3-14-linux-hotfix-1/13175

I recommend using the 2.3.15 RC's.

**Comment by randunel** [comment]
Getting a `502 Bad Gateway` when trying to access the hotfix.

Having the same issue as OP:

```
Natron Version 2.3.14
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
couldn't open library /home/mihai/Natron2/Plugins/OFX/Natron/Arena.ofx.bundle/Contents/Linux-x86-64/Arena.ofx because /lib/x86_64-linux-gnu/libcairo.so.2: undefined symbol: FT_Done_MM_Var
Caught segmentation fault (SIGSEGV) from thread Main(0x2d27a10), faulty address is 0x366a0 from 0x366a0
Backtrace:
```

```
uname -a
Linux work-15 5.4.0-14-generic #17-Ubuntu SMP Thu Feb 6 22:47:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Focal Fossa (development branch)
Release:	20.04
Codename:	focal
```

**Comment by rodlie** [comment]
The hotfix works fine here

```
wget https://github.com/NatronGitHub/Natron/releases/download/v2.3.14/Natron-2.3.14-Linux-hotfix.sh
chmod +x Natron-2.3.14-Linux-hotfix.sh
./Natron-2.3.14-Linux-hotfix.sh <NATRON_INSTALLATION_FOLDER>
```

**Comment by palbergstrom** [comment]
Same problem. New Ubuntu 20.04. Tried the hotfix but the problem persist (worked in 19.10).

How do I install and try 2.3.15 RC?

**Comment by rodlie** [comment]
2.3.15 RC's are available here on GitHub.
