### ISSUE TITLE
Shadertoy inputs broken on Win10 Natron 2.3.15RC15

### ISSUE THREAD

**Issue by bonalex01dev** [NatronGitHub/Natron#464]
### Problem
Shadertoy nodes inputs not working
When opening the panel the viewer display a red message:
"Bad image format was supplied by natron"
I tried to reformat image to 256x256 (power of 2) but it didn't help

**Expected behavior:**
Image modified by the Shadertoy node

**Actual behavior:**
All Shadertoy nodes with inputs result in black image

### Steps to Reproduce
Any Shadertoy with at least 1input connected.

The default shadertoy (with smooth colored checkerboard) works OK when NOT connected to any input. The tools in GLSL/Sources/CROK_lava also work well too

### Versions
Natron 2.3.15RC15 Win 10
It works OK in Natron 2.3.14 (same machine, same install of the shadertoy plugins )

**Comment by devernay** [comment]
Can you please give the 4 first lines of information you get from clicking "Renderer info..." in ShaderToy?
Also, what info do you get in the Natron preferences when selecting "GPU Rendering" from the list?

I'm able to reproduce that by switching ShaderToy or Natron to CPU rendering.

**Comment by devernay** [comment]
It only happens with a ShaderToy compiled in "release" mode.
I tried with a debug Natron and with a debug ColorWheel node:
- when using a debug ShaderToy, it works fine
- when using a release ShaderToy, either from the Natron RC builds or compiled locally in release mode, I get the error

**Comment by devernay** [comment]
It's fixed, thanks for reporting! Now you'll have to wait for the next Windows build.
@rodlie any idea when?

**Comment by rodlie** [comment]
I will start a build within two hours.

Btw, I got extra free time next week to work on Natron related things (as Norway is on lockdown for two weeks from today).

**Comment by rodlie** [comment]
I get a failed regular unit test on Windows:
```
[----------] Global test environment tear-down
[==========] 23 tests from 11 test cases ran. (453 ms total)
[  PASSED  ] 22 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ModelSearch.HomographyMinimal

 1 FAILED TEST

[==========] Running 23 tests from 11 test cases.
[----------] Global test environment set-up.
[----------] 6 tests from ModelSearch
[ RUN      ] ModelSearch.TranslationMinimal
[       OK ] ModelSearch.TranslationMinimal (0 ms)
[ RUN      ] ModelSearch.TranslationNPoints
[       OK ] ModelSearch.TranslationNPoints (0 ms)
[ RUN      ] ModelSearch.SimilarityMinimal
[       OK ] ModelSearch.SimilarityMinimal (0 ms)
[ RUN      ] ModelSearch.SimilarityNPoints
[       OK ] ModelSearch.SimilarityNPoints (0 ms)
[ RUN      ] ModelSearch.HomographyMinimal
Tracker_Test.cpp:439: Failure
Value of: (int)x1.size() - nbOutliers
  Actual: 3
Expected: nbInliers
Which is: 4
Tracker_Test.cpp:444: Failure
The difference between H(i, j) and foundModel(i, j) is 0.037510856786045821, which exceeds 1e-5, where
H(i, j) evaluates to 1,
foundModel(i, j) evaluates to 1.0375108567860458, and
1e-5 evaluates to 1.0000000000000001e-005.
Tracker_Test.cpp:444: Failure
The difference between H(i, j) and foundModel(i, j) is 0.005591432993693345, which exceeds 1e-5, where
H(i, j) evaluates to 0,
foundModel(i, j) evaluates to 0.005591432993693345, and
1e-5 evaluates to 1.0000000000000001e-005.
Tracker_Test.cpp:444: Failure
The difference between H(i, j) and foundModel(i, j) is 2.19872766633776, which exceeds 1e-5, where
H(i, j) evaluates to -4,
foundModel(i, j) evaluates to -6.19872766633776, and
1e-5 evaluates to 1.0000000000000001e-005.
Tracker_Test.cpp:444: Failure
The difference between H(i, j) and foundModel(i, j) is 0.050921463334771641, which exceeds 1e-5, where
H(i, j) evaluates to 0,
foundModel(i, j) evaluates to 0.050921463334771641, and
1e-5 evaluates to 1.0000000000000001e-005.
Tracker_Test.cpp:444: Failure
The difference between H(i, j) and foundModel(i, j) is 0.041487365744602434, which exceeds 1e-5, where
H(i, j) evaluates to 1,
foundModel(i, j) evaluates to 1.0414873657446024, and
1e-5 evaluates to 1.0000000000000001e-005.
Tracker_Test.cpp:444: Failure
The difference between H(i, j) and foundModel(i, j) is 12.744042906776542, which exceeds 1e-5, where
H(i, j) evaluates to 5,
foundModel(i, j) evaluates to -7.7440429067765422, and
1e-5 evaluates to 1.0000000000000001e-005.
Tracker_Test.cpp:444: Failure
The difference between H(i, j) and foundModel(i, j) is 0.00015883528030135051, which exceeds 1e-5, where
H(i, j) evaluates to 0,
foundModel(i, j) evaluates to 0.00015883528030135051, and
1e-5 evaluates to 1.0000000000000001e-005.
Tracker_Test.cpp:444: Failure
The difference between H(i, j) and foundModel(i, j) is 3.310857708437817e-005, which exceeds 1e-5, where
H(i, j) evaluates to 0,
foundModel(i, j) evaluates to 3.310857708437817e-005, and
1e-5 evaluates to 1.0000000000000001e-005.
Tracker_Test.cpp:444: Failure
The difference between H(i, j) and foundModel(i, j) is 0.0098554397705441499, which exceeds 1e-5, where
H(i, j) evaluates to 1,
foundModel(i, j) evaluates to 0.99014456022945585, and
1e-5 evaluates to 1.0000000000000001e-005.
[  FAILED  ] ModelSearch.HomographyMinimal (1 ms)
```

**Comment by devernay** [comment]
This test failure has been on Windows for ages, if not forever

**Comment by rodlie** [comment]
Ok, I didn't notice that error in RC15, that's why I reacted now. Anyway, Windows binaries are now available.

**Comment by bonalex01dev** [comment]
Hi,

here are my results following your questions

Tests done with CROK_Emboss (from community plugins).
I have done "Expand group" to get access to the nested Shadertoy inside
When node properties opened, red bar "Bad Image format was supplied by
Natron. is displayed

Renderer info...
(i) OpenGL renderer info not yet available.
Please execute at least one image render and try again.

Disable GPU Render (controls tab)
same result
GPU rendering (node tab)
same result
OpenGL Rendering Disable (preferences)
same result
OpenGL Rendering Enable (preferences)
same result

OpenGLRenderer Infos:
NVIDIA Geforce RTX2070 with Max-Q/PCIe/SSE2
OPengl:4.6.0 Nvidia 441.45
GLSL Version: 4.60 NVIDIA
Max Memory: Unknown
Max. Texture Size (px) 32768
No of ogl contexts 2
Opengl rendering: (tested with enabled/disabled)


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by bonalex01dev** [comment]
In Natron 2.3.14, the image is processed normally and Renderer info gives:
---------------------------
Shadertoy1_2
---------------------------
<p>OpenGL renderer information:<br>
GL_RENDERER = GeForce RTX 2070 with Max-Q Design/PCIe/SSE2<br>
GL_VERSION = 4.6.0 NVIDIA 441.45 (4.6)<br>
GL_VENDOR = NVIDIA Corporation<br>
GL_SHADING_LANGUAGE_VERSION = 4.60 NVIDIA<br>
GL_EXTENSIONS = GL_AMD_multi_draw_indirect
GL_AMD_seamless_cubemap_per_texture GL_AMD_vertex_shader_viewport_index
GL_AMD_vertex_shader_layer GL_ARB_arrays_of_arrays GL_ARB_base_instance
GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage
GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control
GL_ARB_color_buffer_float GL_ARB_compatibility
GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth
GL_ARB_compute_shader GL_ARB_compute_variable_group_size
GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image
GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float
GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control
GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend G
---------------------------
OK
---------------------------

when i disable GPU Render In Natron 2.3.14, the image is processed normally
and Renderer info gives:
---------------------------
Shadertoy1_2
---------------------------
<p>OpenGL renderer information:<br>
GL_RENDERER = Gallium 0.4 on softpipe<br>
GL_VERSION = 3.0 Mesa 17.1.10 (git-164a5858c8) (3.0)<br>
GL_VENDOR = VMware, Inc.<br>
GL_SHADING_LANGUAGE_VERSION = 1.30<br>
GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra
GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract
GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture
GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array
GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip
GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels
GL_EXT_point_parameters GL_EXT_rescale_normal
GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp
GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp
GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB
GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays
GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map
GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_
---------------------------
OK
---------------------------

Thanks for investigating the case

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
