### ISSUE TITLE
Contributing to the documentation

### ISSUE THREAD

**Issue by bonalex01dev** [NatronGitHub/Natron#465]
#450 # Problem
Hi, I'd like to contribute to the docs of Natron with no luck

Describe the problem or suggestion here.
I try to follow
https://natron.readthedocs.io/en/rb-2.3/guide/tutorials-writedoc.html
but I can't get github app to clone my fork on my local disk
and i don't KNOW how to create a branch. I'm very new to github (and project development too) Do I need an authorisation?

**Expected behavior:** [What you expected to happen]
clone the repo on my local disk then allow me to add doc files

**Actual behavior:** [What actually happened]
github app spitout an error
invalid path 'tools/MacPorts/graphics/openimageio/Portfile'
fatal: unable to checkout working tree

I noticed this happen to be the last file edited by Frederic yestaerday

### Steps to Reproduce

1. fork Natron from github webpage  
2. try to clone in github desktop app

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions

NatronGithub/Natron/RB-2.3

**Comment by devernay** [comment]
There are now easier options: You can also do that on the web without having to clone/edit the files on your computer.

Solution 1: create your branch
- go to https://github.com/bonalex01dev/Natron
- click the button "Branch: RB-2.3" on the left
- type in a new branch name, eg bonalex01dev-docupdate
- now go to the documentation, eg https://github.com/bonalex01dev/Natron/tree/bonalex01dev-docupdate/Documentation/source
- click on the file you want to edit
- edit it ("pencil" button on the right).
- BE CAREFUL, if the top of the file says in a comment "Do not edit this file", follow this advice.
- make a pull request (PR)

Solution 2: let github create a branch and fork for you:
- go to https://github.com/NatronGitHub/Natron/tree/RB-2.3/Documentation/source
- click the file you want to edit
- edit it ("pencil" button on the right).
- github will create a fork and branch for you
- BE CAREFUL, if the top of the file says in a comment "Do not edit this file", follow this advice.
- make a pull request (PR)

Solution 3:
- browse the doc at https://natron.readthedocs.io
- on any page, click "Edit on github" on the topleft (this can also be used to just view the source and see what it looks like)
- edit it ("pencil" button on the right).
- github will create a fork and branch for you
- BE CAREFUL, if the top of the file says in a comment "Do not edit this file", follow this advice.
- make a pull request (PR)

Let me know which one works best for you, and feel free to update https://github.com/NatronGitHub/Natron/blob/RB-2.3/Documentation/source/guide/tutorials-writedoc.rst with what works for you!

**Comment by bonalex01dev** [comment]
Thanks.

**Comment by bonalex01dev** [comment]
Hello,
It seems I succeeded to pull request my changes.
But you may help me for a more reliable workflow... cloning my fork and branches on my computer.

Git desktop sends me an error:
"error:invalid path 'tools/MacPorts/graphics/openimageio/Portfile'
And copying to my local disk fails.

As I noticed you recently worked on that part I hope there may be an easy fix on this.

( I'm a french CG guy sorry for my english)

**Comment by rodlie** [comment]
Closing issue. You where able to do a pull request and your changes was merged (thanks btw).
