### ISSUE TITLE
runtime error of Natron.exe (Mingw64 build)

### ISSUE THREAD

**Issue by 3togo** [NatronGitHub/Natron#466]
$ ./Natron.exe
Natron Version 2.3.15
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
Fontconfig configuration file C:/msys64-20180531/opt/natron-build/source/Natron/App/release/../Resources/etc/fonts does not exist, not setting FONTCONFIG_PATH
Error while loading python module NatronEngine: While executing script:
import sys
from math import *
import NatronEnginePython error:
Python exception: No module named math
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named math

**Comment by 3togo** [comment]
export PYTHONHOME as below will fix the problem

export PYTHONHOME=/mngw64 
./Natron.exe

**Comment by devernay** [comment]
Reopening this, as I need a bit more feedback:
Was PYTHONHOME or PYTHONPATH set in your environment? (type "env" in your shell)
If yes, can you unset both and try to launch Natron?

**Comment by rodlie** [comment]
PYTHONHOME/PYTHONPATH is not set in MSYS2.

**Comment by devernay** [comment]
@rodlie what do you mean?
a- They are not set in the default MSYS2 environment. [I hope so]
b- They are not set by default when installing a Python distrib on Windows, even conda or pythonxy
c- Whatever these variables are set to, Natron overrides them and uses the correct value in any case

**Comment by rodlie** [comment]
I mean that if you build Natron in MSYS2 and want to run it from the build folder as-is then you need to set PYTHONHOME=/mingw64.

**Comment by devernay** [comment]
Is this expected? Shouldn't Natron set PYTHONHOME to this value if the math module is not available?

**Comment by rodlie** [comment]
It has always been this way, but setting PYTHONHOME if modules are not found would be nice.

**Comment by Echolon** [comment]
Hi @3togo 

do you have further feedback on this?
