### ISSUE TITLE
Open Sequence Dialog Shows No Files on Ubuntu 19.10

### ISSUE THREAD

**Issue by richard-pepe** [NatronGitHub/Natron#471]
The Open Sequence Dialog doesn't show any files on Ubuntu 19.10

![image](https://user-images.githubusercontent.com/38479519/77218971-63f54300-6aee-11ea-8af1-9740d789efe7.png)

Neither selecting the 'show hidden files' option nor updating the filter resolve the issue. Dragging and dropping videos doesn't work either.

* **Natron version/commit** 2.3.14
* **OS version:** Ubuntu 19.10

![image](https://user-images.githubusercontent.com/38479519/77219015-cc442480-6aee-11ea-8815-157f22326265.png)

**Comment by rodlie** [comment]
You are using a containerised version of Natron, either snap or flatpack. You will need to give the app access to your home folder (IMHO this should be done by the person that made the package).

Where did you get Natron from?

**Comment by richard-pepe** [comment]
Snap. I tried the hotfix but it was complaining about symlink permissions, even under sudo.

**Comment by rodlie** [comment]
The hotfix is for official Linux binaries downloaded from Github or SourceForge. The snap package is not maintained by Natron.

http://www.linuxandubuntu.com/home/snap-application-permissions
