### ISSUE TITLE
Error at the launch

### ISSUE THREAD

**Issue by Tenshi-shan** [NatronGitHub/Natron#472]
Hello,

When I'm launching the app with ./Natron, I have these outputs :

Natron Version 2.3.14
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
Error while loading OpenGL: GLX: Failed to create context
OpenGL rendering is disabled. 
GLX: Failed to create context
GLX: Failed to create context
Caught segmentation fault (SIGSEGV) from thread Main(0x2124a10), faulty address is 0x7f936be26564 from 0xc8
Erreur de segmentation (core dumped)

I download the app on the website and all his components and I'm running on Ubuntu 19.10.

**Comment by rodlie** [comment]
GCC fix: https://discuss.pixls.us/t/natron-opengl-errors/16401/4?u=rodlie

**Comment by devernay** [comment]
Is that issue fixed in the latest RCs?

**Comment by Tenshi-shan** [comment]
Sorry to annoy you.
All was fixed thanks to the link, thank you very much and keep it up.

**Comment by rodlie** [comment]
@devernay this issue can (only) be fixed by using DTS in CentOS. We should consider moving to CentOS 7 + DTS (8 or 9).

**Comment by devernay** [comment]
DTS 8 is also available on CentOS 6, and making a SDK docker image with centos 6 or 7 with DTS 8 is easy (I already did it), but my concern is about the runtime system: what distributions will be supported by the resulting binaries.

**Comment by devernay** [comment]
And anyway we should probably release 2.3.15 first

**Comment by rodlie** [comment]
If DTS8 is available for CentOS 6, then we use that.

A DTS build of Natron will require the system default gcc, so for CentOS 6 it's gcc 4.4. We used DTS in Natron 1.x and early v2 previews.

Of course after 2.3.15.

**Comment by devernay** [comment]
I doubt the system's default libstdc++ will work, because DTS8 supports C++11, and gcc 4.4 doesn't

**Comment by rodlie** [comment]
This is the point of DTS, we use a modern compiler (GCC 8) but only require GCC 4.4(or better) on the user system.

We have used it in the past, and I use it on many projects, it works.

**Comment by devernay** [comment]
but how could it possibly support C++11 (we need it for some dependencies) without a libstdc++ that supports C++11?
Maybe what you're saying is OK for C++98 only?

**Comment by rodlie** [comment]
DTS is more than "just" a toolchain, they include whatever is needed beyond GCC 4.4 since binaries built with DTS must be ABI compatible with CentOS 6 vanilla, but also need to support anything in the DTS compiler (GCC 8).

**Comment by devernay** [comment]
So the trick is that they link everything that is not in the system's libstdc++ statically using libstdc++_nonshared.a
I'l try to make a dts8-based image

**Comment by rodlie** [comment]
Something like that, yes. They may do other tricks as-well.

I did a test of DTS on Natron several month ago, I built the SDK and a Natron snapshot using DTS, everything worked perfectly (I used vbox).
