### ISSUE TITLE
Linux binaries: use CentOS6+devtoolset-8

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#474]
Linux binaries should be built using devtoolset-8 instead of our own toolset.
Test binaries are available in the following release: https://github.com/NatronGitHub/Natron/releases/tag/v2.3.15-rc18
@rodlie can you please test these?

**Comment by rodlie** [comment]
Great :)

I will test on various distros (and gfx card combos) tomorrow (it's 04:00 at night).

**Comment by devernay** [comment]
@rodlie can you test the newest Linux binaries?

**Comment by rodlie** [comment]
They work as expected here (NVIDIA/Intel). I still need to test a Radeon card, will switch card on my workstation as soon as possible.

Btw, I'm currently looking into the GMIC issue on Windows.

**Comment by devernay** [comment]
The G'MIC issue is on all platforms with gmic 2.9.0. I think the file format changed slightly and the parser does not recognize plugins in the gmic config file.

**Comment by devernay** [comment]
@rodlie Do the binaries work on Linux with Radeon drivers? I'm ready to do the switch to DTS8, I just need confirmation.

**Comment by rodlie** [comment]
The cards I have tested yes, but I don't have access to (modern) cards that uses the latest AMD drivers.

@Tenshi-shan: Could you test on your setup?

**Comment by Tenshi-shan** [comment]
Hello!
It seems to work with AMD Ryzen 5 and NVidia.
Sorry, I don't have an AMD video card.

**Comment by devernay** [comment]
OK great!
