### ISSUE TITLE
Fill node doesn't cover full image

### ISSUE THREAD

**Issue by bonalex01dev** [NatronGitHub/Natron#475]
Problem:
Fill node don't cover the whole image if input is node same format as project format

Cause:
Inside the "Filter/Fill" group the Solid node has no input so it does'nt follow the input format.

Solution
To solve the bug it's sufficient to  plug the Solid1 input in the source

**Comment by bonalex01dev** [comment]
I wonder if an update of a group or other pyplugs will be updated once the bug is fixed or if the Fill group is "hardcoded" in those ?

**Comment by devernay** [comment]
to do the fix:
- edit the PyPlug in Natron
- re-export the pyplug
- compare the exported Fill.py with the one in the Natron sources https://github.com/NatronGitHub/Natron/blob/RB-2.3/Gui/Resources/PyPlugs/Fill.py

https://github.com/NatronGitHub/Natron/commit/31210f8ec8d9226480e7d687fbc70a15286edd7b#diff-1ea566408f5327b1d26f6780b890d8b5

**Comment by devernay** [comment]
Quick fix: note that you can also edit the file Fill.py in your current Natron install and add the missing line.

**Comment by devernay** [comment]
> I wonder if an update of a group or other pyplugs will be updated once the bug is fixed or if the Fill group is "hardcoded" in those ?

I don't know. Can you check?
