### ISSUE TITLE
Project saving is tricki because i need to put project name inside file path edit box. 

### ISSUE THREAD

**Issue by 111ukasz111** [NatronGitHub/Natron#477]
### Problem
There is no way to save natron project with own project name. Save button in save as doesn't work.
Ok, it is not a bug but it is very tricki. I know i need to put project name inside file path edit box.
**Expected behavior:** [What you expected to happen]
Save button in save as should work.
**Actual behavior:** [What actually happened]
If I'm trying to save project using 'save as' 'save' button does not work.

### Steps to Reproduce

1. [First Step]
Press 'Save project as'
2. [Second Step]
Write your project name.
3. [and so on...]
And press save.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
Natron 2.3.14
* **OS version:** 
Windows 10 nvidia Geforce 920M intel core i7

**Comment by rodlie** [comment]
you are probably missing the full path to the filename? can you show us a screenshot of the save dialog issue?

**Comment by 111ukasz111** [comment]
![Adnotacja 2020-04-17 164513](https://user-images.githubusercontent.com/20667528/79581676-14913b00-80cb-11ea-8a19-d79fe6c3d261.png)
It is a bug.

**Comment by 111ukasz111** [comment]
Ok, it is not a bug but it is very tricki. I know i need to put project name inside file path edit box.
