### ISSUE TITLE
PyGuiApplication.questionDialog documented, but not actually defined

### ISSUE THREAD

**Issue by philomory** [NatronGitHub/Natron#485]
### Problem

**Expected behavior:** 
`NatronGui.natron.questionDialog('foo','bar')` produces a modal dialog with 'yes' and 'no' buttons [as described in the documentation](https://natron.readthedocs.io/en/rb-2.3/devel/PythonReference/NatronGui/PyGuiApplication.html#NatronGui.NatronGui.PyGuiApplication.questionDialog).

**Actual behavior:** 
```
While executing script:
NatronGui.natron.questionDialog('foo','bar')
Python error:
Python exception: 'NatronGui.PyGuiApplication' object has no attribute 'questionDialog'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NatronGui.PyGuiApplication' object has no attribute 'questionDialog'
```

### Steps to Reproduce

1. Attempt to call `NatronGui.natron.questionDialog`
2. Double-check `print(dir(NatronGui.natron))`

### Versions

* **Natron version/commit:** 2.3.15 Snapshot (RC17)
* **OS version:** Windows 10

**Comment by devernay** [comment]
this is a confirmed issue. for an unknown reason, shiboken does not generate the wrapper for this function (and maybe others too)

**Comment by devernay** [comment]
Fixed. I'll make a new linux build later today with these fixes

**Comment by devernay** [comment]
https://github.com/NatronGitHub/Natron/releases/tag/v2.3.15-rc20 should fix this bug

**Comment by rodlie** [comment]
Windows build already uploaded.

**Comment by devernay** [comment]
that was fast! thanks
