### ISSUE TITLE
Render: RAM usage keeps increasing until using all system RAM

### ISSUE THREAD

**Issue by jiftw** [NatronGitHub/Natron#486]
During a render, RAM usage keeps gradually increasing until using all available RAM (after a few thousand rendered frames), which results in non-stop hard disk use and basically freezes the system.
The "system RAM to keep free" under Caching preferences has no effect.

Currently, to work around this bug, I have to render a segment of frames, then close Natron (sometimes I have to kill it, but that may be an unrelated bug), re-open Natron to render a few more thousand frames, repeat...

**Expected behavior:** [What you expected to happen]
I don't see why RAM would remain used after frames have been rendered. I'd expect it to correspond to the number of simultaneous frames currently being rendered (ie 4 in my system). Once files have been written to disk I expect RAM to be cleared except for static objects, and to go up again for the next [num_threads] frames, etc.

### Steps to Reproduce

1. Open a project containing 17500+ frames (for my system specs)
2. Render
3. Watch RAM usage slowly increasing.
4. Eventually it uses all system RAM.

### Versions

Natron version 2.3.14 Release (as Flatpak)
LinuxMint 19.3 (tricia)
4.15.0-66-lowlatency (#75-Ubuntu SMP PREEMPT Tue Oct 1 06:11:04 UTC 2019)
Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
RAM: 15918 MiB
Swap: 16068 MiB
GeForce GTX 1050

Thanks for creating Natron !

**Comment by devernay** [comment]
hi,
ram usage also highly depends on the graph itself, and the project resolution.
- reduce the number of threads (I suppose your processor is dual core, so 2 should be fine). more threads use more ram
- read https://natron.readthedocs.io/en/rb-2.3/guide/getstarted-troubleshooting.html#common-workarounds
- try the 2.3.15 rc, bugs may be fixed

**Comment by jiftw** [comment]
Thank you, I had already consulted common-workarounds and was using image sequences, (otherwise it would give 1 frame of backwards motion every second). Processor is quad-core without hyperthreading. Natron detected the number of threads to use properly (4). I'd rather not set it lower than that, as render time is quite long as it is; and it would remain faster for me to render in sub-batches despite the interruption to close/kill and restart Natron and readjust project frame range.

Testing with the 2020-05-03 build:
After starting render, RAM usage is around 800 mb. It fluctuates more and now has periods where it lowers. After 3000 frames, it is around 1.9 gb. It still progressively increases, but much more slowly than with 2.3.14. After approx 15000 frames it got to 7.3 gb. Render was complete. I tried clearing caches - it increased RAM use to 7.5 gb.

It appears to me that a memory leak is still present, but much lower in amplitude.

Thanks !

======
Prevous notes testing with 2.3.14:
After starting a render Natron is using less than 800 mb of RAM so I would think the project isn't too complex. It just increases with each rendered frame (after 3000 frames it got to about 4 gb). It will eat all my 16 gb after some time. If I stop the render, and clear all caches, the memory usage remains. Hence why I must restart Natron before resuming.

**Comment by rodlie** [comment]
For me changing the default settings solves the memory issue. As default Natron is set to keep 5% system RAM free , I usually set this to ~20%.

**Comment by devernay** [comment]
Let's default to 20%! other processes have a right to live!

**Comment by devernay** [comment]
> It appears to me that a memory leak is still present, but much lower in amplitude.

This is not necessarily an indication of a memory leak: freeing memory doesn't necessarily reduce the process size in Linux

**Comment by Songtech-0912** [comment]
I think we can consider this issue closed; the new 20% default solves most issues with RAM usage and anything else to reduce memory usage would likely involve major refactoring
