### ISSUE TITLE
Node Graph Navigation issues

### ISSUE THREAD

**Issue by magdesign** [NatronGitHub/Natron#491]
### Problem

When opening a comp from someone else (e.g.  from a win10 machine),
I am not able to see the nodes in Node Graph.
Trying to navigate in the lower right "finder" but it prevents me from moving over the space where the nodes are.

**Expected behavior:** 
Beeing able to see the node tree and navigate to it.

**Actual behavior:** 
Nodes are offscreen and I have no way to see them.

### Steps to Reproduce

1. opened comp I got
2. could not see the node tree
3. tried to navigate to the node tree, but its in no way possible: 

![notable_navigate](https://user-images.githubusercontent.com/5273166/81921882-9184d700-95db-11ea-841b-e1934c0690fb.gif)

### Versions
Natron RB-2.3 at version 426db22 
Ubuntu Linux 18.04 LTS

### Workaroud
Resizing the window of Natron and trying with middle mouse on Node Graph to navigate, after n attempts it works...

**Comment by devernay** [comment]
Did you try typing 'f' to recenter everything?
The node graph is known to be buggy, and unless someone volunteers to fix this it will stay as it is for a while, see https://github.com/NatronGitHub/Natron/issues/108

**Comment by devernay** [comment]
Also, I suppose scrolling in the main area didn't work either?

**Comment by magdesign** [comment]
'f' did not help also scrolling not.
but after a while clicking, dragging, scrolling, hitting f, using arrow key, i got to the nodes...

**Comment by devernay** [comment]
can you share the project (just the zipped ntp, we don't need the assets)?
It's better if you share it here, so that other people can take a look at the bug, bug you can also send it to me via email (frederic.devernay at m4x.org)

**Comment by magdesign** [comment]
here the faulty project (rename it: maskissue.ntp):
[maskissue.log](https://github.com/NatronGitHub/Natron/files/4630686/maskissue.log)

somethimes it works with navigating just with middle mouse pressed in node graph...

**Comment by devernay** [comment]
the "f" key behavior should be fixed by https://github.com/NatronGitHub/Natron/commit/dd334856de17d620f4c992a219eb6fa8451fad67
