### ISSUE TITLE
When a file is dragged into a text field in a PyModalDialog, the field visibly populates, but the param is still empty

### ISSUE THREAD

**Issue by philomory** [NatronGitHub/Natron#494]
### Problem

**Expected behavior:** When you drag a file into a `LineEdit` (particularly one created by a `FileParam`) in a `PyModalDialog`, the resultant path displayed in the field should be returned as the value of the parameter after the dialog is submitted.

**Actual behavior:** When you drag a file into a `LineEdit` (particularly one created by a `FileParam`) in a `PyModalDialog`, the path to the file is displayed in the field, but if the dialog is submitted without further interaction with that field, `param.get()` call returns the empty string.

### Steps to Reproduce

1. Create `initGui.py` with the following contents:
```python
from NatronGui import *

def exampleDialog():
  d = app.createModalDialog()
  path = d.createFileParam('example','Example')
  d.refreshUserParamsGUI()
  if d.exec_():
    natron.informationDialog('result',path.get())

natron.addMenuCommand('Example/File Dialog','exampleDialog')
```
2. Open Natron
3. Select Example > File Dialog from the menu bar
4. Drag a file to the LineEdit field of the dialog
5. Click 'OK'
6. Observe that in the resulting information dialog, no text is displayed.

If you repeat this process, but alter the text in any way between steps 4 and 5, or click the 'refresh' button to the right of the field, or even simply click within the text field and press 'tab' to change focus, the field label turns white and the results dialog displays the path as expected.

### Versions

* **Natron version/commit:** Natron Snapshot 2.3.15-RC20
* **OS version:** Windows 10

**Comment by philomory** [comment]
If anyone else is running into this problem, I've found a workaround that works at least for my use-case, though it's fairly janky and conceivably won't be reliable across updates:

```python
from NatronGui import *
from PySide import QtGui, QtCore

def exampleDialog():
  d = app.createModalDialog()
  path = d.createFileParam('example','Example')
  d.refreshUserParamsGUI()
  if d.exec_():
    # Trigger 'check-field-for-updates' logic of all fields
    for target in d.findChildren(QtGui.QLineEdit,'dim-0'):
      event = QtGui.QFocusEvent(QtCore.QEvent.FocusOut)
      target.focusOutEvent(event)
    natron.informationDialog('result',path.get())

natron.addMenuCommand('Example/File Dialog','exampleDialog')
```

**Comment by devernay** [comment]
That will be fixed in the next RC or release. Thanks for the very useful bug report.
Now the field gets also gets the focus. That way, the param is set correctly. I also selected the text.
