### ISSUE TITLE
White outlines upon rendering anything with natron.

### ISSUE THREAD

**Issue by Goodgun123456789** [NatronGitHub/Natron#495]
## Problem
Rendering Bug that causes white outlines on anything rendered
Describe the problem or suggestion here.

**Expected behavior:** 
To render cleanly with no artifacts.
**Actual behavior:** [What actually happened]
Opposite of above.  See attached gif (Warning, this gif happened to be very high speed upon rendering.)
https://mega.nz/file/kKZhlabZ#wZPvTQQxmTwxFfUE9JhCLHOsOdjDOyY4ggdrKMuo-0E
### Steps to Reproduce

1. Load any image
2. use a merge to merge it with another image
3. gift the higher layer image a transform
4. Render and wheep as it has a white outline

### Versions
2.3.14 Release
Current PC Specs/OS.
OS: Linux Mint 19.3 Tricia x86_64
Kernel: 5.3.0-51-generic
CPU: AMD Ryzen 5 1600 (12) @ 3.200GHz 
GPU: NVIDIA GeForce GTX 1050 Ti 
Memory: 11119MiB / 15940MiB

**Comment by rodlie** [comment]
Not able to replicate, please provide a project for testing.

**Comment by devernay** [comment]
Looks like your images have a premultiplication issue. My guess is that they are stored unpremultiplied, but you unpremult again on reading, causing the bright outlines. Check the premult setting in your readers

**Comment by Goodgun123456789** [comment]
> Looks like your images have a premultiplication issue. My guess is that they are stored unpremultiplied, but you unpremult again on reading, causing the bright outlines. Check the premult settings in your readers

yep, this was the issue!  Thanks for the help!
