### ISSUE TITLE
Natron Read Node

### ISSUE THREAD

**Issue by AlainH1213** [NatronGitHub/Natron#499]
when i choose a read node and a file natron gives me an error saying that it could not find decoder to read file How do i fix this?

Natron version: 2.3.14

**Comment by rodlie** [comment]
Need more info. Linux? Windows? macOS? and where did you get Natron? (from the website or through a third-party?)

**Comment by AlainH1213** [comment]
> Need more info. Linux? Windows? macOS? and where did you get Natron? (from the website or through a third-party?)

I got Natron from the website and i got it for linux the flatpak version

**Comment by rodlie** [comment]
Flatpaks and Snap runs in a sandbox and needs proper permissions to work.

**Comment by AlainH1213** [comment]
> Flatpaks and Snaps runs in a sandbox and needs proper permissions to work.

So, how do i do that?

**Comment by rodlie** [comment]
https://askubuntu.com/questions/1086529/how-to-give-a-flatpak-app-access-to-a-directory

**Comment by rodlie** [comment]
Btw, @Sunderland93 wasn't this fixed?

* https://github.com/flathub/fr.natron.Natron/issues/14
* https://github.com/flathub/fr.natron.Natron/issues/15

**Comment by Sunderland93** [comment]
@rodlie 

> Btw, @Sunderland93 wasn't this fixed?

Yes, it fixed

**Comment by rodlie** [comment]
Just tested the flatpak to confirm and it works as expected here (this was on a clean install of Fedora).
