### ISSUE TITLE
Meta-issue: 2.4.0 release blockers

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#504]
- Rendering silently stalls after X frames #248 (last one standing)

**Comment by makeworld-the-better-one** [comment]
> Rendering silently stalls after X frames #248 (move to 2.4 if nobody submits a sample project)

@devernay I have submitted a sample project. I responded to @rodlie in that thread and the debugging is ongoing. Just waiting for their response.

**Comment by devernay** [comment]
OK, no time to work on #248 for now, so we might just as well release 2.4.0, which contains a lot of fixes and improvements
