### ISSUE TITLE
Hello, I am having trouble locating my image files on Natron. 

### ISSUE THREAD

**Issue by NicMan620** [NatronGitHub/Natron#505]
I just downloaded Natron today on my Chromebook, and I was trying to import a photo (read) into my project. I tried to find my images from my chromebook that I use, but I have no clue how to access them. I expected to find the images easily, but I have clutter everywhere which I assume is part of my chromebook's system files. Can someone please help me locate the folder which all my downloads (images) are stored? (I have three folders which stores everything.) Thanks! 
![Screenshot 2020-06-07 at 10 50 20 PM](https://user-images.githubusercontent.com/66581203/83988498-660eb700-a911-11ea-899d-3fff82f8ae02.png)
![Screenshot 2020-06-07 at 10 49 53 PM](https://user-images.githubusercontent.com/66581203/83988500-660eb700-a911-11ea-9e0f-7302a2f83bb4.png)

**Comment by NicMan620** [comment]
Also, I would like to say that I don't have any knowledge about coding, I thought Natron was just a Node based editing software, I might not understand what you say unless you explain it. Sorry about that.

**Comment by lehuan5062** [comment]
Found this one: https://superuser.com/questions/729587/where-is-the-location-of-the-downloads-folder-on-a-chromebook

You don't need coding knowledge to use Natron. Though knowing some may help you with doing fancy stuffs.

**Comment by NicMan620** [comment]
Alright, thank you! I'll try to see if this helps!

**Comment by NicMan620** [comment]
Thank you! I found all of my images! I will be learning how to animate on her, big help!
