### ISSUE TITLE
Natron does not install

### ISSUE THREAD

**Issue by lisaraj2009** [NatronGitHub/Natron#506]
Hello, 
I just checked the Natron webpage for downloads and downloaded the executable installer for Windows 10, version 1909. However, when I ran the installer, Windows Defender marked it as unsafe. Ignoring the warning, I ran it anyway. However, after the approval prompt that appears when you run .exe files, nothing happens at all. I hope that this issue can be fixed, and that the inconveniences (showing as an unsigned/unsafe program) can be easily rectified. 
I would like the Natron developers to:

- Take care of the inconveniences, such as showing the program as unsigned. 
- Fix the executable installer's problems
Thank you.

**Comment by lehuan5062** [comment]
I click run anyway then it ask me do I want to run it as administrator. I click yes and the setup run.

Did you miss anything?

**Comment by rodlie** [comment]
We can't do anything about it, see:
* https://discuss.pixls.us/t/natron-2-3-15-released/18640/7
* https://github.com/NatronGitHub/Natron/issues/275

**Comment by lisaraj2009** [comment]
Nothing happens when I run as administrator as well. I will send a screen recording and show what happens

**Comment by lisaraj2009** [comment]
Here you go. I am sorry because the UAC prompt is hidden when I record in OBS Studio

[natron-screen-recording-obs.zip](https://github.com/NatronGitHub/Natron/files/4746590/natron-screen-recording-obs.zip)

**Comment by lehuan5062** [comment]
So it took your OS 10 seconds to handle the prompt, I guess you may want to close other applications and restart your machine. You would want to run the installer when no other application running.

If it doesn't help, only the devs can help you now.

**Comment by lisaraj2009** [comment]
Installers don't usually take that long. I've installed a bunch of different programs today - I reinstalled 
Microsoft Office, installed FireAlpaca, IntelliJ, Python, MiKTeX, BleachBit, Synfig etc. I think there happens to be a problem with Windows 10 or the installer's efficiency.  :(

**Comment by lisaraj2009** [comment]
So let me just clarify to the devs. When I run the installer as an administrator, the prompt appears quickly and I approve the installer. However, the setup wizard does not appear - the running in background cursor just stays normal, and returns to the normal arrow cursor. Perhaps an improvement in installer efficiency?

**Comment by lisaraj2009** [comment]
Please help, I really would like to use this program

**Comment by devernay** [comment]
@lisaraj2009 why don't you simply use the no-installer version? there are two versions of the windows binary releases.

**Comment by rodlie** [comment]
I tested the installer on three computers before publish, one with Windows 10 1909 Pro, one with Windows 10 1909 Home and one with Windows 8.1 Pro. I had no issues installing or using Natron.

I was able to replicate the smart screen warning when I download the installer directly from GitHub, but all needed was to click "run anyway" (one time) and that's it.

The reason I never got the smart screen warning was that I always installed Natron through the local network, seems files copied from the local network are deemed "safe".

**Comment by lisaraj2009** [comment]
That's extremely strange! The installer does not launch on my PC

**Comment by lisaraj2009** [comment]
Also how do I use the no-installer version

**Comment by rodlie** [comment]
Just extract the zip file and run Natron.exe from the extracted folder (Natron-2.3.15-Windows-64-no-installer/bin).

**Comment by lisaraj2009** [comment]
Thanks! I added it to the start menu. For those who don't know, create a shortcut to where the executable is in C:\Users\YourUserName\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\

**Comment by lisaraj2009** [comment]
I will close this issue now
