### ISSUE TITLE
"error: file is not open" when writing H264 MP4 or MOV

### ISSUE THREAD

**Issue by Shrinks99** [NatronGitHub/Natron#507]
### Problem

When tabbing in a write node and saving as test.mp4 H264 FFMPEG auto fills the container and codec correctly, unfortunately this also results in a `error:file is not open` error in the viewer and the node will not render properly.

**Expected behavior:**
No error, everything looks like it is set up correctly and it should render fine both in the viewer and on render in the queue.
**Actual behavior:**
The writer gives the error, this can be fixed by resetting the codec field to any other codec and then setting it back to H264 at which point it will work as expected.  I suspect this is because when I tab in the write node it is not connected to anything and throws an error, when it is reset after it is connected to the node graph it works properly.  This issue does not occur if I tab it in with the constant or read node already selected and the write node works as expected in that case.

Natron project file: [natron-writer-error.zip](https://github.com/NatronGitHub/Natron/files/4748634/natron-writer-error.zip)

### Steps to Reproduce

1. Create a constant
2. Create a write node without the constant selected and attach it, save a file as x.mp4
3. View the write node
4. Error! :(

I am able to reproduce this on multiple machines.

![write error](https://user-images.githubusercontent.com/5672810/84080668-876fb180-a9aa-11ea-8197-c3993ac011ef.png)

### Versions

* **Natron version:** 2.3.15 Release (Also was a problem in 2.3.14)
* **OS version:** Tested on Windows 10 & MacOS 10.14

**Comment by magdesign** [comment]
I guess that:
Natron compresses the *.mp4 files standard as:  `isom`
which is not nativ supported on windows.
maybe it should be changed by default to : `mp4v`

easy workaround is to change the codec before hitting render:

![render](https://user-images.githubusercontent.com/5273166/84138845-3fef3100-aa4f-11ea-8fbc-c024b1b52e24.png)

**Comment by lehuan5062** [comment]
In addition, any time we make a change to our comp which is linked to the write node, the issue will happen again, no matter what codec is chosen.

I think we shouldn't view the write node right now. The node can still render when the "Error" appears though.
