### ISSUE TITLE
2.3.15 Can't read Jpeg2000 files under linux.

### ISSUE THREAD

**Issue by lal0cura** [NatronGitHub/Natron#509]
Problem
Hi guys, I hope you are doing well. I detected a issue when trying to open JPEG 2000 (.JP2, .J2C) files under Linux in the latest release on Natron (2.3.15) in the three versions (Flatpak, Installer and portable)

**Expected behavior:
When hitting "r", and selecting either a .JP2 or .J2C it should read the file and place it into a read node. I did this with a Windows OS with the 2.3.15 and it works OK. I downloaded the linux portable version of the 2.3.14 release and it also works well in the old one.

**Actual behavior:
When hitting "r" in the 2.3.15 release and selecting a .JP2 or .JP3 it shows an error that says that it could not find a decoder to read the file.
The terminal console shows this message as well:

$./Natron
Natron Version 2.3.15
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
Info: init.py script not loaded (this is not an error)
Info: initGui.py script not loaded (this is not an error)

Error while creating node fr.inria.built-in.Read: Could not find a decoder to read j2c file format
Error while creating node fr.inria.built-in.Read: Could not find a decoder to read jp2 file format

I test other file formats (BMP,CIN,DPX,EXR,RGB,JPG,PNG,HDR,TGA,TIF) and they work fine in 2.3.15, it seems it's only having issues with the JPEG2000 under Linux.  I hope it can be corrected cause this file format is used in digital cinema and medial fields. Also helps to save a lot of space. for contrast I have 5 sequences in PNG and they use about 18Gb. The same 5 sequences in JP2 uses about 4.8G so its a space saver with visually the same quality. 

My operating system in Ubuntu 20.04
[JPEG2000.zip](https://github.com/NatronGitHub/Natron/files/4768045/JPEG2000.zip)
I try to attach the .JP2 and J2C files directly, but github wont let me. I put them on this zip file.

Thanks a lot guys. Stay safe.

**Comment by devernay** [comment]
Confirmed, this was an issue in all snapshots and RCs since 2.3.14.

**Comment by devernay** [comment]
can you please test https://github.com/NatronGitHub/Natron/releases/tag/v2.3.16-beta1 ?
