### ISSUE TITLE
Natron is missing in Winget repository

### ISSUE THREAD

**Issue by PolpOnline** [NatronGitHub/Natron#511]
### Natron is missing in Winget repository

Hello, I would like you to add Natron on Winget, this is a package manager for Windows 10, created by Microsoft to install programs on Windows more easily and quickly.

**Add Natron on Winget** [What you expected to happen]

**Comment by rodlie** [comment]
I could probably add support for winget. Silent install should work with qtifw 2+.

**Comment by devernay** [comment]
then why not chocolatey?

**Comment by rodlie** [comment]
Could do that, I don't use either. If wanted I could upgrade the installer on Windows to be compatible with winget (and possible chocolatey, never used it). I have time this weekend.

**Comment by lisaraj2009** [comment]
That's cool! I use winget and this could be great! :D

**Comment by rodlie** [comment]
I got a new working installer (qtifw latest), but never had the time to test it (silent install). I got free time this week, so should be  able to get something working.

**Comment by PolpOnline** [comment]
Hi, i's been about a year since the last comment, does the silent install work well now?

**Comment by rodlie** [comment]
we supply the installer in a zip, but winget does not support that yet (https://github.com/microsoft/winget-cli/issues/140).

I could look into making an installer just for winget, but it will have to wait until my vacation (~1week).

> does the silent install work well now?

Yes it should work fine in silent mode.

**Comment by luzpaz** [comment]
Natron is in winget, 
[![winget package](https://repology.org/badge/version-for-repo/winget/natron.svg)](https://repology.org/project/natron/versions)
see https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/Natron/Natron/2.5.0

This ticket can be closed
