### ISSUE TITLE
Viewer seems to only show the right color if the output is linear

### ISSUE THREAD

**Issue by lehuan5062** [NatronGitHub/Natron#513]
### Steps to Reproduce

1. Use this exr: 
[camera090.zip](https://github.com/NatronGitHub/Natron/files/4790034/camera090.zip)
2. The image has sRGB colorspace. Add a Read node and set file colorspace to sRGB.
3. Viewer only shows the correct color if ouput colorspace is set to linear.

Comparison:
- Davinci Resolve: input, timeline, output = sRGB
https://cdn.discordapp.com/attachments/416187415879876612/722344261139562557/unknown.png
- Nuke: read node colorspace setting = sRGB
https://cdn.discordapp.com/attachments/416187415879876612/722345190915964959/unknown.png
- Natron: file colorspace, output colorspace = sRGB
https://cdn.discordapp.com/attachments/416187415879876612/722346247129923614/unknown.png
- Natron: file colorspace = sRGB, output colorspace = Linear
https://cdn.discordapp.com/attachments/416187415879876612/722346822701678592/unknown.png

Not sure if converting everything to linear is the only workflow in Natron or not.

### Versions

* **Natron version/commit** : 2.3.16 beta 1
* **OS version:** Windows 10

**Comment by devernay** [comment]
this is expected, all the Natron workflow is linear, and there is no colorspace metadata. You have to manually insert an OCIODisplay or OCIOColorSpace node before the viewer to handle other colorspaces
