### ISSUE TITLE
Natron won't start up properly

### ISSUE THREAD

**Issue by Objectedbear431** [NatronGitHub/Natron#519]
Hello,

I just downloaded Natron. Unfortunately, whenever I try to start it up, the program freezes up and doesn't respond. It's strange because the first time I started the program up, it worked just fine.
A window pops up that says this: "Natron Version 2.3.15
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
Info: init.py script not loaded (this is not an error)
Info: initGui.py script not loaded (this is not an error)"

Does anyone know how to fix this problem?

**Comment by devernay** [comment]
Please use the issue template when submitting a new issue. It is here for good reasons.
