### ISSUE TITLE
When try to create a text node

### ISSUE THREAD

**Issue by Na4axz** [NatronGitHub/Natron#522]
Hi as soon as i try to create a text node so i can type in something in natron the program crashes. i have tryd reinstall, update, updatesystem, reboot nothing works it closing natron everytime i hit the text nod button. iam on linux mint ulyana

**Comment by rodlie** [comment]
Natron version? And where did you download it from? What kind of graphics card/driver are you using? Try running Natron from a terminal to get errors/warnings.

**Comment by Na4axz** [comment]
> Natron version? And where did you download it from? What kind of graphics card/driver are you using? Try running Natron from a terminal to get errors/warnings.

I download from programs,  version 2.3.15, my card is an mesa dri hd graphics 4000 (ivb gt2)
Ok i try with terminal :)

**Comment by Na4axz** [comment]
I cant start it from terminal command dont exist it says, i tryed outher programs and they work from terminal

**Comment by rodlie** [comment]
You downloaded Natron from https://github.com/NatronGitHub/Natron/releases or https://natrongithub.github.io? or through the OS? (package manager or store)

The GPU is ok, I have a similar card on two computers. "mint ulyana" is more or less Ubuntu 20.04. I run Ubuntu 20.04 at work and the official binaries from Natron works great on that distro.

**Comment by Na4axz** [comment]
through the os, but now i have download from github.io going to try a reinstall from there

**Comment by Na4axz** [comment]
It works now used github.io link and install from there now i can do text :) thanks fro the help man :)

**Comment by rodlie** [comment]
Great, I guess you used the snap package (not controlled by us), and something is broken in it.

**Comment by Na4axz** [comment]
> Great, I guess you used the snap package (not controlled by us), and something is broken in it.

Yes i did from now on i will use download site insteed of snapackage :)

**Comment by yucefsourani** [comment]
same problem ,fedora 32 workstation  64bit with nvidia proprietary driver nvidia-390xx (nvidia 710m) ,natron from flatub/flatpak Natron version 2.3.15 Release.

Error when add text node .
/usr/include/c++/9.2.0/bits/stl_vector.h:1042: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = const char*; _Alloc = std::allocator<const char*>; std::vector<_Tp, _Alloc>::reference = const char*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.

**Comment by yucefsourani** [comment]
no problem in Natron version 2.3.15 Release portable version .

**Comment by rodlie** [comment]
I highly recommend using the official binaries, the unofficial snap also has issues.
