### ISSUE TITLE
Error while creating node fr.inria.built-in.Write

### ISSUE THREAD

**Issue by yasharya2901** [NatronGitHub/Natron#526]
Please ask questions ("how do I...?") on the [forum](https://discuss.pixls.us/c/software/natron), not by filing issues.

Please read carefully the [Troubleshooting](http://natron.readthedocs.io/en/rb-2.3/guide/getstarted-troubleshooting.html) section of the [Natron documentation](http://natron.readthedocs.io) before submitting an issue: this issue may already be signaled, or may have a simple workaround.

Make concrete suggestions for fixing the code ("here is a patch") by filing
a [pull request](https://github.com/MrKepzie/Natron/pull/new/master), not an issue.

Finally, please follow the [Code of Conduct](https://github.com/NatronGitHub/Natron/blob/RB-2.3/CODE_OF_CONDUCT.md) when interacting with the Natron community (both users and developers).

### Problem

Dear Developers,
I thought to give Natron a try and started working on a project. I did finish the rendering but after rendering, it wasn't looking as it was in the player. However, it turned out to be that I am using the version 2.3.14. So, I thought to upgrade it. Today, I installed version 2.3.15 but when I clicked on Write node, the menu appeared but under file type, I couldn't find those containers. And when I hit Cancel or save, I was prompted with a dialog box saying, "Error while creating node fr.inria.built-in.Write: The IO.ofx.bundle OpenFX plug-in is required to use this node, make sure it is installed."

I don't know what's happening but it was working in the previous version. I also tried version 2.3.16 from GitHub release but still, I got the same issue.

**Expected behavior:** [What you expected to happen]
It should have brought the Write node in the node editor.
**Actual behavior:** [What actually happened]
Produced an error dialog box saying, "Error while creating node fr.inria.built-in.Write: The IO.ofx.bundle OpenFX plug-in is required to use this node, make sure it is installed."
 * If your problem can be reproduced using a Natron project, please include a link to the project on a file-sharing service, or attach the project as a zip file to this issue, if possible.
 
 * If your problem is a crash in an official release/snapshot, please include verbose output from the application from a terminal if possible.  If you also submitted a crash report, indicate the CrashID if possible.
 
 * If you need to report a compilation issue, please create a [gist](https://gist.github.com)
 that contains the _full_ verbose build log.
 
 * If your problem is a crash in a build that you made yourself, please create a [gist](https://gist.github.com)
 that contains a _full_ backtrace.

### Steps to Reproduce

1. Click on Write node
2. Click Cancel

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions
2.3.15 Release
* **Natron version/commit** (they can be retrieved from the About Window): 
* **OS version:** 
Windows 7 Home Premium 64-bit

![image](https://user-images.githubusercontent.com/36362019/88310055-db511280-cd2c-11ea-995a-dc9c34edb12e.png)

**Comment by rodlie** [comment]
Windows 7 is not supported anymore.

***unsupported** "fix" for Windows 7 can be found [here](https://discuss.pixls.us/t/to-bug-or-not-to-bug/17489/19)*

**Comment by yasharya2901** [comment]
Oh, that's sad.

**Comment by rodlie** [comment]
We depend on OpenImageIO and they require Windows 8+. The link above provides a DLL that is compatible with Windows 7 (but is not supported).
