### ISSUE TITLE
Green lines in viewer

### ISSUE THREAD

**Issue by kaovilai** [NatronGitHub/Natron#527]
### Problem
Upon launching Natron for the first time, I am greeted with the following UI
![image](https://user-images.githubusercontent.com/11228024/88370786-ef445500-cdbc-11ea-97c0-1d09d8bbf1bf.png)
It happens upon restart of the software and is not related to a specific project.

**Expected behavior:** No green lines in the viewer

**Actual behavior:** Green lines in the viewer

### Steps to Reproduce

1. Launch Natron.exe
2. Wait
3. And see

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions
Natron version 2.3.15 Release.
#### PC Specification
```
---From System Information---
OS Name	Microsoft Windows 10 Pro
Version	10.0.19041 Build 19041
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	SPECTRE
System Manufacturer	HP
System Model	HP Spectre x360 Convertible 15-bl0XX
System Type	x64-based PC
System SKU	X5P15AV
Processor	Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, 2904 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. F.41, 12/12/2019
SMBIOS Version	2.8
Embedded Controller Version	9.42
BIOS Mode	UEFI
BaseBoard Manufacturer	HP
BaseBoard Product	82C1
BaseBoard Version	09.42
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.1"
Time Zone	SE Asia Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	3.57 GB
Total Virtual Memory	24.8 GB
Available Virtual Memory	4.46 GB
Page File Space	8.95 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, Mode Based Execution Control
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	
---Graphics Adapters---
Name	Intel(R) HD Graphics 620
Name	NVIDIA GeForce 940MX *was not in use by Natron*
```

**Comment by rodlie** [comment]
Looks like an issue with the hybrid GPU solution (Intel+NVIDIA), try disabling the Intel GPU (and/or force the NVIDIA GPU to be always on).

**Comment by kaovilai** [comment]
> Looks like an issue with the hybrid GPU solution

I never had an issue with other software like Blender tho. And games and such run fine. Besides, disabling one of the GPU won't do me any good. The laptop's screen is powered by Intel and Nvidia can only proxy through the intel adapter. This is not the old days switchable graphics where only one is active at a time. The only option in the bios is to disable dedicated GPU if I remember correctly. I do not see _Nvidia GPU activity_ window reporting usage at the time of software opening and when the lines appear so I doubt GPU is the issue.

**Comment by MushrafAltaf** [comment]
I am having the same issue. Did you find a fix for it?

**Comment by kaovilai** [comment]
> 
> 
> I am having the same issue. Did you find a fix for it?

Nope. I am no longer active in this space as I am occupied with university. I hope that someone can fix it tho.

**Comment by Sunnybanala** [comment]
> I am having the same issue. Did you find a fix for it?

i tried changing settings in NVIDIA control panel (it worked), Manage 3D settings --> Program Settings, for Natron select preferred graphics processor as nvidia processor, or else try updating drivers for your graphics card

**Comment by altter** [comment]
If someone is stil having the problem, my solution for a DELL Latitude 501 with Intel Graphic630 was to update the driver to its latest version from Intel web page: https://downloadcenter.intel.com/download/30100/Intel-Graphics-Windows-10-DCH-Drivers.

It could work for any other graphic regarding the manufacturer. My advice before installing any driver is to make a restoration point of your system.

**Comment by tinodo** [comment]
> > I am having the same issue. Did you find a fix for it?
> 
> i tried changing settings in NVIDIA control panel (it worked for me), Manage 3D settings --> Program Settings, for Natron select preferred graphics processor as nvidia processor, or else try updating drivers for your graphics card

This solved the issue for me!
