### ISSUE TITLE
Only 32f processing bit depth. Memory consumtion.

### ISSUE THREAD

**Issue by jaxxtrend** [NatronGitHub/Natron#529]
No have 16f, 8uint or other processing bit depth only 32f. This is produce hard memory consumtion.

**Comment by rodlie** [comment]
This is normal in most (if not all) compositing applications.

**Comment by jaxxtrend** [comment]
Sorry, i think this is not a bug report, maybe this is feature request.

**Comment by charlesangus** [comment]
Offering the ability to process at anything but 32 bit float is a bad idea. Vastly increases complexity (now every node needs to support three code paths) and basically just offers a "trap" setting which people can get wrong (it should always be 32 bit for all professional applications).

There's just no benefit and serious drawbacks.

**Comment by Echolon** [comment]
Hi @jaxxtrend 

I will close this based on the feedback.

@devernay ok?
