### ISSUE TITLE
Natron 2.3.15not installing Windows 10 20.04 

### ISSUE THREAD

**Issue by adriancenciso** [NatronGitHub/Natron#530]
Hello, 

I'd like to ask/report on a problem that I am facing by trying to install Natron 2.3.15 on Windows 10 20.04

I have been trying out natron for the past two years doing not much but than doing some compositing and simple colour grading.
The current laptop that i use runs under intel 1065G7, this is a new laptop i purchased recently and now wanted to install it again and now i cant? 
I get the windows smartscreen prompt screen and I click on running it under my own risk and nothing, no install promp or anything.

Is there anyone else who have issues similarly?

I am also new in github so i do not know much of what i am supposed to do or write.

**Comment by rodlie** [comment]
Try again? I get the smart screen popup, but the installer works just fine here on my test equipment. Worst cast use the "portable" zip https://github.com/NatronGitHub/Natron/releases/download/v2.3.15/Natron-2.3.15-Windows-64-no-installer.zip

**Comment by frelindo** [comment]
For me the problem was that I was using Firefox. Just use another broser. Microsoft Edge worked for me.

**Comment by rodlie** [comment]
I would recommend testing out the latest beta. Also, anti virus software will in most cases block things they don't know/like, this has been a known issue for several people trying to install Natron.

We have a new installer that should improve things, outside of that there is not much we can do. I test on 3 different Windows computers and it WFM.

**Comment by rodlie** [comment]
Will close this... If the installer works or not seems to depend on the "security" settings in Windows 10. Not something we control.
