### ISSUE TITLE
Clicking on draw/text crashes on Linux

### ISSUE THREAD

**Issue by jussikiova** [NatronGitHub/Natron#535]
1) open the Natron
2) click draw/text
3) crash without error message

Screencast here:
https://youtu.be/Yfkn8Wh4sAA

Natron version 2.3.15 Release.

OS:
System:    
Kernel: 5.4.0-42-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal

**Comment by rodlie** [comment]
Probably related to #522

Download the official builds from https://github.com/NatronGitHub/Natron/releases

**Comment by rodlie** [comment]
Official binaries works fine, closing.
