### ISSUE TITLE
Natron write error: Unable to open file: Permission denied

### ISSUE THREAD

**Issue by Ridiculouslyben** [NatronGitHub/Natron#540]
### error: Unable to open file: Permission denied

I was able to render this project before without any issues at all but I wasn't liking the artifacts showing in the final render. Took a break for a few days and came back to it.

**Expected behavior:**
Render without errors, like before.

**Actual behavior:** 
I added a new write node --> Mp4 --> change codec to H264 to see if its better 

Then I get the following **error: Unable to open file: Permission denied**

**What I tried:**
1. I tried to go back to the previous write node
2. tried saving before writing
3. tried erasing the write nodes all together
4. tried changing the codecs
5. tried changing permission settings on file and directory
6. tried writing to a new directory

None of which worked and same failed results.

Any help is greatly appreciated!

Thank you,

Ben

**Comment by Ridiculouslyben** [comment]
Big Sad!!! I figure it out. After over an hour of troubleshooting and frustration I figured it out...

Closing this. **The simple answer was:** Avast anti-virus doesn't like it when Natron exports. Disable all shields and you are good.

**Comment by DRI-UK75** [comment]
The simple answer is to remove or certainly disable the parameters within Avast producing the error. Personally I would Never has avast and it’s constant addition of malware.

Get rid of if.

David Robinson
Digital Compositor (Nuke and Flame)

**Comment by Ridiculouslyben** [comment]
I know unrelated but, any recommendations on a good anti-virus?

> The simple answer is to remove or certainly disable the parameters within Avast producing the error. Personally I would Never has avast and it’s constant addition of malware. Get rid of if. David Robinson Digital Compositor (Nuke and Flame)
> […](#)
> On 12 Sep 2020, at 05:11, Ridiculouslyben ***@***.***> wrote: ﻿ Big Sad!!! I figure it out. After over an hour of troubleshooting and frustration I figured it out... Closing this. The simple answer was: Avast anti-virus doesn't like it when Natron exports. Disable all shields and you are good. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
