### ISSUE TITLE
Blender INtegration

### ISSUE THREAD

**Issue by orangemn6** [NatronGitHub/Natron#541]
This is a suggestion: I think you should have some kind of blender integration for a 3d workspace. In the setup it could say 3d components as one of the options, and would add a blender integration. If anyone would like to develop this i could help.

Thanks,
            Orangemn6

**Comment by Shrinks99** [comment]
For me the value of having a 3D workspace in a compositor is not having to switch applications.  What would integrating Blender look like?  What would this accomplish that cannot be done with the current Blender → Natron workflow?  How would this make it faster?

**Comment by orangemn6** [comment]
I think it would be just a tile in natron reserved for blender. It would make moving files from blender to natron much easier, instead of having to wait to fully switch apps.

**Comment by Shrinks99** [comment]
What would the node do though?

**Comment by lehuan5062** [comment]
I think if a studio want to have a better pipeline from Blender to Natron, they can develope the "integration" they want.

In the end, we have to render everything before applying the post processing composition. So making an "integration" isn't really useful. It can change the way we work but not the time it takes.

If a studio want "real time compositing", they should consider the Blender to Unreal pipeline.

**Comment by garyo** [comment]
Just noticed this. Since Blender doesn't support OFX effects in its compositor pipeline, perhaps a good integration would be to hook Natron into Blender's compositing pipeline as a reader.

**Comment by orangemn6** [comment]
@garyo that would be cool.

**Comment by devernay** [comment]
Will probably happen once Word is merged with Photoshop.
Sorry, ut that's just not possible.

**Comment by garyo** [comment]
@devernay I agree -- and I think if someone has an open-source itch they'd like to scratch, adding OFX host support to Blender would be a better use of that time.
