### ISSUE TITLE
Mocha Pro Working on ubuntu

### ISSUE THREAD

**Issue by orangemn6** [NatronGitHub/Natron#542]
Hello, I got the mocha pro ofx working on ubuntu. Steps:
buy it from borisfx
download the rpm package
use alien to make it into a .deb file
install the .deb file
move /usr/OFX/BorisFX/mochapro2020.5 to Natron-2.3.15/Plugins/OFX

Thanks!

**Comment by Echolon** [comment]
https://github.com/NatronGitHub/Natron/issues/436#issuecomment-816935938
