### ISSUE TITLE
Natron just crashes/closes itself just after start up

### ISSUE THREAD

**Issue by ItzJream** [NatronGitHub/Natron#543]
My natron crashes / closes itself just after launching it...

**Comment by rodlie** [comment]
You will need to provide more information, saying Natron crashed will not help anyone.

**Comment by ItzJream** [comment]
> You will need to provide more information, saying Natron crashed will not help anyone.

plz say what you need...

**Comment by rodlie** [comment]
* OS version
* Natron version
* if on Linux where did you get Natron
* Graphics card
* Terminal/console output from Natron before crash

**Comment by ItzJream** [comment]
- OS Windows 10 

- Natron Version  2.3.15

- GPU Nvidia GT216

- Natron Version 2.3.15


- Terminal LOG

   Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
   >>>Use the --help or -h option to print usage.<<<
   Info: init.py script not loaded (this is not an error)
   Info: initGui.py script not loaded (this is not an error)

**Comment by rodlie** [comment]
Is the GT216 a mobile GPU? Do you also have an Intel GPU? If that's the case disable one of the GPU's

**Comment by ItzJream** [comment]
> Is the GT216 a mobile GPU? Do you also have an Intel GPU? If that's the case disable one of the GPU's

Yes, GT216 is a mobile GPU

By intel GPU you mean my processor?

**Comment by ItzJream** [comment]
> > Is the GT216 a mobile GPU? Do you also have an Intel GPU? If that's the case disable one of the GPU's
> 
> Yes, GT216 is a mobile GPU (Laptop GPU)
> 
> By intel GPU you mean my processor?

**Comment by rodlie** [comment]
If you have an Intel CPU you probably also have an Intel GPU. Most laptops with NVIDIA graphics and Intel CPU uses a hybrid solution where they switch GPU based on load/battery etc, this will not work with Natron. Somewhere (in the NVIDIA drivers or BIOS) you can enable/disable this feature.

**Comment by ItzJream** [comment]
> If you have an Intel CPU you probably also have an Intel GPU. Most laptops with NVIDIA graphics and Intel CPU uses a hybrid solution where they switch GPU based on load/battery etc, this will not work with Natron. Somewhere (in the NVIDIA drivers or BIOS) you can enable/disable this feature.

i kn that but i think its using the nvidia GPU cause on my laptop there is a switch to toggle them...

**Comment by ItzJream** [comment]
im doubting that it might be the problem of my GPU

**Comment by ItzJream** [comment]
It is the problem of my gpu
