### ISSUE TITLE
identical assignment 

### ISSUE THREAD

**Issue by maddin200** [NatronGitHub/Natron#547]
Natron-RB-2.3/libs/libmv/libmv/tracking/retrack_region_tracker.cc line 38:

 if (!tracker_->Track(image1, image2, x1, y1, x2, y2)) {
    return false;
  }
  // Now track x2 and y2 backward, to get xx1 and yy1 which, if the track is
  // good, should match x1 and y1 (but may not if the track is bad).
  double xx1 = *x2, yy1 = *x2; // <- probably *y2 expected
  if (!tracker_->Track(image2, image1, *x2, *y2, &xx1, &yy1)) {
    return false;
  }

**Comment by devernay** [comment]
I don't even know if this code is used in Natron, but it's still in blender. Could you submit an issue to blender?
https://git.blender.org/gitweb/gitweb.cgi/blender.git/blob/HEAD:/intern/libmv/libmv/tracking/retrack_region_tracker.cc
