### ISSUE TITLE
Migrate away from Travis CI

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/Natron#552]
Hi, got an email today from Travis CI, where they introduce their new pricing plans etc. Seems like OSS projects will suffer from this.

> You have 1,000 credits left - these will begin counting down automatically as soon as you run your first build.

It also looks like macOS is now a paid option

> MacOS builders will need to purchase add ons on top of (in addition to) their paid plans. You can purchase packages of 25k credits for $15. 1 macOS build minute = 50 credits.

And when I log in to travis-ci.com

> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

It looks like it's probably a good time to consider other options (GitHub Actions?).

**Comment by devernay** [comment]
or it could be appveyor.
the macOS build system on travis was not great anyway

**Comment by rodlie** [comment]
Sure, I've been using Travis for everything these last years, so I'm not that familiar with the alternatives, as long as they support Windows/macOS/Linux and don't require too much work/maintenance.

**Comment by rodlie** [comment]
See #601
