### ISSUE TITLE
TestRoll and TestSwirl from the test suite seem to hang Natron

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#556]
### Problem

When building Natron binaries, TestRoll and TestSwirl from the test suite seem to hang Natron, and thus all tests fail. What's so special about these tests?

### Steps to Reproduce

```
mkdir builds
docker run -it --rm --mount src="$(pwd)/builds",target=/home/builds_archive,type=bind natrongithub/natron-sdk-centos7-dts8:latest bash
# then once bash is launched inside the docker container
./launchBuildMain.sh
```

The same happens in all linux containers:
- natrongithub/natron-sdk-centos6-dts8
- natrongithub/natron-sdk-centos7-dts8
- natrongithub/natron-sdk-centos8
- natrongithub/natron-sdk-ubuntu18.04
- natrongithub/natron-sdk-ubuntu20.04

@rodlie since this are plugins from https://github.com/NatronGitHub/openfx-arena can you please take a look? What is the difference between those plugins and others in openfx-arena? Does this also happen when launching the tests on a desktop?

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 2.3.16b1
* **OS version:** all Linux versions (didn't check macOS and Windows)

**Comment by rodlie** [comment]
will check.

**Comment by rodlie** [comment]
I was only able to test on my laptop (desktop, no docker/vbox), can do a proper test when I get to work.

I can confirm that the following fail (freeze) on Roll, Swirl, Wave:

* Natron-RB-2.3-202012080218-e7ebb7d-Linux-64-Ubuntu20.04-no-installer.tar.xz
* Natron-RB-2.3-202011270348-2ae6cce-Linux-64-CentOS7-no-installer.tar.xz

These work:

* Natron-2.3.15.1-Linux-64-no-installer.tar.xz
* Natron-RB-2.3-202006140005-e34a969-Linux-64-no-installer.tar.xz

**Comment by rodlie** [comment]
Seems to be an issue with ImageMagick, will try and find out why...

* 6.9.11-37 OK
* 6.9.11-38 FAIL
* 6.9.11-46 FAIL
* 7.0.10 OK

**Comment by devernay** [comment]
@rodlie does the configuration change fix this issue?

**Comment by devernay** [comment]
or maybe it's time to switch to IM 7? Are there other issues with IM 7?

**Comment by rodlie** [comment]
> @rodlie does the configuration change fix this issue?

Yes, it does on my machines (Ubuntu 20.04/CentOS 7). I didn't test docker, but I can't see why the result would be different vs. desktop.

The issue is that IM searches for a policy file (and others), if found apply the settings, if not set the lowest possible settings. None of those are good, we shouldn't include IM settings from the system (most distros include IM and it's config files) and we shouldn't run without (except for when ``zero-configuration`` is enabled). The only reason this has worked in the past is because IM didn't enforce this, now they do (6.9.11-38+).

Note that the memory default setting is ~2GB, I can add a knob in the plugins so users can override this.

> or maybe it's time to switch to IM 7? Are there other issues with IM 7?

I will need to test the plugins again, last year only one plugin had an issue.

**Comment by rodlie** [comment]
Regarding IM7 I noticed a major performance regression on macOS and MinGW (Linux is ok for some reason).

Example (macOS 10.13 using Clang 10):
```
$ time ./Darwin/bin/convert -version input.png -resize 266x192 output.png
Version: ImageMagick 6.9.11-53 Q16 x86_64 2020-12-28 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): bzlib djvu fftw fontconfig freetype gvc heic jbig jng jp2 jpeg lcms ltdl lzma openexr pangocairo png raw tiff webp xml zlib

real	0m1.887s
user	0m2.999s
sys	0m0.206s

$ time ./Darwin2/bin/convert -version input.png -resize 266x192 output.png
Version: ImageMagick 7.0.10-53 Q16 x86_64 2020-12-28 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): bzlib djvu fftw fontconfig freetype gvc heic jbig jng jp2 jpeg lcms ltdl lzma openexr pangocairo png raw tiff webp xml zlib

real	0m4.419s
user	0m10.682s
sys	0m0.361s

```

Seems like IM6 is still the safe choice.
