### ISSUE TITLE
Install issue on Manjaro 20.2 - Hangs at building shiboken

### ISSUE THREAD

**Issue by GregTheHun** [NatronGitHub/Natron#558]
### Problem

**Expected behavior:** 

Expected Natron to install without issue and be able to run

**Actual behavior:**

After getting the initial setup to run for the most part, got stuck on a build error.

### Steps to Reproduce

1. First thing, I had to specify a version of sip (4.19.22) to install from Manjaro:
> ~> sudo pacman -U https://archive.archlinux.org/packages/s/sip/sip-4.19.22-2-x86_64.pkg.tar.zst
> ~> echo 'IgnorePkg = sip' > /etc/pacman.conf

2. Went to my package manager and attempted to install as normal, but got this error finally:
> [ 82%] Building CXX object generator/CMakeFiles/shiboken.dir/shiboken/overloaddata.cpp.o
> [ 83%] Building CXX object generator/CMakeFiles/shiboken.dir/shiboken/headergenerator.cpp.o
> [ 85%] Building CXX object generator/CMakeFiles/shiboken.dir/shiboken/cppgenerator.cpp.o
> [ 87%] Building CXX object generator/CMakeFiles/shiboken.dir/generator.cpp.o
> [ 88%] Building CXX object generator/CMakeFiles/shiboken.dir/shiboken/shibokengenerator.cpp.o
> [ 90%] Building CXX object generator/CMakeFiles/shiboken.dir/shiboken/shibokennormalize.cpp.o
> [ 91%] Building CXX object generator/CMakeFiles/shiboken.dir/main.cpp.o
> [ 93%] Building CXX object generator/CMakeFiles/shiboken.dir/qtdoc/qtdocgenerator.cpp.o
> [ 95%] Linking CXX executable shiboken
> [ 95%] Built target shiboken
> [ 96%] Running generator for 'shiboken'...
> Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)" 
> Detecting inconsistencies in typesystem...   [OK]
> make[2]: *** [shibokenmodule/CMakeFiles/shibokenmodule.dir/build.make:81: shibokenmodule/shiboken/shiboken_module_wrapper.cpp] Segmentation fault (core dumped)
> make[1]: *** [CMakeFiles/Makefile2:355: shibokenmodule/CMakeFiles/shibokenmodule.dir/all] Error 2
> make: *** [Makefile:149: all] Error 2
> ==> ERROR: A failure occurred in build().
>         Aborting...

### Versions

* **Natron version/commit**: Cannot receive as package never installs.
* **OS version:**
> Manjaro Linux
> DISTRIB_ID=ManjaroLinux
> DISTRIB_RELEASE=20.2
> DISTRIB_CODENAME=Nibia
> DISTRIB_DESCRIPTION="Manjaro Linux"

**Comment by rodlie** [comment]
Official binary: https://github.com/NatronGitHub/Natron/releases/download/v2.3.15/Natron-2.3.15.1-Linux-64-no-installer.tar.xz

We do not support the AUR package, please consult the maintainer at https://aur.archlinux.org/packages/natron/
