### ISSUE TITLE
Label all issues in the repository

### ISSUE THREAD

**Issue by Echolon** [NatronGitHub/Natron#563]
Hi @rodlie,

I got advised to reach out to you:

For several opensource projects I have fully labeled the repositories
with appropriate tags (bug, enhancement, etc.)

I would like to do the same for Natron. With more than 250 issues I
think that will be quite helpful. I can probably do also one or the
other clean up with it.

So far everything I did happened on GitHub (see my profile, too):

Jitsi Meet (https://github.com/orgs/jitsi/teams/bug-marshalls/members)
Monal (https://github.com/anurodhp/Monal/issues)
Yax.im (https://github.com/yaxim-org/yaxim/issues)

and some more.

So I wanted to ask, if there is interest from your side. What I would
need are the according rights to label issues.

Kind regards

**Comment by Shrinks99** [comment]
The issues are due for a bit of a cleanup, some (in my opinion) that should be closed:

- https://github.com/NatronGitHub/Natron/issues/541: Not sufficiently detailed.
- https://github.com/NatronGitHub/Natron/issues/541: A very bad idea :P.
- https://github.com/NatronGitHub/Natron/issues/534: Bad issue formatting.
- https://github.com/NatronGitHub/Natron/issues/512: Should be closed once a new version is released, bug fix has been committed!
- https://github.com/NatronGitHub/Natron/issues/457: Question has been answered.
- https://github.com/NatronGitHub/Natron/issues/451: PBR doesn't really have much of a utility without a 3D render engine.  3D is out of scope in Natron at the moment.
- https://github.com/NatronGitHub/Natron/issues/134: Seems very out of scope, Krita supports EXRs and [specifically mentions this as the intended interchange format for Natron.](https://docs.krita.org/en/general_concepts/file_formats/file_exr.html)

**Comment by devernay** [comment]
@Shrinks99 done, thanks!
@Echolon I usually put labels on the issues when I read them. Are you able to add label as well, or do you need some special permissions?

**Comment by Echolon** [comment]
@devernay Unfortunately, I think I would at least need Triade. Writer would be better, because then I can label mupltiple labels at once. But I guess thats too much trust for one random guys from the internet :D Here are some more details: https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization

**Comment by Echolon** [comment]
So yes, @devernay I would access. I did this work Jitsi Meet and Monal as well, see my account.

**Comment by Echolon** [comment]
@devernay thanks for inviting. Will go ahead!
