### ISSUE TITLE
Playhead doesn't snap to per-frame increments on hover

### ISSUE THREAD

**Issue by Shrinks99** [NatronGitHub/Natron#567]
### Problem

Natron's playhead does not snap to the closest per-frame increment when the user is hovering over the timeline.  The playhead _does_ do this when the user has clicked the timeline but the non-clicked ghost indicator moves smoothly based on the mouse cursor.

**Expected behavior:**

Ideally the playhead should only move in per-frame increments so that all timeline operations are shown to the user in the same way.  Moving the playhead smoothly makes selecting a specific frame more difficult and less accurate.  Given that it is impossible to select an inter-frame on the timeline the playhead should always snap to a given frame instead of being able to exist between frames at any point.

https://user-images.githubusercontent.com/5672810/106666701-f0c5b580-6575-11eb-9a74-4837b93e66be.mov

Hovered VS clicked behavior, the clicked behavior is great!

### Versions

* **Natron version:** 2.3.15
* **OS version:** macOS / Windows

**Comment by rodlie** [comment]
Can fix if no one has any objections against adding snapping.
