### ISSUE TITLE
Can't write a 30 fps video. Write node makes 30000/1001 fps instead

### ISSUE THREAD

**Issue by thima2017** [NatronGitHub/Natron#575]
### Problem

My project settings has 30 fps, write node has 30 fps too, but I always get 30000/1001 fps on output. I tried mp4 and mkv containers and h264/h265 codecs with two different image sequences.

**Expected behavior:**
I expected to have a 30 fps as an output of write node.
**Actual behavior:**
I get a 30000/1001 fps video instead of 30.

### Steps to Reproduce

1. Unpack and open the [attached](https://github.com/NatronGitHub/Natron/files/5992154/test-fps.ntp.zip) file
2. Point a frame sequence as input in the Read node
3. Press "Render" button in the Write node
4. Check the fps of the resulting video file (I use MediaInfo program from Ubuntu repos)

### Versions

* **Natron version 2.3.15 Release**
* **Ubuntu 20.04** 

[test-fps.ntp.zip](https://github.com/NatronGitHub/Natron/files/5992154/test-fps.ntp.zip)

**Comment by devernay** [comment]
Fixed. I'll make a 2.3.16beta build soon for Linux

**Comment by thima2017** [comment]
Thank you!
