### ISSUE TITLE
Viewer diagonal pixel bug at small resolutons

### ISSUE THREAD

**Issue by Shrinks99** [NatronGitHub/Natron#577]
### Problem

At very small resolutions such as 20x1 or 12x4 there is a viewer bug where part of the top row of pixels has a strange 45° rotated edge.  Tagging @rodlie because when I mentioned this on the Discord he seemed to recognize the bug, just putting it here so it can be documented officially. :)

**Expected behavior:** The top row of pixels is square like pixels are.

**Actual behavior:** Where'd that strange edge come from???

### Steps to Reproduce

1. Load this PNG file (it's real small!)

![Palette](https://user-images.githubusercontent.com/5672810/108616059-09d4c000-73d8-11eb-8625-f4ec72216b15.png)

2. View it
3. :(

### Screenshot

![Screenshot 2021-02-21 000333](https://user-images.githubusercontent.com/5672810/108616082-4dc7c500-73d8-11eb-960f-c959f07aa943.png)

### Versions

* **Natron version/commit:** 2.3.15
* **OS version:** Windows 10, macOS 11

**Comment by devernay** [comment]
Fixed! 
<img width="560" alt="image" src="https://user-images.githubusercontent.com/3778071/108650953-9e413000-7475-11eb-9268-e1abb0d09dee.png">
