### ISSUE TITLE
Natron reader node can't read Cyrillic relative path to a file.

### ISSUE THREAD

**Issue by thima2017** [NatronGitHub/Natron#578]
### Problem

Natron's Read node can't read a path with a Cyrillic symbols. The attached [file](https://github.com/NatronGitHub/Natron/files/6030585/cyrpaths.zip) has a Read node with this path to a file: ``` [Project]/natron_logo.png ```. It works correctly if there is no Cyrillic symbols in the ```[Project]``` path. But with Cyrillic symbols in the [Project] path it shows an error (can not load frame).
An absolute path (without ``` [Project]/... ```) works as expected, so probably it's not Read node's problem, but somehow related to ```[Project]``` shortcut itself.

**Expected behavior:**
Natron Read node reads file with any (UTF-8?) symbols in the [Project] path.
**Actual behavior:**
Natron shows an error if there are Cyrillic symbols in the [Project] path. 

### Steps to Reproduce

1. Place the attached [file](https://github.com/NatronGitHub/Natron/files/6030585/cyrpaths.zip) in a directory with a path way that contains a Cyrillic symbols and unpack it there
2. Open the .ntp file and press "Reload the file" button in the Read node
3. There should be an error
4. Try the same steps for a path with Latin symbols only. Should work

### Versions

* **Natron version 2.3.15 Release**
* **OS version: Ubuntu 20.04** 

[cyrpaths.zip](https://github.com/NatronGitHub/Natron/files/6030585/cyrpaths.zip)

**Comment by rodlie** [comment]
Confirmed, thanks for the report.

**Comment by devernay** [comment]
fixed
