### ISSUE TITLE
Copied node is removed from node graph on next project load with error dialog

### ISSUE THREAD

**Issue by circledot** [NatronGitHub/Natron#580]
In the node graph I copy and paste a node. Save the project, restart Natron and open last project. Error dialog appears and the node I had pasted is gone:

Project: ERROR: The node net.fxarena.openfx.Text version 6.13 was found in the script but does not exist in the loaded plug-ins.

Project renders okay, but obviously without the new node I pasted.

**Comment by rodlie** [comment]
Not able to replicate, could you give us some more information. OS? If Linux, did you use the official binary? could you attach a project for us to test? Thanks.

**Comment by circledot** [comment]
I've found the problem! In the gui properties it doesn't like the script name being "not".

**Comment by circledot** [comment]
...I mean, the gui does accept the name "not" but if you save the project, quit the app, then reload natron and the project... then it comes up with the error.

**Comment by circledot** [comment]
This will come as no surprise but the script name can also not be named "and". Of course, "not" and "and" are script keywords / operators, so it's my fault, right? - I don't think so. When someone is using a gui, I think there is an expectation that the user is shielded from the low level stuff. In my case, I was naming text objects and I chose the words themselves as the script name. There was no error when I set it but the object was missing when I later loaded the project again. If certain words are problematic then please don't allow them in the first place. Thanks.

**Comment by devernay** [comment]
Yes, sure. create an issue for this: https://github.com/NatronGitHub/Natron/issues/586
Closing this issue

**Comment by devernay** [comment]
@circledot thanks for your feedback, this is fixed in the next beta (2.3.16beta3) or release (2.3.16)
