### ISSUE TITLE
Corner Blur Viewer Rendering Error

### ISSUE THREAD

**Issue by Shrinks99** [NatronGitHub/Natron#581]
### Problem

When a smaller blurred image is composited over a bigger plate it snaps to the bottom left corner as expected.  Unfortunately the blur is not composited correctly when the image is at its origin of 0,0 and must be moved slightly before it is composited correctly.  This isn't exactly a serious issue in practice but seems like a bug nonetheless.

**Expected behavior:**
Should look like image two by default

**Actual behavior:**

Strange incorrect blur box appears.  The fact that the image above is a jpeg is not the issue, alpha has been set to 1 for both sources.  The bounding box is not set properly.

### Steps to Reproduce

1. Load a big and small image, set the plate size to the big one, blur the small one
2. Merge with over, looks strange
3. Use a transform node, instantly gets fixed

![Screenshot 2021-03-02 004050](https://user-images.githubusercontent.com/5672810/109603958-b4439600-7af0-11eb-9d81-1c3eee2705d2.png)
Strange blur box cutoff

![Screenshot 2021-03-02 004111](https://user-images.githubusercontent.com/5672810/109603959-b4dc2c80-7af0-11eb-9e16-9b3fb377fcc1.png)
Blur and bounding box looks as expected when x=0.001

### Versions

* **Natron version/commit:** 2.3.15
* **OS version:** Windows 10

**Comment by devernay** [comment]
did you uncheck "crop to format" in the blur node?

**Comment by Shrinks99** [comment]
Nope, this is intentional and works well, my mistake.
