### ISSUE TITLE
WriteOIIO: do not add "Color." to the channel names of the color plane

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#583]
This results in color EXR with channel names:
channels (type chlist):
Color.A, 16-bit floating-point, sampling 1 1
Color.B, 16-bit floating-point, sampling 1 1
Color.G, 16-bit floating-point, sampling 1 1
Color.R, 16-bit floating-point, sampling 1 1

instead of the standard ones:
channels (type chlist):
A, 16-bit floating-point, sampling 1 1
B, 16-bit floating-point, sampling 1 1
G, 16-bit floating-point, sampling 1 1
R, 16-bit floating-point, sampling 1 1

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/openfx-io/pull/7

**Comment by makeworld-the-better-one** [comment]
I believe this will allow converting the output EXR with `ffmpeg` instead of needing to use the `iconvert` command from OIIO.

**Comment by devernay** [comment]
yes. This means better compatibility with other software
