### ISSUE TITLE
Card3D node linking problem

### ISSUE THREAD

**Issue by cgvirus** [NatronGitHub/Natron#585]
If we use two card3D node to hard link camera properties in Cam Section two things happen:
1. After closing natron session the hard links will be gone
2. Only links that was changed by value will remain hard linked.

The reason it is necessary, is to sync one camera with multiple images.
Demo:

[card3D linking bug.zip](https://github.com/NatronGitHub/Natron/files/6135712/card3D.linking.bug.zip)

**Comment by cgvirus** [comment]
If we could develop a camera node separately like PM_camera and PM_card3D that would be much more better.

https://github.com/NatronGitHub/natron-plugins/tree/master/Transform/PM_Camera
https://github.com/NatronGitHub/natron-plugins/tree/master/Transform/3D_Card

**Comment by devernay** [comment]
I don't understand the issue, it seems to work for me (both with clone and with links)

[card3d.ntp.zip](https://github.com/NatronGitHub/Natron/files/6135736/card3d.ntp.zip)

**Comment by cgvirus** [comment]
Other properties work fine. Only enable camera and camera properties.

**Comment by cgvirus** [comment]
All over the Cam section such as cam projection as well.

**Comment by cgvirus** [comment]
What I am suspecting is enable camera bool is False by default and that's why link targets fail at init.

**Comment by devernay** [comment]
it's strange, because I don't have any issue (macOS).
Can you try loading the attached project?
[toto.ntp.zip](https://github.com/NatronGitHub/Natron/files/6178500/toto.ntp.zip)
Also, can you try if it works differently with a node clone rather than individual parameter links?

**Comment by cgvirus** [comment]
- In the toto project Translate and Rotate in Cam section was successfully linked.
- Here is the demo of what happens with clone: 
[Card3D glitch.zip](https://github.com/NatronGitHub/Natron/files/6178509/Card3D.glitch.zip)

O/S: Linux Mint 20, Natron Build 2.3.14 and the latest Snapshot

**Comment by devernay** [comment]
🤔 WFM (macOS 2.3.16beta2)
Is this project working for you?
Can you post a simple project file that doesn't work?
[toto2.ntp.zip](https://github.com/NatronGitHub/Natron/files/6192003/toto2.ntp.zip)

**Comment by cgvirus** [comment]
Can you check with Enable Camera?
By default if enable camera is unchecked, then the link is intact. as toto2.ntp.

It is broken, If only Enable Camera is checked, then saved. Here is toto2 with enable camera checked.

[toto_enable.zip](https://github.com/NatronGitHub/Natron/files/6192090/toto_enable.zip)

**Comment by cgvirus** [comment]
Can @olear check this as well? Would be more clearer I guess.

**Comment by devernay** [comment]
OK now I can reproduce it

**Comment by cgvirus** [comment]
Awesome Thanks a ton! :)

**Comment by cgvirus** [comment]
When It will be available to use? I am waiting to do dull blown tutorial on this for a long time!

**Comment by devernay** [comment]
work has started in https://github.com/NatronGitHub/Natron/tree/fix-issue-568 but please be patient. It may not make it into 2.3.16.

**Comment by devernay** [comment]
In next beta (2.3.16b3) or release
