### ISSUE TITLE
Render GIFs end up with yellow edges

### ISSUE THREAD

**Issue by EricViso** [NatronGitHub/Natron#604]
Hi guys,

I'm rather new to Natron, just going through tutorial videos. 
I tried to Render a GIF on Natron on 3 different computers (Windows 10), and I ended up with the same strange yellowish color appearing and moving on some black and white logo. My workaround was to export an mp4 and the convert to GIF. 

All my settings are default.
![image](https://user-images.githubusercontent.com/45704565/114638938-0393fd80-9d10-11eb-87d2-c8c27bd01ac1.png)
Screenshot of a GIF. This one is text, but it does the same thing with a Read picture. 

Any thoughts? 😅

**Comment by devernay** [comment]
GIFs are paletted formats and don't allow more than 256 colors. Use PNG and convert to GIF using an external utility.
We should disable writing to GIF altogether (will close this issue when it's disabled).

**Comment by devernay** [comment]
BTW for this kind of animation, you should either prefer separate frames (eg png) or a lossless codec (you can use a png codec inside avi, mov or mp4)

**Comment by EricViso** [comment]
I see, thanks for your fast answer!
