### ISSUE TITLE
How to debug if OFX plugins are not loading?

### ISSUE THREAD

**Issue by 3togo** [NatronGitHub/Natron#605]
I have two computers that have installed  ubuntu 20.04. One could load the plugin while the other cannot. 

Any pointer on how to debug this problem.

**Comment by devernay** [comment]
you probably installed something that added a few lines to your bashrc to modify your environment (typically `LD_LIBRARY_PATH`).
Compare `~/.bashrc` and `~/.bash_profile` on the two systems.
Compare the output of `env`

**Comment by Echolon** [comment]
@3togo can you close if your issue has been solved?

**Comment by rodlie** [comment]
Close as this is question and it was answered.
