### ISSUE TITLE
Node graph slow in macOS Big Sur

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#606]
### Problem

The node graph is awfully slow on macOS Big Sur (macOS 11.2). Even when dragging a single viewer node around, the display is lagging a lot.

This was [first reported on the Natron forum](https://discuss.pixls.us/t/natron-node-graph-slow-in-big-sur/24618/2).

It works fine on Catalina (macOS 10.15)

### Steps to Reproduce

1. Launch Natron
2. Drag the Viewer node around

Profiling revealed that Catalina and Big Sur took very different paths inside QGraphicsScenePrivate::q_processDirtyItems():
- The Catalina version spends some time in `-[NSView _oldDisplayRectIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:]`
- The Big Sur version spends a lot of time in `-[NSBackingLayer displayIfNeeded]`

After doing some research it seems to be related to a major ~~bug~~ change in macOS Big Sur:
- https://developer.apple.com/forums/thread/663256
- https://gist.github.com/lukaskubanek/9a61ac71dc0db8bb04db2028f2635779
- https://trac.wxwidgets.org/ticket/19111 (with fix [here](https://github.com/wxWidgets/wxWidgets/blob/master/src/osx/cocoa/window.mm#L887) which requires the 10.12 SDK)
- https://forum.juce.com/t/apparent-serious-juce-painting-issue-in-big-sur/43430

There are some fix proposals (one being to [disable NSViewUsesAutomaticLayerBackingStores on Big Sur](https://gist.github.com/lukaskubanek/9a61ac71dc0db8bb04db2028f2635779#4%EF%B8%8F%E2%83%A3-current-approach)). We can either implement one of these fixes, or wait for a fix from Apple (which will probably never happen according to [this message](https://developer.apple.com/forums/thread/663256?answerId=646653022#646653022)).

## Proposed solution:

Patch Qt4's [src/gui/kernel/qcocoaview_mac.mm here](https://github.com/qt/qt/blob/4.8/src/gui/kernel/qcocoaview_mac.mm#L1000) to add:
```
#if __MAC_OS_X_VERSION_MAX_ALLOWED >= 101200
- (void) viewWillDraw
{
    if (NSAppKitVersionNumber >= 2022.00)
    {
        CALayer* layer = self.layer;
        layer.contentsFormat = kCAContentsFormatRGBA8Uint;
    }
    
    [super viewWillDraw];
}
#endif
```
(the Big Sur runtime check comes from [VLC](https://www.mail-archive.com/vlc-commits@videolan.org/msg61091.html))

We will have to compile a macOS version for 10.12+

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 2.4.0
* **OS version:** macOS Big Sur

**Comment by devernay** [comment]
Please test https://github.com/NatronGitHub/Natron/releases/download/v2.4.0/Natron-2.4.0-macOS1015.dmg

**Comment by blackearth2014** [comment]
Thanks
