### ISSUE TITLE
Issue with project format/range/fps on Linux

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/Natron#609]
Made a clip for a client today, did most of the project on Windows, but had to review it on my laptop (Ubuntu) and noticed that the project format, range and fps was wrong. Loading the project on Windows or macOS works.

Loaded example project on Windows (and macOS):
![natron-linux-project-bug-screenshot2](https://user-images.githubusercontent.com/34516798/115890367-28494d00-a455-11eb-8001-7fb3de926a8e.png)

Loaded example project on Linux (Ubuntu):
![natron-linux-project-bug-screenshot](https://user-images.githubusercontent.com/34516798/115890425-35663c00-a455-11eb-9f77-fc4282281133.png)

Using Natron 2.4.0 release binaries.

Example project: 
[natron-linux-project-bug.zip](https://github.com/NatronGitHub/Natron/files/6366197/natron-linux-project-bug.zip)

Will debug the issue when I get the time.

**Comment by Songtech-0912** [comment]
Using Natron 2.4.0 binaries on Manjaro Linux 21.0.2, and I wasn't able to reproduce the issue.

![image](https://user-images.githubusercontent.com/61605733/115896478-79dbe280-a429-11eb-98c0-d03518de5249.png)

**Comment by rodlie** [comment]
Based on feedback from other users this seems to be on my end (must be my installation or something), odd... will close.

**Comment by rodlie** [comment]
> Using Natron 2.4.0 binaries on Manjaro Linux 21.0.2, and I wasn't able to reproduce the issue.

Thanks for testing, seems my Ubuntu install is broken or something (got a kernel update a couple of days ago), still odd that this triggers Natron in this way.

**Comment by rodlie** [comment]
Actually, this was not my computer... The reason was https://github.com/NatronGitHub/natron-python-scripting . Any computer I have them installed on will replicate this issue. They seem to lock up the UI for some seconds (on load) and the project settings knob values get changed.

**Comment by cgvirus** [comment]
hi @rodlie can you check if it's alright now? Updated init. Got this bug during 4k project.
https://github.com/NatronGitHub/natron-python-scripting
