### ISSUE TITLE
Alpha CheckerBoard Offset issue (Big Sur)

### ISSUE THREAD

**Issue by blackearth2014** [NatronGitHub/Natron#614]
Mac Big Sur Issue

When I create an alpha channel and go to activate the checkerboard mask option, it is not lining up. See attached image for reference.

![Mac Big Sur Alpha Issue](https://user-images.githubusercontent.com/7956901/116795923-6c1c0200-aaa6-11eb-99ac-f79401082e7e.jpg)

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
* **OS version:**

**Comment by blackearth2014** [comment]
Thanks

**Comment by blackearth2014** [comment]
Was there a test binary for this fix?

Omar Sharif Brown
Blessed House Media
This is your season

**Comment by devernay** [comment]
building it as we speak

**Comment by blackearth2014** [comment]
Cool Breeze.
