### ISSUE TITLE
HueKeyer - Need Mask Input

### ISSUE THREAD

**Issue by blackearth2014** [NatronGitHub/Natron#619]
This is more of a request than an issue. Can the HueKeyer node get a mask input? It can be helpful in certain situations.

**Comment by devernay** [comment]
The reason why keyers don't have a single "mask" input is that it would be  ambiguous (is that an include or an exclude mask?).
The mask meaning everywhere else is: "where the effect applies", so for a Keyer it would mean "keep the input alpha where it's zero, and set alpha to the output of the keyer where it's 1", which is neither an include nor an include mask. Is that what you would want?

IMHO it's more explicit to do masking outside of the keyer

**Comment by devernay** [comment]
And KeyMix will do that operation for you (with a more explicit name)

**Comment by blackearth2014** [comment]
I will try the Keymix node. I will assume that the Keymix Node will give me another way of generating a core matte if I use the HueKeyer to pull a key right.

**Comment by devernay** [comment]
@blackearth2014 did you manage to use Keymix?

**Comment by blackearth2014** [comment]
Yes. Everything is fine now.

Thanks for your help

**Comment by devernay** [comment]
Closing. Maybe we should add a documentation blurb about using KeyMix

**Comment by blackearth2014** [comment]
Will try to come up to something

**Comment by blackearth2014** [comment]
Natron is working for my Office Mac. 10.15 2.4.1.
thanks

Omar Sharif Brown
Blessed House Media
This is your season
