### ISSUE TITLE
Natron 2.4 crash on adding Text node

### ISSUE THREAD

**Issue by BOOtak** [NatronGitHub/Natron#620]
### Problem

Hello, I'm using Natron 2.4 from flatpak,

when I try to add Text node to the project (Draw -> Text), the application crashes.

This is what console output looks like:

```
/usr/include/c++/10.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = const char*; _Alloc = std::allocator<const char*>; std::vector<_Tp, _Alloc>::reference = const char*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
```

It could be reproduced eevn in freshly created empty project.

Please take a look

**Comment by rodlie** [comment]
Download binaries from https://github.com/NatronGitHub/Natron/releases/tag/v2.4.0

**Comment by BOOtak** [comment]
@rodlie It worked! Thank you!

But why does the same version from flatpak crash?

**Comment by rodlie** [comment]
Sorry for the late reply. The snap/flatpak versions are not built correctly it seems, has been this way for a long time. It's up to however maintain those builds to fix it.
