### ISSUE TITLE
flatpak version crashes when opening psd

### ISSUE THREAD

**Issue by MagicRedDeer** [NatronGitHub/Natron#632]
### Problem

Natron flatpak version v2.4 on fedora 34 crashes when opening any psd file.

**Expected behavior:** Natron should be able to read psd via a Read node.

**Actual behavior:** Natron crashes

When run from command line by `flatpak run fr.natron.Natron`, the following error is thrown on the console before the program crashes 

`/usr/include/c++/10.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = const char*; _Alloc = std::allocator<const char*>; std::vector<_Tp, _Alloc>::reference = const char*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
`
### Steps to Reproduce

1. Launch Natron (flatpak version), empty project
2. Create a "Read" Node.
3. Try to load a psd in read node. 

The prebuilt portable binaries are able to read psd files as expected.

### Versions

* **Natron version/commit**: Natron version 2.4 Release. (flatpak - org.flathub.Stable) / 57c4883d980de2dfeeb804ebc8bffff7231bd8e03a1acd1e8465f128f7b5c5dc
* **OS version:** Fedora 34
    Linux 5.12.7-300.fc34.x86_64 #1 SMP Wed May 26 12:58:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
    LSB Version:	:core-4.1-amd64:core-4.1-noarch
    Distributor ID:	Fedora
    Description:	Fedora release 34 (Thirty Four)
    Release:	34
    Codename:	ThirtyFour

**Comment by rodlie** [comment]
See https://github.com/flathub/fr.natron.Natron/issues/25
