### ISSUE TITLE
First Float2D param partly hidden since Natron 2.4

### ISSUE THREAD

**Issue by bonalex01dev** [NatronGitHub/Natron#636]
### Problem
Since Natron 2.4
When an integer2D or Float2D parameter is followed by another param on the same line the value boxes are partly hidden
![first_param_hidden01](https://user-images.githubusercontent.com/61953166/121598186-d9299c80-ca41-11eb-88f2-b28e8548d7a3.jpg)
This happens with user parameters. The Crop OFX is not affected (maybe the position of the knobs is hard coded rather than evaluated upon creation ?)

**Expected behavior:**
in Natron 2..3.14 it displays ok

![first_param_hidden_2 14ok](https://user-images.githubusercontent.com/61953166/121598405-155cfd00-ca42-11eb-9c08-e582547e12e9.jpg)

Note other parameters are not affected like the RGB (see below)

![first_param_hidden_rgbOK](https://user-images.githubusercontent.com/61953166/121642879-66481200-ca91-11eb-9e0e-0b9ee8f83f0d.jpg)

By the way the last user parameter tend to be cropped at the bottom. But this was already existing in 2.3.14

![first_param_bottom crop](https://user-images.githubusercontent.com/61953166/121645197-33534d80-ca94-11eb-818c-65a3cf5b8c0a.jpg)

I will submit another bug about the "2" box of the Float2D as it doesn't seem to be related

### Steps to Reproduce

1. open any node parameters
2. create 2 Float2D parameters but don't check the "new line" box for the second one
3. That's it, the first Float2D only shows the y parameter

### Workaround
Please tell me if seem difficult to fix, in this case I will change the pyplugs with 2 parameters on the same line ( Crop_N from the community plugins)

### Versions

Natron 2.4
Windows 10
NVIDIA GPU

**Comment by rodlie** [comment]
I think this is an issue from my "dev" branch (I see you use that binary), I can't reproduce this in upstream Natron.

**Comment by bonalex01dev** [comment]
Yes probably, I remember you mentioned changing something in that area a little while ago.

But The colorpicker is so nice, I'd like to stick with your builds if you have time to sync with main branch.

I like the idea that new Natron users get a stable build. And more involved people experiment with test builds

**Comment by rodlie** [comment]
I will look at the issue after work today, then do a new build from my dev branch.

Will close as this is not a upstream issue.

**Comment by bonalex01dev** [comment]
Thank you
