### ISSUE TITLE
Missing "2" box for Float2D and integer 2D

### ISSUE THREAD

**Issue by bonalex01dev** [NatronGitHub/Natron#637]
### Problem

Float2D and Integer2D parameters randomly loose the "2" box at the end.
![missing2Dbox01](https://user-images.githubusercontent.com/61953166/121648619-fdb06380-ca97-11eb-94ea-0822071ac039.jpg)

This doesn't seem to be related to #636 

**Expected behavior:**
Whatever the position of the knobs the "2" box should be visible

**Actual behavior:**

The "2" Box is usually invisible when you create Float2D user parameter.
The "2" box can be triggered to reappear for example when adding another Param on the same line, or changing the order of userparams on the tab.

The  problem also happens even on basic OFX node "Crop". (but here it may be hardcoded intended behavior to create a box "4D" parameter ?)
See below on the crop node

![missing on standard Crop node](https://user-images.githubusercontent.com/61953166/121649599-03f30f80-ca99-11eb-8557-35e03d600fb8.jpg)

### Steps to Reproduce

1. Create any node
2. Add float 2D user parameter

I have to say that the bug is hard to reproduce as it is very randomly appearing.

Note: The behavior of the "2" box is different from Nuke (doesn't ditch the y animation). That seems fine to me as the nuke behavior is obtained with "remove animation" on y + click the "2" box.

### Workaround
None that I am aware of

### Versions
I have triggered the bug in Natron 2.3.14 AND Natron 2.4
WIN 10
Nvidia GPU

**Comment by Songtech-0912** [comment]
Tested on a Manjaro Linux PC with Nvidia GTX 1070 graphics card and unable to reproduce.

**Comment by devernay** [comment]
It's not random:
- "position" params, which have the OpenFX property kOfxParamDoubleTypeXYAbsolute, don't have the "2" box, eg Translate in the Transform node or bottomLeft in the Crop node
- "size" params ([kOfxParamDoubleTypeXY](http://openeffects.org/documentation/api_doc/group__ParamPropDefines.html#ga28f363ea7bbca5cc8dbabb30ea964b9c)) have the "2" box
- see http://openeffects.org/documentation/api_doc/group__ParamPropDefines.html#gaa16c45417e802158b8f22a8a8b12f843

From python, use: https://natron.readthedocs.io/en/rb-2.5/devel/PythonReference/NatronEngine/Double2DParam.html#NatronEngine.NatronEngine.Double2DParam.setCanAutoFoldDimensions
