### ISSUE TITLE
Transform point can detatch from the motion path

### ISSUE THREAD

**Issue by Shrinks99** [NatronGitHub/Natron#638]
Motion paths!  These are great!

### Problem

Motion paths are currently constructed with straight lines, this can cause the transform widget to become detached from the motion path at higher zoom levels when between keyframes.

**Expected behavior:** The curve accuracy increases as the user zooms into the viewer.

**Actual behavior:** The curve is made of straight lines that seem to have a fixed accuracy.

### Steps to Reproduce

1. Create a transform node, set three keyframes so that the motion path has a curve
2. Navigate to any point between keyframes, preferably in an area of significant curvature
3. Zoom in

![Screenshot 2021-06-11 160707](https://user-images.githubusercontent.com/5672810/121743599-97473780-cacf-11eb-9f67-0be72f815bc1.png)

### Versions

* **Natron version/commit:** 2.4.1 alpha2
* **OS version:** Windows 10

**Comment by devernay** [comment]
This is OK and expected: each path between two keyframes is divided into a fixed number of segments (I think you can clearly see these, and even count these).
My guess is that if you put a keyframe every 30 frames, you're not interested in the sub-pixel precision at frame 24, but just in the general shape of the motion. If you do, you would just add one more keyframe here. We could do one segment for each frame, but for a long sequence with spaced keyframes that could become slow (it's not about the rendering, it's more about evaluating the values).

**Comment by Shrinks99** [comment]
I also wouldn't consider this a major problem, though After Effects' motion paths display dots at every frame which leads me to believe they just draw segments for all of them?  I obviously can't speak for the performance impact this might have.

<img width="1262" alt="Screen Shot 2021-06-11 at 5 02 08 PM" src="https://user-images.githubusercontent.com/5672810/121748335-c4e3af00-cad6-11eb-95df-b3918136427b.png">

![Screenshot 2021-06-11 170617](https://user-images.githubusercontent.com/5672810/121748733-77b40d00-cad7-11eb-9468-828fbd2118cf.png)

Nuke's motion paths actually do disconnect from the control handle if you zoom in enough but they seem to have more segments.  This viewer has been zoomed in to ~6000% scale.

There's definitely tradeoffs to be made here if it's a performance concern, maybe what you currently have is the current optimal balance and if you think it is go ahead and close the issue?

**Comment by devernay** [comment]
If you raise the number of frames in a project in Nuke, you'll see that the number of point raises.
I'll try something.
