### ISSUE TITLE
Natron command line rendering issue

### ISSUE THREAD

**Issue by Prabu-7** [NatronGitHub/Natron#644]
I'm trying to automate a few kinds of stuff in natron using python and natronrenderer.exe. I have a natron work file that will just apply text overlay to a video and render it and I'm trying to pass the text value as a subprocess argument to python script. "Get rid of LIVE and make it 79,607,544" is the text that I'm passing as argument. This makes the natronrenderer render to different frames instead of project frame range. In this case, it renders frame 607 and 544 instead of project range 1-30 frames.

**Expected behavior:** [natronrenderer.exe should render the frame range 1-30 with "Get rid of LIVE and make it 79,607,544" notes applied as text value of text node]

**Actual behavior:** [it renders random frames that was in notes argument 607 and 455]

This is the full command I tried,
![Screenshot from 2021-06-26 16-43-43](https://user-images.githubusercontent.com/40015085/123512005-8804e400-d6a2-11eb-8adb-523a806e8e70.png)

![Screenshot from 2021-06-26 17-47-39](https://user-images.githubusercontent.com/40015085/123512755-dae09a80-d6a6-11eb-9122-1568ac2fb518.png)

### Steps to Reproduce

1. create natron file called 'notes.ntp'
![Screenshot from 2021-06-26 17-08-01](https://user-images.githubusercontent.com/40015085/123511946-20e72f80-d6a2-11eb-9896-d16c097ca7aa.png)

2. create a python file called 'apply_notes.py' with content as in screenshot
![Screenshot from 2021-06-26 16-39-29](https://user-images.githubusercontent.com/40015085/123511815-3dcf3300-d6a1-11eb-95b6-a83315682643.png)

3. Do natronrenderer.exe cmd rendering with sys arguments
![Screenshot from 2021-06-26 17-11-16](https://user-images.githubusercontent.com/40015085/123511856-8d156380-d6a1-11eb-90ad-46627690246f.png)

### Versions

* **Natron 2.3.14, 2.3.15**
* **OS Windows10**

**Comment by rodlie** [comment]
Unsure if passing arguments like that to the py script will work.

This works (tested on Mac/Win):
`NatronRenderer test.ntp -l test.py -c "textValue=\"SOME TEXT\""`

where test.ntp is a simple project with a text node `Text1` and a write node `Write1`

and test.py contains:
`app.Text1.text.set(textValue)`

**Comment by Prabu-7** [comment]
> Unsure if passing arguments like that to the py script will work.
> 
> This works (tested on Mac/Win):
> `NatronRenderer test.ntp -l test.py -c "textValue=\"SOME TEXT\""`
> 
> where test.ntp is a simple project with a text node `Text1` and a write node `Write1`
> 
> and test.py contains:
> `app.Text1.text.set(textValue)`

Yeah, this will work for a single. but my real workflow has more than 10 text overlay nodes which will do some text manipulation in a python script and set the text during the script execution. So I'm passing the notes as string arguments to python script. This issue only there is ',' separated numbers in notes string like "Get rid of LIVE and make it 79,607,544". But the issue does not occur if I enclose the number inside quotes like "Get rid of LIVE and make it '79','607','544' ". I'm not sure this is a natron arguments issue or is there a fix for it.

**Comment by rodlie** [comment]
> Yeah, this will work for a single. but my real workflow has more than 10 text overlay nodes which will do some text manipulation in a python script and set the text during the script execution

That was an example on how to pass vars from the command line to a Python script, isn't that what you are trying to do?

**Comment by Prabu-7** [comment]
> > Yeah, this will work for a single. but my real workflow has more than 10 text overlay nodes which will do some text manipulation in a python script and set the text during the script execution
> 
> That was an example on how to pass vars from the command line to a Python script, isn't that what you are trying to do?

yes. is there any option to pass args without -c command flags like I was trying previously as shown in the screenshot? Btw I also tried the method you suggested but it did not work for the notes string I have  "Get rid of LIVE and make it 79,607,544"

![Screenshot from 2021-06-30 13-11-51](https://user-images.githubusercontent.com/40015085/123922500-b84fc980-d9a5-11eb-97de-3ce1b8111b40.png)

Is there anything I missed in the above screenshot?

**Comment by devernay** [comment]
I fixed in https://github.com/NatronGitHub/Natron/commit/9d1b50088d3fe63cd2207849f773b1ac1096bbc2 the fact that the argument in the original post was partially parsed as a list of frame ranges

**Comment by devernay** [comment]
This should be fixed in the next build/beta, but I'm keeping this open until @Prabu-7 confirms it's fixed

**Comment by devernay** [comment]
@Prabu-7 is this fixed in 2.4.1?
