### ISSUE TITLE
Power Management Support

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/Natron#648]
Support for basic power management in Natron has been something I wanted for a while, so let's add it :)

I have it working on mac/win and will add support for other OS's (DBus) later this week (Linux is not my primary platform anymore).

What does power management in Natron mean?

* Natron will inhibit the screen saver during playback, this means the screen will not turn off when viewer(s) is active
* Natron(Renderer) will inhibit suspend/hibernate during render, this means your computer will not turn off while working

My progress can be tracked in https://github.com/rodlie/Natron/tree/RB-2.4-PowerManagement

I will do a PR when done.

**Comment by devernay** [comment]
Not sleeping during rendering is nice!

I'm not sure why you want to inhibit the screensaver during playback: Natron is not a video player, so you don't press play and sit and watch for 1h. If the user is away and doesn't move the mouse or anything, and they're probably gone for some time, and it makes sense to keep the screensaver enabled. Autolock is a requirement in many companies, so you'd better not fiddle with the screensaver.

**Comment by Songtech-0912** [comment]
Probably a good idea to send some sort of notification to the user (a toast is best, as it doesn't annoy the user) and ask for the user's choice in this regard.

**Comment by rodlie** [comment]
> Natron is not a video player, so you don't press play and sit and watch for 1h.

* I might have the player running for 15min+
* I might be running it in a loop while talking/reviewing with others

It plays video and should behave as such (in regards to PM).

> Autolock is a requirement in many companies, so you'd better not fiddle with the screensaver.

I guess Autolock is smart enough to ignore/remove/override inhibitors from apps.

**Comment by devernay** [comment]
I don't think one would be reviewing 15 mn of natron footage using the
natron player! Reviewing uses different tools (eg Hiero rather than Nuke).
For natron I would use either Hiero or any subtitling app.
Unless there are stronger arguments, i don't think the screensaver should
be disabled while the viewer is playing, especially because the default
mode is to loop forever.

**Comment by Songtech-0912** [comment]
My proposal: Leave it a preference for users to disable, but set screensaver disabling to ON by default (and show that it's on via a QStatusBar, so it can easily be toggled on and off). And show a toast like "you're now in review mode - screensaver is disabled" with a "re-enable screensaver" button and an "remember this choice" checkbox underneath that button. I can see plenty of reason for both use cases - I have been in situations where the screensaver was a great help (conserved enough battery for my unsaved project to not be auto-deleted) and where it was a problem (screen locking after going upstairs to get some things causing the viewer to glitch).

**Comment by rodlie** [comment]
So, I will remove the screensaver part. Regarding suspend, should this be a setting? and if so, should it be default on/off?

**Comment by devernay** [comment]
I think preventing suspend should be on by default, and that's a very nice new feature!

However, if you disable suspend and Natron crashes, what happens? If everything is reverted to normal, then that's cool. If not (suspend is disabled forever), then maybe there is a better solution.

It seems like, at least on Linux, there is a way to simulate user activity, so instead of suspending we could simulate activity at each rendered frame:
https://askubuntu.com/a/1187134/786472

On macOS there's IOPMAssertionDeclareUserActivity https://developer.apple.com/documentation/iokit/1557127-iopmassertiondeclareuseractivity

**Comment by devernay** [comment]
another advantage of simulating user activity is that if Natron hangs (rather than crashing) then the computer can still suspend

**Comment by rodlie** [comment]
Simulate user activity is for the screensaver, it will keep the screen alive, not the same.

On Linux/BSD ``SimulateUserActivity`` is also deprecated.

**Comment by rodlie** [comment]
On Windows we can remove ``ES_CONTINUOUS`` in ``SetThreadExecutionState``, then the system idle timer will only reset, but we must then setup a QTimer to ping ``ES_SYSTEM_REQUIRED`` every min or so (or some other way, as long as we ping before the timeout). On Linux we get a file handle, so even if we crash the file handle will be released.

On macOS I don't see any other way than to use ``kIOPMAssertionTypePreventUserIdleSystemSleep``, we don't want to keep the screen alive.

Also note that even though we don't release a sleep block the system should be smart enough to handle this, and important sleep actions will not be inhibited, like low battery etc.

```
The system may still sleep for lid close, Apple menu, low battery, or other sleep reasons.
```

**Comment by devernay** [comment]
any progress?

**Comment by rodlie** [comment]
No, I have not done anything. Should I?

If an app crashes while it's "locking" the suspend inhibitor it's IMHO the responsibility of the system power manager to handle this.

**Comment by devernay** [comment]
so can we close this as wontfix?

**Comment by rodlie** [comment]
If you want to, sure.

*The code is still available in my fork if someone else needs it.*
