### ISSUE TITLE
Natron not responding???

### ISSUE THREAD

**Issue by Objectedbear431** [NatronGitHub/Natron#654]
Hey, I just downloaded the updated version of Natron, and I cannot start it. Whenever I open it up, it just freezes and says "not responding." Does anyone know how to fix this?

![NATRON not responding](https://user-images.githubusercontent.com/67492570/125180960-3abe6180-e1ce-11eb-8860-8abef645ddbd.jpg)

**Comment by devernay** [comment]
Sorry, but we need more details.
We have an issue template, please use it to give use the required details: https://github.com/NatronGitHub/Natron/blob/RB-2.4/.github/ISSUE_TEMPLATE.md
