### ISSUE TITLE
(Bug): Red roto-shape outline has a gap between the last and first point

### ISSUE THREAD

**Issue by Shrinks99** [NatronGitHub/Natron#659]
### 

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) and is not a duplicate of a forum thread
- [X] This bug is reproducible
- [X] This issue is not a feature request or a pull request

### Natron version

Natron 2.4.1 beta2

### Operating system

Windows 10

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

Test the new roto changes.

### What did you expect to happen? What happened instead?

Roto shapes appear to not be completed in the viewer overlay.  They result in the correct pixel output as if they were completed (so obviously they _are_ completed properly) but the red outline is not drawn to cover the full outline of the shape.  This is more pronounced with shapes that have smooth curves however can also be seen in cusped bezier shapes at very high zoom levels.  This isn't a new issue (I thought it was for some reason) and I have tested as far back as 2.3.15.

![Screenshot 2021-07-25 034126](https://user-images.githubusercontent.com/5672810/126891909-46c9dc23-d623-4df7-88d1-a8bf8ba0df33.png)

### Step-by-step reproduction instructions

1. Create a roto node
2. Complete a few roto-shapes with smooth bezier curves
3. Note the parts of the curve near the end of the last point just before the line connects to the first point.

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/Natron/commit/234279a43c94edb9c3e6f0d02b9b2f11de776c38
