### ISSUE TITLE
Natron crashes when opening a certain file

### ISSUE THREAD

**Issue by RaminRAY201** [NatronGitHub/Natron#660]
### 

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) and is not a duplicate of a forum thread
- [X] This bug is reproducible
- [X] This issue is not a feature request or a pull request

### Natron version

Natron 2.4

### Operating system

Windows 10

### System specs

```markdown
RAM:8 GB
CPU: Intel Core i5-7200U 2.5GHz with turbo boost up to 3.1GHz
GPU: Nvidia GeForce 940MX 4GB
```

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

```markdown
I have a save that is a bit heavy, but it used to open normally, then one time I put the timeline on a certain frame, which crashed the program, then after opening it worked for a bit then crashed after choosing another frame, but since I saved just before moving to that other frame, now it crashes as soon as I open it, because apparently that first frame started crashing again, and I can't access the file now,

Please help me fix this, this is a very important file to me and I really don't want to redo all of it
```

### What did you expect to happen? What happened instead?

```markdown
I expected to open the file, instead it crashes, I have tried this on other computers and all of them have the same result,

I can't find a crash report nor a crash ID
```

### Step-by-step reproduction instructions

```markdown
1. Start Natron
2. Open the save file provided

https://drive.google.com/file/d/1LZrwKZhYj4V_4aw2p5zvQjw1Fo9uyp2q/view?usp=sharing
```

**Comment by rodlie** [comment]
Hi,

I'm able to replicate the issue on macOS. It seems to be an issue with the tracker, I don't have time to look at this now, but maybe later this weekend.

I did a minor modification to the project file to get it to load (it will probably crash if you connect the viewer, so close the tracker panel before doing anything):
[portifolio 7-1.ntp.zip](https://github.com/NatronGitHub/Natron/files/6985116/portifolio.7-1.ntp.zip)

**Comment by devernay** [comment]
@rodlie got any time to look at this? Should it be a blocker for 2.4.1, or can we release 2.4.1 now? any other fixes you want to add to 2.4.1?

**Comment by rodlie** [comment]
Forgot about it, sorry. Will take a look this weekend.

> any other fixes you want to add to 2.4.1?

I noticed that on Windows Natron is very slow loading/saving large projects, we are talking minutes vs. Mac/Linux that takes seconds, I was planning to try to find a fix (or at least the reason).

**Comment by devernay** [comment]
Is that a regression from previous versions? If not, it can wait for next
minor release

Le jeu. 16 sept. 2021 à 23:45, Ole-André ***@***.***> a
écrit :

**Comment by rodlie** [comment]
Not a regression, it's been like this for a while (always?). Anyway, will try to find a solution, but it's not a blocker for 2.4.1.

**Comment by devernay** [comment]
@rodlie were you able to investigate about this crash? (not the long file loading issue)

**Comment by rodlie** [comment]
Tested on macOS yesterday:

Connecting the viewer to the rectangle in the project file (see above) will crash when using Misc.ofx release build, but not against a debug build of Misc.ofx, then everything is fine.

``
1  (anonymous namespace)::RectangleProcessor<float, 4, 1>::multiThreadProcessImages(OfxRectI const&, OfxPointD const&)                                                                                                                                                                                                                                                                                                                                                                                                                                  (x86_64) /Applications/Natron.app/Contents/Plugins/OFX/Natron/Misc.ofx.bundle/Contents/MacOS/Misc.ofx      0x1222be316    
``

``
2  OFX::ImageProcessor::multiThreadFunction(unsigned int, unsigned int)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 (x86_64) /Applications/Natron.app/Contents/Plugins/OFX/Natron/Misc.ofx.bundle/Contents/MacOS/Misc.ofx      0x121924cee    
``

``
3  Natron::(anonymous namespace)::threadFunctionWrapper(void ( *)(unsigned int, unsigned int, void *), unsigned int, unsigned int, QThread *, void *)                                                                                                                                                                                                                                                                                                                                                                                                   OfxHost.cpp                                                                                           1242 0x101126437    
``

``
4  int boost::_bi::list5<boost::_bi::value<void ( *)(unsigned int, unsigned int, void *)>, boost::arg<1>, boost::_bi::value<unsigned int>, boost::_bi::value<QThread *>, boost::_bi::value<void *>>::operator()<int, int ( *)(void ( *)(unsigned int, unsigned int, void *), unsigned int, unsigned int, QThread *, void *), boost::_bi::rrlist1<unsigned int const&>>(boost::_bi::type<int>, int ( *&)(void ( *)(unsigned int, unsigned int, void *), unsigned int, unsigned int, QThread *, void *), boost::_bi::rrlist1<unsigned int const&>&, long) bind.hpp                                                                                              500  0x101130d16    
``

``
5  int boost::_bi::bind_t<int, int ( *)(void ( *)(unsigned int, unsigned int, void *), unsigned int, unsigned int, QThread *, void *), boost::_bi::list5<boost::_bi::value<void ( *)(unsigned int, unsigned int, void *)>, boost::arg<1>, boost::_bi::value<unsigned int>, boost::_bi::value<QThread *>, boost::_bi::value<void *>>>::operator()<unsigned int const&>(unsigned int const&&&)                                                                                                                                                            bind.hpp                                                                                              1285 0x101130c3d    
``

``
6  QtConcurrent::MappedEachKernel<std::__wrap_iter<unsigned int const *>, boost::_bi::bind_t<int, int ( *)(void ( *)(unsigned int, unsigned int, void *), unsigned int, unsigned int, QThread *, void *), boost::_bi::list5<boost::_bi::value<void ( *)(unsigned int, unsigned int, void *)>, boost::arg<1>, boost::_bi::value<unsigned int>, boost::_bi::value<QThread *>, boost::_bi::value<void *>>>>::runIteration(std::__wrap_iter<unsigned int const *>, int, int *)                                                                              qtconcurrentmapkernel.h                                                                               180  0x10112fe56    
``

``
7  QtConcurrent::MappedEachKernel<std::__wrap_iter<unsigned int const *>, boost::_bi::bind_t<int, int ( *)(void ( *)(unsigned int, unsigned int, void *), unsigned int, unsigned int, QThread *, void *), boost::_bi::list5<boost::_bi::value<void ( *)(unsigned int, unsigned int, void *)>, boost::arg<1>, boost::_bi::value<unsigned int>, boost::_bi::value<QThread *>, boost::_bi::value<void *>>>>::runIterations(std::__wrap_iter<unsigned int const *>, int, int, int *)                                                                        qtconcurrentmapkernel.h                                                                               190  0x10112ff80    
``

``
8  QtConcurrent::IterateKernel<std::__wrap_iter<unsigned int const *>, int>::forThreadFunction()                                                                                                                                                                                                                                                                                                                                                                                                                                                        qtconcurrentiteratekernel.h                                                                           263  0x101131101    
``

``
9  QtConcurrent::IterateKernel<std::__wrap_iter<unsigned int const *>, int>::threadFunction()                                                                                                                                                                                                                                                                                                                                                                                                                                                           qtconcurrentiteratekernel.h                                                                           225  0x101130017    
``

``
10 QtConcurrent::ThreadEngineBase::run()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (x86_64) /opt/local/libexec/qt4/Library/Frameworks/QtCore.framework/Versions/4/QtCore                      0x106191419    
``

``
11 QThreadPoolThread::run()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             (x86_64) /opt/local/libexec/qt4/Library/Frameworks/QtCore.framework/Versions/4/QtCore                      0x106192390    
``

``
12 QThreadPrivate::start(void *)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        (x86_64) /opt/local/libexec/qt4/Library/Frameworks/QtCore.framework/Versions/4/QtCore                      0x10619ff18    
``

``
13 _pthread_body                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        (x86_64) /usr/lib/system/libsystem_pthread.dylib                                                           0x7fff6399d661 
``

``
14 _pthread_start                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       (x86_64) /usr/lib/system/libsystem_pthread.dylib                                                           0x7fff6399d50d 
``

``
15 thread_start 
``

**Comment by devernay** [comment]
This issue came from the Mirror plugin. For some reason, with optimization enabled, sometimes the multithread suite asks to render parts that are outside of src bounds, so that srcPix = 0.

To debug this, add -g to the CXXFLAGS in Makefile.master for the plugins.

**Comment by BANLOGICS** [comment]
> @rodlie were you able to investigate about this crash? (not the long file loading issue)

Hello, I also faced this issue. My video resolution was low compared to the output resolution. I selected different video with higher resolution and it didn't crash. It may crash due to lower resolution. It worked for me. You may try it. Not guarantied at all.
