### ISSUE TITLE
(Feature): <Set default Project Frame Range>

### ISSUE THREAD

**Issue by elevenlevel** [NatronGitHub/Natron#662]
### 

- [X] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

```markdown
I'm sure many people are comfortable that the default Frame Range of a project is set to 1-250, but I would like to be able to choose. In my work, the value 1-1 is convenient and I would like to be able to set this value in the settings. I'm sure I'm not the only one. It is best, of course, to save the default project to a separate file, as it is implemented in many other programs. Thanx.
```

### Is this a realistically implementable feature?

- [X] My feature is realistically implementable
- [ ] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [X] I am unable, or not willing to contribute to creating this feature
- [ ] I am able and willing to contribute to the creation of this feature

**Comment by cgvirus** [comment]
press 's'. It will open the project settings. 
or display> show project settings.
There is frame range first - last.

**Comment by bonalex01dev** [comment]
Install the community scripts.
The initgui.py does exactly this (range 1-25) Just change the 25 into 1 for your own case

IMO this issue can be CLOSED

**Comment by elevenlevel** [comment]
> Install the community scripts.
> The initgui.py does exactly this (range 1-25) Just change the 25 into 1 for your own case
> 
> IMO this issue can be CLOSED

Thanks for the tip. This will come in handy now. But the request remains relevant. It is not overkill when the user has the ability to customize the program for himself. This is the norm today.

**Comment by devernay** [comment]
The solution is to add the following to init.py:
```
def Project_Created_Callback(app):
	app.getProjectParam('frameRange').set(1, 1)

NatronEngine.natron.setOnProjectCreatedCallback("Project_Created_Callback")
```
it's clearly explained in the doc: https://natron.readthedocs.io/en/rb-2.4/devel/startupscripts.html

I'll close it for now, since we don't want all customizable stuff to go in the preferences.
