### ISSUE TITLE
Write mode Show only compatible codec following container

### ISSUE THREAD

**Issue by cgvirus** [NatronGitHub/Natron#663]
### 

- [X] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

```markdown
In write node show only compatible codec according to the container.
Reason: 
- Too much codec in the drop down list 
- Some codecs in the dropdown list are not compatible with a specific container. This is misleading to the users.
- Thus produces virtual bugs

Hint to solve:
- What I am seeing there is already a list mechanism to detect non compatible codecs. Which gives warning in the viewport if selected.
- There are several lists showing codec compatibility. So can be hard coded in the codec dropdown as well.
```

### Is this a realistically implementable feature?

- [ ] My feature is realistically implementable
- [x] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [X] I am unable, or not willing to contribute to creating this feature
- [ ] I am able and willing to contribute to the creation of this feature

**Comment by devernay** [comment]
We thought about it, but it's really bad UX: if you only show the codecs that are selected with the current container, then others are not visible; The current solution is the best possible: everything is shown in the documentation.
