### ISSUE TITLE
(Bug): Natron and Mocha Pro 2022 plugin

### ISSUE THREAD

**Issue by threedslider** [NatronGitHub/Natron#665]
### 

- [x] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) and is not a duplicate of a forum thread
- [X] This bug is reproducible
- [X] This issue is not a feature request or a pull request

### Natron version

Natron 2.4.0

### Operating system

Windows 10

### Did you install Natron using the official installer?

- [ ] Yes, I used the official installer
- [X] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

```markdown
I have installed the new Mocha Pro 2022 plugin and when I launch this plugin, it gets error to run within Mocha Pro 2022 it says it doesn't find the colorspace : "matte_paint"...

I don't find this "matte_paint" in Natron, how to resolve it ?
```

### What did you expect to happen? What happened instead?

```markdown
It runs fine except to "matte_paint" is missing in Natron 2.4.0
```

### Step-by-step reproduction instructions

```markdown
1. Start Natron
2. search video file and add in read node
3. add mocha pro plugin node
3. launch mocha UI
4. it gets error saying "matte_paint" cannot to operate it
```

**Comment by rodlie** [comment]
You already have an issue open regarding Mocha #436
