### ISSUE TITLE
(Bug): Write Node with "override" enabled only modifies existing files

### ISSUE THREAD

**Issue by sihagen** [NatronGitHub/Natron#666]
### 

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) and is not a duplicate of a forum thread
- [X] This bug is reproducible
- [X] This issue is not a feature request or a pull request

### Natron version

Natron 2.4

### Operating system

Windows 10 Home (21H1)

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

```markdown
When enabling the overwrite option in a write node, exisiting files (e.g. in an image sequence) are not 'overwritten'. Rather the files are changed and their metadata is partially altered, but for e.g. not the date of creation.
```

### What did you expect to happen? What happened instead?

```markdown
I expect Natron to replace the existing files with new ones (including new date of creation etc.).
```

### Step-by-step reproduction instructions

```markdown
1. Render a single file or an image sequence
2. Re-render the project. Now the date of creation remains the same, even though it is a new file with a (propably) new content.
```

**Comment by devernay** [comment]
To be more precise, we are talking about the filesystem creation date (as shown by `ls -lU` on Linux).
Modification date is OK, and the "capDate" OpenEXR metadata (aka DateTimeOriginal) is updated correctly.

**Comment by rodlie** [comment]
Will test on Windows now (for some reason I didn't see this issue).

**Comment by rodlie** [comment]
just tested png/tiff/exr on Windows 10. The modification date is changed, the creation date is untouched. Everything seems fine to me, we overwrite the file not recreate it.

**Comment by devernay** [comment]
I'm working on it
