### ISSUE TITLE
Suggestion for lightweight roto 

### ISSUE THREAD

**Issue by bonalex01dev** [NatronGitHub/Natron#676]
Here's a proposal I wish to implement but want opinions before starting to work:

Issue: projects with roto nodes are so big that save/load is very slow up to bugging down autosaves.

Proposal:
- Change serialize code with short names for tags and store values in hexadecimal rather than plain text with sooo many leading zeros
- don't forget to bump file version and keep old code to keep backward compatibility.

Note: grouping fields point, left tangent, right tangent into a single hex code would save even more space... But is probably beyond my coding skills.

Any input is welcome!

**Comment by rodlie** [comment]
> Issue: projects with roto nodes are so big that save/load is very slow up to bugging down autosaves.

Not related to roto, but this is a Windows issue. I have large projects that take forever to load/save in Windows, but not on Linux/Mac. I believe this is related to how Boost is built (or a MinGW issue), I will try to find a fix for this.

**Comment by devernay** [comment]
Beyond fixing loading time on Windows:
We could try boost's binary serialization, which should almost be a drop-in replacement, but of course that would make projects harder to read for humans or other programs. What we could do is support binary or XML at load time, save only in binary, and have a separate "Save project as XML" menu (and the corresponding python function).

**Comment by bonalex01dev** [comment]
Fred suggestion is nice.
The easier solution would be good to me. As a compositor I can only testify that opening a nuke project in a text editor saved my life only a handful times.

- fixing Boost seems too much work on @rodlie shoulders. And anyway Nuke had to deal with the same issue a few years ago. In the end the XML is always too big.
- If we go the binary road I can help converting types if you give me a model

For the record: Nuke seems to use fixed point notation for most values, hexadecimal for colors , and some sort of "packed" hexadecimal for rotos.
They also save space with pseudo XML that doesn't close the tag for simple values.
Labels are also very short

Just to make sure my "simplify labels+change notation" suggestion isn't good here are a couple questions:

Defaultfloat might be a good option because we store many 0's and integers in floats ?
To get defaultfloat Do we only have to change the flag for the file being written ?  like in
` std::cout << "defaultfloat:\n" << std::defaultfloat;`
or do we have to change each serialization function?

keyframe/Curve data seems to be 75% of a .ntp file. So changing only CurveSerialization.h might be sufficient ?

for the labels we can go from 315 to 150 chars with 
`<item>
										<Time>8.20000000000000000e+001</Time>
										<Value>9.96626086956521931e+002</Value>
										<InterpolationMethod>2</InterpolationMethod>
										<LeftDerivative>0.00000000000000000e+000</LeftDerivative>
										<RightDerivative>0.00000000000000000e+000</RightDerivative>
									</item>
`

turned into

`<i>
										<T>82</T>
										<V>9.96626086956521931</V>
										<IM>2</IM>
										<LD>0</LD>
										<RD>0</RD>
									</item>
`

Can we pack multiple values together before sending them to boost::serialization::make_nvp ?
like in:

`Keyframe::serialize
ar & ::boost::serialization::make_nvp("KF", float_to_hexString(_time) + '-' + float_to_hexString(_value) + '-' + str(_interpolation) + '-' + float_to_hexString(_leftDerivative) + '-' + float_to_hexString(_rightDerivative) ));  `

But we would have to write a deserialize function to parse the string. Am I right ?


to obtain 76 chars

`<i>
										<KF>3eccc800-2-3eccc800-3eccc800-3eccc800</KF>
									</i> `

Please tell me what you think.
Sorry for that long post.

**Comment by rodlie** [comment]
> fixing Boost seems too much work on @rodlie shoulders.

It's mostly a matter of getting the time to sit down and do it ;)

**Comment by bonalex01dev** [comment]
I was clearly talking about your time, not your skills that are light years beyond mines... 
And I want to save every second you have in case you can try adding the python node for windows that we discussed in July :-)
Or have a beer!

**Comment by rodlie** [comment]
> adding the python node for windows that we discussed in July

I got distracted by Midi during the summer :) anyway, I will fix the script node stuff, but it will require a re-write (probably using Boost.Process).

**Comment by bonalex01dev** [comment]
Oh nice, If I get you right, we could even have python 3 at no extra cost?

**Comment by devernay** [comment]
I thought we didn't do the switch to python 3 because PySide required python 2, but that's not true, so we may want to switch to python3  soon. This would require some heavy testing and validation, though.

**Comment by rodlie** [comment]
Note that PySide 1.2 only support up to Python 3.4 (officially). Unsure if that's trivial to work around.

**Comment by devernay** [comment]
Shiboken and PySide still compile and work in Python 3.9, see MacPorts:
- https://github.com/macports/macports-ports/tree/master/python/py-shiboken (especially https://github.com/macports/macports-ports/blob/master/python/py-shiboken/files/patch-tpprint-py3.patch )
- https://github.com/macports/macports-ports/tree/master/python/py-pyside

**Comment by OlafHaag** [comment]
It's not just roto. I have a project with 285 nodes without any roto, and it has ~90,000 triples of keyframes (colors). It takes ages to load on Windows and kills turn-around times. Any work on this is highly appreciated!

**Comment by rodlie** [comment]
> It's not just roto

It's loading of projects in general, no matter what the project does. The larger the file the longer it takes to load.

I still believe this is a Boost issue, but I have no solution.

**Comment by bonalex01dev** [comment]
I found this:
https://stackoverflow.com/questions/1675193/how-to-use-array-optimization-in-boost-serialization
Maybe we could use this idea to make animation of a parameter one long string that we parse ourselves with '/' separator.

**Comment by bonalex01dev** [comment]
Hello @devernay  . I did a quick test with binary serialization as you suggested : Faster save and 6x size reduction! What would you suggest now ? We had a small discussion about this with @rodlie on Discord but we definitely need your guidance.

- add a format (enum) parameter to the project save and saveinternal function. 
So we could autosave in binary and save xml or binary
Avoid copying code

- add a preference for default filesave format

- use .ntb extension for binary files (probably easier for me than trying to detect the format on file read)


It's a bit tricky to have xml and binary as we have to write the archiveXml and archiveBinary classes. But it may be the way to go.
[](https://stackoverflow.com/questions/23417630/how-can-i-overload-serialize-boost-function-to-have-one-for-file-storing-and-ano)

I had the hacky idea to use cereal for the binary save with help of:
[](https://uscilab.github.io/cereal/transition_from_boost.html)

- probably easier for me not having to overload existing classes just call ceral:: for one type boost:: for the other
- maybe the beginning of a transition for shorter xml in the future
- maybe a bad idea if smart pointers behave badly and I don't understand what's happening :-)

If it's too long to answer me and you feel like talking francais a little bit, we could use zoom if you wish.

**Comment by rodlie** [comment]
Did some tests on Windows today (31mb ntp), all Natron versions from 2.0.5 (the lowest I tested) to 2.4.3 all are extremely slow, takes 1min to load the project . Running the same Natron version through WSL2 on Windows 11 loads the project in 4 secs. The CPU usage seems to be the same vs native.

**Comment by bonalex01dev** [comment]
Thanks for the tests. As a result should I test CEREAL serialization to see if it is fast enough so we could keep on using XML (or JSON) only ?
It's a bit too soon to require all windows users of Natron to rely on WSL2. Isn't it ?
I should admit that I didn't tried WSL2. But I can do so if you think it's the way to go. Especially if it lightens @rodlie maintaining work. ( and possibly a solution for me to get runscript OFX working ? ;-)    )

**Comment by rodlie** [comment]
> It's a bit too soon to require all windows users of Natron to rely on WSL2. Isn't it ?

It was just a test to verify that this is a Windows-only (and probably a MinGW) issue, and that Boost/XML is not the bottleneck (in general).

And, Natron in WSL2 is not the best experience, a lot of UI issues (probably Qt4 related, could also be WSL, Windows 11 has it's issues).
