### ISSUE TITLE
Switch to Python 3.9

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#680]
If we can get Shiboken+PySide1 to compile for Python3.9, we're good!

Unfortunately, PySide  does not officially support Python more recent than 3.4, see https://github.com/pyside/PySide/issues/132

But MacPorts does it, and the patches are pretty simple:
-    https://github.com/macports/macports-ports/tree/master/python/py-shiboken (especially https://github.com/macports/macports-ports/blob/master/python/py-shiboken/files/patch-tpprint-py3.patch )
-    https://github.com/macports/macports-ports/tree/master/python/py-pyside
- note that to build the docs with recent sphinx-build, one has to replace occurences of `html_add_permalinks` with `html_permalinks`

We may also want to collect the Win-specific patches from there: https://github.com/krrr/PySide/compare/1.2.4...1.2.4-1

What needs to be done:
- apply patches when building on Windows, macOS, Linux
- install PySide for python3 in a different place than PySide for python2 (ok on macOS, not ok on Linux where it is installed in the Qt dir, what about Windows?)
- fix the installer scripts to pick the right PySide version
- bump Natron version to 2.5 (since this may break some existing projects which use Python2 syntax)

**Comment by rodlie** [comment]
Sounds like a plan :)

I will also need to update everything Python3 related on Windows, I think I'm on 3.6 (didn't bother to upgrade since it's only used during the build process).

**Comment by devernay** [comment]
The branch https://github.com/NatronGitHub/Natron/tree/RB-2.4-python3support adds full python3 support (add `CONFIG+=python3` to the qmake line), and I was able to compile and run the tests on macOS.
Next steps are:
1. ~~add shiboken-py3 and pyside-py3 to the linux SDK. See https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-pyside and https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=shiboken -> I'll do that~~ DONE
1. same on Windows (can you help @rodlie?)
1. push this to RB-2.5 with https://github.com/NatronGitHub/Natron/pull/686
1. maybe push https://github.com/NatronGitHub/Natron/pull/687 too
1. publish 2.5.0-alpha1, with python2 and python3 versions

**Comment by rodlie** [comment]
> same on Windows (can you help @rodlie?)

Already fixed shiboken(py2+py3), pyside will need to wait, currently I'm not able to build pyside at all. Might be related to my move to Windows 10, or something... (will find a fix).

EDIT: found the pyside issue, object path was set to 1024 max.

**Comment by devernay** [comment]
@rodlie is the Windows SDK now containing py3 versions of shiboken/pyside? If yes, can you edit the comment above, and review #686 ?

**Comment by rodlie** [comment]
Should work in theory, have not tested it yet. Was holding back until 2.4.1 was released (so I didn't mess up the build machine). Should have time to start testing today/tomorrow.

**Comment by devernay** [comment]
Released https://github.com/NatronGitHub/Natron/releases/tag/v2.5.0-alpha.1 which runs Python 3.9
