### ISSUE TITLE
Release Natron 2.4.1

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#683]
This issue is to mark what's left to be done before releasing 2.4.1.
On my side (Linux & macOS), everything is clear, what about Windows @rodlie ?

**Comment by rodlie** [comment]
I should be done with Windows today, I will need to test it a bit first to make sure I didn't break anything. Will continue after work.

*The Windows update took a bit longer than expected, and I hit various issues on the way (mostly related to path limitations on Windows).*

**Comment by rodlie** [comment]
https://discuss.pixls.us/t/error-reading-cr2-raw-files-in-version-2-4/27514/5

OIIO on Linux seems to be missing libraw support.

**Comment by rodlie** [comment]
Windows seems good to me, if anyone wants to help with regression testing I uploaded the binary on SF.net https://sourceforge.net/projects/natron/files/Windows/64/snapshots/Natron-RB-2.4-202110220916-caa6c74-Windows-x86_64.zip/download

**Comment by devernay** [comment]
OK, releasing

**Comment by rodlie** [comment]
Ok.
