### ISSUE TITLE
Linux builds don't support libraw (OIIO compiled w/o libraw support)

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#685]
See https://discuss.pixls.us/t/error-reading-cr2-raw-files-in-version-2-4/27514

I'm fixing it.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 2.4
* **OS version:** Linux

**Comment by rodlie** [comment]
I remember this happened on Windows a while ago, some version of OIIO dropped proper detection of libraw.

I use LibRaw_INCLUDE_DIR, LibRaw_ROOT, LibRaw_r_LIBRARIES on Windows.

**Comment by devernay** [comment]
only LibRaw_ROOT is needed.

**Comment by rodlie** [comment]
Should be enough, don't remember why I added the others, might be a Windows issue. Will check the next time I rebuild OIIO.

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/Natron/commit/9819ec5bd06082f4295f10823b52664dae36c8af
