### ISSUE TITLE
Color Selector: support color palette/history

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/Natron#688]
Feature request from William Young on Facebook.

> While the new color picker is in so many ways a vast improvement over the old one there is one thing I do miss A LOT, and that is a color pallet. With the new picker it becomes exceptionally difficult to work with more than one color at a time between multiple nodes. The simplest way I've found for now is creating a series of constants I connect the viewer to, but even with those the sampling doesn't get the colors 100% correct all the time, which makes that unreliable. The only other option is to use the hex numbers, but they have the limitation of being limited to 8bit values. What is really needed is a series of swatches in the picker that keep the full 32 bit float values. What would be even better is if there was the ability add new swatches up to say a maximum of around 1000 and have the ability to to save and load the swatch sets so we could create color swatch pallet sets for things like pantones, the web, inkscape, photoshop, krita, gimp. Even one step cooler would be if we could actual load pallets from krita, gimp or inkscape.... Oh... yeah... I just blew the feature request into something crazy to think about down the line.

**Comment by rodlie** [comment]
So, had an hour to spare and made a "draft":

https://user-images.githubusercontent.com/34516798/139508667-3c75c170-beb7-470f-a6c5-52a04cb05443.mp4

This is not a finished feature, just wanted to know if I'm going in the right direction before I continue (tomorrow).

**Comment by Shrinks99** [comment]
Looks reasonable to me, I assume it stores RGB floating point values per-project?

If it's a global setting the values alone don't mean anything without colourspace info attached, seems like that would be much more complicated to implement properly.

**Comment by rodlie** [comment]
I was not planning to store anything in the project, the plan was to store it just like the old QColorDialog, in the settings.

**Comment by Shrinks99** [comment]
A non-ideal implementation but so is anything related to QColor!

**Comment by rodlie** [comment]
> A non-ideal implementation but so is anything related to QColor!

It has nothing to do with QColor, the float values are stored. I meant that the color values are stored in the setting like the old dialog, not in the project.

**Comment by Shrinks99** [comment]
Oh got it.  In any case, there is currently no per-project colour setting (there IS a globally set OCIO config of course...) so AFAIK there's no easy way to attach colourspace information to the float values which would be required for conversion & accurate reproduction should the same colour value be picked when operating in a different project and working in a different space.

I'm just poking holes in it, I'm sure you know all this already but good to document shortcomings.  Seems like most of this could be addressed by better per-project colour management settings? (The LUT tab doesn't count ;P )  The global config options can stay to influence the default but until that information is baked into projects there's a lot of places we can't reference it nicely to manage features.

UI is nice enough, right click menu to remove colours?

**Comment by rodlie** [comment]
Currently my goal is to add back the feature I removed, so I will not make any changes to how it should work (at the moment). When you click "add" the values from the spin boxes are stored, that's it.

The (color selector) widget is not aware of any color management, to be that Natron would need to give the widget this info somehow, and to my knowledge this is not possible (as-is).

> right click menu to remove colours?

Sure, I can add that. Currently I have not added any way to remove a color (only replace).

**Comment by rodlie** [comment]
Did some minor modifications:
![natron-color-selector-v3](https://user-images.githubusercontent.com/34516798/139563511-e4cf66f3-fdf7-4072-87f2-6ecd6d9482f6.png)

* adjustments to UI
* added a shortcut for "Add"
* right click will clear a color

I will probably make a preview build for testing tomorrow (or Monday).

**Comment by rodlie** [comment]
Test builds: https://github.com/rodlie/Natron/releases/tag/ColorSelectorV4

**Comment by devernay** [comment]
Colors don't appear in the palette on macOS (using the OSX9 build on macOS12, I added two colors), but it sets the color correctly when I click where they should be
<img width="414" alt="image" src="https://user-images.githubusercontent.com/3778071/139790576-440f7bca-3ece-4f83-b585-a4b8b4c042ab.png">

**Comment by rodlie** [comment]
Odd, I tested on 10.13/10.14/11 and it works there.

**Comment by devernay** [comment]
also note the RGB values are misaligned with the labels in the above macOS screenshot, maybe that's something that can be fixed

**Comment by devernay** [comment]
@rodlie can you make a PR with this one?

**Comment by rodlie** [comment]
Will need to do some minor adjustment for macOS first.

>  RGB values are misaligned with the labels in the above macOS screenshot

I don't think I do anything with the alignment, has to be the Natron widget(s) that does this. Will check.

**Comment by rodlie** [comment]
better?:
![macos](https://user-images.githubusercontent.com/34516798/148649767-62e452ba-c377-4f73-93da-0fdd1e86d4a0.png)

**Comment by devernay** [comment]
closed by https://github.com/NatronGitHub/Natron/commit/43a8d502b301f8bcba90f4352ad068a5ffdc1674 via https://github.com/NatronGitHub/Natron/pull/754
