### ISSUE TITLE
RB-2.5: upgrade OIIO to 2.3.x

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#689]
- [x] macOS: present in SDK
- [x] macOS: tested
- [x] Linux: present in SDK
- [x] Linux: tested
- [x] Windows: present in SDK
- [ ] Windows: tested

**Comment by rodlie** [comment]
Note that v2.3 now requires us to link against `OpenImageIO_Util`, so the hardcoded link flags in https://github.com/NatronGitHub/openfx-io/blob/master/Makefile.master#L36 will fail.

Is `OpenImageIO.pc` ok on Linux/Mac? In that case we should use pkg-config to get the OIIO linker flags in openfx-io.

**Comment by devernay** [comment]
Sorry I didn't see your comment. I fixed openfx-io y'day

**Comment by rodlie** [comment]
No problem, I'm currently working on updating the Windows SDK (Python 3.9 required some changes).

**Comment by devernay** [comment]
Is this fixed?

**Comment by rodlie** [comment]
I downgraded to 2.2 due to unit tests stalling again in 2.3. Can try the latest version again and see if it works better.
