### ISSUE TITLE
Crash: reverse play then forward play without hitting stop

### ISSUE THREAD

**Issue by xcelente** [NatronGitHub/Natron#690]
### 

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) and is not a duplicate of a forum thread
- [X] This bug is reproducible
- [X] This issue is not a feature request or a pull request

### Natron version

2.4.1

### Operating system

Linux Mint

### System specs

```markdown
i7, 16GB RAM
```

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

```markdown
Switch from reverse play to forward play without doing stop first.
```

### What did you expect to happen? What happened instead?

```markdown
Bombs out.
```

### Step-by-step reproduction instructions

```markdown
Reverse render preview then forward, do not press stop
```

**Comment by rodlie** [comment]
Unable to replicate on Windows or macOS. Will test on Linux after work.

**Comment by rodlie** [comment]
Also not able to replicate on CentOS/Ubuntu. Could you provide a project file where this happens? and/or a screen recording?

**Comment by xcelente** [comment]
This isn't happening to me anymore and I'm not sure why. It did repeatedly occur during one computer session, maybe it's a memory issue? - dunno
