### ISSUE TITLE
Send mail or execute shell command when Write node fails

### ISSUE THREAD

**Issue by xcelente** [NatronGitHub/Natron#692]
### 

- [X] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

```markdown
This feature would be very useful to me.

When writing out image sequences, I often get a "Failed" progress status. Rendering can take a long time so I'm usually not at the computer during this process. I would like to set an email address for alerts, either when the rendering process is complete or if the status turns to "Failed". And / or, let me execute a local shell command.
```

### Is this a realistically implementable feature?

- [X] My feature is realistically implementable
- [ ] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [X] I am unable, or not willing to contribute to creating this feature
- [ ] I am able and willing to contribute to the creation of this feature

**Comment by devernay** [comment]
Natron will never send an email (for security reasons), but you could easily write a script that checks that the output renders exist after the execution of NatronRenderer, or simply check the output status of NatronRenderer. I think that's outside of Natron's scope, and this kind of scheduling or watchdog actions are the scope of data management platform (e.g. Autodesk ShotGrid - previously Shotgun).

**Comment by devernay** [comment]
For a FOSS alternative, see Afanasy https://github.com/CGRU/cgru

Tutorial: http://ramellij.blogspot.com/2015/06/afanasy-and-natron.html
Natron-specific doc: https://cgru.readthedocs.io/en/latest/software/natron.html
