### ISSUE TITLE
Check that Natron community plugins still work with Natron 2.5

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#695]
Natron is switching to Python 3 for its next version. Natron 2.5.0-alpha.1 is available from the github releases.

We need to check that third-party plugins still work with Natron, and maybe fix them if they still use python2 syntax.

Natron cumminity plugins is a large collection of third-party plugins and scripts: https://github.com/NatronGitHub/natron-plugins

@rodlie @Shrinks99 @cgvirus can you help testing these with Natron 2.5 and finding/fixing issues?

Things to look for:
- python 2 syntax
- PySide use should be replaced by QtPy if possible (eg [here](https://github.com/NatronGitHub/natron-plugins/blob/ed3097bde49e46c5bd6e336ba0554ccdbb223e4e/Draw/Audio_VLC/Audio_VLCExt.py))

**Comment by Shrinks99** [comment]
Have had good success using [2to3](https://docs.python.org/3/library/2to3.html) in the past to update my Nuke tools.  Will probably be useful here as well!

**Comment by cgvirus** [comment]
On it. It seems only Ext manual implementation will require slight tweaks. 
What library should be imported instead "PySide.QtGui" ?
Got it : qtpy.QtGui

**Comment by cgvirus** [comment]
@devernay is qtpy properly linked in 2.5.0 Alpha?
I am seeing error in terminal
o/s: Linux Mint 20.1
installer: https://github.com/NatronGitHub/Natron/releases/download/v2.5.0-alpha.1/Natron-RB-2.5-202111012250-075ea8e-Linux-x86_64-no-installer.tar.xz
```
Failed to import qtpy.QtCore, make sure it is bundled with your Natron installation or reachable through the Python path. Note that Natron disables usage of site-packages).
Failed to import qtpy.QtGui
```

**Comment by cgvirus** [comment]
https://github.com/NatronGitHub/natron-plugins
- All tested against Natron 2.5.0 Alpha. Working.
- Audio VlcExt doesn't need qtgui library at all. Was following documentation back then. Omitted.

Although this repo will require heavy translation. Currently Natron can't recognize/link qtpy library in Linux. So waiting for a proper patch.
https://github.com/NatronGitHub/natron-python-scripting

**Comment by devernay** [comment]
closing this one, then!
