### ISSUE TITLE
(Feature): Preference setting to disable pop-up help boxes

### ISSUE THREAD

**Issue by xcelente** [NatronGitHub/Natron#702]
### 

- [X] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

```markdown
Those pop-up help boxes are forever getting in the way. Would love to switch them off / summon them when needed.

Thanks
```

### Is this a realistically implementable feature?

- [X] My feature is realistically implementable
- [ ] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [X] I am unable, or not willing to contribute to creating this feature
- [ ] I am able and willing to contribute to the creation of this feature

**Comment by Shrinks99** [comment]
Pop-up help boxes?  Are you referring to tool-tips or pop-up dialogues that ask if you're sure you want to quit without saving?  Can you provide a screenshot?

**Comment by xcelente** [comment]
Ah yes, tool tips every time I go to change a value they keep getting in the way.

**Comment by xcelente** [comment]
So sorry for posting this here as it is entirely unrelated to this post... but I have tried numerous times to create a new issue and I'm always getting a blank page on submit. This post may also not work, I will only know when I hit submit.

Bug: A node with the script-name Text1_2 already exists.

Steps:

1. Create new text node.
2. copy node “Text1” to clipboard, CTRL + C
3. paste below first text node, CTRL + V
4. delete second text node, DELETE
5. paste below first text node again, CTRL + V
6. rename text node to “Test1_2”

“Could not set node script-name to Text1_2: A node with the script-name Text1_2 already exists.”

**Comment by devernay** [comment]
@xcelente tooltips should never get in the way, and they are handled by Qt. Could you show an example where the tooltip is displayed over the value you are editing?

**Comment by xcelente** [comment]
After a long break, I've just gone back to natron to try and reproduce this tooltip problem and it no longer happens! I have no idea why it works now unless it was an issue with qt.

**Comment by devernay** [comment]
ok thanks
