### ISSUE TITLE
OCIOLookTransform gives incorrect output when GPU acceleration is enabled

### ISSUE THREAD

**Issue by Shrinks99** [NatronGitHub/Natron#706]
### 

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) and is not a duplicate of a forum thread
- [X] This bug is reproducible
- [X] This issue is not a feature request or a pull request

### Natron version

2.4.1

### Operating system

Windows 10

### System specs

```markdown
RAM: 16 GB
CPU: i7 5820k
GPU: Nvidia GTX 970
```

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer

### What were you trying to do?

Use OCIOLookTransform to apply Filmic Blender look transforms

### What did you expect to happen? What happened instead?

The OCIOLookTransform node provides incorrect output when GPU acceleration is enabled.  When it is disabled the node works as expected.  Here are screenshots showing the Natron Viewer overlaid atop Nuke's viewer as a reference.  Node graphs are identical between the two programs.

GPU Render is enabled
![GPU Render On](https://user-images.githubusercontent.com/5672810/140872102-67278572-8aee-4041-9408-3cfa3ae317e3.png)

GPU Render is Disabled

![GPU Render Off](https://user-images.githubusercontent.com/5672810/140872134-5217018f-bfb7-4b14-b68e-83c7bcf0cbb6.png)

### Step-by-step reproduction instructions

1. Set OCIO configs (download [here](https://sobotka.github.io/filmic-blender/))
2. Open file provided
3. Enable GPU in OCIOLookTransform
4. The output is posterized and wrong :(

[filmictests.zip](https://github.com/NatronGitHub/Natron/files/7502380/filmictests.zip)

Download the exr file used [here](https://www.dropbox.com/s/6mlc2qjxrxy35vr/0001.exr?dl=0) (Original art by [Juan Callejas](https://juancallejas.com/), will try to keep hosted on Dropbox until this issue is closed)

**Comment by devernay** [comment]
This is expected, see the doc for that parameter:
"Note that GPU render is not as accurate as CPU render, so this should be enabled with care."

OCIO is responsible for that implementation.

**Comment by Shrinks99** [comment]
Fair enough, apparently OCIO v2 includes a new GPU enabled renderer which matches the CPU one so maybe that can be implemented in the future?

**Comment by devernay** [comment]
There's an OCIO2 branch in openfx-io, but there's a good amount of work to do to to port the GPU rendering stuff from OCIO1 to OCIO2 (they broke the API).
see https://github.com/NatronGitHub/openfx-io/issues/4

**Comment by devernay** [comment]
The next build (alpha2?) should use OpenColorIO 2 (at least on Linux and macOS), thanks to @YakoYakoYokuYoku.
This should fix the GPU render issues
