### ISSUE TITLE
Preview isn't rendered after changing value in Properties bin, etc.

### ISSUE THREAD

**Issue by yozba** [NatronGitHub/Natron#708]
For some reason I couldn't post with the new template, so I'll post with this one.
I checked them all except "I've run Natron via the command line and the issue persists"

### Problem

I tried to use transform node and I noticed that Interactive Update and some other things isn't woking correctly.

**Expected behavior:**

In 2.4.0
it works correctly.

https://user-images.githubusercontent.com/45725762/143272077-dfa9e46d-8613-4d15-bdb8-a0184f90eea1.mp4

**Actual behavior:**

In 2.4.1
- Preview isn't rendered after undo or changing value in Properties bin.
- Interactive Update doesn't work correctly even if I disable "refresh viewer only when editing is finished" option in user interface preferences.

https://user-images.githubusercontent.com/45725762/143272009-6587dc9d-fccf-45a6-b297-0246839c0098.mp4

### Steps to Reproduce

1. Start Natron
2. Add Transform node and Rectangle node (or something else)
3. Make sure enabling Interactive Update and disabling "refresh viewer only when editing is finished" option in user interface preferences
4. Move it in Preview, Undo, change value

### Versions

* **Natron version/commit**:  2.4.1
* **OS version:** Windows 10 and MacBook Pro (MacOS 11.4 Big Sur, intel)

**Comment by devernay** [comment]
confirmed:
- if the viewer interact is left untouched, everything works fine (scrub the rotate angle slider to check: viewer is updated live)
- after using the viewer interact, the viewer is sometimes updated, and live preview doesn't work

maybe a "begin/end edit group" bug in the interact code?

**Comment by devernay** [comment]
actions:
- try Natron 2.4.1 with the 2.4.0 version of the Misc plugins (including SupportExt)
- try Natron 2.4.0 with the 2.4.1 version of the Misc plugins
- fix the bug (probably in the Transform plugins)
- if that's a begin/end issue, make sure on the Natron side that all editBegin() calls are closed after action ends. Issue a warning and close the ones that are still open.
