### ISSUE TITLE
Bug template doesn't work on github

### ISSUE THREAD

**Issue by bonalex01dev** [NatronGitHub/Natron#709]
I can't use the bug issue on github

it stays locked on a white page when I hit new issue. (firefow / chrome Win 10)

I finally found I could use this blank issue but it is not very visible on github page

I'm not the only one with that problem that is mentioned in #708

**Comment by rodlie** [comment]
Seems to work now? There was a PR for the bug template, but it ended up in the wrong branch (RB-2.4), Frédéric merged the branch a couple of hours ago.

**Comment by Shrinks99** [comment]
I also have no issues navigating to the form.  This issue seems like it would be on GitHub's side or your browser.  Have tested on Firefox on macOS & Windows.

**Comment by bonalex01dev** [comment]
I'm still landing on a white page (win 10 firefox)
Not a real problem for me now that I am aware of the "empty template" trick to publish my issues

**Comment by rodlie** [comment]
> I'm still landing on a white page (win 10 firefox)

Just tested Firefox on Win10 (latest) and I can't see any issues with the template:
![template01](https://user-images.githubusercontent.com/34516798/144009370-709b9696-21a0-46e8-9a09-ade451e12fb2.png)

![template02](https://user-images.githubusercontent.com/34516798/144009378-8be7572c-368b-4ad3-921b-d8af8109cfff.png)

**Comment by yozba** [comment]
In my case (6 days ago), It sent me a blank page when i clicked "Submit new issue". (win 10 chrome)

**Comment by Shrinks99** [comment]
We tried to track this down today on Discord, could you all try visiting https://github.com/NatronGitHub/Natron/issues/new/choose and seeing if you get the new issue option list?  This appears to be a problem with GitHub.

**Comment by Shrinks99** [comment]
@bonalex01dev This issue got auto-closed because of a linked PR.  Could you double check that it works for you now?
