### ISSUE TITLE
EXR Reader Bug: With file colourspace != outputcolourspace, all layers are set to the output (color) layer

### ISSUE THREAD

**Issue by Phoenix-64** [NatronGitHub/Natron#714]
Do to the Bug issue template being broken I am trying to submmit my issue this way

Natron 2.4.1

Windows 10

RAM: 23.8 GB
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
GPU 0: Intel(R) UHD Graphics 630
GPU 1: NVIDIA GeForce GTX 1660 Ti with Max-Q Design

With the file colorspace set to somthing else as output colorspace, using aces_1.2 ocio config. Viewing a multilayer OpenEXR generated by Blenders file output node with three layers: Image.RGBA, AO.RGBA, Emit.RGBA. Display a Layer different the one selected as output layer

No matter how I change the Layer in the Viewer1 only the layer selected as output layer in the Reader1 is displayed. If file colourspace is == output colourspace this problem vanishes.

0. Download aces_1.2 https://github.com/colour-science/OpenColorIO-Configs/tree/feature/aces-1.2-config/aces_1.2
1. Start Natron
2. In Prefrences -> Color Managment select as OpenColorIO configuration Custom configuration and as Custome OpenColorIO configuration file selected aces_1.2/config.ocio
3. Run Project [natron_problem.zip](https://github.com/NatronGitHub/Natron/files/7654694/natron_problem.zip)
4. Make sure exr is loaded properly in both Read nodes
5. Make sure in node Read1 File colourspaces and Output colourspaces are set to ACES/ACES - ACEScg and Output layer is set to AO.RGBA
6. Make sure in node Read1_2 File colourspaces is set to ACES/ACES - ACEScg and output colourspace is set to ACES/ACES ACES2065-1 and Output layer is set to AO.RGBA
7. Make sure  Viewer1 Layer is set to I
mage.RGBA 
![image](https://user-images.githubusercontent.com/52720948/144724597-a2acde13-4345-47b4-945f-827076f2432e.png)
8. View Read1 node and observe Image.RGBA being properly displayed, colourful image
9.  View Read1_2 node and observe, even though Viewer1 Layer is till set to Image.RGBA, how AO.RGBA, Grayscale image, is displayed.
10. Wounder why??

**Comment by devernay** [comment]
Confirmed!
simpler way to reproduce (no need to set a custom OCIO config):
- create a reader from the EXR in the sample project above. The output color layer is set to the first layer (AO).
- if file colorspace in the reader is the same as the output colorspace, all layers are set to the selecter color layer

What is expected:
- all original layers should remain unchanged (no colorspace conversion)
- the Color layer (Color.RGBA) should be set to the selected output layer transformed from input to output colorspace

**Comment by devernay** [comment]
I found the bug and I'm fixing it, but be careful that all color layers will be affected by the colorspace change. in the case of your file, this includes the AO layer, which is RGBA, so be careful about that. One solution is to write a single-channel AO

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/openfx-io/commit/d48adf0b2d028472f71faff75642c82ad4660033

**Comment by Phoenix-64** [comment]
Hello, thank you for fixing it so quickly. Yes I am awear that this changes
all layers.
Have a nice holliday

Frédéric Devernay ***@***.***> schrieb am Fr., 17. Dez. 2021,
10:25:
