### ISSUE TITLE
After deleting a node, cannot create node with same name

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#732]
On behalf of @xcelente (https://github.com/NatronGitHub/Natron/issues/702#issuecomment-969132526)

So sorry for posting this here as it is entirely unrelated to this post... but I have tried numerous times to create a new issue and I'm always getting a blank page on submit. This post may also not work, I will only know when I hit submit.

Bug: A node with the script-name Text1_2 already exists.

Steps:

    Create new text node.
    copy node “Text1” to clipboard, CTRL + C
    paste below first text node, CTRL + V
    delete second text node, DELETE
    paste below first text node again, CTRL + V
    rename text node to “Test1_2”

“Could not set node script-name to Text1_2: A node with the script-name Text1_2 already exists.”

**Comment by devernay** [comment]
Explanation: the nodes are not deleted while they're still in the Undo stack (which has a depth of 20 actions by default). You'll notice that if you do 20 actions (move 20 times a node in the graph), you will be able to do that rename.

I have a proposed change, which allows using the name of an existing *deactivated* node. To reactivate the deactivated node, the name change would be reverted by `RenameNodeUndoRedoCommand::undo()` anyway. I had to add a few checks in the code, where the node name could only be used if it's activated, and it seems ok so far, but I'll wait for a review

**Comment by devernay** [comment]
PR #733 submitted, waiting for review

**Comment by Shrinks99** [comment]
Unsure if this warrants a separate issue but as a bonus hopefully small fix that could maybe be bundled into this: When you copy and paste a node it doesn't up the number on the end but instead adds "_2".  This can result in really long names with a bunch of underscores if you copy things repeatedly.

![Screenshot 2021-12-24 030232](https://user-images.githubusercontent.com/5672810/147332343-62019c30-61c0-4aa3-b599-850306bc435b.png)

I ran into this a few times while working on Perfect Restaurant and while obviously not a huge deal it would be helpful if it searched the graph for the largest number and upped it by 1 in the same way that adding a new node does.

**Comment by devernay** [comment]
@Shrinks99 updated PR #733 to include this proposed change
