### ISSUE TITLE
Issue templates are now missing

### ISSUE THREAD

**Issue by Shrinks99** [NatronGitHub/Natron#749]
Don't have time to look into this until later today but wanted to flag it, will update this post accordingly.

Right now if you click "view org issue templates" you can see all our form submission config yml files exist but they don't actually show up as options which means the only option is a blank issue.  As for why this is, I am not immediately sure.

<img width="1280" alt="Screen Shot 2022-01-11 at 10 50 47 AM" src="https://user-images.githubusercontent.com/5672810/148975704-9d132733-1117-41f5-bbcf-3694d4685a57.png">

**Comment by devernay** [comment]
fixed by #750 
Thanks @YakoYakoYokuYoku !
