### ISSUE TITLE
(Typo): spelling errors found

### ISSUE THREAD

**Issue by alexmyczko** [NatronGitHub/Natron#759]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

2.4.2+git20220109

### Operating system

Debian sid

### Did you install Natron using the official installer?

- [ ] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [X] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

build an official debian package (py3, qt5)

### What did you expect to happen? What happened instead?

it builds, but lintian (debian tool) reports spelling errors

### Step-by-step reproduction instructions

Please find the report here: https://mentors.debian.net/package/natron/

**Comment by rodlie** [comment]
> it builds, but lintian (debian tool) reports spelling errors

And? We are not responsible for third-party package issues. This is not a bug.

**Comment by alexmyczko** [comment]
@rodlie I wasn't claiming responsibility for an untested test built third-party package issue. I was just pointing you to a possible spelling mistake in the source that you might want to fix (or not, at your preference). I agree that is not a bug -> thus fixed the title accordingly.

From your reply, am I right that Natron developers are not interested in having third packages in Linux distributions like Debian, Ubuntu (Ubuntustudio), and other places? Or you don't care, or would you like to help?

Just to find out, what your thoughts are on these: https://repology.org/project/natron/versions
a) they are fine, but we don't support them? b) something else (we only support our binary distributed builds)?

**Comment by rodlie** [comment]
>  I was just pointing you to a possible spelling mistake in the source that you might want to fix

Ok, the link you provided showed a lot of issues, I though this was about packaging. If possible link directly to the files that might need changes, much easier to parse than the Debian link :)

> I right that Natron developers are not interested in having third packages in Linux distributions like Debian, Ubuntu (Ubuntustudio)

No, I only speak for myself.

I have no issues with third-party packages, but it will most likely end up with more issues for us to respond to, as distros package stuff however they want and it usually end up with sub-par experience (that reflects badly on the project).


> Just to find out, what your thoughts are on these: https://repology.org/project/natron/versions
a) they are fine, but we don't support them? b) something else (we only support our binary distributed builds)?

We only support the binary builds available here on GitHub.

**Comment by alexmyczko** [comment]
> > I was just pointing you to a possible spelling mistake in the source that you might want to fix
> 
> Ok, the link you provided showed a lot of issues, I though this was about packaging. If possible link directly to the files that might need changes, much easier to parse than the Debian link :)

Okay sorry will copy paste relevant part next time...

Minor annoyance, are these needed in the source tarballs?
```
libs/google-breakpad/src/tools/windows/binaries/dump_syms.exe
libs/google-breakpad/src/tools/windows/binaries/symupload.exe
libs/openMVG/openMVG/image/image_test/lena.png
```

No problem for me to drop them recreating a source tarball, just asking...

> > I right that Natron developers are not interested in having third packages in Linux distributions like Debian, Ubuntu (Ubuntustudio)
> 
> No, I only speak for myself.

Ack.

> I have no issues with third-party packages, but it will most likely end up with more issues for us to respond to, as distros package stuff however they want and it usually end up with sub-par experience (that reflects badly on the project).

Well, with debian.org it's more like, they don't package stuff however they want, but try to work together with upstream.
Speaking for myself: I try to.

> 
> > Just to find out, what your thoughts are on these: https://repology.org/project/natron/versions
> > a) they are fine, but we don't support them? b) something else (we only support our binary distributed builds)?
> 
> We only support the binary builds available here on GitHub.

Ack.

one question arised when trying to build deb packages from source (with py3+qt5):
the path for OFX in /usr/OFX, do you plan to keep that or will it be more like /usr/lib/OFX in the future?
and am I right to get natron working I do have to install the openfx-misc, openfx-... and so on? Can probably read up on it in the manuals/documentation.

**Comment by rodlie** [comment]
> Minor annoyance, are these needed in the source tarballs?

We don't use them, but they are part of the upstream projects we bundle (in source).

> Well, with debian.org it's more like, they don't package stuff however they want, but try to work together with upstream.

That's good. Note that we have patches against several third-party depends, like Qt, OpenImageIO, OpenEXR.

> the path for OFX in /usr/OFX, do you plan to keep that or will it be more like /usr/lib/OFX in the future?

The OpenFX spec says /usr/OFX/Plugins.
