### ISSUE TITLE
Very minor request: audio file amplitude extraction node

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#76]
<a href="https://github.com/blackearth2014"><img src="https://avatars1.githubusercontent.com/u/7956901?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [blackearth2014](https://github.com/blackearth2014)**
_Thursday Jul 03, 2014 at 01:07 GMT_
_Originally opened as https://github.com/MrKepzie/Natron/issues/76_

----

Can we get a node that can analyze an audio waveform file for it amplitude levels.  This way we can use the data to drive the transform node's scale, rotation and location parameters to simulate a camera shake. It can also drive a blur node parameters to create random focus effects and etc.

**Comment by devernay** [comment]
<a href="https://github.com/fPaglia"><img src="https://avatars3.githubusercontent.com/u/5074015?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fPaglia](https://github.com/fPaglia)**
_Thursday Jul 03, 2014 at 04:56 GMT_

----

In fact its quite an interesting tool for many mograph task

2014-07-03 3:07 GMT+02:00 Omar Brown notifications@github.com:

> Can we get a node that can analyze an audio waveform file for it amplitude
> levels. This way we can use the data to drive the transform node's scale,
> rotation and location parameters to simulate a camera shake. It can also
> drive a blur node parameters to create random focus effects and etc.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MrKepzie/Natron/issues/76.

## 

Francesco Paglia
Vfx and Production Supervisor

mobile  +39 347.82.12.473
e-mail   f.paglia.80@gmail.com

**Comment by devernay** [comment]
<a href="https://github.com/devernay"><img src="https://avatars3.githubusercontent.com/u/3778071?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [devernay](https://github.com/devernay)**
_Thursday Jul 03, 2014 at 10:29 GMT_

----

don't expect audio support before 1.1, or even 2.0.

**Comment by devernay** [comment]
<a href="https://github.com/olear"><img src="https://avatars1.githubusercontent.com/u/7461595?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [olear](https://github.com/olear)**
_Monday Jun 22, 2015 at 08:31 GMT_

----

I can probably make a plugin with libsndfile and create a waveform, but where to take it from there I don't know... ("export" some value to something ...)

**Comment by devernay** [comment]
<a href="https://github.com/sozap"><img src="https://avatars2.githubusercontent.com/u/9614046?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sozap](https://github.com/sozap)**
_Tuesday Jun 23, 2015 at 09:57 GMT_

----

I don't know if that make much sense, but why not having your node to show read-only floating value (like amplitude , maximal amplitude , minimal amplitude ) on the properties panel, and then let the user link these value like he want using expressions ?
That would make a nice workaround without having to do all the work for full audio support in Natron.

**Comment by devernay** [comment]
<a href="https://github.com/sozap"><img src="https://avatars2.githubusercontent.com/u/9614046?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sozap](https://github.com/sozap)**
_Tuesday Jun 23, 2015 at 10:00 GMT_

----

Another way could be like the imageStatistic node : a button to analyse the sound, making an animation on the sliders....

**Comment by devernay** [comment]
<a href="https://github.com/olear"><img src="https://avatars1.githubusercontent.com/u/7461595?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [olear](https://github.com/olear)**
_Friday Jun 26, 2015 at 03:11 GMT_

----

Creating a plugin has been delayed (https://github.com/olear/openfx-arena/issues/110) on my part, but have alternatives:
https://github.com/rcspam/audio2ascii (bash script)
https://github.com/olear/audio2ascii (qt port)

Select an audio file, tweak some params, save to txt, import into curve editor in Natron.

**Comment by devernay** [comment]
<a href="https://github.com/olear"><img src="https://avatars1.githubusercontent.com/u/7461595?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [olear](https://github.com/olear)**
_Thursday Jul 09, 2015 at 11:44 GMT_

----

Thanks to @rcspam we are getting close to a working "plugin". Just need to adjust/tweak the pythonstuff.

![screenshot](https://cloud.githubusercontent.com/assets/7461595/8578640/1ba82028-25b0-11e5-93ad-dd8abd672e9e.png)

**Comment by devernay** [comment]
<a href="https://github.com/olear"><img src="https://avatars1.githubusercontent.com/u/7461595?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [olear](https://github.com/olear)**
_Thursday Jul 09, 2015 at 13:43 GMT_

----

One question, where can python plugins be located? using the system OFX folder don't seems to work here, only the Plugins folder bundled with Natron (and possible the homefolder/.INRIA/something. Trying to make an installer ...

**Comment by unfa** [comment]
Awesome!

Would it be possible to have a lowpass / highpass filter pair also so one could use multiple nodes to process a few frequency bands separately? That'd allow for some really cool effects that sync to music.

Could be very useful in creating animated audio visualisers.

**Comment by rodlie** [comment]
Closing as 2.3.15 includes AudioCurve from openfx-arena.
