### ISSUE TITLE
(Bug): PyPlug overlay/interact missing in 2.4.3

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/Natron#762]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

2.4.3

### Operating system

Windows 10 / macOS 11

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

Use a PyPlug interact.

### What did you expect to happen? What happened instead?

In Natron 2.4.3 the overlay/interact for PyPlugs are gone.

### Step-by-step reproduction instructions

Use any PyPlug with an interact.

**Comment by devernay** [comment]
- repro?
- last known working version? (gone since when?)
- does changing the new preference setting affect it?

**Comment by rodlie** [comment]
> repro?

Draw/Lightning_Bolt from natron-plugins, notice that the two mouse interacts are missing. Also happens with any plugin from that repo that uses interacts.

> last known working version? (gone since when?)

I upgraded from 2.4.2 at work and noticed the issue.

> does changing the new preference setting affect it?

Not tested.

Just got home from work and can check a bit further, added the issue at work so I didn't forget.

**Comment by rodlie** [comment]
Sorry for the delay. Changing settings work.

The issue seems to be the use of ``bool ok = _imp->getTimeTransform(time, view, *it, getInternalNode(), &transformedTime);`` as this only takes effect instance into account, not if it's an effect group.

Adding a check for isEffectGroup in ``ViewerTabPrivate::getTimeTransform`` seems to work here, unsure if that's the best solution though.

**Comment by devernay** [comment]
there's a bit more work than that

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/Natron/commit/f88a5887578d084b61dc7fba306163fe481909c1

**Comment by rodlie** [comment]
Thanks.
