### ISSUE TITLE
(Bug): Issue with roto masking

### ISSUE THREAD

**Issue by ApplicationCoding** [NatronGitHub/Natron#768]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.4.2

### Operating system

Windows 10 21H2

### System specs

RAM: 8GB
CPU: Intel(R) Core(TM) i5-4460 CPU @3.20GHz
GPU: Intel(R) HD Graphics 4600

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

On my animated short, I was trying to mask the smoke so that it looks behind the focal point. I used the roto and it did not work. So I used the **Corner Pin** node instead as an alternative to the roto node. Please refer to the image below to see if I have connected the nodes wrong or I have done a wrong step on rotoing.

![Roto node issue](https://user-images.githubusercontent.com/76902392/153971544-dfb6803e-21c1-437e-b920-aa7dad785df2.png)

### What did you expect to happen? What happened instead?

It did not mask the clip. 
![Roto node issue screenshot 2](https://user-images.githubusercontent.com/76902392/153977401-df6e10b0-a708-4a5f-b6e1-0f6a4e1fbef9.png)
Project link: https://bit.ly/3sEclNL

### Step-by-step reproduction instructions

1. Start Natron
2. Add a Read node
3. Add a Roto node
4. Add points

**Comment by Shrinks99** [comment]
This doesn't seem to be a bug, the roto node generates an alpha, you can then use a premult node to apply your alpha to the RGB channels.  The cornerpin node is not an alternative to the roto node, it transforms images, but if it does what you want here that's great.

For more information on masking workflows in Natron, [check out my forum post on the topic](https://discuss.pixls.us/t/natron-tutorials/7492/20?u=shrinks99).  Also if you have any other questions about how to use Natron the forum is a much better place to ask them!

**Comment by ApplicationCoding** [comment]
Oh okay. Thanks for the help @Shrinks99 🙂

**Comment by Shrinks99** [comment]
If your question has been answered you should close this issue :)

**Comment by ApplicationCoding** [comment]
The question has been answered. The forum issue did solve my problem. Thanks!
