### ISSUE TITLE
(Request): Natron and ffmpeg5

### ISSUE THREAD

**Issue by a61kt** [NatronGitHub/Natron#771]
### Make sure to follow our issue report guidelines

- [X] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

Could  Natron  give problems on ffmpeg5.0  ...  

Im Asking cos archlinux/manjaro  updated ffmpeg (From 4.4 to **5.0)**   and arch  replaced some stuff  at chromium (to make it ffmpeg5 compatible)  https://github.com/archlinux/svntogit-packages/commit/a4401d45a9c70a6c0a25f008890f8404ce5a6a08

### Is this a realistically implementable feature?

- [X] My feature is realistically implementable
- [ ] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [X] I am unable, or not willing to contribute to creating this feature
- [ ] I am able and willing to contribute to the creation of this feature

### Additional details

_ffmpeg5    replaced their apis  https://ffmpeg.org/  so it miiiight give problems_

**Comment by devernay** [comment]
The only major change is deprecation of old APIs, and we did that some time ago.
Natron lnux binaries are still being built with ffmpeg 4.4.1.

We will upgrade when 5.0 is considered stable enough (usually when https://www.linuxfromscratch.org/blfs/view/svn/multimedia/ffmpeg.html is updated)

**Comment by a61kt** [comment]
and  do u think that it will give problems .. or nah  (archlinux   has 5.0

**Comment by devernay** [comment]
we don't care what arch linux has, since we bring our own build of ffmpeg with Natron
