### ISSUE TITLE
(Bug): Natron Linux builds use obsolete libcrypt

### ISSUE THREAD

**Issue by wsippel** [NatronGitHub/Natron#772]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.5 alpha 2

### Operating system

Linux (Endeavour OS)

### System specs

RAM: 32GB
CPU: AMD Ryzen 7 3700x
GPU: AMD Radeon 5700XT

### Did you install Natron using the official installer?

- [ ] Yes, I used the official installer
- [X] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### Custom installation path

/home/wsippel/Applications/Natron-RB-2.5-202201231914-6956ce3-Linux-x86_64-no-installer

### What were you trying to do?

Start the application

### What did you expect to happen? What happened instead?

/home/wsippel/Applications/Natron-RB-2.5-202201231914-6956ce3-Linux-x86_64-no-installer/bin/Natron: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory

### Step-by-step reproduction instructions

Start Natron

### Additional details

The official Natron build was compiled with glibc's built-in libcrypt support, which has been deprecated since at least 2020 and completely removed from glibc in recent releases (tested with 2.35). Applications that rely on the feature are supposed to use the stand-alone libxcrypt instead. libxcrypt is not fully compatible as insecure hash functions have been removed, and the soname changed accordingly (to libcrypt.so.2). Even if Natron doesn't use any of the removed functions, some includes might have to be updated, as uninstd.h no longer provides a declaration of the crypt function.

**Comment by rodlie** [comment]
This is not a bug, it's by design. We support glibc 2.17+.

>  which has been deprecated since at least 2020 and completely removed from glibc in recent releases

It's still available in glibc (all releases and HEAD), they have not removed it.

> Applications that rely on the feature are supposed to use the stand-alone libxcrypt instead. libxcrypt is not fully compatible as insecure hash functions have been removed, and the soname changed accordingly (to libcrypt.so.2)

A default build of latest libxcrypt uses libcrypt.so.1.

You use ArchLinux (or a spinoff), they have decided to break compat with libcrypt.so.1, not our problem IMHO.

**Comment by devernay** [comment]
And also please, if you think having Natron installed compromises your security, give good reasons (Natron is not being used to access your bank account afaik)

**Comment by Bugaboo2000** [comment]
You need to install the libxcrypt-compat package if you are using Arch Linux derivates.
