### ISSUE TITLE
Cannot render prores 4444 xq

### ISSUE THREAD

**Issue by Prabu-7** [NatronGitHub/Natron#773]
I cannot find prores 4444 xq codec for mov renders. Please suggest me how can i render out movs in 4444 xq

![Screenshot from 2022-03-04 11-37-01](https://user-images.githubusercontent.com/40015085/156709500-a6ac3b4d-cc4e-4049-988e-e37cc3535b88.png)

**Comment by Shrinks99** [comment]
Don't think it's exposed in there yet.  Your best bet currently would be to write out an EXR frame sequence and convert it to a ProRes 4444 XQ file with another program.

**Comment by devernay** [comment]
Natron relies on open source implementations of ProRes in ffmpeg (see https://trac.ffmpeg.org/wiki/Encode/VFX).
What @Shrinks99 suggests is the right way to go: render to EXR, encode and mux audio with a separate utility (eg FCP)
