### ISSUE TITLE
(Bug): 

### ISSUE THREAD

**Issue by tuchaVshortah** [NatronGitHub/Natron#776]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron Version 2.4.3

### Operating system

Kubuntu 21.10

### System specs

8GBs of RAM
AMD Ryzen 5 3550H
Geforce GTX 1650

### Did you install Natron using the official installer?

- [ ] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [X] No, I installed Natron via another method

### What were you trying to do?

I was trying to use it.

### What did you expect to happen? What happened instead?

I wanted to use the timeline panel but it has some glitches in my installation:
![Screenshot_20220317_092913](https://user-images.githubusercontent.com/71591558/158732116-1a347931-2c4c-40ea-8037-af52785cae3e.png)

If I resize the window, the panel starts showing something like parts of the logos of other apps:
![Screenshot_20220317_093110](https://user-images.githubusercontent.com/71591558/158732290-dbf84c2a-514e-4ee4-9a05-36c3d086adc2.png)

Compare to this:
![Screenshot_20220317_095637](https://user-images.githubusercontent.com/71591558/158734079-654291a3-526a-43d0-93fb-2940e341989f.png)

### Step-by-step reproduction instructions

1. Start Natron...

(only one step is requiered)

### Additional details

_I installed Natron from FlatHub (this method was listed in the official [site,](https://natrongithub.github.io/) so I consider it to be official)_

I also tried launching this app in Konsole with _--clear-cache --clear-openfx-cache --no-settings_ flags set, but nothing changed.

Output (outputs are similar when launching with or without flags and nothing changes in the GUI):
(C) 2018-2022 The Natron developers
(C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
\>>>Use the --help or -h option to print usage.<<<
Qt: Session management error: Could not open network socket
Info: init.py script not loaded (this is not an error)
Info: initGui.py script not loaded (this is not an error)

**Comment by rodlie** [comment]
Try this: https://github.com/NatronGitHub/Natron/releases/download/v2.4.3/Natron-2.4.3-Linux-x86_64-no-installer.tar.xz

Does it work?

> (this method was listed in the official [site,](https://natrongithub.github.io/) so I consider it to be official)

It a re-package of the official binaries, but might behave differently (since it is a flatpak).

**Comment by tuchaVshortah** [comment]
Thanks, it works now.

**Comment by rholinux** [comment]
Thanks, it worked for me too!
