### ISSUE TITLE
My timeline looks goofy in Linux Mint

### ISSUE THREAD

**Issue by rholinux** [NatronGitHub/Natron#778]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.4.3

### Operating system

Linux Mint 20.3

### System specs

RAM 32GB
Ryzen 5 3550H
Integrated Vega 8

### Did you install Natron using the official installer?

- [ ] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [X] No, I installed Natron via another method

### Custom installation path

flatpak from flathub

### What were you trying to do?

I was trying to edit a logo animation.

### What did you expect to happen? What happened instead?

That I could read my timeline.

### Step-by-step reproduction instructions

Start Natron and problem is there.

**Comment by rholinux** [comment]
![Natron timeline](https://user-images.githubusercontent.com/102883766/161408903-e384379c-07fc-4d95-ac83-e551a543d40b.png)

**Comment by rodlie** [comment]
See https://github.com/NatronGitHub/Natron/issues/776

For Flatpak issues go to https://github.com/flathub/fr.natron.Natron/issues
