### ISSUE TITLE
(Feature): Chromatic Aberration Node

### ISSUE THREAD

**Issue by ApplicationCoding** [NatronGitHub/Natron#781]
### Make sure to follow our issue report guidelines

- [X] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

This will make a clip look like it has a glitch effect.
![Chromatic_aberration_(comparison)_-_enlargement](https://user-images.githubusercontent.com/76902392/162924228-0d0360d4-0480-4aed-81b1-8fac948e9b5a.jpg)
^From Wikipedia

The higher the amount of dispersion is, the more there will be a chromatic aberration or the more glitchy it will look.

### Is this a realistically implementable feature?

- [X] My feature is realistically implementable
- [ ] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [ ] I am unable, or not willing to contribute to creating this feature
- [X] I am able and willing to contribute to the creation of this feature

**Comment by ApplicationCoding** [comment]
Just found out that this can be done in Natron with the help of GMIC so I closed this issue.

**Comment by rodlie** [comment]
You can find it in the community repo: https://github.com/NatronGitHub/natron-plugins/tree/master/Filter

**Comment by ApplicationCoding** [comment]
> You can find it in the community repo: https://github.com/NatronGitHub/natron-plugins/tree/master/Filter

Okay, thanks!
