### ISSUE TITLE
Garbled words appear in the setup

### ISSUE THREAD

**Issue by PermissionDenied7335** [NatronGitHub/Natron#782]
I have just installed the latest natron into my laptop(debian sid, zh_CN.UTF-8).And I find that its setup just looks like these.
![Screenshot_20220416_230815](https://user-images.githubusercontent.com/54110849/163680628-91bca3b6-e237-4e0b-8fde-c2366791e59d.png)
![Screenshot_20220416_230803](https://user-images.githubusercontent.com/54110849/163680631-86bc1821-52f5-4b86-b802-58b6fff6fbce.png)
Nearly none of the characters are displayed properly. Luckily, things goes well in the main window.
![Screenshot_20220416_232157](https://user-images.githubusercontent.com/54110849/163680697-cd2a5f82-500a-4942-b17a-56f5de136ed3.png)
The UI may not have the necessity of being translated, but it should be shown properly at least.

**Comment by rodlie** [comment]
The installer requires a bitmap font installed, this will be fixed when we move to Qt5.
