### ISSUE TITLE
How Can I convert nk(nuke) file to npt

### ISSUE THREAD

**Issue by a01163125** [NatronGitHub/Natron#788]
Now I want to use natron to finish rendering as natron is free while my old projects were generated from nuke. So how can I convert from nk file?

**Comment by rodlie** [comment]
Natron can't read or convert Nuke project files.

Some third-party scripts exists (unsure if they actually work) https://gitlab.com/mikhail.litvinov/natron-automation/-/tree/master/src/nuke_to_natron

**Comment by a01163125** [comment]
> 

thx

**Comment by a01163125** [comment]
> Natron can't read or convert Nuke project files.
> 
> Some third-party scripts exists (unsure if they actually work) https://gitlab.com/mikhail.litvinov/natron-automation/-/tree/master/src/nuke_to_natron

thx
