### ISSUE TITLE
strcpy error in PythonUtils.cpp

### ISSUE THREAD

**Issue by a01163125** [NatronGitHub/Natron#790]
Natron\Global\PythonUtils.cpp
char* pathCpy = strcpy(path.c_str());

Error (active)	E0167	argument of type "const char *" is incompatible with parameter of type "char *"	Engine	
Error (active)	E0165	too few arguments in function call	Engine	

Hi, everyone. I encountered this issue like above. I googled strcpy function, there are no examples like only take single parameter. Is anyone knows the real solution, of course I know I could prefix with (char*) just do not want change the source code.

**Comment by devernay** [comment]
Yes, this has been here forever, and this was dead code since Natron has not been compiled with Visual Studio for ages (more than 5 years).
 If you want to help porting Natron so that it compiles with VS, you are very welcome. You should probably use the RB-2.5 branch with qt5.

**Comment by a01163125** [comment]
Many thanks anyway.
1. I will leave this alone temporarily because this is not a big issue.
2. Yes, I am using vs2019 with Qt5 and did not directly compiled successfully so I used a very stupid way, disassembled everything and re-assemble them up.
3. Thanks for help and I will try to contribute when convenient in return.
4. By the way, do you know where can find _PyInit_NatronEngine_'s definition? Should be in a lib file just not sure which one is. @devernay
