### ISSUE TITLE
Defined functions in KnobImpl.h cause errors

### ISSUE THREAD

**Issue by a01163125** [NatronGitHub/Natron#804]
Hi,
I found a list of errors of unresolved external symbols like:

```
Severity Code Description Project File Line Suppression State
Error LNK2001 unresolved external symbol
"public: enum Natron::KnobHelper::ValueChangedReturnCodeEnum __cdecl Natron::Knob
<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >
::setValue(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >
const &,class Natron::ViewSpec,int,bool)"
(?setValue@?$Knob@V?$basic_string@DU?$char_traits@D@std@
@V?$allocator@D@2@@std@
@@Natron@@QEAA?AW4ValueChangedReturnCodeEnum@KnobHelper@2@AEBV
?$basic_string@DU?$char_traits@D@std@
@V?$allocator@D@2@@std@@VViewSpec@2@H_N@Z)
Engine D:\Users\Source\Repos\Natron\Engine\AppInstance.obj 1
```

I am using Visual Studio 2019 on Win10 with Natron 2.5.

I am sure that it is a commonsense no defining functions in H file as this behaviour will cause "already defined" error when this function been called from more than one file. However I found that KnobImpl.h implemented many methods of Knob.h and only been included by Knob.cpp and when I compile it I found many 2001 errors. So how can I solve this problem? Should I change this into a cpp file or did I missed any settings in VS?

**Comment by devernay** [comment]
Those are template functions, so they definitely fit inside a header file.
Knob.obj should have this symbol definition `Knob<string>::setValue(const string&,...)`, since Knob.cpp ends with explicit template instantiations:
```
template class Knob<int>;
template class Knob<double>;
template class Knob<bool>;
template class Knob<std::string>;
```
Can you check if Knob.obj contains these symbols?

**Comment by a01163125** [comment]
> Those are template functions, so they definitely fit inside a header file. Knob.obj should have this symbol definition `Knob<string>::setValue(const string&,...)`, since Knob.cpp ends with explicit template instantiations:
> 
> ```
> template class Knob<int>;
> template class Knob<double>;
> template class Knob<bool>;
> template class Knob<std::string>;
> ```
> 
> Can you check if Knob.obj contains these symbols?

Thank you! I have solved this problem by copying functions into H file.  And engine is a lib instead of exe project. I forgot to close this question.
And, how can I check  if Knob.obj contains these symbols?

**Comment by YakoYakoYokuYoku** [comment]
> And, how can I check if Knob.obj contains these symbols?

Simply you can use `dumpbin` from the [MSVC toolkit](https://docs.microsoft.com/en-us/cpp/build/reference/dumpbin-reference) or `llvm-nm` from LLVM/Clang. Closing since this question was solved.
