### ISSUE TITLE
(Bug): Changing SeNoise node parameter `Y Rotate` has no visible effect on generated noise

### ISSUE THREAD

**Issue by jdknox** [NatronGitHub/Natron#805]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

2.4.3 Release

### Operating system

Windows 10

### System specs

RAM: 24 GB
CPU: Intel Core i7-8550U CPU @ 1.80GHz
GPU: NVIDIA GeForce MX 150 (2 GB VRAM)

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### Custom installation path

g:/apps/natron-2.4.3

### What were you trying to do?

While building a node tree I tried to modify the `X Rotate` and `Y Rotate` parameter of an SeNoise node.

### What did you expect to happen? What happened instead?

The `X Rotate` works (somewhat) as expected, but the `Y Rotate` had no visible effect on the output noise.
[SeNoise.zip](https://github.com/NatronGitHub/Natron/files/8884194/SeNoise.zip)

### Step-by-step reproduction instructions

1. Start Natron
2. Open attached file
3a. Scrub through timeline or playback the animation (`Y Rotate` on SeNoise1 node is driven by expression tied to current `frame`)
3b. Change the `Y Rotate` manually on the SeNoise1 node

4. Notice the noise does not change, while it does for the `X Rotate`

(You can also just start a new file and add an SeNoise node, then attach it to a viewer.)

### Additional details

As this is regarding an OpenFX node, should the bug report be made upstream instead of here?

**Comment by jdknox** [comment]
I think I found the culprit:
https://github.com/NatronGitHub/openfx-io/blob/99d447138884950feee4b1543ea844ce538043ab/SeExpr/SeNoise.cpp#L914

The xRotate variable is being used instead of yRotate.  This would also explain the odd behavior of the X Rotate!

**Comment by YakoYakoYokuYoku** [comment]
Could replicate and PR accepted, closing.
