### ISSUE TITLE
Custom BG colour is not preserved when copying a node or a group

### ISSUE THREAD

**Issue by savchenko** [NatronGitHub/Natron#813]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.4.3 Release

### Operating system

MS Windows 10 21H2

### System specs

32GB RAM
AMD Ryzen 3700X
AMD 6600 XT

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

Duplicate group that has a custom background and font colours.

### What did you expect to happen? What happened instead?

*Expected*

Group colour preferences are preserved between copies.

*Reality*

Pasted group duplicate reverts to the default black-on-grey.

### Step-by-step reproduction instructions

1. Group some nodes
2. Set group background / foreground to non-default values
3. Create a copy of the group

### Additional details

![image](https://user-images.githubusercontent.com/300146/175456490-0d8e64de-3c8e-4e1b-8ecd-5c1dd99bb782.png)

**Comment by rodlie** [comment]
Confirmed on node background color, the text however is correct

**Comment by YakoYakoYokuYoku** [comment]
Could replicate with ungrouped nodes too. Adding the current color of a node to its serialization might be the fix in this case.

**Comment by rodlie** [comment]
> Could replicate with ungrouped nodes too. Adding the current color of a node to its serialization might be the fix in this case.

Yes, as nodes are serialized before copy/paste. I can add it (nodeColor) if wanted.
