### ISSUE TITLE
ubuntu 18.04  compile SeExpr v2.11  

### ISSUE THREAD

**Issue by a01163125** [NatronGitHub/Natron#835]
https://github.com/wdas/SeExpr 
FOR OpenFX-io
.y file could not generate to cpp file

error shows:

-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.17") 
CMake Warning (dev) at /usr/local/share/cmake/Modules/FindOpenGL.cmake:315 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  src/SeExprEditor/CMakeLists.txt:33 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/local/Trolltech/Qt-4.8.7/bin/qmake (found version "4.8.7") 
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.9.4") found components: doxygen dot 
-- Found ZLIB: /usr/local/lib/libz.so (found version "1.2.12") 
-- Found PNG: /usr/local/lib/libpng.so (found version "1.6.37") 
-- Found Qt4: /usr/local/Trolltech/Qt-4.8.7/bin/qmake (found version "4.8.7") 
-- Configuring done
CMake Error at src/SeExpr/CMakeLists.txt:22 (ADD_LIBRARY):
  Cannot find source file:

    generated/SeExprParser.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at src/SeExprEditor/CMakeLists.txt:57 (add_library):
  Cannot find source file:

    generated/SeExprSpecParser.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at src/SeExpr/CMakeLists.txt:22 (ADD_LIBRARY):
  No SOURCES given to target: SeExpr

CMake Error at src/SeExpr/CMakeLists.txt:23 (ADD_LIBRARY):
  No SOURCES given to target: SeExpr-static

CMake Error at src/SeExprEditor/CMakeLists.txt:57 (add_library):
  No SOURCES given to target: SeExprEditor

**Comment by WangBreeze** [comment]
I have encountered it too, and would like to know how to solve it

**Comment by WangBreeze** [comment]
> https://github.com/wdas/SeExpr FOR OpenFX-io .y file could not generate to cpp file
> 
> error shows:
> 
> -- The C compiler identification is GNU 4.8.5 -- The CXX compiler identification is GNU 4.8.5 -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Check for working C compiler: /usr/bin/cc - skipped -- Detecting C compile features -- Detecting C compile features - done -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Check for working CXX compiler: /usr/bin/c++ - skipped -- Detecting CXX compile features -- Detecting CXX compile features - done -- Found PythonInterp: /usr/bin/python (found version "2.7.17") -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.17") CMake Warning (dev) at /usr/local/share/cmake/Modules/FindOpenGL.cmake:315 (message): Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when available. Run "cmake --help-policy CMP0072" for policy details. Use the cmake_policy command to set the policy and suppress this warning.
> 
> FindOpenGL found both a legacy GL library:
> 
> ```
> OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
> ```
> 
> and GLVND libraries for OpenGL and GLX:
> 
> ```
> OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
> OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
> ```
> 
> OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for compatibility with CMake 3.10 and below the legacy GL library will be used. Call Stack (most recent call first): src/SeExprEditor/CMakeLists.txt:33 (find_package) This warning is for project developers. Use -Wno-dev to suppress it.
> 
> -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so -- Looking for Q_WS_X11 -- Looking for Q_WS_X11 - found -- Looking for Q_WS_WIN -- Looking for Q_WS_WIN - not found -- Looking for Q_WS_QWS -- Looking for Q_WS_QWS - not found -- Looking for Q_WS_MAC -- Looking for Q_WS_MAC - not found -- Found Qt4: /usr/local/Trolltech/Qt-4.8.7/bin/qmake (found version "4.8.7") -- Found Doxygen: /usr/local/bin/doxygen (found version "1.9.4") found components: doxygen dot -- Found ZLIB: /usr/local/lib/libz.so (found version "1.2.12") -- Found PNG: /usr/local/lib/libpng.so (found version "1.6.37") -- Found Qt4: /usr/local/Trolltech/Qt-4.8.7/bin/qmake (found version "4.8.7") -- Configuring done CMake Error at src/SeExpr/CMakeLists.txt:22 (ADD_LIBRARY): Cannot find source file:
> 
> ```
> generated/SeExprParser.cpp
> ```
> 
> Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
> 
> CMake Error at src/SeExprEditor/CMakeLists.txt:57 (add_library): Cannot find source file:
> 
> ```
> generated/SeExprSpecParser.cpp
> ```
> 
> Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
> 
> CMake Error at src/SeExpr/CMakeLists.txt:22 (ADD_LIBRARY): No SOURCES given to target: SeExpr
> 
> CMake Error at src/SeExpr/CMakeLists.txt:23 (ADD_LIBRARY): No SOURCES given to target: SeExpr-static
> 
> CMake Error at src/SeExprEditor/CMakeLists.txt:57 (add_library): No SOURCES given to target: SeExprEditor

apply  command :   **sudo apt-get install flex sed bison**

**Comment by a01163125** [comment]
Thanks!
