### ISSUE TITLE
(Feature): Calculation in Input Fields

### ISSUE THREAD

**Issue by erayerdin** [NatronGitHub/Natron#837]
### Make sure to follow our issue report guidelines

- [X] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

If a number type is expected in an input field, one can use math in it to calculate something.

To give an example, take a look at this project settings panel:

![project settings panel](https://user-images.githubusercontent.com/2399084/195944092-1440aa53-ab78-49c1-8137-823faac62d99.png)

In the "last frame range" input field, one can write "30*10" and then the program automatically evaluates it to 300 as a result.

This feature is in Godot game engine. It is a small thing but a quality-of-life feature.

### Is this a realistically implementable feature?

- [X] My feature is realistically implementable
- [ ] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [X] I am unable, or not willing to contribute to creating this feature
- [ ] I am able and willing to contribute to the creation of this feature

**Comment by devernay** [comment]
Fixed in https://github.com/NatronGitHub/Natron/commit/a3f5966eb620b88917160a9380418e53cfad469d
This was already working everywhere except in the project settings.
