### ISSUE TITLE
app wont install from flatpak linux

### ISSUE THREAD

**Issue by qwertyuiopa69** [NatronGitHub/Natron#853]
im on the linux environment on chromeos and it wont let me install the app
![Screenshot 2022-12-16 11 51 43 AM](https://user-images.githubusercontent.com/120741457/208148706-a378073e-5f6f-43a2-bb1a-ff82621da1f0.png)

**Comment by spacebanana420** [comment]
Hello. As a daily Linux user, I never used ChromeOS, but I can think of 1 reason there are no matches
First type `flatpak search natron` to see if you have any search results related to Natron

Is your machine's architecture x86_64? Natron on flathub is only built for x86_64 as you can see [here](https://flathub.org/apps/fr.natron.Natron)

![imagem](https://user-images.githubusercontent.com/98528301/236548382-01003ff9-ec64-4a46-8f62-c8a5b59c383f.png)

**Comment by devernay** [comment]
ChromeOS is not officially supported for Natron. Even if the flatpak for arm64 were available (which may happen), the hardware is probably too weak to run Natron. Get a 5-year old linux laptop at around $200 with 16Gb RAM and you'll be good.
