### ISSUE TITLE
(Bug): Natron Crashes on Startup

### ISSUE THREAD

**Issue by Alerymin** [NatronGitHub/Natron#863]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.5.0

### Operating system

Arch Linux

### System specs

RAM: 16GB
CPU: Intel Core i7 10700K
GPU: NVIDIA GeForce RTX 2080 SUPER

### Did you install Natron using the official installer?

- [ ] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [X] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

Starting Natron for the first time

### What did you expect to happen? What happened instead?

Natron being open and usable

### Step-by-step reproduction instructions

1. Start Natron
2. Natron shows up for 0.5 seconds
3. Natron crashes

### Additional details

X Error of failed request:  GLXBadContext
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  3763
  Current serial number in output stream:  3763

**Comment by pfennig59** [comment]
I and a colleague of mine are experiencing exactly the same under Windows 11 Pro 64 Bit (on Windows 10 it works fine) after installing version 2.5 via offical installer.

RAM: 32 GB DDR4
CPU: AMD Ryzen 7 5700G
GPU: NVIDIA GeForce GTX 1650 4 GB

**Comment by Alerymin** [comment]
It works when I install it from flatpak, wierd

**Comment by f-dy** [comment]
If you compiled from sources, there is high chances that issues come from library versions or dependencies. That's why we ship the official Natron binaries with all the dependencies. These are the only ones we can support.
