### ISSUE TITLE
(Bug): MacOS Crash on zoom in/out viewer (Project file attached)

### ISSUE THREAD

**Issue by gitbugr** [NatronGitHub/Natron#874]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.5.0

### Operating system

MacOS Ventura 13.2.1

### System specs

Mac Studio 2022

RAM: 32 GB
CPU/GPU: Apple M1 Max

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

Zoom in/out of the viewer with a test file.

### What did you expect to happen? What happened instead?

[cmd_output.txt](https://github.com/NatronGitHub/Natron/files/11303348/cmd_output.txt)
[crash_log.txt](https://github.com/NatronGitHub/Natron/files/11303349/crash_log.txt)
[Natron_Test_Project.zip](https://github.com/NatronGitHub/Natron/files/11303350/Natron_Test_Project.zip)
[test image for Read1 Node](https://user-images.githubusercontent.com/6732567/233832186-34985394-d502-41f2-8f1f-059097c9b189.png)

### Step-by-step reproduction instructions

Start Natron, open project file, move around in viewer (zoom in/out), crashes.

### Additional details

This may have something to do with G'MIC nodes. I've had crashes using them quite often.

**Comment by devernay** [comment]
Please use the 2.6 builds on M1/M2/Apple SIlicon mac: https://github.com/NatronGitHub/Natron/releases/tag/v2.6.0-alpha1

Natron 2.5 crashes often on M1 macs because of Qt4 issues which will never be fixed.
