### ISSUE TITLE
(Bug): EXR Compression Level

### ISSUE THREAD

**Issue by 360highdynamicrangehdr** [NatronGitHub/Natron#889]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.6.0

### Operating system

windows 10

### System specs

RAM: 8.0 GB
CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
GPU: Radeon (TM) R7 M445

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

see: [https://openimageio.readthedocs.io/en/master/builtinplugins.html#openexr](https://openimageio.readthedocs.io/en/master/builtinplugins.html#openexr)

DWA Compression Level Problem.

### What did you expect to happen? What happened instead?

![Untitled 131](https://github.com/NatronGitHub/Natron/assets/25839678/25eb67cd-aec0-4579-a5b0-470b4bf90b7d)
![Untitled 132](https://github.com/NatronGitHub/Natron/assets/25839678/b8d51b17-e64e-418e-bd5e-fcc77e4c2b7f)

### Step-by-step reproduction instructions

1. Open Natron
2. Write
3. Compression DWAA/DWAB or zip/zips
4. DWA Compression Level
5. Render

**Comment by devernay** [comment]
cryptic bug report (doesn't answer the question "What happened instead?") but I was able to guess and fix.
