### ISSUE TITLE
(Bug): Using more CPU than GPU when rendering

### ISSUE THREAD

**Issue by RafaelLinux** [NatronGitHub/Natron#904]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [x] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.4.0

### Operating system

Linux

### System specs

System info
```
Operating System: openSUSE Tumbleweed 20230718
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.4.3-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2

```
vainfo
```
Trying display: wayland
Trying display: x11
libva info: VA-API version 1.18.0
libva info: User environment variable requested driver 'nvidia'
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_0
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.18 (libva 2.18.2)
vainfo: Driver version: VA-API NVDEC driver [direct backend]
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain12             : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD

```
![imagen](https://github.com/NatronGitHub/Natron/assets/13048959/d9960004-7248-47ac-a390-bce198c23532)

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### Custom installation path

~/bin/Natron

### What were you trying to do?

Play project

### What did you expect to happen? What happened instead?

Natron is not using GPU for rendering (not appear even in "nvtop" command line program).

### Step-by-step reproduction instructions

1. Start Natron
2. Open gnu.ntp project
3. Click "Play forward" button

**Comment by rodlie** [comment]
Natron uses the CPU, some nodes can use OpenGL, that's it.

**Comment by RafaelLinux** [comment]
Are there plans to use GPU in next versions?

**Comment by rodlie** [comment]
Not really. The primary focus is maintenance and bug fixes.

**Comment by RafaelLinux** [comment]
I am sorry to read that. I thought Natron was also looking to optimise its performance. Personally, on my Intel i5, Natron is so slow that an acceptable workflow becomes impossible, not even for testing (I have loaded your examples from the web). 
After my experience, in my opinion, I see Natron as a good idea (working with nodes) as Resolve does, but in practice, Olive (which also includes nodes at a more basic level) works with a more than reasonable level of optimisation.

Thank you for your great job
