### ISSUE TITLE
Cannot find egl.h

### ISSUE THREAD

**Issue by a01163125** [NatronGitHub/Natron#906]
hi:

I encountered a problem when I was using docker command.
(BTW: before the error egl.h, there are two files CImg.h Inpaint.h could not be downloaded directly, I used docker cp to solve this. )
../SupportExt/glad/gladegl.cpp:6:10: fatal error: EGL/egl.h: No such file or directory
a little help pls.
thx!

**Comment by luzpaz** [comment]
no version info

Googling around it seems that 
> EGL/egl.h is in libegl1-mesa-dev, so apt-get install libegl1-mesa-dev should help.

Not sure this is the answer though

**Comment by luzpaz** [comment]
@devernay can you weigh in ?

**Comment by rodlie** [comment]
EGL is needed if Wayland is found during configure (before build).

**Comment by luzpaz** [comment]
@rodlie looks like there is a line in CMake that addresses this
https://github.com/NatronGitHub/Natron/blob/526e05e9b1e9efbbedb99167c334ee7e98d23541/CMakeLists.txt#L76

**Comment by a01163125** [comment]
> no version info
> 
> Googling around it seems that
> 
> > EGL/egl.h is in libegl1-mesa-dev, so apt-get install libegl1-mesa-dev should help.
> 
> Not sure this is the answer though

hi, thank you much.

But how can I pause docker run to install packages?

**Comment by devernay** [comment]
you mean that? https://github.com/NatronGitHub/Natron/tree/RB-2.5/tools/docker#debugging-a-build

**Comment by a01163125** [comment]
> you mean that? https://github.com/NatronGitHub/Natron/tree/RB-2.5/tools/docker#debugging-a-build

Looks like very helpful. I am trying with a VM in windows, I will also try in your way when time is possible.
Cheers.
