### ISSUE TITLE
(Feature): Setting kOfxParamPropAnimates to 0 should prevent that param from having an expression

### ISSUE THREAD

**Issue by valadaptive** [NatronGitHub/Natron#910]
### Make sure to follow our issue report guidelines

- [X] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

Right now, setting `kOfxParamPropAnimates` to 0 on a parameter will prevent that parameter from having keyframes set, but it's still possible for that prop to animate over time because you can use an expression to control it.

At least one other OFX host (DaVinci Resolve) prevents the user from setting expressions on parameters that cannot animate. Here's a comparison of Natron and Resolve handling a non-animatable parameter (the "Enabled" checkbox):

| Natron | Resolve |
| - | - |
|![image](https://github.com/NatronGitHub/Natron/assets/79560998/2c7c6213-b9c8-4447-9cc0-c510ae40a1c7)|![image](https://github.com/NatronGitHub/Natron/assets/79560998/9770e365-4571-411d-be62-f78ff5037470)|

It would be nice to implement this in Natron as well, so users can't animate parameters that the plugin author didn't intend for users to be able to animate.

### Is this a realistically implementable feature?

- [X] My feature is realistically implementable
- [ ] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [X] I am unable, or not willing to contribute to creating this feature
- [ ] I am able and willing to contribute to the creation of this feature

### Additional details

I *would* be interested in looking into implementing this, but I can't right now because [the official instructions for building via Docker don't seem to work right now](https://github.com/NatronGitHub/Natron/issues/906).

**Comment by devernay** [comment]
OK, that's a loophole, you *can* actually animate anything using an expression, but we cannot prevent setting an expression on a parameter that can't be animated, because... the expression may evaluate to a constant!
So, rather that getting complaints because one cannot set an constant expression on a parameter that cannot be animated, we decided that we should leave that openb, and it's the user's responsibility to do the right thing.

Note: Resolve is not the best-in-class in terms of OFX implementation. Our reference for OFX is Nuke.

**Comment by valadaptive** [comment]
Is there at least some way (either in the OFX API or otherwise) to detect when a property that isn't supposed to be animated has changed? As I mentioned in #909, I want to be able to dynamically enable/disable certain param groups when checkbox params are checked/unchecked. Right now, there doesn't seem to be any way to detect those checkboxes updating because `kOfxActionInstanceChanged` doesn't fire when a param updates due to animation (and AFAIK it shouldn't).

**Comment by devernay** [comment]
You mean changes from frame t-1 to frame t? No, there's no other way other than getvalueattime at the two frames during the render action. Maybe you have in mind that frames are processed in some order, but openfx doesn't require it, so that "parameter changes due to animation" is hard to specify.
