### ISSUE TITLE
(Bug): Natron crashes when using the GMIC Rotate node on Arch

### ISSUE THREAD

**Issue by jacquavantius** [NatronGitHub/Natron#924]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.5.0

### Operating system

Arch 6.5.3-arch1-1 

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

I tried using the GMIC Rotate node on a read node at it crashes when I try setting the orientation to other than 0 degrees

### What did you expect to happen? What happened instead?

Expected for the node to rotate the source, got a crash instead
Output when running from terminal:
https://pastebin.com/mvCNdtDT

Output from journalctl -f:
https://pastebin.com/VcxcWDwD

### Step-by-step reproduction instructions

1. Start Natron
2. Create new project
3. Add a read node with source
4. Add a GMIC Rotate node
5. Connect the read node to GMIC Rotate node source
6. Set the orientation in GMIC Rotate node properties to other than 0 degrees
7. Crash

### Additional details

Desktop Enviroment is Hyprland

**Comment by devernay** [comment]
Please use the Transform node, which is officially supported and much faster. The GMIC Nodes are provided "as is", and some may crash randomly.
