### ISSUE TITLE
(Bug): App doesn't start on M1 Pro MacOS 14.0

### ISSUE THREAD

**Issue by hallleron** [NatronGitHub/Natron#927]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

2.5.0

### Operating system

macOS 14.0 Sonoma

### System specs

RAM: 16GB
CPU: M1 Pro

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

I downloaded the app in version 2.5.0 and tried to start it. After some time, the GUI shows for like half a second and then the app just crashes. I tried restarts, new installations - it's always the same result. The app just does not start on my Mac.

### What did you expect to happen? What happened instead?

I just tried to start Natron. It crashed. No crash report, nothing.

### Step-by-step reproduction instructions

Start Natron
Watch how it crashes after hald a second

**Comment by devernay** [comment]
Please try https://github.com/NatronGitHub/Natron/releases/tag/v2.6.0-alpha1 or https://github.com/NatronGitHub/Natron/releases/tag/v2.5.1-pre1 and report (I don't have macOS 14 for testing)

**Comment by hallleron** [comment]
> Please try https://github.com/NatronGitHub/Natron/releases/tag/v2.6.0-alpha1 or https://github.com/NatronGitHub/Natron/releases/tag/v2.5.1-pre1 and report (I don't have macOS 14 for testing)

I tried the 2.6.0 alpha and this seems to work. It starts at least, but I haven't tried any of the actual functionality for now. Thank you!
