### ISSUE TITLE
(Flatpak): Natron not up to date

### ISSUE THREAD

**Issue by Chantology** [NatronGitHub/Natron#937]
### Make sure to follow our issue report guidelines

- [ ] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.4.4

### Operating system

Fedora 37

### Did you install Natron using the official installer?

- [ ] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [X] No, I installed Natron via another method

### What were you trying to do?

Who is maintaining the Flatpak version of Natron? There is already Natron 2.5.0 released on Github, but only 2.4.4 on Flathub: 
https://flathub.org/apps/fr.natron.Natron

### What did you expect to happen? What happened instead?

...

### Step-by-step reproduction instructions

...

**Comment by rodlie** [comment]
Report flatpak issues here: https://github.com/flathub/fr.natron.Natron/issues
