### ISSUE TITLE
Cannot save project 

### ISSUE THREAD

**Issue by chemicalsam** [NatronGitHub/Natron#940]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.6 Pre-builds

### Operating system

macOS 14.2.1 Sonoma

### System specs

RAM: 64
M1 Max

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

Cannot save project, dialog shows up but does not allow me to press save. Will not allow me to render out video either because I cannot create a path.

### What did you expect to happen? What happened instead?

Be able to save project

### Step-by-step reproduction instructions

1. Start natron
2. Create something
3. File, Save

**Comment by rodlie** [comment]
Works for me (macOS 12 MBA Intel). Please provide more information or a screenshot of the issue.

**Comment by chemicalsam** [comment]
![CleanShot 2024-01-24 at 09 09 51@2x](https://github.com/NatronGitHub/Natron/assets/67978865/d1d62683-f3b6-4be0-84ff-4112afb640b5)
When the dialog pops up to save, nothing happens when you press save. So I am unable to save a project or render anything out because I cannot specify a path. 

I am using this pre-release version cause I am unable to open the app without it crashing immediately

**Comment by rodlie** [comment]
Looks good to me.

`/Users/Sam/Desktop/` is a folder, add a file name.

**Comment by chemicalsam** [comment]
When I add a file name and press save, nothing happens  The save button does not do anything.

**Comment by rodlie** [comment]
So `/Users/Sam/Desktop/whatever.ntp` does not work?

**Comment by chemicalsam** [comment]
Nope, the save button does not seem to work. I am unable to save anything or render anything. And I cannot use the stable release because of the crashing bug.

**Comment by rodlie** [comment]
You didn't add the filename to the `Filter:` input? (I need to ask because several users have used the filter input to add the filename).

If nothing happens it's probably a permission issue. macOS should popup a permission dialog when a new app tries to access various folders in the home folder.

**Comment by chemicalsam** [comment]
![CleanShot 2024-01-24 at 10 32 40@2x](https://github.com/NatronGitHub/Natron/assets/67978865/fa3645b6-06bb-47dd-afed-75fc95446871)
![CleanShot 2024-01-24 at 10 31 46@2x](https://github.com/NatronGitHub/Natron/assets/67978865/287d9299-05bd-4745-8d2f-38bf402ef3e6)
I am not sure whats going on here, everything is set right. The button just does not work.

**Comment by rodlie** [comment]
This is because you have the filename in the filter. The input above is for the complete filename (with path).

![Screenshot from 2024-01-24 16-40-05](https://github.com/NatronGitHub/Natron/assets/34516798/fcfe87a3-f3ad-4a9e-b5da-f5bf906a8d13)
