### ISSUE TITLE
(Bug): Natron crashes on startup

### ISSUE THREAD

**Issue by SSolarite** [NatronGitHub/Natron#948]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [x] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.5.0

### Operating system

Windows 11 22H2

### System specs

RAM: 8 GB (7.3 GB usable)
CPU: AMD Ryzen 5 5600H with Radeon Graphics, 3.30 GHz
GPU: NVIDIA GeForce GTX 1650

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

Just open natron and maybe create a new composition

### What did you expect to happen? What happened instead?

No window opens, nothing happens when i open natron

### Step-by-step reproduction instructions

1. Start natron (from shortcut, or from installation path)
2. Nothing happens

**Comment by SSolarite** [comment]
no idea how to make a bug report

**Comment by SSolarite** [comment]
![image](https://github.com/NatronGitHub/Natron/assets/118111762/c8ba94b7-fe63-49e3-9088-bc5ef40805ed)
![image](https://github.com/NatronGitHub/Natron/assets/118111762/a5cf707d-fbdd-4932-b70d-f3737394b6f3)

**Comment by rodlie** [comment]
Theory: Natron uses your APU (Radeon) and due to known issues with Radeon Natron fails.

In the NVIDIA settings you should be able to select which app/game you want to use the NVIDIA card on, add Natron.

**Comment by SSolarite** [comment]
![image](https://github.com/NatronGitHub/Natron/assets/118111762/d0821247-f834-4e44-8919-e74a9bdec50a)
these are the only settings i have and i have a gtx 1650

**Comment by acolwell** [comment]
Sorry. I didn't mean to close this yet. I just checked in a change that I believe should fix this for you. I'll post a link to a build you can test with this fix once it is ready.

**Comment by acolwell** [comment]
@solarite1797 You should be able to test my AMD fixes with [last night's build](https://github.com/acolwell/Natron/releases/download/nightly/Natron-AJC-RB-2.5-202403131212-648134a-Windows-x86_64.zip) from my [nightly builds release page](https://github.com/acolwell/Natron/releases/tag/nightly). Please let me know if this works for you. Note, this is NOT an official Natron build, but it can be used to verify if my fix from #949 addresses the crashes you were seeing.

Please give this build a try and let me know if it works out for you.

**Comment by SSolarite** [comment]
> @solarite1797 You should be able to test my AMD fixes with [last night's build](https://github.com/acolwell/Natron/releases/download/nightly/Natron-AJC-RB-2.5-202403131212-648134a-Windows-x86_64.zip) from my [nightly builds release page](https://github.com/acolwell/Natron/releases/tag/nightly). Please let me know if this works for you. Note, this is NOT an official Natron build, but it can be used to verify if my fix from #949 addresses the crashes you were seeing.
> 
> Please give this build a try and let me know if it works out for you.

not found

**Comment by acolwell** [comment]
That's because the older builds get deleted as time passes. You should still be able to use any of the builds on that nightly build release page. At this point they all include the AMD fixes.

**Comment by Spypie60** [comment]
> > @solarite1797 You should be able to test my AMD fixes with [last night's build](https://github.com/acolwell/Natron/releases/download/nightly/Natron-AJC-RB-2.5-202403131212-648134a-Windows-x86_64.zip) from my [nightly builds release page](https://github.com/acolwell/Natron/releases/tag/nightly). Please let me know if this works for you. Note, this is NOT an official Natron build, but it can be used to verify if my fix from #949 addresses the crashes you were seeing.
> > Please give this build a try and let me know if it works out for you.
> 
> not found

This help me so much thanks
