### ISSUE TITLE
(Feature): Change default branch to RB-2.6

### ISSUE THREAD

**Issue by acolwell** [NatronGitHub/Natron#978]
### Make sure to follow our issue report guidelines

- [X] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

Change the default branch from RB-2.5 to RB-2.6.
Reasoning:
- Highly unlikely we'll do another RB-2.5 release given how much code has changed and how old QT4 is.
- Allows all changes to be focused on the branch that the next release will likely come from. This also encourages folks, who are not familiar with the historical branching strategy, to submit changes to a branch that will generate the least amount of work going forward (i.e. reduce the need for merging).
- Commits us to Qt5 and beyond and provides more encouragement to fix any remaining issues.

### Is this a realistically implementable feature?

- [X] My feature is realistically implementable
- [ ] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [X] I am unable, or not willing to contribute to creating this feature
- [ ] I am able and willing to contribute to the creation of this feature

### Additional details

I'm willing to contribute, but I don't have the necessary permissions to make this change.

**Comment by devernay** [comment]
done!

**Comment by acolwell** [comment]
> done!

Thank you.

**Comment by rodlie** [comment]
Great,

I will try to fix up the remaining Qt5 related issues when my vacation starts.
