### ISSUE TITLE
(Bug) Crash on startup on MacOS Sonoma

### ISSUE THREAD

**Issue by chemicalsam** [NatronGitHub/Natron#992]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

2.5

### Operating system

macOS 14.5 Sonoma

### System specs

Apple M3 Max 64gb RAM

Natron keeps crashing on open, I have tried different releases and still have the same issue. 

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

Open Natron 

### What did you expect to happen? What happened instead?

Use natron

### Step-by-step reproduction instructions

1. Download Natron
2. Open Natron

**Comment by devernay** [comment]
Please use the 2.6 pre builds on apple silicon
