### ISSUE TITLE
(Bug): AUR cannot install natron-compositor in Arch Linux

### ISSUE THREAD

**Issue by MrDie2233** [NatronGitHub/Natron#997]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.5.0

### Operating system

Arch Linux

### Did you install Natron using the official installer?

- [ ] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

install natron-compositor from AUR in my arch linux

### What did you expect to happen? What happened instead?

i am following INSTALL_LINUX.md instruction, try to install natron from AUR, occur error:

```
$ paru natron-compositor
error: could not find all required packages:
    clang=17.0.6 (wanted by: natron-compositor -> shiboken2)
```
my clang version:

```
$ pacman -Qs clang
local/clang 18.1.8-2
    C language family frontend for LLVM
```

### Step-by-step reproduction instructions

paru natron-compositor

**Comment by rodlie** [comment]
Please contact maintainer in AUR: https://aur.archlinux.org/account/tecnotercio

We do not support distro builds or packages.
