### ISSUE TITLE
(Bug): Natron Crashing Immediately After Startup

### ISSUE THREAD

**Issue by JustSumGuy314** [NatronGitHub/Natron#998]
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.5

### Operating system

macOS 14.4 (23E214) Sonoma

### System specs

RAM 36GB. Apple M3 Max chip—14-core CPU with 10 performance cores and 4 efficiency cores
30-core GPU.

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

As stated in the title, simply open Natron. I get the splash screen which then proceeds to the main window then immediate crash.

### What did you expect to happen? What happened instead?

I expected the software to run… Sorry, much of this isn't very applicable. 

### Step-by-step reproduction instructions

1. Start Natron
2. Nothing, it crashes immediately after opening the interface

### Additional details

The machine is new, literally picked it up today. Please advise if there are any tasks I can complete to help determine the issue.

**Comment by devernay** [comment]
Known issue, please use https://github.com/NatronGitHub/Natron/releases/tag/v2.6.0-alpha1

**Comment by JustSumGuy314** [comment]
> Known issue, please use https://github.com/NatronGitHub/Natron/releases/tag/v2.6.0-alpha1

Ah, sorry.

**Comment by devernay** [comment]
Duplicate of:
- https://github.com/NatronGitHub/Natron/issues/992
- https://github.com/NatronGitHub/Natron/issues/927 
- https://github.com/NatronGitHub/Natron/issues/874
- https://github.com/NatronGitHub/Natron/issues/737
